Repository vllm-project/vllm, pull requests merged in 2024-12, with the labels that each got.

#10769 [Model] Replace embedding models with pooling adapter
  .buildkite/test-pipeline.yaml
  docs/source/models/supported_models.rst
  tests/conftest.py
  tests/models/embedding/language/test_embedding.py
  tests/models/test_registry.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_gemma_embedding.py
  tests/test_config.py
  vllm/config.py
  vllm/inputs/registry.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/utils.py
  vllm/multimodal/base.py
  vllm/multimodal/registry.py
  vllm/utils.py
Labels: documentation, ready, ci/build

#10763 [Misc] Improve type annotations for `support_torch_compile`
  vllm/compilation/decorators.py
Labels: ready

#10801 [Misc] Rename embedding classes to pooling
  examples/offline_inference_embedding.py
  tests/entrypoints/llm/test_encode.py
  tests/models/test_registry.py
  tests/worker/test_model_input.py
  vllm/__init__.py
  vllm/config.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/protocol.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_score.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/interfaces_base.py
  vllm/model_executor/models/registry.py
  vllm/outputs.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/async_stream.py
  vllm/worker/cpu_pooling_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/pooling_model_runner.py
  vllm/worker/worker.py
Labels: frontend, ready

#10804 [Misc] Adding `MMMU-Pro` vision dataset to serving benchmark
  benchmarks/benchmark_serving.py
Labels: ready

#10502 [Core] Implement disagg prefill by StatelessProcessGroup
  .buildkite/test-pipeline.yaml
  benchmarks/disagg_benchmarks/disagg_overhead_benchmark.sh
  benchmarks/disagg_benchmarks/disagg_performance_benchmark.sh
  benchmarks/disagg_benchmarks/disagg_prefill_proxy_server.py
  benchmarks/disagg_benchmarks/round_robin_proxy.py
  benchmarks/disagg_benchmarks/visualize_benchmark_results.py
  examples/disaggregated_prefill.sh
  tests/kv_transfer/disagg_test.py
  tests/kv_transfer/module_test.py
  tests/kv_transfer/test_lookup_buffer.py
  tests/kv_transfer/test_lookup_buffer.sh
  tests/kv_transfer/test_send_recv.py
  tests/kv_transfer/test_send_recv.sh
  vllm/config.py
  vllm/distributed/kv_transfer/README.md
  vllm/distributed/kv_transfer/__init__.py
  vllm/distributed/kv_transfer/disagg_prefill_workflow.jpg
  vllm/distributed/kv_transfer/kv_connector/__init__.py
  vllm/distributed/kv_transfer/kv_connector/base.py
  vllm/distributed/kv_transfer/kv_connector/factory.py
  vllm/distributed/kv_transfer/kv_connector/simple_connector.py
  vllm/distributed/kv_transfer/kv_lookup_buffer/__init__.py
  vllm/distributed/kv_transfer/kv_lookup_buffer/base.py
  vllm/distributed/kv_transfer/kv_lookup_buffer/simple_buffer.py
  vllm/distributed/kv_transfer/kv_pipe/__init__.py
  vllm/distributed/kv_transfer/kv_pipe/base.py
  vllm/distributed/kv_transfer/kv_pipe/pynccl_pipe.py
  vllm/distributed/kv_transfer/kv_transfer_agent.py
  vllm/distributed/parallel_state.py
  vllm/engine/arg_utils.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
  vllm/worker/worker_base.py
Labels: ready, ci/build

#10795 [Model] Add BNB support to Llava and Pixtral-HF
  vllm/model_executor/models/llava.py
Labels: ready

#10809 [core] Avoid metrics log noise when idle - include speculative decodi…
  vllm/engine/metrics.py
Labels: ready

#10811 [Kernel] Use `out` in flash_attn_varlen_func
  CMakeLists.txt
  tests/kernels/test_flash_attn.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, ci/build

#10799 Fill TorchSDPAAttentionMetadata seq_lens_field for prefill
  vllm/attention/backends/torch_sdpa.py
Labels: ready

#10814 [misc] remove xverse modeling file
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/xverse.py
Labels: ready

#10732 [doc]Update config docstring
  vllm/config.py
Labels: ready

#10770 [Model]: add some tests for aria model
  tests/conftest.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/core.py
  tests/models/decoder_only/vision_language/vlm_utils/types.py
Labels: ready

#10822 [misc] use out argument for flash attention
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/config.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready

#10829 [Misc][LoRA] Move the implementation of lora bias to punica.py
  tests/lora/test_llama_tp.py
  vllm/lora/fully_sharded_layers.py
  vllm/lora/layers.py
  vllm/lora/punica.py
Labels: ready

#10747 [Misc][XPU] Avoid torch compile for XPU platform
  .buildkite/run-xpu-test.sh
  vllm/plugins/__init__.py
Labels: ready, ci/build

#10793 Fix openvino on GPU
  vllm/worker/openvino_worker.py
Labels: ready

#10834 [Model] Add TP and BNB quantization support to LlavaMultiModalProjector
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/llava.py
Labels: ready

#10753 [Bugfix] Prevent benchmark_throughput.py from using duplicated random prompts
  benchmarks/benchmark_throughput.py
Labels: ready

#10842 [Model] support bitsandbytes quantization with minicpm model
  vllm/model_executor/models/minicpm.py
Labels: ready

#10844 [Bugfix] Fix QKVParallelLinearWithShardedLora bias bug
  .buildkite/test-pipeline.yaml
  vllm/lora/fully_sharded_layers.py
Labels: ready, ci/build

#10843 [core][distributed] add pynccl broadcast
  tests/distributed/test_pynccl.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/device_communicators/pynccl_wrapper.py
Labels: ready

#10838 [torch.compile] remove compilation_context and simplify code
  tests/compile/piecewise/test_simple.py
  tests/compile/piecewise/test_toy_llama.py
  tests/models/decoder_only/language/test_jamba.py
  tests/models/decoder_only/language/test_mamba.py
  tests/worker/test_encoder_decoder_model_runner.py
  tests/worker/test_model_runner.py
  vllm/compilation/backends.py
  vllm/compilation/compile_context.py
  vllm/config.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mamba.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
Labels: ready

#10672 [Doc] Add github links for source code references
  docs/requirements-docs.txt
  docs/source/conf.py
Labels: documentation, ready

#10817 [Misc] Remove deprecated names
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/entrypoints/llm.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/model_executor/models/aria.py
  vllm/multimodal/__init__.py
  vllm/multimodal/base.py
Labels: frontend, ready

#10785 [Core][Performance] Add XGrammar support for guided decoding and set it as default
  docs/source/conf.py
  requirements-common.txt
  tests/entrypoints/llm/test_guided_generate.py
  tests/model_executor/test_guided_processors.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
Labels: documentation, performance, frontend, ready, ci/build

#10850 [Speculative Decoding] Move indices to device before filtering output
  vllm/spec_decode/multi_step_worker.py
Labels: ready

#10640 [V1] VLM - Run the mm_mapper preprocessor in the frontend process
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/inputs/data.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/core.py
  vllm/v1/engine/processor.py
  vllm/v1/request.py
Labels: frontend, ready

#10859 [MISC][XPU] quick fix for XPU CI
  .buildkite/run-xpu-test.sh
Labels: ready, ci/build

#10865 [Bugfix] Only require XGrammar on x86
  requirements-common.txt
  vllm/model_executor/guided_decoding/__init__.py
  vllm/platforms/__init__.py
  vllm/platforms/interface.py
Labels: ready, ci/build

#10853 [Bugfix][Frontend] correctly record prefill and decode time metrics
  vllm/engine/metrics.py
Labels: ready

#10866 [Build][Bugfix] Using the correct type hint
  vllm/utils.py
Labels: ready

#10557 [Benchmark] Benchmark structured output with datasets
  benchmarks/benchmark_guided.py
  benchmarks/structured_schemas/structured_schema_1.json
Labels: ready

#10876 [CI/Build] Replace mean with torch.all in test_pynccl.py
  tests/distributed/test_pynccl.py
Labels: ready

#10767 Drop ROCm load format check
  vllm/config.py
Labels: ready

#10875 [ci/build] Change queue name for Release jobs
  .buildkite/release-pipeline.yaml
Labels: ready, ci/build

#10877 [ci/build] Job to build and push release image
  .buildkite/release-pipeline.yaml
Labels: ready, ci/build

#10854 [bugfix] fixed parameter “n” not work when set parameter “bestof” > 1
  vllm/sampling_params.py
Labels: ready

#10887 [ci/build] Update vLLM postmerge ECR repo
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
  .buildkite/nightly-benchmarks/scripts/wait-for-image.sh
  docs/source/getting_started/installation.rst
Labels: documentation, ready, ci/build

#10796 [LoRA] Change lora_tokenizers capacity
  tests/lora/test_tokenizer_group.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/transformers_utils/tokenizer_group/__init__.py
  vllm/transformers_utils/tokenizer_group/tokenizer_group.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/llm_engine.py
Labels: ready

#10880 Benchmark serving structured output
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving_guided.py
Labels: ready

#9621 [CI/Build] improve python-only dev setup
  docs/source/getting_started/installation.rst
  python_only_dev.py
  setup.py
  vllm/envs.py
Labels: documentation, ready, ci/build

#10903 [V1] Fix when max_model_len is not divisible by block_size
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#10908 [benchmark] Make H100 benchmark optional
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
Labels: ci/build

#10899 [Bugfix] Fallback to outlines for complex json schemas
  tests/entrypoints/conftest.py
  tests/entrypoints/llm/test_guided_generate.py
  vllm/model_executor/guided_decoding/__init__.py
Labels: ready

#10827 [Doc] Create a new "Usage" section
  docs/source/design/multimodal/multimodal_index.rst
  docs/source/index.rst
  docs/source/models/enabling_multimodal_inputs.rst
  docs/source/models/supported_models.rst
  docs/source/serving/openai_compatible_server.md
  docs/source/usage/compatibility_matrix.rst
  docs/source/usage/engine_args.rst
  docs/source/usage/env_vars.rst
  docs/source/usage/faq.rst
  docs/source/usage/lora.rst
  docs/source/usage/multimodal_inputs.rst
  docs/source/usage/performance.rst
  docs/source/usage/spec_decode.rst
  docs/source/usage/structured_outputs.rst
  docs/source/usage/usage_stats.md
  vllm/attention/backends/rocm_flash_attn.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/output_processor/multi_step.py
  vllm/executor/cpu_executor.py
  vllm/platforms/cpu.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/utils.py
  vllm/worker/multi_step_model_runner.py
  vllm/worker/utils.py
Labels: documentation, ready

#10720 [Bugfix] Fix BNB loader target_modules
  vllm/model_executor/model_loader/loader.py
Labels: ready

#10901 [Misc] Update llama 3.2 template to support system prompt with images
  examples/tool_chat_template_llama3.2_json.jinja
Labels: ready

#10917 [Misc][LoRA] Clean up the function interface of Punica
  tests/lora/test_layers.py
  vllm/lora/fully_sharded_layers.py
  vllm/lora/layers.py
  vllm/lora/models.py
  vllm/lora/punica.py
Labels: ready

#10106 [CI/Build] Bump test transformers version
  requirements-test.txt
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_pixtral.py
  tests/models/embedding/vision_language/test_llava_next.py
  tests/models/test_initialization.py
Labels: ready, ci/build

#10897 [Misc][Gaudi] Avoid torch.compile and enable lazy collectives by default for HPU lazy backend
  vllm/plugins/__init__.py
Labels: ready

#10915 [ci][build] add tests for python only compilation
  .buildkite/test-pipeline.yaml
  setup.py
  tests/standalone_tests/lazy_torch_compile.py
  tests/standalone_tests/python_only_compile.sh
Labels: ci/build

#10941 [torch.compile] add logging for compilation time
  vllm/compilation/backends.py
  vllm/compilation/decorators.py
  vllm/compilation/monitor.py
  vllm/config.py
  vllm/engine/llm_engine.py
  vllm/v1/engine/core.py
Labels: ready

#10950 [CI/Build] Fix broken multimodal test
  tests/models/embedding/vision_language/test_llava_next.py
Labels: ready

#10870 [Core] Support Lark grammars for XGrammar
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
  vllm/model_executor/guided_decoding/xgrammar_utils.py
Labels: ready

#10837 [Doc] add KubeAI to serving integrations
  docs/source/serving/deploying_with_kubeai.rst
  docs/source/serving/integrations.rst
Labels: documentation, ready

#10961 [Core] Cleanup startup logging a bit
  vllm/engine/arg_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/plugins/__init__.py
Labels: frontend, ready

#10973 [Bugfix] Fix test-pipeline.yaml
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build

#10676 [3/N] Support and implement merged input processor for LLaVA model
  tests/multimodal/test_mapper.py
  tests/multimodal/test_processing.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  vllm/inputs/registry.py
  vllm/model_executor/models/llava.py
  vllm/multimodal/base.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
  vllm/v1/engine/mm_input_mapper.py
  vllm/v1/engine/processor.py
Labels: ready

#10060 [Build] Fix for the Wswitch-bool clang warning
  csrc/attention/paged_attention_v1.cu
  csrc/attention/paged_attention_v2.cu
Labels: ready

#10958 [Misc][LoRA] Refactor and clean MergedQKVParallelLinearWithLora implementation
  vllm/lora/layers.py
Labels: ready

#10944 [Model] Composite weight loading for multimodal Qwen2
  vllm/config.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/utils.py
Labels: ready

#10978 [Doc] Explicitly state that InternVL 2.5 is supported
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
Labels: documentation, ready

#10711 [Model] Update multi-modal processor to support Mantis(LLaVA) model
  .buildkite/test-pipeline.yaml
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  requirements-test.in
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/core.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  tests/models/decoder_only/vision_language/vlm_utils/types.py
  tests/models/registry.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/registry.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
Labels: documentation, ready, ci/build

#10975 [Doc] Explicitly state that PP isn't compatible with speculative decoding yet
  docs/source/usage/spec_decode.rst
  tests/distributed/test_pipeline_parallel.py
  vllm/model_executor/models/exaone.py
  vllm/model_executor/models/granite.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/nemotron.py
  vllm/model_executor/models/solar.py
  vllm/spec_decode/spec_decode_worker.py
Labels: documentation, ready

#10928 [BugFix][Kernel]: fix illegal memory access in causal_conv1d when conv_states is None
  csrc/mamba/causal_conv1d/causal_conv1d.cu
  tests/kernels/test_causal_conv1d.py
Labels: ready

#10976 [core][executor] simplify instance id
  vllm/config.py
  vllm/envs.py
  vllm/executor/cpu_executor.py
  vllm/executor/multiproc_gpu_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/executor/ray_hpu_executor.py
  vllm/executor/ray_tpu_executor.py
  vllm/executor/ray_xpu_executor.py
  vllm/utils.py
  vllm/worker/worker_base.py
Labels: ready

#10920 [core][misc] remove use_dummy driver for _run_workers
  vllm/executor/ray_gpu_executor.py
  vllm/executor/ray_hpu_executor.py
  vllm/executor/ray_tpu_executor.py
  vllm/executor/ray_xpu_executor.py
Labels: ready

#10984 [torch.compile] allow candidate compile sizes
  tests/engine/test_arg_utils.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/llm.py
Labels: frontend, ready

#10699 [V1] Initial support of multimodal models for V1 re-arch
  vllm/engine/arg_utils.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/utils.py
  vllm/multimodal/inputs.py
  vllm/multimodal/utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/mm_input_mapper.py
Labels: ready

#10998 [Doc][V1] Add V1 support column for multimodal models
  docs/source/models/supported_models.rst
Labels: documentation, ready

#11021 [Core] Require xgrammar >= 0.1.6
  requirements-common.txt
Labels: ready, ci/build

#10768 [Platform] Move `async output` check to platform
  vllm/config.py
  vllm/platforms/cpu.py
  vllm/platforms/cuda.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/openvino.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
Labels: ready

#10989 [V1] Further reduce CPU overheads in flash-attn
  csrc/cache_kernels.cu
  vllm/v1/attention/backends/flash_attn.py
Labels: ready

#10977 [Model] Implement merged input processor for Phi-3-Vision models
  tests/entrypoints/openai/test_vision.py
  tests/entrypoints/openai/test_vision_embedding.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_phi3v.py
  tests/multimodal/test_processor_kwargs.py
  vllm/inputs/registry.py
  vllm/model_executor/models/phi3v.py
  vllm/multimodal/processing.py
Labels: ready

#11028 [Bugfix][Hardware][Gaudi] Bump vllm_hpu_extension version
  requirements-hpu.txt
  vllm/attention/backends/hpu_attn.py
Labels: ci/build

#11016 [Neuron] Upgrade neuron to 2.20.2
  Dockerfile.neuron
  vllm/utils.py
Labels: ci/build

#10936 Build tpu image in release pipeline
  .buildkite/release-pipeline.yaml
Labels: ready, ci/build

#10554 [Docs] Add dedicated tool calling page to docs
  docs/source/index.rst
  docs/source/serving/openai_compatible_server.md
  docs/source/usage/tool_calling.md
Labels: documentation, ready

#10739 [Model] Add has_weight to RMSNorm and re-enable weights loading tracker for Mamba
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/mamba/mamba_mixer.py
  vllm/model_executor/models/mamba.py
Labels: ready

#11025 [Bugfix] Fix usage of `deprecated` decorator
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/entrypoints/llm.py
Labels: frontend, ready

#10968 [Frontend] Use request id from header
  docs/requirements-docs.txt
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_score.py
  vllm/entrypoints/openai/serving_tokenization.py
Labels: documentation, frontend, ready

#11040 [Pixtral] Improve loading
  vllm/model_executor/models/pixtral.py
Labels: ready

#9856 [V1] Multiprocessing Tensor Parallel Support for v1
  tests/basic_correctness/test_basic_correctness.py
  tests/conftest.py
  vllm/distributed/device_communicators/shm_broadcast.py
  vllm/executor/multiproc_gpu_executor.py
  vllm/executor/multiproc_worker_utils.py
  vllm/model_executor/layers/logits_processor.py
  vllm/platforms/cuda.py
  vllm/utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/executor/abstract.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/executor/uniproc_executor.py
  vllm/v1/outputs.py
  vllm/v1/sample/sampler.py
  vllm/v1/utils.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready

#11031 monitor metrics of tokens per step using cudagraph batchsizes
  tests/metrics/test_metrics.py
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
  vllm/engine/metrics_types.py
Labels: ready

#11043 [Bugfix] Fix xgrammar failing to read a vocab_size from LlavaConfig on PixtralHF.
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
Labels: ready

#11034 Update README.md
  README.md
Labels: documentation

#11047 [Bugfix] cuda error running llama 3.2
  vllm/platforms/cuda.py
Labels: ready

#9199 Add example of helm chart for vllm deployment on k8s
  .github/workflows/lint-and-deploy.yaml
  docs/source/index.rst
  docs/source/serving/architecture_helm_deployment.png
  docs/source/serving/deploying_with_helm.rst
  examples/chart-helm/.helmignore
  examples/chart-helm/Chart.yaml
  examples/chart-helm/ct.yaml
  examples/chart-helm/lintconf.yaml
  examples/chart-helm/templates/_helpers.tpl
  examples/chart-helm/templates/configmap.yaml
  examples/chart-helm/templates/custom-objects.yaml
  examples/chart-helm/templates/deployment.yaml
  examples/chart-helm/templates/hpa.yaml
  examples/chart-helm/templates/job.yaml
  examples/chart-helm/templates/poddisruptionbudget.yaml
  examples/chart-helm/templates/pvc.yaml
  examples/chart-helm/templates/secrets.yaml
  examples/chart-helm/templates/service.yaml
  examples/chart-helm/values.schema.json
  examples/chart-helm/values.yaml
Labels: documentation, frontend, ready, ci/build

#11039 [Bugfix] Handle <|tool_call|> token in granite tool parser
  vllm/entrypoints/openai/tool_parsers/granite_tool_parser.py
Labels: frontend, ready

#11003 [Misc][LoRA] Add PEFTHelper for LoRA
  tests/lora/test_lora_manager.py
  vllm/lora/lora.py
  vllm/lora/models.py
  vllm/lora/peft_helper.py
Labels: ready

#11022 [BUG] Remove token param #10921
  vllm/transformers_utils/config.py
Labels: ready

#10576 [Core] Update to outlines >= 0.1.8
  requirements-common.txt
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
Labels: ready, ci/build

#11059 [torch.compile] add a flag to track batchsize statistics
  vllm/envs.py
  vllm/forward_context.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#11061 [V1][Bugfix] Always set enable_chunked_prefill = True for V1
  vllm/engine/arg_utils.py
Labels: ready

#11071 [Bugfix] Fix Mamba multistep
  vllm/attention/backends/placeholder_attn.py
  vllm/worker/multi_step_model_runner.py
Labels: ready

#9057 [Misc] LoRA + Chunked Prefill
  tests/lora/test_chatglm3_tp.py
  tests/lora/test_gemma.py
  tests/lora/test_llama_tp.py
  tests/lora/test_long_context.py
  tests/lora/test_minicpmv.py
  tests/lora/test_minicpmv_tp.py
  tests/lora/test_mixtral.py
  tests/lora/test_phi.py
  tests/lora/test_quant_model.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/worker/model_runner.py
Labels: ready

#10992 [Model] PP support for Mamba-like models
  docs/source/models/supported_models.rst
  tests/distributed/test_pipeline_parallel.py
  vllm/config.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mamba.py
  vllm/model_executor/models/registry.py
  vllm/utils.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
  vllm/worker/cache_engine.py
Labels: documentation, ready

#11069 Fix streaming for granite tool call when <|tool_call|> is present
  vllm/entrypoints/openai/tool_parsers/granite_tool_parser.py
Labels: frontend, ready

#10991 [CI/Build] Check transformers v4.47
  requirements-test.txt
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_idefics3.py
  tests/models/embedding/vision_language/test_llava_next.py
Labels: ready, ci/build

#11087 [ci/build] Fix AMD CI dependencies
  requirements-rocm.txt
Labels: ready, ci/build

#11088 [ci/build] Fix entrypoints test and pin outlines version
  requirements-common.txt
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
Labels: ci/build

#11076 [Core] v1: Use atexit to handle engine core client shutdown
  vllm/v1/engine/core_client.py
Labels: ready

#11080 [Bugfix] Fix Idefics3 fails during multi-image inference
  vllm/model_executor/models/idefics3.py
Labels: ready

#11073 [Bugfix]: Clamp `-inf` logprob values in prompt_logprobs
  vllm/entrypoints/openai/serving_completion.py
Labels: frontend, ready

#11093 [Doc] Update docs to refer to pooling models
  docs/source/usage/faq.rst
  vllm/attention/backends/placeholder_attn.py
  vllm/config.py
  vllm/core/placeholder_block_space_manager.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/serving_score.py
  vllm/sequence.py
  vllm/v1/engine/processor.py
  vllm/worker/cpu_worker.py
  vllm/worker/hpu_worker.py
  vllm/worker/worker.py
Labels: documentation, frontend, ready

#11098 [CI/Build] Enable prefix caching test for AMD
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build

#11103 [Doc] Installed version of llmcompressor for int8/fp8 quantization
  docs/source/quantization/fp8.rst
  docs/source/quantization/int8.rst
Labels: documentation, ready

#10972 [torch.compile] use depyf to dump torch.compile internals
  requirements-common.txt
  vllm/compilation/backends.py
  vllm/compilation/decorators.py
  vllm/compilation/monitor.py
  vllm/compilation/wrapper.py
  vllm/config.py
  vllm/worker/model_runner.py
Labels: ci/build

#10410 [core] Bump ray to use _overlap_gpu_communication in compiled graph tests
  requirements-test.in
  requirements-test.txt
  vllm/envs.py
  vllm/executor/ray_gpu_executor.py
Labels: ready, ci/build

#11083 [CI/Build] Split up VLM tests
  .buildkite/test-pipeline.yaml
  pyproject.toml
  tests/models/decoder_only/vision_language/test_models.py
  tests/utils.py
Labels: ready, ci/build

#11113 [V1][Core] Remove should_shutdown to simplify core process termination
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
Labels: ready

#11020 [V1] VLM preprocessor hashing
  examples/offline_inference_vision_language.py
  requirements-common.txt
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/core.py
  vllm/v1/engine/mm_input_mapper.py
  vllm/v1/engine/processor.py
  vllm/v1/utils.py
Labels: ready, ci/build

#10979 [Bugfix] Multiple fixes to tool streaming with hermes and mistral
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: frontend, ready

#11112 Update link to LlamaStack remote vLLM guide in serving_with_llamastack.rst
  docs/source/serving/serving_with_llamastack.rst
Labels: documentation, ready

#10816 [Model] Add support for embedding model GritLM
  docs/source/models/supported_models.rst
  tests/models/embedding/language/test_gritlm.py
  tests/models/registry.py
  vllm/model_executor/models/gritlm.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready

#11111 [V1] Use more persistent buffers to optimize input preparation overheads
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#10986 [core][distributed] initialization from StatelessProcessGroup
  .buildkite/test-pipeline.yaml
  tests/distributed/test_same_node.py
  tests/distributed/test_shm_broadcast.py
  vllm/distributed/device_communicators/shm_broadcast.py
  vllm/distributed/parallel_state.py
Labels: ready, ci/build

#11094 [Misc][LoRA] Ensure Lora Adapter requests return adapter name
  tests/entrypoints/openai/test_serving_engine.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend, ready

#11141 fix(docs): typo in helm install instructions
  docs/source/serving/deploying_with_helm.rst
Labels: documentation, ready

#11024 [Bugfix] Quick fix to make Pixtral-HF load correctly again after 39e227c7ae.
  vllm/model_executor/models/llava.py
Labels: ready

#11119 [Misc] Validate grammar and fail early
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
  vllm/model_executor/guided_decoding/xgrammar_utils.py
Labels: ready

#11151 [Misc][V1] Fix type in v1 prefix caching
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
Labels: ready

#10906 [torch.compile] Dynamic fp8 + rms_norm fusion
  CMakeLists.txt
  benchmarks/fused_kernels/layernorm_rms_benchmarks.py
  csrc/dispatch_utils.h
  csrc/ops.h
  csrc/quantization/fp8/common.cuh
  csrc/quantization/fused_kernels/fused_layernorm_dynamic_per_token_quant.cu
  csrc/quantization/fused_kernels/layernorm_utils.cuh
  csrc/quantization/fused_kernels/quant_conversions.cuh
  csrc/quantization/vectorization.cuh
  csrc/torch_bindings.cpp
  tests/compile/test_functionalization.py
  tests/compile/test_fusion.py
  tests/kernels/test_fused_quant_layernorm.py
  vllm/_custom_ops.py
  vllm/compilation/fix_functionalization.py
  vllm/compilation/fusion.py
  vllm/compilation/fx_utils.py
  vllm/compilation/multi_output_match.py
  vllm/compilation/reshapes.py
  vllm/compilation/vllm_inductor_pass.py
Labels: ready, ci/build

#11144 [Bugfix] Use runner_type instead of task in GritLM
  tests/models/embedding/language/test_gritlm.py
  vllm/model_executor/models/gritlm.py
Labels: ready

#11148 [Bugfix] Update starcoder2 to remap k/v scale names for kv_cache quantization
  vllm/model_executor/models/starcoder2.py
Labels: ready

#11146 [ROCm][AMD] Disable auto enabling chunked prefill on ROCm
  vllm/engine/arg_utils.py
Labels: ready

#10996 [core] clean up cudagraph batchsize padding logic
  tests/models/decoder_only/language/test_jamba.py
  tests/models/decoder_only/language/test_mamba.py
  tests/worker/test_encoder_decoder_model_runner.py
  tests/worker/test_model_runner.py
  vllm/config.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mamba.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: ready

#11142 PaliGemma 2 support
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  vllm/model_executor/models/paligemma.py
Labels: documentation, ready

#11129 [Frontend] Separate pooling APIs in offline inference
  .buildkite/test-pipeline.yaml
  docs/source/models/pooling_models.rst
  examples/offline_inference_classification.py
  examples/offline_inference_embedding.py
  examples/offline_inference_scoring.py
  examples/offline_inference_vision_language_embedding.py
  tests/conftest.py
  tests/entrypoints/openai/test_score.py
  tests/models/embedding/language/test_scoring.py
  tests/models/test_oot_registration.py
  vllm/__init__.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_score.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/gritlm.py
  vllm/outputs.py
  vllm/sequence.py
Labels: documentation, frontend, ready, ci/build

#11165 [V1][VLM] Fix edge case bug for InternVL2
  vllm/model_executor/models/internvl.py
Labels: ready

#11163 [Refactor]A simple device-related refactor
  vllm/platforms/cpu.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/openvino.py
  vllm/platforms/xpu.py
  vllm/utils.py
Labels: ready

#8240 [Core] support LoRA and prompt adapter in content-based hashing for Block Manager v2 prefix caching
  tests/core/block/test_prefix_caching_block.py
  tests/core/utils.py
  vllm/core/block/block_table.py
  vllm/core/block/common.py
  vllm/core/block/cpu_gpu_block_allocator.py
  vllm/core/block/interfaces.py
  vllm/core/block/naive_block.py
  vllm/core/block/prefix_caching_block.py
  vllm/core/block_manager.py
  vllm/sequence.py
Labels: ready

#11156 [Bugfix] using len(tokenizer) instead of tokenizer.vocab_size in AllowedTokenIdsLogitsProcessor
  vllm/entrypoints/openai/logits_processors.py
Labels: frontend, ready

#11174 [Misc] Add tokenizer_mode param to benchmark_serving.py
  benchmarks/benchmark_serving.py
Labels: ready

#11172 [Doc] Reorganize online pooling APIs
  docs/source/models/pooling_models.rst
  docs/source/serving/openai_compatible_server.md
  docs/source/usage/multimodal_inputs.rst
  examples/offline_inference_openai.md
  examples/openai_chat_embedding_client_for_multimodal.py
  examples/openai_cross_encoder_score.py
  tests/entrypoints/openai/test_score.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/outputs.py
Labels: documentation, frontend, ready

#11138 [Distributed] Allow the placement group more time to wait for resources to be ready
  vllm/executor/ray_utils.py
Labels: ready

#11074 [Core] V1: Use multiprocessing by default
  docs/source/design/multiprocessing.md
  docs/source/getting_started/debugging.rst
  docs/source/index.rst
  vllm/entrypoints/llm.py
  vllm/envs.py
  vllm/executor/multiproc_worker_utils.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/executor/multiproc_executor.py
Labels: documentation, frontend, ready

#11185 [V1][Bugfix] Fix EngineCoreProc profile
  vllm/v1/engine/core.py
Labels: ready

#11183 update compressed-tensors to latest version
  requirements-common.txt
Labels: ready, ci/build

#11140 [Core] Update outlines and increase its threadpool size
  requirements-common.txt
  vllm/model_executor/guided_decoding/outlines_decoding.py
Labels: ready, ci/build

#11182 [V1][Bugfix] Fix V1 TP trust-remote-code
  vllm/v1/engine/core.py
Labels: ready

#11200 [Misc] Minor improvements to the readability of PunicaWrapperBase
  vllm/lora/punica_wrapper/punica_base.py
  vllm/lora/punica_wrapper/punica_gpu.py
  vllm/lora/punica_wrapper/punica_hpu.py
Labels: ready

#11150 [Frontend] Add `logits_processors` as an extra completion argument
  tests/entrypoints/openai/test_serving_chat.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
Labels: frontend, ready

#11199 [VLM] Fully dynamic prompt replacement in merged input processor
  examples/offline_inference_vision_language.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_phi3v.py
  tests/multimodal/test_processing.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  vllm/inputs/registry.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/multimodal/base.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
  vllm/utils.py
Labels: ready

#11105 Enable mypy checking on V1 code
  tools/mypy.sh
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/mm_input_mapper.py
  vllm/v1/engine/processor.py
  vllm/v1/executor/abstract.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/executor/uniproc_executor.py
  vllm/v1/request.py
  vllm/v1/utils.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready

#7209 [Performance][Core] Optimize the performance of evictor v1 and v2 by applying a priority queue and lazy deletion
  vllm/core/evictor.py
Labels: ready

#11201 [[Misc]Upgrade bitsandbytes to the latest version 0.45.0
  Dockerfile
  docs/source/quantization/bnb.rst
  requirements-test.in
  requirements-test.txt
  vllm/model_executor/layers/quantization/bitsandbytes.py
Labels: documentation, ready, ci/build

#11081 [torch.compile] allow tracking forward time
  vllm/forward_context.py
Labels: ready

#11207 [Misc] Clean up multi-modal processor
  examples/offline_inference_vision_language.py
  tests/multimodal/test_processing.py
  vllm/multimodal/processing.py
Labels: ready

#11213 [Bugfix] Fix error handling of unsupported sliding window
  vllm/model_executor/models/llama.py
Labels: ready
