Repository vllm-project/vllm, pull requests merged in 2024-02, with the labels that each got.

#2498 [ROCm] Fix some kernels failed unit tests
  tests/kernels/allclose_default.py
  tests/kernels/test_activation.py
  tests/kernels/test_attention.py
  tests/kernels/test_cache.py
  tests/kernels/test_pos_encoding.py
Labels: rocm

#2627 [ROCm] Fixup arch checks for ROCM
  Dockerfile.rocm
  setup.py
Labels: rocm

#2768 [ROCm] support Radeon™ 7900 series (gfx1100) without using flash-attention
  Dockerfile.rocm
  docs/source/getting_started/amd-installation.rst
  setup.py
  vllm/model_executor/layers/attention.py
Labels: rocm

#2855 Don't use cupy NCCL for AMD backends
  vllm/model_executor/parallel_utils/custom_all_reduce.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: rocm, v0.3.1

#2882 [BugFix] Fix GC bug for `LLM` class
  tests/test_regression.py
  vllm/lora/punica.py
Labels: v0.3.1

#2792 [ROCm] include gfx908 as supported
  setup.py
Labels: rocm

#2514 Support per-request seed
  tests/samplers/test_sampler.py
  tests/samplers/test_seeded_generate.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/sampling_metadata.py
  vllm/sampling_params.py
  vllm/sequence.py
  vllm/worker/model_runner.py
Labels: v0.3.2

#2918 Add LogProbs for Chat Completions in OpenAI
  tests/entrypoints/test_openai_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend

#2979 Optimized fused MoE Kernel, take 2
  benchmarks/kernels/benchmark_mixtral_moe.py
  setup.py
  vllm/model_executor/layers/fused_moe/__init__.py
  vllm/model_executor/layers/fused_moe/configs/E=8,N=3584,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=7168,device_name=NVIDIA_H100_80GB_HBM3.json
  vllm/model_executor/layers/fused_moe/configs/README
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: kernel, moe

#2569 Support inference with transformers-neuronx
  examples/offline_inference_neuron.py
  tests/lora/conftest.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/lora/layers.py
  vllm/model_executor/__init__.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/model_loader.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/neuron/llama.py
  vllm/model_executor/neuron_model_loader.py
  vllm/model_executor/sampling_metadata.py
  vllm/model_executor/utils.py
  vllm/utils.py
  vllm/worker/cache_engine.py
  vllm/worker/model_runner.py
  vllm/worker/neuron_worker.py
Labels: Inferentia/Trainium

#2330 Add Support for 2/3/8-bit GPTQ Quantization Models
  csrc/ops.h
  csrc/quantization/gptq/matrix_view.cuh
  csrc/quantization/gptq/q_gemm.cu
  csrc/quantization/gptq/qdq_2.cuh
  csrc/quantization/gptq/qdq_3.cuh
  csrc/quantization/gptq/qdq_4.cuh
  csrc/quantization/gptq/qdq_8.cuh
  vllm/model_executor/layers/quantization/gptq.py
Labels: quantization

#3099 [Fix] Don't deep-copy LogitsProcessors when copying SamplingParams
  vllm/engine/llm_engine.py
  vllm/sampling_params.py
Labels: v0.3.3
