Repository vllm-project/vllm, pull requests merged in 2024-07, with the labels that each got.

#6043 [ROCm][AMD][Model]Adding alibi slopes support in ROCm triton flash attention and naive flash attention
  vllm/attention/backends/rocm_flash_attn.py
Labels: rocm

#6008 [Hardware][Intel CPU] Adding intel openmp tunings in Docker file
  .buildkite/run-cpu-test.sh
  Dockerfile.cpu
  vllm/utils.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU

#6157 bump version to v0.5.1
  vllm/version.py
Labels: perf-benchmarks

#6245 [Bugfix][TPU] Add missing None to model input
  vllm/worker/tpu_model_runner.py
Labels: tpu

#6279 [Bugfix][TPU] Add prompt adapter methods to TPUExecutor
  vllm/executor/tpu_executor.py
Labels: tpu

#6313 [Bugfix][Neuron] Fix soft prompt method error in NeuronExecutor
  vllm/executor/neuron_executor.py
Labels: Inferentia/Trainium

#6003 [Doc] Update description of vLLM support for CPUs
  README.md
  docs/source/getting_started/cpu-installation.rst
Labels: x86 CPU

#6047 Benchmark: add H100 suite
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
  .buildkite/nightly-benchmarks/run-benchmarks-suite.sh
Labels: perf-benchmarks

#5362 [CI/Build] Add nightly benchmarking for tgi, tensorrt-llm and lmdeploy
  .buildkite/nightly-benchmarks/README.md
  .buildkite/nightly-benchmarks/kickoff-pipeline.sh
  .buildkite/nightly-benchmarks/nightly-descriptions.md
  .buildkite/nightly-benchmarks/nightly-pipeline.yaml
  .buildkite/nightly-benchmarks/run-nightly-suite.sh
  .buildkite/nightly-benchmarks/scripts/download-tokenizer.py
  .buildkite/nightly-benchmarks/scripts/get-lmdeploy-modelname.py
  .buildkite/nightly-benchmarks/scripts/launch-trt-server.sh
  .buildkite/nightly-benchmarks/scripts/nightly-annotate.sh
  .buildkite/nightly-benchmarks/scripts/plot-nightly-results.py
  .buildkite/nightly-benchmarks/scripts/run-lmdeploy-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-tgi-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-trt-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-vllm-nightly.sh
  .buildkite/nightly-benchmarks/scripts/summary-nightly-results.py
  .buildkite/nightly-benchmarks/tests/nightly-tests.json
  README.md
  benchmarks/benchmark_serving.py
Labels: perf-benchmarks, nightly-benchmarks

#6352 [ROCm][AMD] unify CUDA_VISIBLE_DEVICES usage in vllm to get device count
  Dockerfile.rocm
  tests/distributed/test_utils.py
  vllm/config.py
  vllm/utils.py
  vllm/worker/worker_base.py
Labels: rocm

#5327 [MISC] Upgrade dependency to PyTorch 2.3.1
  .github/workflows/publish.yml
  CMakeLists.txt
  pyproject.toml
  requirements-build.txt
  requirements-cuda.txt
Labels: perf-benchmarks

#6382 [Bugfix] Fix illegal memory access in FP8 MoE kernel
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#6386 [Misc] Add generated git commit hash as `vllm.__commit__`
  .gitignore
  setup.py
  tests/test_embedded_commit.py
  vllm/__init__.py
  vllm/version.py
Labels: ready

#6397 [Bugfix][TPU] Fix megacore setting for v5e-litepod
  vllm/attention/backends/pallas.py
Labels: tpu

#6392 [Doc] Fix Typo in Doc
  README.md
  docs/source/index.rst
Labels: ready

#6280 [ci] try to add multi-node tests
  .buildkite/run-multi-node-test.sh
  .buildkite/test-pipeline.yaml
  tests/async_engine/test_openapi_server_ray.py
  tests/distributed/test_pipeline_parallel.py
  tests/distributed/test_same_node.py
  tests/entrypoints/openai/test_chat.py
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_embedding.py
  tests/entrypoints/openai/test_models.py
  tests/entrypoints/openai/test_vision.py
  tests/tensorizer_loader/test_tensorizer.py
  tests/utils.py
  vllm/executor/ray_gpu_executor.py
Labels: ready

#6411 Updating LM Format Enforcer version to v10.3
  requirements-common.txt
Labels: ready

#6359 [ Misc ] More Cleanup of Marlin
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
Labels: ready

#6402 [Misc] Add deprecation warning for beam search
  vllm/envs.py
  vllm/sampling_params.py
Labels: ready

#6417 [ Misc ] Apply MoE Refactor to Deepseekv2 To Support Fp8
  .buildkite/lm-eval-harness/configs/DeepSeek-V2-Lite-Chat.yaml
  .buildkite/lm-eval-harness/configs/models-large.txt
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/qwen2_moe.py
Labels: ready

#3924 [Model] Initialize Fuyu-8B support
  docs/source/models/supported_models.rst
  examples/fuyu_example.py
  tests/models/test_fuyu.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/persimmon.py
Labels: ready

#6405 Remove unnecessary trailing period in spec_decode.rst
  docs/source/models/spec_decode.rst
Labels: ready

#6384 [Kernel] Turn off CUTLASS scaled_mm for Ada Lovelace
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-FP8-compressed-tensors.yaml
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-FP8.yaml
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
Labels: ready

#6420 [ci][build] fix commit id
  .buildkite/test-pipeline.yaml
  Dockerfile
  setup.py
Labels: ready

#6423 [ Misc ] Enable Quantizing All Layers of DeekSeekv2
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#5090 [Feature] vLLM CLI for serving and querying OpenAI compatible server
  benchmarks/benchmark_serving.py
  docs/source/serving/openai_compatible_server.md
  setup.py
  tests/utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/scripts.py
Labels: ready

#6393 [Doc] xpu backend requires running setvars.sh
  docs/source/getting_started/xpu-installation.rst
Labels: Intel GPU

#6394 [CI/Build] Cross python wheel
  .buildkite/release-pipeline.yaml
  Dockerfile
Labels: ready

#6404 Report usage for beam search
  vllm/sampling_params.py
  vllm/usage/usage_lib.py
Labels: ready

#6345 [BugFix] BatchResponseData body should be optional
  tests/entrypoints/openai/test_run_batch.py
  vllm/entrypoints/openai/protocol.py
Labels: ready

#6406 [core][distributed] simplify code to support pipeline parallel
  .buildkite/test-pipeline.yaml
  tests/basic_correctness/test_basic_correctness.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/utils.py
Labels: ready

#6430 [Bugfix] Convert image to RGB by default
  vllm/multimodal/utils.py
Labels: ready

#6436 [VLM] Minor space optimization for `ClipVisionModel`
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/phi3v.py
Labels: ready

#6447 [Misc] Use 0.0.9 version for flashinfer
  Dockerfile
Labels: ready

#6409 [Bugfix] use float32 precision in samplers/test_logprobs.py for comparing with HF
  tests/samplers/test_logprobs.py
  vllm/attention/ops/prefix_prefill.py
Labels: ready

#6433 bump version to v0.5.2
  vllm/version.py
Labels: ready

#6277 [CI/Build][TPU] Add TPU CI test
  .buildkite/run-tpu-test.sh
  Dockerfile.tpu
  examples/offline_inference_tpu.py
Labels: tpu, ready

#6453 Pin sphinx-argparse version
  docs/requirements-docs.txt
Labels: ready

#6425 [BugFix][Model] Jamba - Handle aborted requests, Add tests and fix cleanup bug
  tests/models/test_jamba.py
  vllm/core/scheduler.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/jamba.py
Labels: ready

#6419 [Bugfix][CI/Build] Test prompt adapters in openai entrypoint tests
  tests/entrypoints/openai/test_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: ready

#6444 [CI/Build] vLLM cache directory for images
  .buildkite/download-images.sh
  .buildkite/test-pipeline.yaml
  examples/llava_example.py
  examples/paligemma_example.py
  examples/phi3v_example.py
  tests/conftest.py
  vllm/assets/__init__.py
  vllm/assets/base.py
  vllm/assets/image.py
  vllm/distributed/device_communicators/custom_all_reduce_utils.py
  vllm/envs.py
  vllm/usage/usage_lib.py
  vllm/worker/tpu_worker.py
Labels: ready

#6470 [Misc] Fix typos in spec. decode metrics logging.
  vllm/engine/metrics.py
Labels: ready

#6460 [CI/Build] Remove "boardwalk" image asset
  tests/conftest.py
  tests/models/test_fuyu.py
  tests/models/test_llava.py
  tests/models/test_llava_next.py
  tests/models/test_paligemma.py
  tests/models/test_phi3v.py
  vllm/assets/image.py
Labels: ready

#6457 [Hardware][TPU] Support MoE with Pallas GMM kernel
  Dockerfile.tpu
  docs/source/getting_started/tpu-installation.rst
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/moe_pallas.py
  vllm/worker/tpu_model_runner.py
Labels: tpu

#6454 [Misc] Log spec decode metrics
  tests/metrics/test_metrics.py
  tests/spec_decode/e2e/conftest.py
  tests/spec_decode/e2e/test_multistep_correctness.py
  vllm/engine/metrics.py
Labels: ready

#6081 [Kernel][Attention] Separate `Attention.kv_scale` into `k_scale` and `v_scale`
  benchmarks/kernels/benchmark_paged_attention.py
  csrc/attention/attention_kernels.cu
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/cpu/attention.cpp
  csrc/cpu/cache.cpp
  csrc/cpu/torch_bindings.cpp
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/kernels/test_attention.py
  tests/kernels/test_blocksparse_attention.py
  tests/kernels/test_cache.py
  tests/quantization/test_fp8.py
  vllm/_custom_ops.py
  vllm/_ipex_ops.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/attention/ops/ipex_attn.py
  vllm/attention/ops/paged_attn.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/qwen2.py
Labels: ready

#6410 [ci][distributed] add pipeline parallel correctness test
  .buildkite/test-pipeline.yaml
  tests/distributed/test_pipeline_parallel.py
  vllm/executor/multiproc_gpu_executor.py
Labels: ready

#6455 [Distributed][Model] Rank-based Component Creation for Pipeline Parallelism Memory Optimization
  vllm/model_executor/models/llama.py
Labels: ready

#6482 [ROCm] Cleanup Dockerfile and remove outdated patch
  Dockerfile.rocm
  docs/source/getting_started/amd-installation.rst
  rocm_patch/rocm_bf16.patch
Labels: rocm, ready

#6467 [Misc][Speculative decoding] Typos and typing fixes
  vllm/spec_decode/multi_step_worker.py
  vllm/spec_decode/ngram_worker.py
  vllm/spec_decode/proposer_worker_base.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/top1_proposer.py
Labels: ready

#6431 [Doc][CI/Build] Update docs and tests to use `vllm serve`
  docs/source/getting_started/quickstart.rst
  docs/source/models/adding_model.rst
  docs/source/models/engine_args.rst
  docs/source/models/lora.rst
  docs/source/models/vlm.rst
  docs/source/serving/deploying_with_dstack.rst
  docs/source/serving/distributed_serving.rst
  docs/source/serving/openai_compatible_server.md
  examples/api_client.py
  examples/logging_configuration.md
  examples/openai_vision_api_client.py
  examples/production_monitoring/Otel.md
  examples/production_monitoring/README.md
  tests/async_engine/test_openapi_server_ray.py
  tests/distributed/test_pipeline_parallel.py
  tests/entrypoints/openai/test_chat.py
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_embedding.py
  tests/entrypoints/openai/test_models.py
  tests/entrypoints/openai/test_tokenization.py
  tests/entrypoints/openai/test_vision.py
  tests/tensorizer_loader/test_tensorizer.py
  tests/utils.py
Labels: ready

#6495 [Bugfix] Fix for multinode crash on 4 PP
  tests/distributed/test_pipeline_parallel.py
  vllm/executor/ray_gpu_executor.py
Labels: ready

#6504 [TPU] Remove multi-modal args in TPU backend
  vllm/worker/tpu_model_runner.py
Labels: tpu

#6505 [Misc] Use `torch.Tensor` for type annotation
  benchmarks/cutlass_benchmarks/w8a8_benchmarks.py
  vllm/worker/worker.py
Labels: ready

#6164 [Core] Refactor _prepare_model_input_tensors - take 2
  tests/worker/test_model_input.py
  vllm/attention/__init__.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/attention/selector.py
  vllm/worker/model_runner.py
  vllm/worker/model_runner_base.py
Labels: ready

#6354 [Bugfix] Fix Ray Metrics API usage
  tests/metrics/test_metrics.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
Labels: ready

#6338 [Core] draft_model_runner: Implement prepare_inputs on GPU for advance_step
  CMakeLists.txt
  csrc/ops.h
  csrc/prepare_inputs/advance_step.cu
  csrc/prepare_inputs/advance_step.cuh
  csrc/torch_bindings.cpp
  tests/spec_decode/e2e/conftest.py
  tests/spec_decode/test_multi_step_worker.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/sampling_metadata.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/multi_step_worker.py
Labels: ready

#6511 [ Kernel ] FP8 Dynamic-Per-Token Quant Kernel
  csrc/ops.h
  csrc/quantization/fp8/common.cu
  csrc/torch_bindings.cpp
  tests/kernels/quant_utils.py
  tests/kernels/test_fp8_quant.py
  tests/kernels/test_int8_quant.py
  vllm/_custom_ops.py
Labels: ready

#6516 [Model] Pipeline parallel support for Mixtral
  tests/distributed/test_pipeline_parallel.py
  vllm/config.py
  vllm/model_executor/models/mixtral.py
Labels: ready

#6530 [BugFix] Avoid secondary error in ShmRingBuffer destructor
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#6032 [Core] Introduce SPMD worker execution using Ray accelerated DAG
  .buildkite/test-pipeline.yaml
  vllm/engine/llm_engine.py
  vllm/envs.py
  vllm/executor/distributed_gpu_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/executor/ray_utils.py
  vllm/executor/ray_xpu_executor.py
  vllm/worker/worker_base.py
Labels: ready

#6523 [Misc] Minor patch for draft model runner
  vllm/spec_decode/draft_model_runner.py
Labels: ready

#6227 [BugFix][Frontend] Use LoRA tokenizer in OpenAI APIs
  tests/async_engine/test_chat_template.py
  tests/entrypoints/openai/test_chat.py
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/entrypoints/openai/test_tokenization.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/chat_utils.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/transformers_utils/detokenizer.py
  vllm/transformers_utils/tokenizer.py
Labels: ready

#6501 [Bugfix] Update flashinfer.py with PagedAttention forwards - Fixes Gemma2 OpenAI Server Crash
  vllm/attention/backends/flashinfer.py
Labels: ready

#6506 [TPU] Refactor TPU worker & model runner
  vllm/worker/tpu_model_runner.py
  vllm/worker/tpu_worker.py
Labels: tpu

#6522 [ Misc ] Improve Min Capability Checking in `compressed-tensors`
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_scheme.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_unquantized.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w4a16_24.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
Labels: ready

#6548 [Model] Support Mistral-Nemo
  vllm/model_executor/models/llama.py
Labels: ready

#6549 [ci][test] add correctness test for cpu offloading
  .buildkite/test-pipeline.yaml
  tests/basic_correctness/test_cpu_offload.py
  tests/distributed/test_pipeline_parallel.py
  tests/utils.py
Labels: ready

#6552 [Kernel] Implement fallback for FP8 channelwise using torch._scaled_mm
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#6517 [CI/Build] Build on Ubuntu 20.04 instead of 22.04
  .buildkite/test-pipeline.yaml
  Dockerfile
  Dockerfile.openvino
  Dockerfile.xpu
Labels: ready

#6553 Add support for a rope extension method
  vllm/config.py
  vllm/model_executor/layers/rotary_embedding.py
Labels: ready

#6130 [Core] Multiprocessing Pipeline Parallel support
  .buildkite/test-pipeline.yaml
  tests/distributed/test_pipeline_parallel.py
  vllm/config.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/executor/multiproc_gpu_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/utils.py
  vllm/worker/worker_base.py
Labels: ready

#6034 [Bugfix] Make spec. decode respect per-request seed.
  tests/samplers/test_rejection_sampler.py
  tests/spec_decode/e2e/conftest.py
  tests/spec_decode/e2e/test_seed.py
  vllm/model_executor/layers/rejection_sampler.py
  vllm/model_executor/layers/spec_decode_base_sampler.py
  vllm/model_executor/layers/typical_acceptance_sampler.py
  vllm/spec_decode/batch_expansion.py
  vllm/spec_decode/spec_decode_worker.py
Labels: ready

#6515 [ Misc ] non-uniform quantization via `compressed-tensors` for `Llama`
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-nonuniform-compressed-tensors.yaml
  .buildkite/lm-eval-harness/configs/models-small.txt
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_unquantized.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/utils.py
Labels: ready

#6463 [Bugfix][Frontend] Fix missing `/metrics` endpoint
  tests/entrypoints/openai/test_basic.py
  vllm/entrypoints/openai/api_server.py
Labels: ready

#6369 [BUGFIX] Raise an error for no draft token case when draft_tp>1
  tests/spec_decode/e2e/test_integration_dist_tp4.py
  vllm/spec_decode/interfaces.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/top1_proposer.py
Labels: ready

#6327 [Model] RowParallelLinear: pass bias to quant_method.apply
  tests/spec_decode/e2e/test_integration_dist_tp2.py
  vllm/model_executor/layers/linear.py
Labels: ready

#6581 [Bugfix][Frontend] remove duplicate init logger
  vllm/entrypoints/openai/api_server.py
Labels: ready

#6520 [Misc] Small perf improvements
  tests/core/block/test_block_manager_v2.py
  tests/core/block/test_cpu_gpu_block_allocator.py
  vllm/core/block/block_table.py
  vllm/core/block/prefix_caching_block.py
  vllm/model_executor/models/__init__.py
  vllm/sequence.py
  vllm/utils.py
Labels: ready

#6578 [Bugfix] [SpecDecode] AsyncMetricsCollector: update time since last collection
  tests/spec_decode/test_metrics.py
  vllm/spec_decode/metrics.py
Labels: ready

#6547 [ Kernel ] Enable Dynamic Per Token `fp8`
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-Channelwise-compressed-tensors.yaml
  .buildkite/lm-eval-harness/configs/models-small.txt
  tests/kernels/test_fp8_quant.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#6593 [ Kernel ] FP8 Dynamic Per Token Quant - Add scale_ub
  csrc/ops.h
  csrc/quantization/fp8/common.cu
  csrc/torch_bindings.cpp
  tests/kernels/quant_utils.py
  tests/kernels/test_fp8_quant.py
  vllm/_custom_ops.py
Labels: ready

#6557 [Core] Allow specifying custom Executor
  tests/conftest.py
  tests/engine/test_custom_executor.py
  tests/tokenization/test_tokenizer_group.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/executor/cpu_executor.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/executor/multiproc_gpu_executor.py
  vllm/executor/neuron_executor.py
  vllm/executor/openvino_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/executor/ray_xpu_executor.py
  vllm/executor/tpu_executor.py
  vllm/executor/xpu_executor.py
  vllm/transformers_utils/tokenizer_group/__init__.py
  vllm/transformers_utils/tokenizer_group/base_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/ray_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/tokenizer_group.py
  vllm/worker/worker_base.py
Labels: ready

#6541 [Misc] Consolidate and optimize logic for building padded tensors
  tests/conftest.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
  vllm/model_executor/sampling_metadata.py
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: ready

#6559 [ Misc ] `fbgemm` checkpoints
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-Channelwise-compressed-tensors.yaml
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-8B-Instruct-FBGEMM-nonuniform.yaml
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  vllm/_custom_ops.py
  vllm/attention/layer.py
  vllm/config.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/aqlm.py
  vllm/model_executor/layers/quantization/awq.py
  vllm/model_executor/layers/quantization/base_config.py
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/deepspeedfp.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/gptq.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/gptq_marlin_24.py
  vllm/model_executor/layers/quantization/marlin.py
  vllm/model_executor/layers/quantization/squeezellm.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
Labels: ready

#6543 [Bugfix][CI/Build][Hardware][AMD] Fix AMD tests, add HF cache, update CK FA, add partially supported model notes
  .buildkite/run-amd-test.sh
  .buildkite/test-pipeline.yaml
  CMakeLists.txt
  Dockerfile.rocm
  docs/source/getting_started/amd-installation.rst
  requirements-rocm.txt
  tests/basic_correctness/test_cpu_offload.py
  tests/models/test_paligemma.py
  tests/models/test_phi3v.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/model_executor/models/__init__.py
  vllm/spec_decode/draft_model_runner.py
Labels: rocm, ready

#6606 [ Kernel ] Enable `fp8-marlin` for `fbgemm-fp8` models
  .buildkite/lm-eval-harness/configs/Meta-Llama-3-70B-Instruct-FBGEMM-nonuniform.yaml
  .buildkite/lm-eval-harness/configs/models-large.txt
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_fp8.py
Labels: ready

#6579 [Misc] Fix input_scale typing in w8a8_utils.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#6609 [ Bugfix ] Fix AutoFP8 fp8 marlin
  vllm/model_executor/layers/quantization/utils/marlin_utils_fp8.py
Labels: ready

#6602 [Frontend] Move chat utils
  tests/async_engine/test_chat_template.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
Labels: ready

#6485 [Spec Decode] Disable Log Prob serialization to CPU for spec decoding for both draft and target models.
  tests/spec_decode/e2e/test_logprobs.py
  tests/spec_decode/test_dynamic_spec_decode.py
  tests/spec_decode/test_spec_decode_worker.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/target_model_runner.py
  vllm/spec_decode/util.py
Labels: ready

#6619 [Misc] Remove abused noqa
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#6621 [Model] Refactor and decouple phi3v image embedding
  vllm/model_executor/models/phi3v.py
Labels: ready

#5770 [Model] Initial Support for Chameleon
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/chameleon.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/chameleon.py
Labels: ready

#6618 [Misc] Add a wrapper for torch.inference_mode
  vllm/platforms/__init__.py
  vllm/platforms/interface.py
  vllm/platforms/tpu.py
  vllm/worker/model_runner_base.py
  vllm/worker/worker_base.py
Labels: ready

#6624 [Bugfix] Fix `vocab_size` field access in LLaVA models
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
Labels: ready

#4028 [Frontend] Refactor prompt processing
  benchmarks/benchmark_latency.py
  docs/source/dev/multimodal/multimodal_index.rst
  docs/source/dev/offline_inference/llm_inputs.rst
  docs/source/models/vlm.rst
  tests/engine/output_processor/test_stop_checker.py
  tests/entrypoints/openai/test_serving_chat.py
  vllm/__init__.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/logger.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/sequence.py
Labels: ready

#6649 [Bugfix][Kernel] Use int64_t for indices in fp8 quant kernels
  csrc/quantization/fp8/common.cu
  tests/kernels/test_fp8_quant.py
Labels: ready

#6656 [ci] Use different sccache bucket for CUDA 11.8 wheel build
  .buildkite/release-pipeline.yaml
  Dockerfile
Labels: ready

#6234 [Core] Support dynamically loading Lora adapter from HuggingFace
  tests/core/test_scheduler.py
  tests/lora/conftest.py
  tests/lora/test_long_context.py
  tests/lora/test_lora_huggingface.py
  tests/lora/test_utils.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/lora/request.py
  vllm/lora/utils.py
  vllm/lora/worker_manager.py
  vllm/transformers_utils/tokenizer.py
  vllm/worker/model_runner.py
Labels: ready

#6659 [Misc] Remove deprecation warning for beam search
  vllm/sampling_params.py
Labels: ready

#6596 [Core] Modulize prepare input and attention metadata builder
  vllm/attention/backends/abstract.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
  vllm/utils.py
  vllm/worker/model_runner.py
Labels: ready

#6665 [Bugfix] Fix null `modules_to_not_convert` in FBGEMM Fp8 quantization
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
Labels: ready

#6666 [Misc] Enable chunked prefill by default for long context models
  vllm/engine/arg_utils.py
Labels: ready

#6528 [Misc] Support FP8 kv cache scales from compressed-tensors
  tests/quantization/test_compressed_tensors.py
  vllm/attention/layer.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/kv_cache.py
  vllm/model_executor/models/llama.py
Labels: ready

#6600 [Misc] Manage HTTP connections in one place
  tests/conftest.py
  tests/entrypoints/openai/test_vision.py
  tests/multimodal/test_utils.py
  vllm/assets/image.py
  vllm/connections.py
  vllm/multimodal/utils.py
  vllm/usage/usage_lib.py
Labels: ready

#6633 [VLM][Model] Support image input for Chameleon
  docs/source/models/supported_models.rst
  tests/models/test_chameleon.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/chameleon.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/chameleon.py
Labels: ready

#6673 support ignore patterns in model loader
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#6674 Bump version to v0.5.3
  vllm/version.py
Labels: ready

#6693 [BugFix] Fix RoPE error in Llama 3.1
  vllm/config.py
  vllm/model_executor/layers/rotary_embedding.py
Labels: ready

#6657 [Misc] Add ignored layers for `fp8` quantization
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
Labels: ready

#6652 [Frontend] Add Usage data in each chunk for chat_serving. #6540
  tests/entrypoints/openai/test_chat.py
  vllm/entrypoints/openai/serving_chat.py
Labels: ready

#6690 Bump `transformers` version for Llama 3.1 hotfix and patch Chameleon
  requirements-common.txt
  tests/test_config.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/chameleon.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/chameleon.py
Labels: ready

#6702 [CI] Add smoke test for non-uniform AutoFP8 quantization
  tests/quantization/test_fp8.py
Labels: ready

#6645 [Bugfix] StatLoggers: cache spec decode metrics when they get collected.
  tests/metrics/test_metrics.py
  vllm/engine/metrics.py
Labels: ready

#5753 [bitsandbytes]: support read bnb pre-quantized model
  docs/source/index.rst
  docs/source/quantization/bnb.rst
  tests/quantization/test_bitsandbytes.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#6708 [Bugfix] fix flashinfer cudagraph capture for PP
  tests/distributed/test_pipeline_parallel.py
  vllm/worker/model_runner.py
Labels: ready

#6714 [SpecDecoding] Update MLPSpeculator CI tests to use smaller model
  tests/spec_decode/e2e/test_mlp_correctness.py
Labels: ready

#6724 [Bugfix] Fix token padding for chameleon
  vllm/model_executor/models/chameleon.py
Labels: ready

#6680 [Docs][ROCm] Detailed instructions to build from source
  docs/source/getting_started/amd-installation.rst
Labels: rocm

#6711 [Build/CI] Update run-amd-test.sh. Enable Docker Hub login.
  .buildkite/run-amd-test.sh
Labels: rocm, ready

#6730 [Bugfix]fix modelscope compatible issue
  vllm/model_executor/model_loader/loader.py
Labels: ready

#6748 Adding f-string to validation error which is missing
  vllm/entrypoints/chat_utils.py
Labels: ready

#6686 [Bugfix] Miscalculated latency lead to time_to_first_token_seconds inaccurate.
  vllm/engine/llm_engine.py
  vllm/spec_decode/spec_decode_worker.py
Labels: ready

#6740 [Frontend] split run_server into build_server and run_server
  vllm/entrypoints/openai/api_server.py
  vllm/scripts.py
Labels: ready

#6667 [Kernels] Add fp8 support to `reshape_and_cache_flash`
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_cache.py
  vllm/_custom_ops.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/utils.py
Labels: ready

#6712 [Core] Tweaks to model runner/input builder developer APIs
  vllm/attention/backends/flashinfer.py
  vllm/worker/embedding_model_runner.py
  vllm/worker/model_runner.py
Labels: ready

#6752 [Bugfix] Bump transformers to 4.43.2
  requirements-common.txt
  tests/test_config.py
Labels: ready

#6754 [Doc][AMD][ROCm]Added tips to refer to mi300x tuning guide for mi300x users
  docs/source/getting_started/amd-installation.rst
Labels: rocm, ready

#6759 [core][distributed] fix zmq hang
  vllm/connections.py
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#6626 [Frontend] Represent tokens with identifiable strings
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_return_tokens_as_ids.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: ready

#4087 [Model] Adding support for MiniCPM-V
  docs/source/dev/multimodal/multimodal_index.rst
  docs/source/models/supported_models.rst
  examples/minicpmv_example.py
  tests/conftest.py
  tests/models/test_minicpmv.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/minicpmv.py
  vllm/multimodal/__init__.py
  vllm/multimodal/base.py
Labels: ready

#6757 [Bugfix] Fix decode tokens w. CUDA graph
  tests/worker/test_model_runner.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
Labels: ready

#6745 [Bugfix] Fix awq_marlin and gptq_marlin flags
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
Labels: ready

#6787 [Bugfix] Add image placeholder for OpenAI Compatible Server of MiniCPM-V
  examples/minicpmv_example.py
  vllm/entrypoints/chat_utils.py
Labels: ready

#6761 [Bugfix] Fix `kv_cache_dtype=fp8` without scales for FP8 checkpoints
  tests/quantization/test_fp8.py
  vllm/model_executor/layers/quantization/kv_cache.py
Labels: ready

#6788 [Bugfix] Add synchronize to prevent possible data race
  vllm/distributed/parallel_state.py
Labels: ready

#6412 [Doc] Add documentations for nightly benchmarks
  .buildkite/nightly-benchmarks/README.md
  README.md
  docs/source/index.rst
  docs/source/performance_benchmark/benchmarks.rst
Labels: ready

#6798 [Bugfix] Fix empty (nullptr) channelwise scales when loading wNa16 using compressed tensors
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
Labels: ready

#6799 [Docs] Publish 5th meetup slides
  README.md
  docs/source/community/meetups.rst
Labels: ready

#6792 [Core] Fix ray forward_dag error mssg
  vllm/executor/ray_gpu_executor.py
Labels: ready

#6793 Fix ReplicatedLinear weight loading
  vllm/model_executor/layers/linear.py
Labels: ready

#6779 [Core] Use array to speedup padding
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/sampling_metadata.py
  vllm/sequence.py
Labels: ready

#6816 [doc][debugging] add known issues for hangs
  docs/source/getting_started/debugging.rst
Labels: ready

#6611 [Model] Support Nemotron models (Nemotron-3, Nemotron-4, Minitron)
  .buildkite/lm-eval-harness/configs/Minitron-4B-Base.yaml
  .buildkite/lm-eval-harness/configs/models-small.txt
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/nemotron.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/nemotron.py
Labels: ready

#6838 [Bugfix][Kernel] Promote another index to int64_t
  csrc/quantization/fp8/common.cu
Labels: ready

#6811 [Build/CI][ROCm] Minor simplification to Dockerfile.rocm
  Dockerfile.rocm
Labels: rocm, ready

#6812 [Misc][TPU] Support TPU in initialize_ray_cluster
  vllm/executor/ray_utils.py
Labels: tpu, ready

#6125 [Hardware] [Intel] Enable Multiprocessing and tensor parallel in CPU backend and update documentation
  .buildkite/run-cpu-test.sh
  Dockerfile.cpu
  cmake/cpu_extension.cmake
  csrc/cpu/torch_bindings.cpp
  csrc/cpu/utils.cpp
  docs/source/getting_started/cpu-installation.rst
  requirements-cpu.txt
  vllm/distributed/parallel_state.py
  vllm/engine/async_llm_engine.py
  vllm/envs.py
  vllm/executor/cpu_executor.py
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU, ready

#6843 [Doc] Add Nemotron to supported model docs
  docs/source/models/supported_models.rst
  vllm/model_executor/layers/activation.py
Labels: ready
