Repository vllm-project/vllm, pull requests merged in 2024-09, with the labels that each got.

#8063 [Misc] Optional installation of audio related packages
  requirements-common.txt
  requirements-test.txt
  setup.py
  tests/models/test_ultravox.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/utils.py
Labels: ready

#7436 [Model] Adding Granite model.
  tests/models/test_granite.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/granite.py
  vllm/transformers_utils/configs/granite.py
Labels: ready

#7244 [SpecDecode][Kernel] Use Flashinfer for Rejection Sampling in Speculative Decoding
  Dockerfile
  tests/samplers/test_rejection_sampler.py
  tests/samplers/test_typical_acceptance_sampler.py
  tests/spec_decode/test_spec_decode_worker.py
  vllm/envs.py
  vllm/model_executor/layers/rejection_sampler.py
  vllm/model_executor/layers/spec_decode_base_sampler.py
  vllm/model_executor/layers/typical_acceptance_sampler.py
  vllm/spec_decode/spec_decode_worker.py
Labels: ready

#7932 [TPU] Align worker index with node boundary
  vllm/executor/ray_tpu_executor.py
Labels: tpu

#8055 [Bugfix] Fix internlm2 tensor parallel inference
  vllm/model_executor/models/internlm2.py
Labels: ready

#7874 [Bugfix] Fix #7592 vllm 0.5.4 enable_chunked_prefill throughput is slightly lower than 0.5.3~0.5.0.
  tests/basic_correctness/test_chunked_prefill.py
  vllm/core/scheduler.py
Labels: ready

#8050 [Core] Optimize Async + Multi-step
  tests/multi_step/test_correctness_async_llm.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/output_processor/multi_step.py
  vllm/sequence.py
  vllm/worker/model_runner.py
  vllm/worker/multi_step_model_runner.py
  vllm/worker/multi_step_worker.py
Labels: ready

#7750 [Misc] Raise a more informative exception in add/remove_logger
  vllm/engine/llm_engine.py
Labels: ready

#8128 [TPU][Bugfix] Fix next_token_ids shape
  vllm/worker/tpu_model_runner.py
Labels: tpu

#7964 [Benchmark] Add `--async-engine` option to benchmark_throughput.py
  benchmarks/benchmark_throughput.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/client.py
Labels: ready

#8137 [TPU][Bugfix] Use XLA rank for persistent cache path
  docs/source/getting_started/tpu-installation.rst
  vllm/worker/tpu_worker.py
Labels: tpu

#7972 [Misc] Update fbgemmfp8 to use `vLLMParameters`
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#7963 [Model] Add Ultravox support for multiple audio chunks
  examples/offline_inference_audio_language.py
  tests/models/test_ultravox.py
  vllm/model_executor/models/ultravox.py
Labels: ready

#8098 [Frontend] Multimodal support in offline chat
  tests/entrypoints/llm/test_generate.py
  tests/entrypoints/test_chat_utils.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/multimodal/utils.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#8103 chore: Update check-wheel-size.py to read MAX_SIZE_MB from env
  .buildkite/check-wheel-size.py
  Dockerfile
Labels: ready

#8106 [Bugfix] remove post_layernorm in siglip
  vllm/model_executor/models/siglip.py
Labels: ready

#8131 [MISC] Consolidate FP8 kv-cache tests
  .buildkite/run-cpu-test.sh
  tests/basic_correctness/test_chunked_prefill.py
  tests/models/test_fp8.py
  tests/models/test_fp8kv_flashinfer.py
Labels: ready

#7369 [CI/Build][ROCm] Enabling LoRA tests on ROCm
  .buildkite/run-amd-test.sh
  .buildkite/test-pipeline.yaml
  tests/lora/test_gemma.py
  tests/lora/test_quant_model.py
Labels: rocm, ready

#5649 [Feature] OpenAI-Compatible Tools API + Streaming for Hermes & Mistral models
  .buildkite/test-pipeline.yaml
  docs/source/serving/openai_compatible_server.md
  examples/openai_chat_completion_client_with_tools.py
  examples/tool_chat_template_hermes.jinja
  examples/tool_chat_template_mistral.jinja
  examples/tool_chat_template_mistral_parallel.jinja
  requirements-common.txt
  tests/tool_use/__init__.py
  tests/tool_use/conftest.py
  tests/tool_use/test_chat_completions.py
  tests/tool_use/test_parallel_tool_calls.py
  tests/tool_use/test_tool_calls.py
  tests/tool_use/utils.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/abstract_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/utils.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/outlines_decoding.py
Labels: ready

#8164 [MISC] Replace input token throughput with total token throughput
  benchmarks/benchmark_serving.py
Labels: ready

#8062 [Neuron] Adding support for adding/ overriding neuron configuration a…
  examples/offline_inference_neuron_int8_quantization.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/neuron_quant.py
  vllm/model_executor/model_loader/neuron.py
  vllm/worker/neuron_model_runner.py
Labels: Inferentia/Trainium, ready

#8166 Bump version to v0.6.0
  vllm/version.py
Labels: ready

#8169 [bugfix] >1.43 constraint for openai
  requirements-common.txt
Labels: ready

#8173 [Core/Bugfix] Add query dtype as per FlashInfer API requirements.
  tests/kernels/test_flashinfer.py
  vllm/attention/backends/flashinfer.py
Labels: ready

#8181 [Doc] Add multi-image input example and update supported models
  .buildkite/test-pipeline.yaml
  docs/source/getting_started/debugging.rst
  docs/source/getting_started/quickstart.rst
  docs/source/models/supported_models.rst
  docs/source/models/vlm.rst
  examples/offline_inference_vision_language_multi_image.py
  examples/openai_vision_api_client.py
Labels: ready

#7860 Inclusion of InternVLChatModel In PP_SUPPORTED_MODELS(Pipeline Parallelism)
  tests/distributed/test_pipeline_parallel.py
  tests/utils.py
  vllm/config.py
  vllm/model_executor/models/internlm2.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/utils.py
Labels: ready

#8029 [MODEL] Qwen Multimodal Support (Qwen-VL / Qwen-VL-Chat)
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  tests/models/test_qwen.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/layers/resampler.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/qwen.py
Labels: ready

#8165 Move verify_marlin_supported to GPTQMarlinLinearMethod
  vllm/model_executor/layers/quantization/gptq_marlin.py
Labels: ready

#7962 [Documentation][Spec Decode] Add documentation about lossless guarantees in Speculative Decoding in vLLM
  docs/source/models/spec_decode.rst
  docs/source/serving/faq.rst
Labels: ready

#8216 [BugFix] Fix Granite model configuration
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
Labels: ready

#8191 [Frontend] Add --logprobs argument to `benchmark_serving.py`
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving.py
  tests/multi_step/test_correctness_llm.py
Labels: ready

#7938 [Misc] Use ray[adag] dependency instead of cuda
  Dockerfile
  MANIFEST.in
  requirements-adag.txt
  requirements-test.txt
  vllm/executor/ray_gpu_executor.py
Labels: ready

#8203 [CI/Build] Increasing timeout for multiproc worker tests
  tests/engine/test_multiproc_workers.py
Labels: ready

#8248 [Kernel] [Triton] Memory optimization for awq_gemm and awq_dequantize, 2x throughput
  vllm/model_executor/layers/quantization/awq_triton.py
Labels: ready

#8220 [Misc] Remove `SqueezeLLM`
  CMakeLists.txt
  csrc/ops.h
  csrc/quantization/squeezellm/quant_cuda_kernel.cu
  csrc/torch_bindings.cpp
  docs/source/quantization/supported_hardware.rst
  examples/fp8/README.md
  vllm/_custom_ops.py
  vllm/config.py
  vllm/entrypoints/llm.py
  vllm/lora/layers.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/squeezellm.py
Labels: ready

#8168 [Model] Allow loading from original Mistral format
  tests/models/test_mistral.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/llama.py
  vllm/transformers_utils/config.py
Labels: ready

#7943 [misc] [doc] [frontend] LLM torch profiler support
  docs/source/dev/profiling/profiling_index.rst
  examples/offline_inference_with_profiler.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/executor/cpu_executor.py
  vllm/executor/gpu_executor.py
Labels: ready

#8256 [Bugfix] Fix Hermes tool call chat template bug
  examples/tool_chat_template_hermes.jinja
Labels: ready

#8238 [Model] Multi-input support for LLaVA and fix embedding inputs for multi-image models
  docs/source/models/supported_models.rst
  tests/conftest.py
  tests/distributed/test_multimodal_broadcast.py
  tests/models/test_llava.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/siglip.py
Labels: ready

#8241 Enable Random Prefix Caching in Serving Profiling Tool (benchmark_serving.py)
  benchmarks/benchmark_serving.py
Labels: ready

#8258 [Bugfix] Fix broken OpenAI tensorizer test
  tests/utils.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/tensorizer.py
Labels: ready

#8201 [Model][VLM] Support multi-images inputs for InternVL2 models
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language_multi_image.py
  tests/models/test_internvl.py
  tests/models/test_phi3v.py
  vllm/model_executor/models/internvl.py
Labels: ready

#8269 [Model][VLM] Decouple weight loading logic for `Paligemma`
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/siglip.py
Labels: ready

#8133 [CI/Build] Use python 3.12 in cuda image
  Dockerfile
  requirements-common.txt
  tests/test_logger.py
Labels: ready

#8267 [Bugfix] Fix async postprocessor in case of preemption
  vllm/core/scheduler.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/worker/multi_step_model_runner.py
Labels: ready

#8272 [Bugfix] Streamed tool calls now more strictly follow OpenAI's format; ensures Vercel AI SDK compatibility
  tests/tool_use/utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/abstract_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: ready

#8060 [Frontend] Add progress reporting to run_batch.py
  vllm/entrypoints/openai/run_batch.py
Labels: ready

#8292 [Bugfix] Correct adapter usage for cohere and jamba
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/jamba.py
Labels: ready

#8135 [Misc] GPTQ Activation Ordering
  tests/weight_loading/models.txt
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#8217 [Misc] Fused MoE Marlin support for GPTQ
  .buildkite/test-pipeline.yaml
  csrc/moe/marlin_moe_ops.cu
  csrc/moe/marlin_moe_ops.h
  csrc/moe/torch_bindings.cpp
  tests/kernels/test_moe.py
  tests/weight_loading/models-large.txt
  tests/weight_loading/models.txt
  vllm/model_executor/layers/fused_moe/__init__.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_test.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/mixtral.py
Labels: ready

#8314 [Frontend] Clean up type annotations for mistral tokenizer
  tests/async_engine/test_chat_template.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#8130 [CI/Build] Enabling kernels tests for AMD, ignoring some of then that fail
  .buildkite/run-amd-test.sh
  .buildkite/test-pipeline.yaml
Labels: rocm, ready

#8309 Fix ppc64le buildkite job
  .buildkite/run-cpu-test-ppc64le.sh
  Dockerfile.ppc64le
Labels: ready

#8224 [Spec Decode] Move ops.advance_step to flash attn advance_step
  vllm/attention/backends/flash_attn.py
  vllm/spec_decode/draft_model_runner.py
  vllm/worker/multi_step_model_runner.py
Labels: ready

#8162 [Misc] remove peft as dependency for prompt models
  vllm/config.py
  vllm/prompt_adapter/models.py
  vllm/prompt_adapter/utils.py
Labels: ready

#8340 [Bugfix] Ensure multistep lookahead allocation is compatible with cuda graph max capture
  vllm/attention/backends/flash_attn.py
Labels: ready

#8172 [Core/Bugfix] pass VLLM_ATTENTION_BACKEND to ray workers
  vllm/executor/ray_gpu_executor.py
Labels: ready

#8043 [CI/Build][Kernel] Update CUTLASS to 3.5.1 tag
  CMakeLists.txt
Labels: ready

#8329 [Misc] Skip loading extra bias for Qwen2-MOE GPTQ models
  vllm/model_executor/models/qwen2_moe.py
Labels: ready

#8299 [Bugfix] Fix InternVL2 vision embeddings process with pipeline parallel
  tests/distributed/test_pipeline_parallel.py
  vllm/model_executor/models/internvl.py
Labels: ready

#6112 [Hardware][NV] Add support for ModelOpt static scaling checkpoints.
  examples/fp8/quantizer/README.md
  tests/models/test_modelopt.py
  vllm/config.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#7559 [model] Support for Llava-Next-Video model
  Dockerfile
  Dockerfile.cpu
  Dockerfile.neuron
  Dockerfile.openvino
  Dockerfile.ppc64le
  Dockerfile.tpu
  Dockerfile.xpu
  docs/source/conf.py
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  requirements-test.txt
  setup.py
  tests/conftest.py
  tests/models/test_llava_next_video.py
  vllm/assets/video.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/llava_next_video.py
  vllm/multimodal/registry.py
  vllm/multimodal/utils.py
  vllm/multimodal/video.py
  vllm/transformers_utils/image_processor.py
Labels: ready

#8347 [Frontend] Create ErrorResponse instead of raising exceptions in run_batch
  tests/entrypoints/openai/test_run_batch.py
  vllm/entrypoints/openai/run_batch.py
Labels: ready

#7905 [Model][VLM] Add Qwen2-VL model support
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
  requirements-common.txt
  tests/models/test_registry.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/multimodal/base.py
  vllm/sequence.py
  vllm/transformers_utils/processor.py
  vllm/worker/model_runner.py
Labels: ready

#8373 [CI/Build] Excluding test_moe.py from AMD Kernels tests for investigation
  .buildkite/run-amd-test.sh
Labels: rocm, ready

#6917 [Kernel][Misc] Add meta functions for ops to prevent graph breaks
  .github/PULL_REQUEST_TEMPLATE.md
  cmake/utils.cmake
  csrc/cpu/torch_bindings.cpp
  csrc/ops.h
  csrc/quantization/gptq_marlin/awq_marlin_repack.cu
  csrc/quantization/gptq_marlin/gptq_marlin_repack.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_activation.py
  tests/kernels/test_attention.py
  tests/kernels/test_cache.py
  tests/kernels/test_cutlass.py
  tests/kernels/test_int8_quant.py
  tests/kernels/test_layernorm.py
  tests/kernels/test_machete_gemm.py
  tests/kernels/test_marlin_gemm.py
  tests/kernels/utils.py
  tests/models/test_aqlm.py
  vllm/_custom_ops.py
  vllm/envs.py
  vllm/model_executor/models/jamba.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: ready, torch.compile

#8322 [Misc] Move device options to a single place
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_throughput.py
  vllm/engine/arg_utils.py
Labels: ready

#8317 [Speculative Decoding] Test refactor
  .buildkite/test-pipeline.yaml
  tests/spec_decode/e2e/conftest.py
  tests/spec_decode/e2e/test_eagle_correctness.py
  tests/spec_decode/e2e/test_integration.py
  tests/spec_decode/e2e/test_integration_dist_tp2.py
  tests/spec_decode/e2e/test_integration_dist_tp4.py
  tests/spec_decode/e2e/test_logprobs.py
  tests/spec_decode/e2e/test_medusa_correctness.py
  tests/spec_decode/e2e/test_mlp_correctness.py
  tests/spec_decode/e2e/test_multistep_correctness.py
  tests/spec_decode/e2e/test_ngram_correctness.py
  tests/spec_decode/e2e/test_seed.py
Labels: ready

#8377 Pixtral
  docs/source/models/supported_models.rst
  examples/offline_inference_pixtral.py
  requirements-common.txt
  tests/models/test_pixtral.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/pixtral.py
  vllm/transformers_utils/config.py
Labels: ready

#8379 Bump version to v0.6.1
  vllm/version.py
Labels: ready

#8305 [MISC] Dump model runner inputs when crashing
  .github/ISSUE_TEMPLATE/400-bug report.yml
  tests/basic_correctness/test_basic_correctness.py
  vllm/worker/model_runner.py
  vllm/worker/model_runner_base.py
Labels: ready

#8126 [misc] remove engine_use_ray
  tests/async_engine/test_api_server.py
  tests/async_engine/test_async_llm_engine.py
  tests/async_engine/test_openapi_server.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/openai/run_batch.py
  vllm/envs.py
Labels: ready

#8389 [TPU] Use Ray for default distributed backend
  vllm/config.py
Labels: tpu

#8390 Fix the AMD weight loading tests
  vllm/config.py
Labels: ready

#8366 [Bugfix]: Fix the logic for deciding if tool parsing is used
  vllm/entrypoints/openai/serving_chat.py
Labels: ready

#8338 [Gemma2] add bitsandbytes support for Gemma2
  vllm/model_executor/models/gemma2.py
Labels: ready

#8355 [Misc] Raise error when using encoder/decoder model with cpu backend
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
Labels: ready

#8396 [Misc] Use RoPE cache for MRoPE
  vllm/model_executor/layers/rotary_embedding.py
Labels: ready

#8399 [Hotfix][VLM] Fixing max position embeddings for Pixtral
  vllm/transformers_utils/config.py
Labels: ready

#8375 [Bugfix] Fix InternVL2 inference with various num_patches
  tests/models/test_internvl.py
  vllm/model_executor/models/internvl.py
Labels: ready

#8247 [Model] Support multiple images for qwen-vl
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language_multi_image.py
  tests/models/test_qwen.py
  vllm/model_executor/models/qwen.py
Labels: ready

#8403 [BugFix] lazy init _copy_stream to avoid torch init wrong gpu instance
  vllm/worker/multi_step_model_runner.py
Labels: ready

#8423 [BugFix] Fix Duplicate Assignment of Class Variable in Hermes2ProToolParser
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
Labels: ready

#7381 [Core] Add engine option to return only deltas or final output
  .buildkite/test-pipeline.yaml
  tests/async_engine/test_async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/outputs.py
  vllm/sampling_params.py
  vllm/sequence.py
Labels: ready

#8427 [Bugfix] multi-step + flashinfer: ensure cuda graph compatible
  vllm/attention/backends/flashinfer.py
Labels: ready

#8425 [Hotfix][Core][VLM] Disable chunked prefill by default and prefix caching for multimodal models
  vllm/engine/arg_utils.py
  vllm/model_executor/models/__init__.py
Labels: ready

#8428 [CI/Build] Disable multi-node test for InternVL2
  tests/distributed/test_pipeline_parallel.py
Labels: ready

#8415 [Hotfix][Pixtral] Fix multiple images bugs
  tests/conftest.py
  tests/models/fixtures/pixtral_chat.pickle
  tests/models/fixtures/pixtral_chat_engine.pickle
  tests/models/test_pixtral.py
  vllm/model_executor/models/pixtral.py
Labels: ready

#8293 [Bugfix] Fix weight loading issue by rename variable.
  vllm/model_executor/models/phimoe.py
Labels: ready

#8430 [BugFix] fix group_topk
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#7329 [Core] Factor out input preprocessing to a separate class
  tests/engine/test_skip_tokenizer_init.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/inputs/parse.py
  vllm/inputs/preprocess.py
Labels: ready

#8290 [Bugfix] Mapping physical device indices for e2e test utils
  tests/utils.py
Labels: ready

#8435 [Bugfix] Bump fastapi and pydantic version
  requirements-common.txt
Labels: ready

#8436 [CI/Build] Update pixtral tests to use JSON
  pyproject.toml
  tests/models/fixtures/pixtral_chat.json
  tests/models/fixtures/pixtral_chat.pickle
  tests/models/fixtures/pixtral_chat_engine.json
  tests/models/fixtures/pixtral_chat_engine.pickle
  tests/models/test_pixtral.py
Labels: ready

#8417 [Bugfix] Fix async log stats
  tests/basic_correctness/test_preemption.py
  vllm/engine/llm_engine.py
Labels: ready

#8354 [bugfix] torch profiler bug for single gpu with GPUExecutor
  examples/offline_inference_with_profiler.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
Labels: ready

#8437 [CI/Build] Enable InternVL2 PP test only on single node
  tests/distributed/test_pipeline_parallel.py
Labels: ready

#8446 [doc] recommend pip instead of conda
  docs/source/getting_started/installation.rst
Labels: ready

#8442 [Misc] Skip loading extra bias for Qwen2-VL GPTQ-Int8
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#8449 [misc][ci] fix quant test
  tests/quantization/test_bitsandbytes.py
  tests/quantization/utils.py
Labels: ready

#8456 [Installation] Gate FastAPI version for Python 3.8
  requirements-common.txt
Labels: ready

#8467 [Doc] Add oneDNN installation to CPU backend documentation
  docs/source/getting_started/cpu-installation.rst
Labels: x86 CPU, ready

#8468 [HotFix] Fix final output truncation with stop string + streaming
  tests/async_engine/test_async_llm_engine.py
  vllm/sequence.py
Labels: ready

#8365 [Hardware][intel GPU] bump up ipex version to 2.3
  Dockerfile.xpu
  requirements-xpu.txt
  vllm/_ipex_ops.py
  vllm/attention/backends/ipex_attn.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/layernorm.py
Labels: Intel GPU

#8310 [Kernel][Hardware][Amd]Custom paged attention kernel for rocm
  CMakeLists.txt
  csrc/rocm/attention.cu
  csrc/rocm/ops.h
  csrc/rocm/torch_bindings.cpp
  setup.py
  tests/kernels/test_attention.py
  vllm/_custom_ops.py
  vllm/attention/backends/rocm_flash_attn.py
Labels: rocm

#8297 [Model] support minicpm3
  .buildkite/run-cpu-test.sh
  docs/source/models/supported_models.rst
  requirements-test.txt
  tests/models/decoder_only/language/test_big_models.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/minicpm3.py
Labels: ready

#8489 [TPU] Implement multi-step scheduling
  vllm/config.py
  vllm/executor/ray_tpu_executor.py
  vllm/executor/tpu_executor.py
  vllm/worker/multi_step_tpu_worker.py
  vllm/worker/tpu_model_runner.py
Labels: tpu

#8490 [Bugfix][Model] Fix Python 3.8 compatibility in Pixtral model by updating type annotations
  vllm/model_executor/models/pixtral.py
Labels: ready

#8357 [Bugfix][Kernel] Add `IQ1_M` quantization implementation to GGUF kernel
  csrc/quantization/gguf/dequantize.cuh
  csrc/quantization/gguf/ggml-common.h
  csrc/quantization/gguf/gguf_kernel.cu
  csrc/quantization/gguf/mmvq.cuh
  csrc/quantization/gguf/vecdotq.cuh
  requirements-common.txt
  tests/kernels/test_gguf.py
  vllm/model_executor/layers/quantization/gguf.py
Labels: ready

#8032 [Kernel] Enable 8-bit weights in Fused Marlin MoE
  csrc/moe/marlin_moe_ops.cu
  csrc/moe/marlin_moe_ops.h
  csrc/moe/torch_bindings.cpp
  tests/kernels/test_moe.py
  tests/weight_loading/models-large.txt
  tests/weight_loading/run_model_weight_loading_test.sh
  vllm/_custom_ops.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/model_loader/utils.py
Labels: ready

#8501 [Frontend] Expose revision arg in OpenAI server
  vllm/entrypoints/openai/api_server.py
Labels: ready

#8492 [BugFix] Fix clean shutdown issues
  tests/async_engine/test_async_llm_engine.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/launcher.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/executor/multiproc_gpu_executor.py
  vllm/executor/multiproc_worker_utils.py
  vllm/executor/ray_tpu_executor.py
  vllm/scripts.py
  vllm/utils.py
Labels: ready

#8506 [Bugfix][Kernel] Fix build for sm_60 in GGUF kernel
  csrc/quantization/gguf/vecdotq.cuh
Labels: ready

#7270 [Kernel] AQ AZP 3/4: Asymmetric quantization kernels
  csrc/cpu/quant.cpp
  csrc/cpu/torch_bindings.cpp
  csrc/ops.h
  csrc/quantization/compressed_tensors/int8_quant_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_int8_quant.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/qqq.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#8491 [Bugfix] Bind api server port before starting engine
  vllm/entrypoints/openai/api_server.py
Labels: ready

#8516 [perf bench] set timeout to debug hanging
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
  .buildkite/nightly-benchmarks/scripts/wait-for-image.sh
Labels: perf-benchmarks

#8510 [Bugfix] Fix 3.12 builds on main
  Dockerfile
  requirements-common.txt
Labels: ready

#8524 [refactor] remove triton based sampler
  tests/kernels/test_rand.py
  tests/kernels/test_sampler.py
  vllm/model_executor/layers/ops/__init__.py
  vllm/model_executor/layers/ops/rand.py
  vllm/model_executor/layers/ops/sample.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/sampling_metadata.py
  vllm/triton_utils/sample.py
  vllm/utils.py
Labels: ready

#8525 [Frontend] Improve Nullable kv Arg Parsing
  tests/engine/test_arg_utils.py
  vllm/engine/arg_utils.py
Labels: ready

#8521 [Misc][Bugfix] Disable guided decoding for mistral tokenizer
  vllm/model_executor/guided_decoding/__init__.py
Labels: ready

#8526 [torch.compile] register allreduce operations as custom ops
  .buildkite/test-pipeline.yaml
  csrc/custom_all_reduce.cu
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/compile/__init__.py
  tests/compile/test_full_graph.py
  vllm/_custom_ops.py
  vllm/distributed/device_communicators/custom_all_reduce.py
  vllm/distributed/parallel_state.py
Labels: ready

#8509 [Misc] Limit to ray[adag] 2.35 to avoid backward incompatible change
  requirements-test.txt
  vllm/executor/ray_gpu_executor.py
Labels: ready

#8495 [Benchmark] Support sample from HF datasets and image input for benchmark_serving
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving.py
Labels: ready

#7631 [Encoder decoder] Add cuda graph support during decoding for encoder-decoder models
  .buildkite/test-pipeline.yaml
  tests/encoder_decoder/__init__.py
  tests/encoder_decoder/test_e2e_correctness.py
  tests/worker/test_encoder_decoder_model_runner.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/llm.py
  vllm/model_executor/models/bart.py
  vllm/utils.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/utils.py
Labels: ready

#8434 [Feature][kernel] tensor parallelism with bitsandbytes quantization
  tests/quantization/test_bitsandbytes.py
  vllm/config.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/model_loader/loader.py
Labels: ready

#8515 [Model] Add mistral function calling format to all models loaded with "mistral" format
  examples/offline_chat_with_tools.py
  tests/models/decoder_only/language/test_mistral.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#8527 [Misc] Don't dump contents of kvcache tensors on errors
  vllm/worker/model_runner_base.py
Labels: ready

#8544 [Bugfix] Fix TP > 1 for new granite
  vllm/model_executor/models/granite.py
Labels: ready

#8520 [CI/Build] Excluding kernels/test_gguf.py from ROCm
  .buildkite/run-amd-test.sh
Labels: ready

#8012 [Kernel] Change interface to Mamba causal_conv1d_update for continuous batching
  csrc/mamba/causal_conv1d/causal_conv1d.cu
  csrc/mamba/causal_conv1d/causal_conv1d.h
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/kernels/test_causal_conv1d.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/mamba/ops/causal_conv1d.py
Labels: ready

#8540 [CI/Build] fix Dockerfile.cpu on podman
  Dockerfile.cpu
Labels: ready

#8554 [Misc] Add argument to disable FastAPI docs
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
Labels: ready

#8534 [CI/Build] Avoid CUDA initialization
  benchmarks/kernels/benchmark_layernorm.py
  benchmarks/kernels/benchmark_moe.py
  benchmarks/kernels/benchmark_paged_attention.py
  benchmarks/kernels/benchmark_quant.py
  benchmarks/kernels/benchmark_rope.py
  tests/kernels/test_activation.py
  tests/kernels/test_attention.py
  tests/kernels/test_attention_selector.py
  tests/kernels/test_awq_triton.py
  tests/kernels/test_blocksparse_attention.py
  tests/kernels/test_cache.py
  tests/kernels/test_causal_conv1d.py
  tests/kernels/test_cutlass.py
  tests/kernels/test_flash_attn.py
  tests/kernels/test_flashinfer.py
  tests/kernels/test_fp8_quant.py
  tests/kernels/test_gguf.py
  tests/kernels/test_int8_quant.py
  tests/kernels/test_layernorm.py
  tests/kernels/test_machete_gemm.py
  tests/kernels/test_mamba_ssm.py
  tests/kernels/test_moe.py
  tests/kernels/test_pos_encoding.py
  tests/kernels/test_prefix_prefill.py
  tests/lora/test_layers.py
  tests/lora/test_punica_sizes.py
  tests/lora/test_punica_variation.py
  tests/models/decoder_only/language/test_granite.py
  tests/quantization/test_fp8.py
  tests/quantization/utils.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/ops/blocksparse_attention/interface.py
  vllm/attention/ops/prefix_prefill.py
  vllm/attention/selector.py
  vllm/config.py
  vllm/distributed/parallel_state.py
  vllm/envs.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/utils.py
  vllm/platforms/cpu.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/prompt_adapter/utils.py
  vllm/usage/usage_lib.py
  vllm/utils.py
  vllm/worker/worker.py
Labels: ready

#8469 [CI/Build] Update Ruff version
  .github/workflows/ruff.yml
  benchmarks/kernels/graph_machete_bench.py
  format.sh
  pyproject.toml
  requirements-lint.txt
  tests/conftest.py
  tests/lora/conftest.py
  tests/multimodal/test_base.py
  tests/test_cache_block_hashing.py
  tests/test_logger.py
  tests/worker/test_encoder_decoder_model_runner.py
  tests/worker/test_model_runner.py
  vllm/adapter_commons/utils.py
  vllm/attention/backends/utils.py
  vllm/core/block/prefix_caching_block.py
  vllm/core/block_manager_v2.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/model_loader/tensorizer.py
  vllm/model_executor/models/minicpmv.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/metrics.py
  vllm/triton_utils/libentry.py
Labels: ready

#8157 [Core][Bugfix][Perf] Introduce `MQLLMEngine` to avoid `asyncio` OH
  .buildkite/test-pipeline.yaml
  docs/source/dev/profiling/profiling_index.rst
  tests/async_engine/test_openapi_server.py
  tests/entrypoints/openai/rpc/test_zmq_client.py
  tests/entrypoints/openai/test_accuracy.py
  tests/entrypoints/openai/test_chat_template.py
  tests/entrypoints/openai/test_mp_api_server.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/entrypoints/openai/test_serving_engine.py
  tests/entrypoints/openai/test_shutdown.py
  tests/mq_llm_engine/__init__.py
  tests/mq_llm_engine/test_abort.py
  tests/mq_llm_engine/test_error_handling.py
  tests/mq_llm_engine/test_load.py
  tests/mq_llm_engine/utils.py
  tests/tpu/test_custom_dispatcher.py
  tests/utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/launcher.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/__init__.py
  vllm/entrypoints/openai/rpc/client.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/envs.py
  vllm/executor/cpu_executor.py
  vllm/executor/multiproc_worker_utils.py
Labels: ready

#8199 [Core] *Prompt* logprobs support in Multi-step
  tests/conftest.py
  tests/models/utils.py
  tests/multi_step/test_correctness_llm.py
  tests/utils.py
  vllm/worker/multi_step_model_runner.py
Labels: ready

#8543 [Core] zmq: bind only to 127.0.0.1 for local-only usage
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#8386 [Model] Support Solar Model
  docs/source/models/supported_models.rst
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/solar.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/solar.py
Labels: ready

#8380 [AMD][ROCm]Quantization methods on ROCm; Fix _scaled_mm call
  vllm/config.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: rocm, ready

#8039 [Kernel] Change interface to Mamba selective_state_update for continuous batching
  tests/kernels/test_mamba_ssm.py
  vllm/model_executor/layers/mamba/ops/mamba_ssm.py
Labels: ready

#8572 [BugFix] Nonzero exit code if MQLLMEngine startup fails
  vllm/entrypoints/openai/api_server.py
Labels: ready

#8574 [Bugfix] add `dead_error` property to engine client
  vllm/engine/multiprocessing/client.py
Labels: ready

#8573 [Kernel] Remove marlin moe templating on thread_m_blocks
  csrc/moe/marlin_moe_ops.cu
Labels: ready

#8545 [Bugfix] [Encoder-Decoder] Bugfix for encoder specific metadata construction during decode of encoder-decoder models.
  tests/worker/test_encoder_decoder_model_runner.py
  vllm/worker/enc_dec_model_runner.py
Labels: ready

#8593 Revert "[Misc][Bugfix] Disable guided decoding for mistral tokenizer"
  vllm/model_executor/guided_decoding/__init__.py
Labels: ready

#8616 [Bugfix] fixing sonnet benchmark bug in benchmark_serving.py
  benchmarks/benchmark_serving.py
Labels: ready

#8615 [MISC] remove engine_use_ray in benchmark_throughput.py
  benchmarks/benchmark_throughput.py
Labels: ready

#8584 [Frontend] Use MQLLMEngine for embeddings models too
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
Labels: ready

#8577 [Kernel][Amd] Add fp8 kv cache support for rocm custom paged attention
  csrc/rocm/attention.cu
  csrc/rocm/ops.h
  csrc/rocm/torch_bindings.cpp
  tests/kernels/test_attention.py
  vllm/_custom_ops.py
  vllm/attention/backends/rocm_flash_attn.py
Labels: ready

#8619 [Core] simplify logits resort in _apply_top_k_top_p
  vllm/model_executor/layers/sampler.py
Labels: ready
