Repository vllm-project/vllm, pull requests merged in 2024-03, with the labels that each got.

#2762 Add Automatic Prefix Caching
  benchmarks/benchmark_throughput.py
  docs/source/models/engine_args.rst
  examples/offline_inference_with_prefix.py
  tests/prefix_caching/test_prefix_caching.py
  tests/test_cache_block_hashing.py
  vllm/block.py
  vllm/config.py
  vllm/core/block_manager.py
  vllm/core/evictor.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/api_server.py
  vllm/entrypoints/llm.py
  vllm/prefix.py
  vllm/sequence.py
  vllm/worker/model_runner.py
Labels: v0.3.4

#2978 Add document for vllm paged attention kernel.
  docs/source/assets/kernel/k_vecs.png
  docs/source/assets/kernel/key.png
  docs/source/assets/kernel/logits_vec.png
  docs/source/assets/kernel/q_vecs.png
  docs/source/assets/kernel/query.png
  docs/source/assets/kernel/v_vec.png
  docs/source/assets/kernel/value.png
  docs/source/dev/kernel/paged_attention.rst
  docs/source/index.rst
Labels: documentation

#3123 [ROCm] enable cupy in order to enable cudagraph mode for AMD GPUs
  Dockerfile.rocm
  vllm/worker/worker.py
Labels: rocm

#3321 [ROCm] Fix warp and lane calculation in blockReduceSum
  csrc/reduction_utils.cuh
Labels: rocm

#3153 Support Mistral Model Inference with transformers-neuronx
  examples/offline_inference_neuron.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/neuron/mistral.py
Labels: Inferentia/Trainium

#3357 [PREFIX CACHING FOLLOW UP] A bunch of fixes to block allocator performance when automatic prefix caching is disabled
  tests/core/test_block_manager.py
  tests/prefix_caching/test_prefix_caching.py
  vllm/core/block_manager.py
  vllm/core/evictor.py
Labels: action-required

#3471 [Hardware][Neuron] Refactor neuron support
  examples/offline_inference_neuron.py
  tests/lora/test_worker.py
  tests/spec_decode/test_spec_decode_worker.py
  tests/spec_decode/utils.py
  tests/worker/test_swap.py
  vllm/config.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/executor/gpu_executor.py
  vllm/executor/neuron_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/lora/layers.py
  vllm/lora/lora.py
  vllm/lora/models.py
  vllm/model_executor/__init__.py
  vllm/model_executor/input_metadata.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/neuron/llama.py
  vllm/model_executor/models/neuron/mistral.py
  vllm/model_executor/neuron_model_loader.py
  vllm/model_executor/sampling_metadata.py
  vllm/model_executor/utils.py
  vllm/spec_decode/metrics.py
  vllm/spec_decode/multi_step_worker.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/utils.py
  vllm/worker/cache_engine.py
  vllm/worker/model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/neuron_worker.py
  vllm/worker/worker.py
Labels: Inferentia/Trainium

#3042 [Feature] Add vision language model support.
  .buildkite/download-images.sh
  .buildkite/test-pipeline.yaml
  examples/llava_example.py
  requirements-dev.txt
  tests/conftest.py
  tests/models/test_llava.py
  tests/models/test_models.py
  tests/spec_decode/utils.py
  tests/worker/test_model_runner.py
  tests/worker/test_swap.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/executor/ray_gpu_executor.py
  vllm/model_executor/model_loader.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/sequence.py
  vllm/transformers_utils/config.py
  vllm/utils.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: new model

#3625 [Core] remove cupy dependency
  .buildkite/test-pipeline.yaml
  Dockerfile
  Dockerfile.rocm
  requirements.txt
  setup.py
  tests/distributed/test_basic_distributed_correctness.py
  tests/distributed/test_comm_ops.py
  tests/distributed/test_pynccl.py
  vllm/executor/ray_gpu_executor.py
  vllm/model_executor/parallel_utils/communication_op.py
  vllm/model_executor/parallel_utils/cupy_utils.py
  vllm/model_executor/parallel_utils/parallel_state.py
  vllm/model_executor/parallel_utils/pynccl.py
  vllm/model_executor/parallel_utils/pynccl_utils.py
  vllm/test_utils.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: release-blocker

#3660 [Model] Add support for DBRX
  README.md
  docs/source/models/supported_models.rst
  requirements.txt
  vllm/config.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/dbrx.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/dbrx.py
Labels: release-blocker

#3433 Add support for Cohere's Command-R model
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/commandr.py
Labels: new model, release-blocker

#3610 [Model] Add support for xverse
  README.md
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/xverse.py
Labels: new model, action-required

#3701 fix logging msg for block manager
  vllm/attention/selector.py
  vllm/core/block_manager_v1.py
  vllm/model_executor/parallel_utils/pynccl_utils.py
Labels: release-blocker

#2852 Usage Stats Collection
  .buildkite/test-template.j2
  Dockerfile
  docs/source/index.rst
  docs/source/serving/usage_stats.md
  requirements-neuron.txt
  requirements-rocm.txt
  requirements.txt
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/api_server.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/api_server.py
  vllm/model_executor/model_loader.py
  vllm/usage/__init__.py
  vllm/usage/usage_lib.py
Labels: release-blocker

#3731 [BugFix][Frontend] Fix completion logprobs=0 error
  tests/entrypoints/test_openai_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/model_executor/layers/sampler.py
  vllm/outputs.py
Labels: release-blocker

#3727 [Bugfix] Command-R Max Model Length
  vllm/config.py
Labels: release-blocker

#3699 [ROCm][Bugfix] Fixed several bugs related to rccl path and attention selector logic
  Dockerfile.rocm
  requirements-rocm.txt
  vllm/attention/backends/xformers.py
  vllm/model_executor/parallel_utils/pynccl.py
Labels: rocm

#3662 [Kernel] Layernorm performance optimization
  cmake/utils.cmake
  csrc/layernorm_kernels.cu
  csrc/reduction_utils.cuh
  tests/kernels/test_layernorm.py
Labels: rocm
