Repository vllm-project/vllm, pull requests merged in 2024-11, with the labels that each got.

#9892 [Bugfix][Frontend] Reject guided decoding in multistep mode
  docs/source/serving/compatibility_matrix.rst
  tests/entrypoints/openai/test_prompt_validation.py
  vllm/engine/llm_engine.py
  vllm/sampling_params.py
Labels: documentation, ready

#9896 [torch.compile] directly register custom op
  tests/compile/piecewise/test_simple.py
  tests/compile/piecewise/test_toy_llama.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/distributed/parallel_state.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/utils.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready

#9887 [Bugfix] Fix layer skip logic with bitsandbytes
  vllm/model_executor/layers/quantization/bitsandbytes.py
Labels: ready

#9866 [torch.compile] rework test plans
  tests/compile/test_basic_correctness.py
  tests/utils.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/phi3v.py
Labels: ready

#9891 [Model] Support bitsandbytes for MiniCPMV
  vllm/model_executor/models/minicpmv.py
Labels: ready

#9876 [torch.compile] Adding torch compile annotations to some models
  docs/source/models/supported_models.rst
  tests/distributed/test_pipeline_parallel.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_moe.py
Labels: documentation

#9906 [Doc] Update multi-input support
  docs/source/models/supported_models.rst
Labels: documentation, ready

#9759 [Frontend] Chat-based Embeddings API
  docs/requirements-docs.txt
  docs/source/conf.py
  docs/source/dev/pooling_params.rst
  docs/source/getting_started/quickstart.rst
  docs/source/index.rst
  docs/source/models/vlm.rst
  docs/source/serving/openai_compatible_server.md
  tests/entrypoints/openai/test_basic.py
  tests/entrypoints/openai/test_embedding.py
  tests/entrypoints/openai/test_metrics.py
  tests/entrypoints/openai/test_tokenization.py
  tests/entrypoints/openai/test_vision_embedding.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/pooling_params.py
Labels: documentation, frontend, ready

#9813 [CI/Build] Add Model Tests for PixtralHF
  tests/models/decoder_only/vision_language/test_models.py
Labels: ready

#9912 [Frontend] Use a proper chat template for VLM2Vec
  docs/source/models/vlm.rst
  examples/openai_chat_completion_client_for_multimodal.py
  examples/openai_chat_embedding_client_for_multimodal.py
  examples/template_vlm2vec.jinja
  tests/entrypoints/openai/test_vision_embedding.py
  vllm/entrypoints/chat_utils.py
Labels: documentation, frontend, ready

#9625 [Bugfix] Fix edge cases for MistralTokenizer
  tests/tokenization/test_detokenize.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#9889 [torch.compile] use interpreter with stable api from pytorch
  vllm/compilation/backends.py
Labels: ready

#9861 [Bugfix/Core] Remove assertion for Flashinfer k_scale and v_scale
  tests/kernels/test_cache.py
  vllm/attention/backends/flashinfer.py
  vllm/model_executor/layers/quantization/modelopt.py
Labels: ready

#9933 [1/N] pass the complete config from engine to executor
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/engine.py
  vllm/executor/executor_base.py
  vllm/executor/xpu_executor.py
  vllm/v1/engine/llm_engine.py
Labels: ready

#9934 [Bugfix] PicklingError on RayTaskError
  vllm/engine/multiprocessing/engine.py
Labels: ready

#8346 [Core][VLM] Add precise multi-modal placeholder tracking
  examples/offline_inference_audio_language.py
  tests/kernels/utils.py
  tests/models/decoder_only/audio_language/test_ultravox.py
  tests/multimodal/test_processor_kwargs.py
  tests/multimodal/test_utils.py
  tests/worker/test_model_input.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/placeholder_attn.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/core/scheduler.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/inputs/registry.py
  vllm/model_executor/models/blip.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/utils.py
  vllm/multimodal/__init__.py
  vllm/multimodal/base.py
  vllm/multimodal/image.py
  vllm/multimodal/registry.py
  vllm/multimodal/utils.py
  vllm/multimodal/video.py
  vllm/sequence.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/model_runner_base.py
  vllm/worker/openvino_model_runner.py
  vllm/worker/tpu_model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: ready

#9935 [ci/build] Have dependabot ignore pinned dependencies
  .github/dependabot.yml
Labels: ready, ci/build

#9559 [Encoder Decoder] Add flash_attn kernel support for encoder-decoder models
  tests/encoder_decoder/test_e2e_correctness.py
  tests/kernels/test_encoder_decoder_attn.py
  tests/kernels/utils.py
  tests/models/encoder_decoder/vision_language/test_florence2.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/attention/selector.py
  vllm/model_executor/models/bart.py
  vllm/utils.py
  vllm/worker/enc_dec_model_runner.py
Labels: ready

#9947 [torch.compile] fix cpu broken code
  vllm/utils.py
Labels: ready

#9930 [Docs] Update Granite 3.0 models in supported models table
  docs/source/models/supported_models.rst
Labels: documentation, ready

#9926 [Doc] Updated tpu-installation.rst with more details
  docs/source/getting_started/tpu-installation.rst
Labels: documentation, ready

#9938 [2/N] executor pass the complete config to worker/modelrunner
  tests/lora/test_long_context.py
  tests/lora/test_worker.py
  tests/spec_decode/utils.py
  tests/worker/test_encoder_decoder_model_runner.py
  tests/worker/test_model_runner.py
  tests/worker/test_profile.py
  tests/worker/test_swap.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/executor/cpu_executor.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/executor/neuron_executor.py
  vllm/executor/openvino_executor.py
  vllm/executor/tpu_executor.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/ngram_worker.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/target_model_runner.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/executor/gpu_executor.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/embedding_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/model_runner_base.py
  vllm/worker/multi_step_model_runner.py
  vllm/worker/multi_step_worker.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/neuron_worker.py
  vllm/worker/openvino_model_runner.py
  vllm/worker/openvino_worker.py
  vllm/worker/tpu_model_runner.py
  vllm/worker/tpu_worker.py
  vllm/worker/worker.py
  vllm/worker/worker_base.py
  vllm/worker/xpu_model_runner.py
  vllm/worker/xpu_worker.py
Labels: ready

#9954 [V1] Fix `EngineArgs` refactor on V1
  vllm/v1/executor/gpu_executor.py
Labels: ready

#9955 [bugfix] fix chatglm dummy_data_for_glmv
  vllm/model_executor/models/chatglm.py
Labels: ready

#9956 [CI/Build] Quoting around >
  Dockerfile
  Dockerfile.neuron
  Dockerfile.ppc64le
  Dockerfile.rocm
  Dockerfile.tpu
Labels: ci/build

#9747 [Model] Add support for H2OVL-Mississippi models
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
  tests/models/decoder_only/vision_language/test_h2ovl.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/h2ovl.py
Labels: documentation, frontend, ready

#9971 [V1] Fix Configs
  vllm/v1/executor/gpu_executor.py
Labels: ready

#9885 [Bugfix]Using the correct type hints
  vllm/sequence.py
Labels: ready

#9984 [Bugfix] Fix E2EL mean and median stats
  benchmarks/benchmark_serving.py
Labels: ready

#9974 [Bugfix][OpenVINO] Fix circular reference #9939
  vllm/platforms/openvino.py
Labels: ready

#9978 [4/N] make quant config first-class citizen
  vllm/config.py
  vllm/model_executor/model_loader/loader.py
Labels: ready

#9987 [Misc]Reduce BNB static variable
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/qwen2.py
Labels: ready

#8993 [Model] factoring out MambaMixer out of Jamba
  vllm/model_executor/layers/mamba/mamba_mixer.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mamba.py
Labels: documentation, frontend, ready, ci/build

#9968 [CI] Basic Integration Test For TPU
  .buildkite/run-tpu-test.sh
  tests/entrypoints/openai/test_accuracy.py
Labels: tpu, ready, ci/build

#9279 [Bugfix][CI/Build][Hardware][AMD] Shard ID parameters in AMD tests running parallel jobs
  .buildkite/run-amd-test.sh
  tests/lora/test_minicpmv.py
Labels: ready, ci/build

#9999 [Doc] Update VLM doc about loading from local files
  docs/source/models/vlm.rst
Labels: documentation, ready

#9973 [Bugfix] Fix `MQLLMEngine` hanging
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready

#9779 [Misc] Refactor benchmark_throughput.py
  benchmarks/benchmark_throughput.py
Labels: ready

#9881 [Frontend] Add max_tokens prometheus metric
  tests/entrypoints/openai/test_metrics.py
  tests/metrics/test_metrics.py
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
  vllm/engine/metrics_types.py
Labels: ready

#10001 [Bugfix] Upgrade to pytorch 2.5.1
  CMakeLists.txt
  pyproject.toml
  requirements-build.txt
  requirements-cuda.txt
  requirements-openvino.txt
  requirements-test.in
  requirements-test.txt
Labels: ready, ci/build

#9895 [Bugfix] Respect modules_to_not_convert within awq_marlin
  vllm/model_executor/layers/quantization/awq_marlin.py
Labels: ready

#9994 [Core] Use os.sched_yield in ShmRingBuffer instead of time.sleep
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#10004 [Bugfix] Fixup Mamba
  vllm/model_executor/models/mamba.py
Labels: ready

#10017 [Misc] vllm CLI flags should be ordered for better user readability
  vllm/utils.py
Labels: ready

#10012 [Frontend] Fix tcp port reservation for api server
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready

#10010 Refactor TPU requirements file and pin build dependencies
  Dockerfile.tpu
  docs/source/getting_started/tpu-installation.rst
  requirements-tpu.txt
Labels: documentation, ready, ci/build

#9928 [CI/Build] Limit github CI jobs based on files changed
  .github/workflows/actionlint.yml
  .github/workflows/clang-format.yml
  .github/workflows/mypy.yaml
  .github/workflows/ruff.yml
  .github/workflows/yapf.yml
Labels: ready, ci/build

#9921 [Model] Support quantization of PixtralHFTransformer for PixtralHF
  vllm/model_executor/layers/activation.py
  vllm/model_executor/models/pixtral.py
Labels: ready

#9851 [Feature] Update benchmark_throughput.py to support image input
  benchmarks/README.md
  benchmarks/benchmark_throughput.py
Labels: documentation, frontend, ready, ci/build

#9997 [Misc] Modify BNB parameter name
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/layers/resampler.py
  vllm/model_executor/model_loader/loader.py
Labels: ready

#9940 [CI] Prune tests/models/decoder_only/language/* tests
  .buildkite/test-pipeline.yaml
  tests/models/decoder_only/language/test_big_models.py
  tests/models/decoder_only/language/test_fp8.py
  tests/models/decoder_only/language/test_gptq_marlin.py
  tests/models/decoder_only/language/test_gptq_marlin_24.py
  tests/models/decoder_only/language/test_marlin.py
  tests/models/decoder_only/language/test_mistral.py
  tests/models/decoder_only/language/test_models.py
  tests/models/decoder_only/language/test_qwen.py
Labels: ready, ci/build

#9932 [CI] Prune back the number of tests in tests/kernels/*
  tests/kernels/test_activation.py
  tests/kernels/test_attention.py
  tests/kernels/test_awq_marlin.py
  tests/kernels/test_blocksparse_attention.py
  tests/kernels/test_cache.py
  tests/kernels/test_cutlass.py
  tests/kernels/test_int8_quant.py
  tests/kernels/test_marlin_gemm.py
  tests/kernels/test_moe.py
  tests/kernels/test_pos_encoding.py
Labels: ready

#10047 [Bugfix] Properly propagate trust_remote_code settings
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/molmo.py
Labels: ready

#9931 [Bugfix] Fix pickle of input when async output processing is on
  tests/basic_correctness/test_basic_correctness.py
  vllm/worker/model_runner.py
Labels: ready

#9730 [Bugfix][SpecDecode] kv corruption with bonus tokens in spec decode
  tests/spec_decode/test_multi_step_worker.py
  tests/spec_decode/utils.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/multi_step_worker.py
Labels: ready

#10037 [Misc] Sort the list of embedding models
  vllm/model_executor/models/registry.py
Labels: ready

#10045 [Model][OpenVINO] Fix regressions from #8346
  .buildkite/run-openvino-test.sh
  vllm/attention/backends/openvino.py
  vllm/model_executor/models/molmo.py
Labels: ready, ci/build

#10051 [Bugfix] Fix edge-case crash when using chat with the Mistral Tekken Tokenizer
  tests/models/decoder_only/language/test_mistral.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#10063 [Bugfix] Gpt-j-6B patch kv_scale to k_scale path
  vllm/model_executor/models/gpt_j.py
Labels: ready

#10054 [Bugfix] Remove CustomChatCompletionContentPartParam multimodal input type
  vllm/entrypoints/chat_utils.py
Labels: frontend, ready

#10064 [distributed] add function to create ipc buffers directly
  .buildkite/test-pipeline.yaml
  tests/distributed/test_ca_buffer_sharing.py
  vllm/distributed/device_communicators/custom_all_reduce.py
Labels: ci/build

#10070 [CI/Build] Fix large_gpu_mark reason
  tests/utils.py
Labels: ready

#6143 [Hardware][Intel-Gaudi] Add Intel Gaudi (HPU) inference backend
  Dockerfile.hpu
  docs/source/getting_started/gaudi-installation.rst
  docs/source/index.rst
  requirements-hpu.txt
  setup.py
  vllm/_custom_ops.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/ops/hpu_paged_attn.py
  vllm/attention/selector.py
  vllm/config.py
  vllm/core/block/cpu_gpu_block_allocator.py
  vllm/distributed/device_communicators/hpu_communicator.py
  vllm/distributed/parallel_state.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/executor/hpu_executor.py
  vllm/executor/ray_hpu_executor.py
  vllm/executor/ray_utils.py
  vllm/model_executor/custom_op.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
  vllm/model_executor/sampling_metadata.py
  vllm/platforms/__init__.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/utils.py
  vllm/worker/hpu_model_runner.py
  vllm/worker/hpu_worker.py
Labels: documentation, Gaudi, ci/build

#10073 [Hotfix] Fix ruff errors
  setup.py
  vllm/executor/ray_hpu_executor.py
  vllm/worker/hpu_model_runner.py
Labels: ci/build

#10071 [Model][LoRA]LoRA support added for LlamaEmbeddingModel
  docs/source/models/supported_models.rst
  vllm/model_executor/models/llama.py
Labels: documentation, ready

#9767 [Model] Add Idefics3 support
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
  tests/models/decoder_only/vision_language/test_models.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/idefics2_vision_model.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/registry.py
Labels: documentation, frontend, ready

#10022 [Model][LoRA]LoRA support added for Qwen2VLForConditionalGeneration
  docs/source/models/supported_models.rst
  vllm/model_executor/models/qwen2_vl.py
Labels: documentation, ready

#10057 Remove ScaledActivation for AWQ
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/quantization/aqlm.py
  vllm/model_executor/layers/quantization/awq.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/base_config.py
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/deepspeedfp.py
  vllm/model_executor/layers/quantization/experts_int8.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/gguf.py
  vllm/model_executor/layers/quantization/gptq.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/gptq_marlin_24.py
  vllm/model_executor/layers/quantization/ipex_quant.py
  vllm/model_executor/layers/quantization/marlin.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/layers/quantization/neuron_quant.py
  vllm/model_executor/layers/quantization/qqq.py
  vllm/model_executor/layers/quantization/tpu_int8.py
  vllm/model_executor/models/bart.py
  vllm/model_executor/models/bloom.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/gpt_bigcode.py
  vllm/model_executor/models/gpt_j.py
  vllm/model_executor/models/gpt_neox.py
  vllm/model_executor/models/mpt.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/persimmon.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/starcoder2.py
Labels: ready

#10038 [CI/Build] Drop Python 3.8 support
  .readthedocs.yaml
  CMakeLists.txt
  docs/source/getting_started/amd-installation.rst
  docs/source/getting_started/installation.rst
  docs/source/getting_started/neuron-installation.rst
  docs/source/getting_started/quickstart.rst
  setup.py
  vllm/distributed/parallel_state.py
Labels: documentation, ready, ci/build

#10092 [CI/Build] Always run the ruff workflow
  .github/workflows/ruff.yml
Labels: ready, ci/build

#10072 [core][distributed] add stateless_init_process_group
  .buildkite/test-pipeline.yaml
  tests/distributed/test_utils.py
  vllm/distributed/utils.py
Labels: ci/build

#10095 [Bugfix] Fix FP8 torch._scaled_mm fallback for torch>2.5 with CUDA<12.4
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#9823 [Misc][XPU] Upgrade to Pytorch 2.5 for xpu backend
  Dockerfile.xpu
  requirements-xpu.txt
  vllm/_ipex_ops.py
  vllm/attention/backends/ipex_attn.py
Labels: Intel GPU, ci/build

#10056 [Frontend] Adjust try/except blocks in API impl
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
Labels: frontend, ready

#9911 [Hardware][CPU] Update torch 2.5
  .buildkite/run-cpu-test.sh
  Dockerfile.cpu
  cmake/cpu_extension.cmake
  csrc/cpu/attention.cpp
  csrc/cpu/cpu_types_x86.hpp
  csrc/cpu/dnnl_helper.hpp
  csrc/cpu/quant.cpp
  docs/source/getting_started/cpu-installation.rst
  requirements-cpu.txt
  tests/models/decoder_only/language/test_models.py
  vllm/executor/cpu_executor.py
  vllm/model_executor/layers/quantization/ipex_quant.py
Labels: documentation, frontend, ready, ci/build

#10100 [doc] add back Python 3.8 ABI
  docs/source/getting_started/installation.rst
Labels: documentation

#10097 [V1][BugFix] Fix Generator construction in greedy + seed case
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#10104 [Misc] Consolidate ModelConfig code related to HF config
  docs/source/serving/compatibility_matrix.rst
  tests/test_config.py
  vllm/config.py
  vllm/inputs/preprocess.py
  vllm/transformers_utils/config.py
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: documentation, ready

#10083 [CI/Build] re-add codespell to CI
  .github/workflows/codespell.yml
Labels: ready, ci/build

#9927 Doc: Improve benchmark documentation
  docs/source/dev/profiling/profiling_index.rst
  docs/source/index.rst
  docs/source/performance/benchmarks.rst
  docs/source/performance_benchmark/benchmarks.rst
Labels: documentation

#10041 [CI/Build] Improve mypy + python version matrix
  .github/workflows/mypy.yaml
  pyproject.toml
  tools/mypy.sh
Labels: documentation, ready, ci/build

#9506 Adds method to read the pooling types from model's files
  examples/fp8/quantizer/quantize.py
  tests/engine/test_arg_utils.py
  tests/model_executor/test_model_load_with_params.py
  tests/test_config.py
  tests/utils.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/pooler.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/tokenizer_group/__init__.py
Labels: frontend, ready

#10076 [Frontend] Fix multiple values for keyword argument error (#10075)
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend, ready

#10108 [Hardware][CPU][bugfix] Fix half dtype support on AVX2-only target
  cmake/cpu_extension.cmake
  csrc/cpu/cpu_types_x86.hpp
Labels: ready, ci/build

#10112 [Bugfix] Make image processor respect `mm_processor_kwargs` for Qwen2-VL
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#10105 [Misc] Add Gamma-Distribution Request Generation Support for Serving Benchmark.
  benchmarks/benchmark_serving.py
Labels: ready

#9027 [Frontend] Tool calling parser for Granite 3.0 models
  docs/source/serving/openai_compatible_server.md
  examples/tool_chat_template_granite.jinja
  tests/tool_use/conftest.py
  tests/tool_use/utils.py
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/granite_tool_parser.py
Labels: documentation, frontend, ready, ci/build

#9291 [Feature] [Spec decode]: Combine chunked prefill with speculative decoding
  tests/spec_decode/e2e/test_compatibility.py
  tests/spec_decode/e2e/test_multistep_correctness.py
  tests/spec_decode/e2e/test_ngram_correctness.py
  tests/spec_decode/test_ngram_worker.py
  tests/spec_decode/test_scorer.py
  tests/spec_decode/test_spec_decode_worker.py
  tests/spec_decode/utils.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/xformers.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/engine/output_processor/multi_step.py
  vllm/spec_decode/batch_expansion.py
  vllm/spec_decode/mqa_scorer.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/top1_proposer.py
Labels: documentation, frontend, ready, ci/build

#10122 [CI/Build] Always run mypy
  .github/workflows/mypy.yaml
Labels: ready, ci/build

#7925 [CI/Build] Add shell script linting using shellcheck
  .buildkite/lm-eval-harness/run-lm-eval-gsm-hf-baseline.sh
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  .buildkite/lm-eval-harness/run-tests.sh
  .buildkite/nightly-benchmarks/scripts/launch-server.sh
  .buildkite/nightly-benchmarks/scripts/nightly-annotate.sh
  .buildkite/nightly-benchmarks/scripts/run-nightly-benchmarks.sh
  .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh
  .buildkite/nightly-benchmarks/scripts/wait-for-image.sh
  .buildkite/run-amd-test.sh
  .buildkite/run-benchmarks.sh
  .buildkite/run-cpu-test-ppc64le.sh
  .buildkite/run-cpu-test.sh
  .buildkite/run-multi-node-test.sh
  .buildkite/run-neuron-test.sh
  .buildkite/run-openvino-test.sh
  .buildkite/run-tpu-test.sh
  .buildkite/run-xpu-test.sh
  .github/workflows/scripts/cuda-install.sh
  .github/workflows/scripts/pytorch-install.sh
  .github/workflows/shellcheck.yml
  .gitignore
  .shellcheckrc
  benchmarks/launch_tgi_server.sh
  examples/run_cluster.sh
  format.sh
  tests/weight_loading/run_model_weight_loading_test.sh
  tools/mypy.sh
  tools/shellcheck.sh
Labels: ready, ci/build

#10082 [CI/Build] Automate PR body text cleanup
  .github/scripts/cleanup_pr_body.sh
  .github/workflows/cleanup_pr_body.yml
Labels: ready, ci/build

#10135 [V1] Add all_token_ids attribute to Request
  vllm/v1/core/scheduler.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/request.py
  vllm/v1/utils.py
Labels: ready

#9972 [V1] Prefix caching (take 2)
  benchmarks/benchmark_prefix_caching.py
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/llm_engine.py
Labels: ready

#10139 [CI/Build] Give PR cleanup job PR write access
  .github/workflows/cleanup_pr_body.yml
Labels: ready, ci/build

#9662 [Doc] Update FAQ links in spec_decode.rst
  docs/source/models/spec_decode.rst
Labels: documentation, ready

#5895 [Bugfix] Add error handling when server cannot respond any valid tokens
  benchmarks/backend_request_func.py
Labels: ready

#9493 [Misc] Fix ImportError causing by triton
  vllm/executor/multiproc_gpu_executor.py
Labels: ready

#9924 [Doc] Move CONTRIBUTING to docs site
  CONTRIBUTING.md
  docs/source/contributing/dockerfile/dockerfile.rst
  docs/source/contributing/overview.rst
  docs/source/contributing/profiling/profiling_index.rst
  docs/source/design/input_processing/input_processing_pipeline.rst
  docs/source/design/input_processing/model_inputs_index.rst
  docs/source/design/kernel/paged_attention.rst
  docs/source/design/multimodal/adding_multimodal_plugin.rst
  docs/source/design/multimodal/multimodal_index.rst
  docs/source/index.rst
Labels: documentation, ready

#10145 [Misc] Fix typo in #5895
  benchmarks/backend_request_func.py
Labels: ready

#10144 [Bugfix][XPU] Fix xpu tp by introducing XpuCommunicator
  vllm/distributed/device_communicators/xpu_communicator.py
  vllm/distributed/parallel_state.py
Labels: ready

#10146 [Model] Expose size to Idefics3 as mm_processor_kwargs
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_idefics3.py
  vllm/model_executor/models/idefics3.py
Labels: ready

#5481 [CI/Build] Update CPU tests to include all "standard" tests
  .buildkite/run-cpu-test-ppc64le.sh
  .buildkite/run-cpu-test.sh
  .buildkite/test-pipeline.yaml
  pyproject.toml
  requirements-test.in
  tests/models/decoder_only/audio_language/test_ultravox.py
  tests/models/decoder_only/vision_language/test_h2ovl.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_phi3v.py
  tests/models/utils.py
  vllm/assets/image.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/utils.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU, ready, ci/build

#10152 Fix edge case Mistral tokenizer
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#10136 Disable spec-decode + chunked-prefill for draft models with tensor parallelism > 1
  tests/spec_decode/e2e/test_compatibility.py
  vllm/config.py
Labels: ready

#10090 [Misc] Improve Web UI
  docs/source/_static/custom.js
Labels: documentation

#10162 [CI/Build] Ignore .gitignored files for shellcheck
  tools/shellcheck.sh
Labels: ready

#10134 Rename vllm.logging to vllm.logging_utils
  pyproject.toml
  tests/test_logger.py
  vllm/logger.py
  vllm/logging/__init__.py
  vllm/logging_utils/__init__.py
  vllm/logging_utils/formatter.py
Labels: ready

#9857 [Kernel][Triton] Add Triton implementation for scaled_mm_triton to support fp8 and int8 SmoothQuant, symmetric case
  tests/kernels/test_triton_scaled_mm.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/compressed_tensors/triton_scaled_mm.py
Labels: ready

#6892 [CI/Build] Adding timeout in CPU CI to avoid CPU test queue blocking
  .buildkite/run-cpu-test-ppc64le.sh
  .buildkite/run-cpu-test.sh
Labels: ready, ci/build, unstale

#10040 [0/N] Rename `MultiModalInputs` to `MultiModalKwargs`
  docs/source/design/multimodal/multimodal_index.rst
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_qwen.py
  tests/multimodal/test_base.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/__init__.py
  vllm/multimodal/audio.py
  vllm/multimodal/base.py
  vllm/multimodal/image.py
  vllm/multimodal/registry.py
  vllm/multimodal/video.py
  vllm/spec_decode/draft_model_runner.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/embedding_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/hpu_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/openvino_model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: documentation, ready

#10161 [CI/Build] Fix VLM broadcast tests `tensor_parallel_size` passing
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/types.py
Labels: ready

#10176 [Doc] Adjust RunLLM location
  docs/source/_static/custom.js
Labels: documentation, ready

#10167 [CI/Build] Add run-hpu-test.sh script
  .buildkite/run-hpu-test.sh
  Dockerfile.hpu
Labels: ready, ci/build

#10171 [Bugfix] Enable some fp8 and quantized fullgraph tests
  tests/compile/utils.py
Labels: ready

#10173 [doc] explaining the integration with huggingface
  docs/source/design/huggingface_integration.rst
  docs/source/index.rst
Labels: documentation

#2756 bugfix: fix the bug that stream generate not work
  vllm/entrypoints/api_server.py
Labels: frontend, ready, unstale

#9594 [Frontend] add `add_request_id` middleware
  docs/source/serving/openai_compatible_server.md
  vllm/entrypoints/openai/api_server.py
Labels: documentation, frontend, ready

#5836 [Frontend][Core] Override HF `config.json` via CLI
  tests/test_config.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/transformers_utils/config.py
  vllm/v1/engine/llm_engine.py
Labels: frontend, ready

#10069 [CI/Build] Split up models tests
  .buildkite/test-pipeline.yaml
  pyproject.toml
  tests/models/decoder_only/language/test_aqlm.py
  tests/models/decoder_only/language/test_fp8.py
  tests/models/decoder_only/language/test_gguf.py
  tests/models/decoder_only/language/test_gptq_marlin.py
  tests/models/decoder_only/language/test_gptq_marlin_24.py
  tests/models/decoder_only/language/test_granite.py
  tests/models/decoder_only/language/test_granitemoe.py
  tests/models/decoder_only/language/test_modelopt.py
  tests/models/decoder_only/language/test_models.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_llava_next.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_phi3v.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_qwen2_vl.py
  tests/models/decoder_only/vision_language/test_awq.py
  tests/models/decoder_only/vision_language/test_intern_vit.py
  tests/models/decoder_only/vision_language/test_models.py
  vllm/config.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/internlm2_ve.py
  vllm/model_executor/models/utils.py
Labels: ready, ci/build

#10188 [ci][build] limit cmake version
  Dockerfile.neuron
  Dockerfile.ppc64le
  docs/source/getting_started/cpu-installation.rst
  pyproject.toml
  requirements-build.txt
  requirements-tpu.txt
  requirements-xpu.txt
Labels: documentation, ci/build

#10190 [Doc] Fix typo error in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, ready

#10195 [doc] Polish the integration with huggingface doc
  docs/source/design/huggingface_integration.rst
Labels: documentation

#9543 [Misc] small fixes to function tracing file path
  docs/source/index.rst
  vllm/logger.py
  vllm/utils.py
Labels: documentation

#10202 [misc] improve cloudpickle registration and tests
  tests/distributed/test_pipeline_parallel.py
  vllm/engine/arg_utils.py
  vllm/transformers_utils/config.py
Labels: ready

#10196 [Doc] Fix typo error in vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/cli_args.py
Labels: frontend, ready

#10206 [doc] improve debugging code
  docs/source/getting_started/debugging.rst
Labels: documentation

#10193 [Hardware][CPU] Add embedding models support for CPU backend
  .buildkite/run-cpu-test-ppc64le.sh
  .buildkite/run-cpu-test.sh
  tests/models/embedding/language/test_embedding.py
  vllm/attention/backends/torch_sdpa.py
  vllm/model_executor/models/bert.py
  vllm/worker/cpu_embedding_model_runner.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU, ready, ci/build

#10214 [LoRA][Kernel] Remove the unused libentry module
  tests/lora/test_punica_sizes.py
  tests/lora/test_punica_variation.py
  vllm/lora/ops/sgmv_expand.py
  vllm/lora/ops/sgmv_expand_slice.py
  vllm/lora/ops/sgmv_shrink.py
  vllm/triton_utils/__init__.py
  vllm/triton_utils/libentry.py
Labels: ready

#10211 [V1] Allow `tokenizer_mode` and `trust_remote_code` for Detokenizer
  vllm/v1/engine/llm_engine.py
  vllm/v1/tokenizer/detokenizer.py
Labels: ready

#4464 [Metrics] add more metrics
  examples/production_monitoring/grafana.json
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
  vllm/engine/metrics_types.py
Labels: ready

#10212 [Doc] fix doc string typo in block_manager `swap_out` function
  vllm/core/block_manager.py
Labels: ready

#10183 Add docs on serving with Llama Stack
  docs/source/serving/integrations.rst
  docs/source/serving/serving_with_llamastack.rst
Labels: documentation

#10233 Make shutil rename in python_only_dev
  python_only_dev.py
Labels: frontend

#9826 [V1] `AsyncLLM` Implementation
  .buildkite/test-pipeline.yaml
  tests/entrypoints/llm/test_accuracy.py
  tests/entrypoints/openai/test_accuracy.py
  tests/v1/__init__.py
  tests/v1/engine/__init__.py
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_detokenizer.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/config.py
  vllm/engine/multiprocessing/engine.py
  vllm/engine/output_processor/stop_checker.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/api_server.py
  vllm/envs.py
  vllm/outputs.py
  vllm/v1/__init__.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/async_stream.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/processor.py
  vllm/v1/request.py
  vllm/v1/tokenizer/detokenizer.py
Labels: frontend, ready, ci/build

#10236 [doc] update debugging guide
  docs/source/getting_started/debugging.rst
Labels: documentation

#10231 [Doc] Update help text for `--distributed-executor-backend`
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#10223 [Misc][LoRA] Replace hardcoded cuda device with configurable argument
  tests/lora/test_layers.py
  tests/lora/test_lora_manager.py
  tests/lora/utils.py
  vllm/lora/models.py
  vllm/lora/punica.py
  vllm/lora/worker_manager.py
Labels: documentation, frontend, ready, ci/build

#10240 [doc] explain the class hierarchy in vLLM
  docs/source/assets/design/hierarchy.png
  docs/source/design/class_hierarchy.rst
  docs/source/design/huggingface_integration.rst
  docs/source/index.rst
Labels: documentation, ready

#10222 [CI][CPU]refactor CPU tests to allow to bind with different cores
  .buildkite/run-cpu-test.sh
Labels: ready, ci/build

#10000 [BugFix] Do not raise a `ValueError` when `tool_choice` is set to the supported `none` option and `tools` are not defined.
  docs/source/serving/openai_compatible_server.md
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_engine.py
Labels: documentation, frontend, ready

#9982 [Encoder Decoder] Update Mllama to run with both FlashAttention and XFormers
  tests/encoder_decoder/test_e2e_correctness.py
  tests/models/encoder_decoder/vision_language/test_mllama.py
  tests/test_config.py
  vllm/model_executor/models/mllama.py
  vllm/worker/enc_dec_model_runner.py
Labels: ready

#5733 [LoRA] Adds support for bias in LoRA
  tests/lora/conftest.py
  tests/lora/test_lora_bias_e2e.py
  tests/lora/test_utils.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/lora/fully_sharded_layers.py
  vllm/lora/layers.py
  vllm/lora/lora.py
  vllm/lora/models.py
  vllm/lora/utils.py
Labels: ready

#10266 [doc] fix location of runllm widget
  docs/source/_static/custom.js
Labels: documentation

#10270 [doc] improve debugging doc
  docs/source/getting_started/debugging.rst
Labels: documentation

#10271 Revert "[ci][build] limit cmake version"
  Dockerfile.neuron
  Dockerfile.ppc64le
  docs/source/getting_started/cpu-installation.rst
  pyproject.toml
  requirements-build.txt
  requirements-tpu.txt
  requirements-xpu.txt
Labels: documentation, ci/build

#10272 [V1] Fix CI tests on V1 engine
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/v1/engine/core.py
Labels: ready

#9871 [V1] Support VLMs with fine-grained scheduling
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2.py
  vllm/v1/core/encoder_cache_manager.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/core.py
  vllm/v1/engine/mm_input_mapper.py
  vllm/v1/request.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#10279 Bump to compressed-tensors v0.8.0
  requirements-common.txt
Labels: ready, ci/build

#10221 [Model] Add support for Qwen2-VL video embeddings input & multiple image embeddings input with varied resolutions
  docs/source/models/supported_models.rst
  tests/models/decoder_only/vision_language/test_qwen2_vl.py
  vllm/model_executor/models/qwen2_vl.py
Labels: documentation, ready

#9944 [Model] Adding Support for Qwen2VL as an Embedding Model. Using MrLight/dse-qwen2-2b-mrl-v1
  docs/source/models/supported_models.rst
  docs/source/models/vlm.rst
  examples/openai_chat_embedding_client_for_multimodal.py
  examples/template_dse_qwen2_vl.jinja
  tests/conftest.py
  tests/models/embedding/vision_language/test_dse_qwen2_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready
