Repository vllm-project/vllm, pull requests merged in 2024-01, with the labels that each got.

#1011 [DOC] Add additional comments for LLMEngine and AsyncLLMEngine
  docs/source/conf.py
  docs/source/dev/engine/async_llm_engine.rst
  docs/source/dev/engine/engine_index.rst
  docs/source/dev/engine/llm_engine.rst
  docs/source/index.rst
  vllm/core/scheduler.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/worker/worker.py
Labels: documentation

#2065 [Neuron] Add an option to build with neuron
  requirements-neuron.txt
  setup.py
  vllm/utils.py
Labels: Inferentia/Trainium

#2274 [ROCm] add support to ROCm 6.0 and MI300
  Dockerfile.rocm
  README.md
  csrc/cuda_utils.h
  csrc/cuda_utils_kernels.cu
  csrc/pybind.cpp
  docs/source/getting_started/amd-installation.rst
  setup.py
  vllm/utils.py
Labels: rocm

#2566 AWQ: Up to 2.66x higher throughput
  csrc/ops.h
  csrc/pybind.cpp
  csrc/quantization/awq/gemm_kernels.cu
  vllm/model_executor/layers/quantization/awq.py
Labels: quantization

#2581 ROCm: Allow setting compilation target
  setup.py
Labels: rocm
