Repository vllm-project/vllm, pull requests merged in 2024-04, with the labels that each got.

#3634 [Hardware][Intel] Add CPU inference backend
  .buildkite/run-cpu-test.sh
  .buildkite/test-template.j2
  CMakeLists.txt
  Dockerfile.cpu
  cmake/cpu_extension.cmake
  csrc/cpu/activation.cpp
  csrc/cpu/attention.cpp
  csrc/cpu/cache.cpp
  csrc/cpu/cpu_types.hpp
  csrc/cpu/layernorm.cpp
  csrc/cpu/pos_encoding.cpp
  csrc/cpu/pybind.cpp
  docs/source/getting_started/cpu-installation.rst
  docs/source/index.rst
  requirements-cpu.txt
  setup.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/selector.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/executor/cpu_executor.py
  vllm/utils.py
  vllm/worker/cpu_worker.py
Labels: action-required, Intel CPU

#3550 [3/N] Refactor scheduler for chunked prefill scheduling
  tests/core/test_scheduler.py
  tests/core/utils.py
  vllm/core/scheduler.py
  vllm/engine/llm_engine.py
  vllm/utils.py
Labels: action-required

#3290 Enable scaled FP8 (e4m3fn) KV cache on ROCm (AMD GPU)
  .gitignore
  CMakeLists.txt
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_throughput.py
  benchmarks/kernels/benchmark_paged_attention.py
  cmake/utils.cmake
  csrc/attention/attention_dtypes.h
  csrc/attention/attention_kernels.cu
  csrc/attention/dtype_fp8.cuh
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/ops.h
  csrc/pybind.cpp
  csrc/quantization/fp8/amd_detail/hip_float8.h
  csrc/quantization/fp8/amd_detail/hip_float8_impl.h
  csrc/quantization/fp8/amd_detail/quant_utils.cuh
  docs/source/index.rst
  docs/source/quantization/fp8_e4m3_kvcache.rst
  docs/source/quantization/fp8_e5m2_kvcache.rst
  examples/fp8/README.md
  examples/fp8/extract_scales.py
  examples/fp8/quantizer/README.md
  examples/fp8/quantizer/quantize.py
  pyproject.toml
  tests/fp8_kv/llama2-70b-fp8-kv/kv_cache_scales.json
  tests/fp8_kv/llama2-7b-fp8-kv/kv_cache_scales.json
  tests/kernels/test_attention.py
  tests/kernels/test_cache.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/attention/ops/paged_attn.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/model_executor/layers/quantization/schema.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/weight_utils.py
  vllm/utils.py
  vllm/worker/model_runner.py
Labels: rocm

#3840 [Bugfix] Add kv_scale input parameter to CPU backend
  csrc/cpu/attention.cpp
  csrc/cpu/cache.cpp
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/ops/paged_attn.py
Labels: x86 CPU

#3854 [Hardware][CPU] Update cpu torch to match default of 2.2.1
  requirements-cpu.txt
Labels: x86 CPU

#3915 [Benchmark] Add cpu options to bench scripts
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_throughput.py
Labels: x86 CPU

#3962 [Bugfix][ROCm] Add numba to Dockerfile.rocm
  Dockerfile.rocm
Labels: rocm

#3972 [Model][AMD] ROCm support for 256 head dims for Gemma
  vllm/attention/ops/triton_flash_attention.py
Labels: rocm

#3950 [WIP][Core][Refactor] move vllm/model_executor/parallel_utils into vllm/distributed and vllm/device_communicators
  tests/conftest.py
  tests/distributed/test_comm_ops.py
  tests/distributed/test_custom_all_reduce.py
  tests/distributed/test_pynccl.py
  tests/lora/conftest.py
  vllm/distributed/__init__.py
  vllm/distributed/communication_op.py
  vllm/distributed/device_communicators/__init__.py
  vllm/distributed/device_communicators/custom_all_reduce.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/device_communicators/pynccl_utils.py
  vllm/distributed/parallel_state.py
  vllm/distributed/utils.py
  vllm/lora/layers.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
  vllm/model_executor/models/baichuan.py
  vllm/model_executor/models/bloom.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/dbrx.py
  vllm/model_executor/models/deepseek.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/gpt_bigcode.py
  vllm/model_executor/models/gpt_j.py
  vllm/model_executor/models/gpt_neox.py
  vllm/model_executor/models/internlm2.py
  vllm/model_executor/models/jais.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/mixtral_quant.py
  vllm/model_executor/models/mpt.py
  vllm/model_executor/models/olmo.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/orion.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/stablelm.py
  vllm/model_executor/models/starcoder2.py
  vllm/model_executor/models/xverse.py
  vllm/model_executor/parallel_utils/README.md
  vllm/test_utils.py
  vllm/worker/cpu_worker.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: action-required

#3824 [Hardware][Intel] Isolate CPUModelRunner and ModelRunner for better maintenance
  vllm/attention/backends/torch_sdpa.py
  vllm/executor/cpu_executor.py
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU

#3441 Fix echo/logprob OpenAI completion bug
  tests/entrypoints/test_openai_server.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: action-required

#3984 Fix triton compilation issue
  vllm/attention/ops/triton_flash_attention.py
Labels: rocm

#4051 [Bugfix] fix_small_bug_in_neuron_executor
  vllm/executor/neuron_executor.py
Labels: Inferentia/Trainium

#3571 [CI/CD] add neuron docker and ci test scripts
  .buildkite/run-neuron-test.sh
  .buildkite/test-template.j2
  Dockerfile.neuron
  setup.py
  vllm/engine/async_llm_engine.py
  vllm/executor/neuron_executor.py
Labels: Inferentia/Trainium

#4129 [AMD][Hardware][Misc][Bugfix] xformer cleanup and light navi logic and CI fixes and refactoring
  .buildkite/test-pipeline.yaml
  Dockerfile.rocm
  patch_xformers.rocm.sh
  rocm_patch/commonpy_xformers-0.0.23.rocm.patch
  rocm_patch/flashpy_xformers-0.0.23.rocm.patch
  vllm/attention/backends/rocm_flash_attn.py
Labels: rocm

#3968 [Misc] Add vision language model support to CPU backend
  vllm/executor/cpu_executor.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU

#3993 [Frontend] Enable support for CPU backend in AsyncLLMEngine.
  vllm/engine/async_llm_engine.py
  vllm/executor/cpu_executor.py
Labels: x86 CPU

#3287 AQLM CUDA support
  CMakeLists.txt
  benchmarks/kernels/benchmark_aqlm.py
  csrc/ops.h
  csrc/pybind.cpp
  csrc/quantization/aqlm/gemm_kernels.cu
  examples/aqlm_example.py
  tests/models/test_aqlm.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/aqlm.py
  vllm/model_executor/layers/quantization/awq.py
  vllm/model_executor/layers/quantization/gptq.py
  vllm/model_executor/layers/quantization/marlin.py
  vllm/model_executor/layers/quantization/squeezellm.py
Labels: quantization

#4304 [Misc] Reduce supported Punica dtypes
  CMakeLists.txt
  csrc/punica/bgmv/bgmv_bf16_bf16_fp16.cu
  csrc/punica/bgmv/bgmv_bf16_fp16_bf16.cu
  csrc/punica/bgmv/bgmv_bf16_fp16_fp16.cu
  csrc/punica/bgmv/bgmv_bf16_fp32_fp16.cu
  csrc/punica/bgmv/bgmv_fp16_bf16_bf16.cu
  csrc/punica/bgmv/bgmv_fp16_bf16_fp16.cu
  csrc/punica/bgmv/bgmv_fp16_fp16_bf16.cu
  csrc/punica/bgmv/bgmv_fp16_fp32_bf16.cu
  csrc/punica/bgmv/bgmv_fp32_bf16_fp16.cu
  csrc/punica/bgmv/bgmv_fp32_fp16_bf16.cu
  csrc/punica/bgmv/bgmv_fp32_fp32_bf16.cu
  csrc/punica/bgmv/bgmv_fp32_fp32_fp16.cu
  csrc/punica/bgmv/generator.py
  csrc/punica/punica_ops.cc
  tests/lora/test_layers.py
Labels: release-blocker

#4376 [ROCm][Hardware][AMD][Doc] Documentation update for ROCm
  docs/source/getting_started/amd-installation.rst
Labels: rocm

#4406 [ROCm][Hardware][AMD] Enable group query attention for triton FA
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/ops/triton_flash_attention.py
Labels: rocm
