Repository vllm-project/vllm, pull requests merged in 2024-08, with the labels that each got.

#5036 [Kernel][RFC] Refactor the punica kernel based on Triton
  .github/workflows/scripts/build.sh
  CMakeLists.txt
  Dockerfile
  Dockerfile.rocm
  csrc/punica/LICENSE
  csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu
  csrc/punica/bgmv/bgmv_bf16_fp32_bf16.cu
  csrc/punica/bgmv/bgmv_config.h
  csrc/punica/bgmv/bgmv_fp16_fp16_fp16.cu
  csrc/punica/bgmv/bgmv_fp16_fp32_fp16.cu
  csrc/punica/bgmv/bgmv_fp32_bf16_bf16.cu
  csrc/punica/bgmv/bgmv_fp32_fp16_fp16.cu
  csrc/punica/bgmv/bgmv_impl.cuh
  csrc/punica/bgmv/generator.py
  csrc/punica/bgmv/vec_dtypes.cuh
  csrc/punica/punica_ops.cu
  csrc/punica/punica_ops.h
  csrc/punica/torch_bindings.cpp
  csrc/punica/type_convert.h
  docs/source/getting_started/installation.rst
  setup.py
  tests/kernels/test_sampler.py
  tests/lora/test_gemma.py
  tests/lora/test_layers.py
  tests/lora/test_lora.py
  tests/lora/test_punica.py
  tests/lora/test_punica_sizes.py
  tests/lora/test_punica_variation.py
  tests/lora/test_quant_model.py
  tests/lora/utils.py
  vllm/_custom_ops.py
  vllm/envs.py
  vllm/lora/fully_sharded_layers.py
  vllm/lora/layers.py
  vllm/lora/models.py
  vllm/lora/ops/__init__.py
  vllm/lora/ops/bgmv_expand.py
  vllm/lora/ops/bgmv_expand_slice.py
  vllm/lora/ops/bgmv_shrink.py
  vllm/lora/ops/sgmv_expand.py
  vllm/lora/ops/sgmv_expand_slice.py
  vllm/lora/ops/sgmv_shrink.py
  vllm/lora/ops/utils.py
  vllm/lora/punica.py
  vllm/triton_utils/__init__.py
  vllm/triton_utils/libentry.py
  vllm/worker/model_runner.py
Labels: ready

#6981 [Bugfix][TPU] Do not use torch.Generator for TPUs
  vllm/model_executor/model_loader/weight_utils.py
Labels: tpu

#6758 [Bugfix][Model] Skip loading lm_head weights if using tie_word_embeddings
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/olmo.py
Labels: ready

#6695 PP comm optimization: replace send with partial send + allgather
  vllm/distributed/parallel_state.py
  vllm/worker/worker_base.py
Labels: ready

#6954 [Bugfix] Set SamplingParams.max_tokens for OpenAI requests if not provided by user
  tests/entrypoints/openai/test_serving_chat.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: ready

#6951 [CI/Build] Update torch to 2.4
  .buildkite/test-pipeline.yaml
  .github/workflows/publish.yml
  CMakeLists.txt
  Dockerfile
  pyproject.toml
  requirements-build.txt
  requirements-cuda.txt
  vllm/model_executor/layers/ops/sample.py
Labels: ready

#6992 [Bugfix] Fix RMSNorm forward in InternViT attention qk_layernorm
  vllm/model_executor/models/intern_vit.py
Labels: ready

#7037 [CI/Build] Remove sparseml requirement from testing
  requirements-test.txt
  tests/conftest.py
  tests/models/test_compressed_tensors.py
  tests/quantization/test_compressed_tensors.py
Labels: ready

#7002 [Bugfix] Lower gemma's unloaded_params exception to warning
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/paligemma.py
Labels: ready

#6974 [Models] Support Qwen model with PP
  docs/source/serving/distributed_serving.rst
  vllm/config.py
  vllm/model_executor/models/qwen.py
Labels: ready

#7022 [Misc] Support attention logits soft-capping with flash-attn
  requirements-cuda.txt
  tests/kernels/test_flash_attn.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/model_executor/models/gemma2.py
Labels: ready

#7034 [CI/Build][Bugfix] Fix CUTLASS header-only line
  CMakeLists.txt
Labels: ready

#7051 [Performance] Optimize `get_seqs`
  vllm/core/block_manager_v1.py
  vllm/sequence.py
  vllm/transformers_utils/detokenizer.py
Labels: ready

#7008 [Kernel] Fix input for flashinfer prefill wrapper.
  vllm/attention/backends/flashinfer.py
Labels: ready

#7023 [Core] Comment out unused code in sampler
  vllm/model_executor/sampling_metadata.py
Labels: ready

#7035 [CI/Build] Add support for Python 3.12
  .github/workflows/mypy.yaml
  .github/workflows/publish.yml
  .github/workflows/ruff.yml
  .github/workflows/yapf.yml
  CMakeLists.txt
  docs/source/getting_started/installation.rst
  setup.py
Labels: ready

#6396 [Misc] Disambiguate quantized types via a new ScalarType
  CMakeLists.txt
  Dockerfile.openvino
  benchmarks/kernels/benchmark_marlin.py
  cmake/cpu_extension.cmake
  csrc/core/registration.h
  csrc/core/scalar_type.hpp
  csrc/core/torch_bindings.cpp
  csrc/cpu/torch_bindings.cpp
  csrc/moe/torch_bindings.cpp
  csrc/ops.h
  csrc/quantization/gptq_marlin/gptq_marlin.cu
  csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu
  csrc/torch_bindings.cpp
  setup.py
  tests/kernels/test_int8_quant.py
  tests/kernels/test_marlin_gemm.py
  tests/test_scalartype.py
  vllm/_core_ext.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w4a16_24.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/gptq_marlin_24.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_test.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_test_24.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/scalar_type.py
Labels: ready

#6837 [Core] Pipeline parallel with Ray ADAG
  Dockerfile
  MANIFEST.in
  requirements-adag.txt
  requirements-test.txt
  tests/distributed/test_pipeline_parallel.py
  tests/utils.py
  vllm/envs.py
  vllm/executor/ray_gpu_executor.py
  vllm/executor/ray_utils.py
  vllm/worker/worker_base.py
Labels: ready

#6883 [ Frontend ] Multiprocessing for OpenAI Server with `zeromq`
  tests/entrypoints/openai/test_disable_mp.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/logits_processors.py
  vllm/entrypoints/openai/rpc/__init__.py
  vllm/entrypoints/openai/rpc/client.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/envs.py
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
  vllm/tracing.py
  vllm/transformers_utils/tokenizer_group/__init__.py
  vllm/utils.py
Labels: ready

#7055 [Frontend] Factor out chat message parsing
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
Labels: ready

#7067 [Model] Refactor and decouple weight loading logic for InternVL2 model
  vllm/model_executor/models/intern_vit.py
  vllm/model_executor/models/internvl.py
Labels: ready

#7018 [Bugfix] Fix block table for seqs that have prefix cache hits
  tests/prefix_caching/test_prefix_caching.py
  vllm/attention/backends/flash_attn.py
Labels: ready

#7104 [CI] Temporarily turn off H100 performance benchmark
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
Labels: ready

#7080 [Frontend] Warn if user `max_model_len` is greater than derived `max_model_len`
  vllm/config.py
  vllm/envs.py
Labels: ready

#6878 Support for guided decoding for offline LLM
  docs/source/conf.py
  tests/entrypoints/conftest.py
  tests/entrypoints/llm/test_guided_generate.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/guided_fields.py
  vllm/model_executor/guided_decoding/lm_format_enforcer_decoding.py
  vllm/model_executor/guided_decoding/outlines_decoding.py
Labels: ready

#7020 [Model]Refactor MiniCPMV
  docs/source/models/supported_models.rst
  vllm/model_executor/models/idefics2_vision_model.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/na_vit.py
Labels: ready

#7105 [Bugfix] [SpecDecode] Default speculative_draft_tensor_parallel_size to 1 when using MLPSpeculator
  vllm/config.py
Labels: ready

#7027 Clean up remaining Punica C information
  .github/workflows/clang-format.yml
  cmake/utils.cmake
  format.sh
  vllm/config.py
  vllm/lora/layers.py
Labels: ready

#7122 [Model] Add multi-image support for minicpmv
  tests/conftest.py
  tests/models/test_minicpmv.py
  vllm/model_executor/models/minicpmv.py
  vllm/multimodal/image.py
Labels: ready

#7095 [Frontend] Reapply "Factor out code for running uvicorn"
  vllm/entrypoints/api_server.py
  vllm/entrypoints/launcher.py
  vllm/entrypoints/openai/api_server.py
Labels: ready

#6963 [Speculative decoding] Add periodic log with time spent in proposal/scoring/verification
  tests/spec_decode/test_spec_decode_worker.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/spec_decode/util.py
Labels: ready

#6926 [SpecDecode] Support FlashInfer in DraftModelRunner
  vllm/spec_decode/draft_model_runner.py
Labels: ready

#7121 [BugFix] Use args.trust_remote_code
  vllm/entrypoints/openai/api_server.py
Labels: ready

#7085 [Kernel] Update CUTLASS to 3.5.1
  CMakeLists.txt
  csrc/quantization/cutlass_w8a8/broadcast_load_epilogue_c3x.hpp
  csrc/quantization/cutlass_w8a8/scaled_mm_c2x.cuh
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x.cu
Labels: ready

#7001 [CI/Build] Suppress divide-by-zero and missing return statement warnings
  csrc/attention/dtype_bfloat16.cuh
  csrc/quantization/awq/dequantize.cuh
  csrc/quantization/fp8/nvidia/quant_utils.cuh
  csrc/quantization/gptq_marlin/gptq_marlin.cu
Labels: ready

#7171 [Bugfix][CI/Build] Fix CUTLASS FetchContent
  CMakeLists.txt
Labels: ready

#7100 [Doc] [SpecDecode] Update MLPSpeculator documentation
  docs/source/models/spec_decode.rst
  vllm/model_executor/models/mlp_speculator.py
Labels: ready

#7172 [MISC] Use non-blocking transfer in prepare_input
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
  vllm/worker/model_runner.py
Labels: ready

#5191 [Core] Support loading GGUF model
  .github/workflows/clang-format.yml
  CMakeLists.txt
  csrc/ops.h
  csrc/quantization/gguf/dequantize.cuh
  csrc/quantization/gguf/ggml-common.h
  csrc/quantization/gguf/gguf_kernel.cu
  csrc/quantization/gguf/mmq.cuh
  csrc/quantization/gguf/mmvq.cuh
  csrc/quantization/gguf/vecdotq.cuh
  csrc/torch_bindings.cpp
  examples/gguf_inference.py
  format.sh
  requirements-common.txt
  tests/models/test_gguf.py
  tests/quantization/test_lm_head.py
  vllm/_custom_ops.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/base_config.py
  vllm/model_executor/layers/quantization/gguf.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/qwen2.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/tokenizer.py
Labels: ready

#6841 [Build] Add initial conditional testing spec
  .buildkite/test-pipeline.yaml
Labels: ready

#7146 [LoRA] Relax LoRA condition
  tests/lora/test_layers.py
  tests/lora/test_punica_variation.py
  vllm/config.py
  vllm/lora/layers.py
Labels: ready

#7153 [Model] Support SigLIP encoder and alternative decoders for LLaVA models
  requirements-test.txt
  tests/models/test_llava.py
  tests/models/test_llava_next.py
  tests/models/test_paligemma.py
  tests/models/test_registry.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/utils.py
Labels: ready

#7178 [BugFix] Fix DeepSeek remote code
  .buildkite/lm-eval-harness/configs/DeepSeek-V2-Lite-Chat.yaml
  .buildkite/lm-eval-harness/test_lm_eval_correctness.py
Labels: ready

#7205 [ BugFix ] Fix ZMQ when `VLLM_PORT` is set
  vllm/envs.py
Labels: ready

#7183 [SpecDecode] [Minor] Fix spec decode sampler tests
  tests/samplers/test_rejection_sampler.py
  tests/samplers/test_typical_acceptance_sampler.py
  vllm/model_executor/layers/spec_decode_base_sampler.py
Labels: ready

#5941 [Kernel] Add per-tensor and per-token AZP epilogues
  benchmarks/cutlass_benchmarks/w8a8_benchmarks.py
  csrc/ops.h
  csrc/quantization/cutlass_w8a8/Epilogues.md
  csrc/quantization/cutlass_w8a8/broadcast_load_epilogue_c2x.hpp
  csrc/quantization/cutlass_w8a8/scaled_mm_c2x.cu
  csrc/quantization/cutlass_w8a8/scaled_mm_c2x.cuh
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x.cu
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_cutlass.py
  vllm/_custom_ops.py
Labels: ready

#4942 [Core] Subclass ModelRunner to support cross-attention & encoder sequences (towards eventual encoder/decoder model support)
  .buildkite/test-pipeline.yaml
  examples/offline_inference_encoder_decoder.py
  tests/conftest.py
  tests/core/test_scheduler.py
  tests/core/test_scheduler_encoder_decoder.py
  tests/core/utils.py
  tests/distributed/test_basic_distributed_correctness_enc_dec.py
  tests/kernels/test_attention_selector.py
  tests/kernels/test_encoder_decoder_attn.py
  tests/kernels/test_flash_attn.py
  tests/kernels/utils.py
  tests/models/test_bart.py
  tests/models/utils.py
  tests/worker/test_encoder_decoder_model_runner.py
  vllm/attention/__init__.py
  vllm/attention/layer.py
  vllm/attention/selector.py
  vllm/config.py
  vllm/core/block/utils.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/bart.py
  vllm/outputs.py
  vllm/sequence.py
  vllm/utils.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/utils.py
  vllm/worker/worker.py
Labels: ready

#7225 [Bugfix] Fix GPTQ and GPTQ Marlin CPU Offloading
  tests/basic_correctness/test_cpu_offload.py
  tests/utils.py
  vllm/model_executor/layers/quantization/gptq.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
Labels: ready

#7111 [BugFix] Overhaul async request cancellation
  tests/async_engine/api_server_async_engine.py
  tests/async_engine/test_request_tracker.py
  tests/test_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/api_server.py
  vllm/entrypoints/openai/rpc/client.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/utils.py
Labels: ready

#7245 [Doc] Mock new dependencies for documentation
  docs/source/conf.py
Labels: ready

#7227 [BUGFIX]: top_k is expected to be an integer.
  vllm/sampling_params.py
Labels: ready

#7238 [Frontend] Gracefully handle missing chat template and fix CI failure
  tests/async_engine/test_chat_template.py
  tests/async_engine/test_openapi_server_ray.py
  tests/entrypoints/openai/test_oot_registration.py
  tests/utils.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/transformers_utils/tokenizer.py
Labels: ready

#5874 [Misc] Refactor linear layer weight loading; introduce `BasevLLMParameter` and `weight_loader_v2`
  tests/quantization/test_compressed_tensors.py
  vllm/model_executor/__init__.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_unquantized.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w4a16_24.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a16_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/parameter.py
Labels: ready

#7222 [ BugFix ] Move `zmq` frontend to IPC instead of TCP
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/client.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/envs.py
  vllm/utils.py
Labels: ready

#7164 [Bugfix] Fix input processor for InternVL2 model
  tests/models/test_internvl.py
  vllm/model_executor/models/internvl.py
Labels: ready

#7251 [OpenVINO] migrate to latest dependencies versions
  Dockerfile.openvino
  docs/source/getting_started/openvino-installation.rst
  requirements-openvino.txt
  setup.py
Labels: ready

#7243 [Doc] add online speculative decoding example
  docs/source/models/spec_decode.rst
Labels: ready

#7217 [BugFix] Fix frontend multiprocessing hang
  tests/entrypoints/openai/test_mp_crash.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/client.py
Labels: ready

#7219 [Bugfix][FP8] Fix dynamic FP8 Marlin quantization
  tests/quantization/test_fp8.py
  vllm/envs.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready

#7264 [Bugfix] Fix gptq failure on T4s
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
Labels: ready

#7284 [Kernel] Fix Flashinfer Correctness
  vllm/attention/backends/flashinfer.py
Labels: ready

#7288 [Frontend] remove max_num_batched_tokens limit for lora
  vllm/config.py
Labels: ready

#7273 [Model] Rename MiniCPMVQwen2 to MiniCPMV2.6
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  vllm/model_executor/models/minicpmv.py
Labels: ready

#7305 [Bugfix][Kernel] Increased atol to fix failing tests
  tests/kernels/test_flash_attn.py
Labels: ready

#6594 [Frontend] Kill the server on engine death
  tests/entrypoints/openai/test_shutdown.py
  vllm/engine/async_llm_engine.py
  vllm/entrypoints/api_server.py
  vllm/entrypoints/launcher.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/rpc/client.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/envs.py
Labels: ready

#6849 [Bugfix][fast] Fix the get_num_blocks_touched logic
  tests/core/block/test_block_manager_v2.py
  tests/core/block/test_naive_block.py
  tests/core/block/test_prefix_caching_block.py
  tests/core/utils.py
  vllm/core/block/naive_block.py
  vllm/core/block/prefix_caching_block.py
Labels: ready

#7298 [CI/Build] Dockerfile.cpu improvements
  .dockerignore
  Dockerfile.cpu
Labels: x86 CPU, ready

#7269 [Bugfix] Fix new Llama3.1 GGUF model loading
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#7308 [Misc] Temporarily resolve the error of BitAndBytes
  vllm/config.py
Labels: ready

#7005 [TPU] Add Load-time W8A16 quantization for TPU Backend
  vllm/config.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/tpu_int8.py
  vllm/model_executor/model_loader/loader.py
Labels: tpu

#7331 [TPU] Fix dockerfile.tpu
  Dockerfile.tpu
Labels: tpu

#7162 [Performance] Optimize e2e overheads: Reduce python allocations
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/utils.py
  vllm/block.py
  vllm/core/block_manager_v1.py
  vllm/core/scheduler.py
  vllm/model_executor/__init__.py
  vllm/model_executor/sampling_metadata.py
  vllm/outputs.py
  vllm/sequence.py
  vllm/utils.py
  vllm/worker/model_runner.py
Labels: ready

#7218 [Bugfix] Fix speculative decoding with MLPSpeculator with padded vocabulary
  tests/spec_decode/e2e/test_mlp_correctness.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/layers/rejection_sampler.py
  vllm/model_executor/models/mlp_speculator.py
Labels: ready

#6971 [Speculative decoding] [Multi-Step] decouple should_modify_greedy_probs_inplace
  tests/samplers/test_sampler.py
  vllm/lora/layers.py
  vllm/model_executor/layers/sampler.py
  vllm/spec_decode/medusa_worker.py
  vllm/spec_decode/multi_step_worker.py
  vllm/spec_decode/proposer_worker_base.py
  vllm/spec_decode/smaller_tp_proposer_worker.py
  vllm/spec_decode/spec_decode_worker.py
Labels: ready

#7336 [Core] Streamline stream termination in `AsyncLLMEngine`
  tests/async_engine/test_request_tracker.py
  vllm/engine/async_llm_engine.py
Labels: ready

#6739 [Model][Jamba] Mamba cache single buffer
  vllm/model_executor/models/jamba.py
  vllm/worker/model_runner.py
Labels: ready

#7354 [VLM][Doc] Add `stop_token_ids` to InternVL example
  examples/offline_inference_vision_language.py
Labels: ready

#7364 [Performance] e2e overheads reduction: Small followup diff
  vllm/core/block_manager_v1.py
  vllm/sequence.py
Labels: ready

#7360 [Bugfix] Fix reinit procedure in ModelInputForGPUBuilder
  vllm/worker/model_runner.py
Labels: ready

#7372 [Bugfix] Fix ITL recording in serving benchmark
  benchmarks/backend_request_func.py
Labels: ready

#7089 [Core] Add span metrics for model_forward, scheduler and sampler time
  tests/tracing/test_tracing.py
  tests/worker/test_model_runner.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/sequence.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/target_model_runner.py
  vllm/tracing.py
  vllm/worker/embedding_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/worker.py
  vllm/worker/worker_base.py
Labels: ready

#7376 [Bugfix] Fix `PerTensorScaleParameter` weight loading for fused models
  vllm/model_executor/layers/linear.py
Labels: ready

#7377 [Misc] Add numpy implementation of `compute_slot_mapping`
  vllm/attention/backends/utils.py
Labels: ready

#7380 [Core] Fix edge case in chunked prefill + block manager v2
  tests/core/block/e2e/test_correctness.py
  vllm/core/block/block_table.py
Labels: ready

#7392 [Bugfix] Fix phi3v batch inference when images have different aspect ratio
  tests/models/test_phi3v.py
  tests/tracing/test_tracing.py
  vllm/model_executor/models/phi3v.py
  vllm/multimodal/utils.py
Labels: ready

#7340 [TPU] Use mark_dynamic to reduce compilation time
  Dockerfile.tpu
  docs/source/getting_started/tpu-installation.rst
  vllm/worker/tpu_model_runner.py
Labels: tpu

#7189 Updating LM Format Enforcer version to v0.10.6
  requirements-common.txt
Labels: ready

#7387 [core] [2/N] refactor worker_base input preparation for multi-step
  vllm/worker/worker.py
  vllm/worker/worker_base.py
Labels: ready

#7407 [CI/Build] Minor refactoring for vLLM assets
  vllm/assets/base.py
  vllm/assets/image.py
Labels: ready

#7319 [Kernel] Flashinfer correctness fix for v0.1.3
  .buildkite/test-pipeline.yaml
  Dockerfile
  vllm/attention/backends/flashinfer.py
Labels: ready

#6613 [Core][VLM] Support image embeddings as input
  docs/source/models/vlm.rst
  tests/models/test_llava_image_embeds.py
  vllm/assets/image.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/siglip.py
  vllm/multimodal/image.py
Labels: ready

#7347 [Frontend] Disallow passing `model` as both argument and option
  vllm/engine/arg_utils.py
  vllm/scripts.py
Labels: ready

#6832 [CI/Build] bump Dockerfile.neuron image base, use public ECR
  Dockerfile.neuron
Labels: Inferentia/Trainium

#7423 [ci] Entrypoints run upon changes in vllm/
  .buildkite/test-pipeline.yaml
Labels: ready

#7433 [ci] Cancel fastcheck when PR is ready
  .github/workflows/cancel_fastcheck_when_ready.yml
Labels: invalid

#7323 [Misc] Use scalar type to dispatch to different `gptq_marlin` kernels
  csrc/core/scalar_type.hpp
  csrc/quantization/gptq_marlin/gptq_marlin.cu
Labels: ready

#7416 [Core] Consolidate `GB` constant and enable float GB arguments
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/executor/cpu_executor.py
  vllm/executor/openvino_executor.py
  vllm/utils.py
  vllm/worker/tpu_worker.py
Labels: ready

#7208 [Core/Bugfix] Add FP8 K/V Scale and dtype conversion for prefix/prefill Triton Kernel
  docs/source/quantization/fp8_e4m3_kvcache.rst
  docs/source/quantization/fp8_e5m2_kvcache.rst
  tests/basic_correctness/test_chunked_prefill.py
  tests/kernels/test_prefix_prefill.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/xformers.py
  vllm/attention/ops/ipex_attn.py
  vllm/attention/ops/paged_attn.py
  vllm/attention/ops/prefix_prefill.py
  vllm/config.py
Labels: ready

#7398 [Bugfix] Handle PackageNotFoundError when checking for xpu version
  vllm/utils.py
Labels: ready

#6999 [CI/Build] bump minimum cmake version
  CMakeLists.txt
  pyproject.toml
  requirements-build.txt
  requirements-common.txt
Labels: ready

#7224 [Core] Shut down aDAG workers with clean async llm engine exit
  tests/distributed/test_pipeline_parallel.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/openai/rpc/server.py
  vllm/executor/ray_gpu_executor.py
Labels: ready

#7417 [mypy] Misc. typing improvements
  tests/tensorizer_loader/conftest.py
  tests/test_utils.py
  tests/utils.py
  vllm/inputs/registry.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/phi3v.py
  vllm/multimodal/image.py
  vllm/platforms/cuda.py
  vllm/transformers_utils/detokenizer.py
  vllm/transformers_utils/tokenizer.py
  vllm/transformers_utils/tokenizer_group/__init__.py
  vllm/transformers_utils/tokenizer_group/base_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/ray_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/tokenizer_group.py
  vllm/utils.py
Labels: ready

#7435 [Misc] improve logits processors logging message
  tests/entrypoints/openai/test_serving_chat.py
  vllm/entrypoints/openai/logits_processors.py
Labels: ready

#7410 [Bugfix] Fix weight loading for Chameleon when TP>1
  tests/conftest.py
  tests/distributed/test_multimodal_broadcast.py
  tests/entrypoints/openai/test_oot_registration.py
  tests/models/test_chameleon.py
  tests/models/test_llava.py
  tests/models/test_minicpmv.py
  tests/models/test_oot_registration.py
  vllm/distributed/communication_op.py
  vllm/distributed/parallel_state.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/arctic.py
  vllm/model_executor/models/baichuan.py
  vllm/model_executor/models/bart.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/bloom.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/dbrx.py
  vllm/model_executor/models/deepseek.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/gpt_bigcode.py
  vllm/model_executor/models/gpt_j.py
  vllm/model_executor/models/gpt_neox.py
  vllm/model_executor/models/internlm2.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/jais.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/medusa.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/mixtral_quant.py
  vllm/model_executor/models/mpt.py
  vllm/model_executor/models/nemotron.py
  vllm/model_executor/models/olmo.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/orion.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/persimmon.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/phi3_small.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/stablelm.py
  vllm/model_executor/models/starcoder2.py
  vllm/model_executor/models/xverse.py
  vllm/outputs.py
Labels: ready

#7102 [hardware] unify usage of is_tpu to current_platform.is_tpu()
  vllm/attention/selector.py
  vllm/config.py
  vllm/executor/ray_utils.py
  vllm/model_executor/custom_op.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/model_loader/loader.py
  vllm/platforms/__init__.py
  vllm/utils.py
Labels: tpu

#7458 [TPU] Suppress import custom_ops warning
  vllm/_custom_ops.py
  vllm/utils.py
Labels: tpu

#7446 [Frontend][Core] Add plumbing to support audio language models
  docs/source/conf.py
  docs/source/models/enabling_multimodal_inputs.rst
  requirements-common.txt
  tests/entrypoints/openai/test_audio.py
  vllm/entrypoints/chat_utils.py
  vllm/envs.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/utils.py
  vllm/multimodal/audio.py
  vllm/multimodal/base.py
  vllm/multimodal/registry.py
  vllm/multimodal/utils.py
  vllm/worker/model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: ready

#7473 [Misc] Update LM Eval Tolerance
  .buildkite/lm-eval-harness/test_lm_eval_correctness.py
Labels: ready

#7281 [Misc] Update `gptq_marlin` to use new vLLMParameters
  .buildkite/test-pipeline.yaml
  tests/weight_loading/models.txt
  tests/weight_loading/run_model_weight_loading_test.sh
  tests/weight_loading/test_weight_loading.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/parameter.py
Labels: ready

#7334 [Misc] Update Fused MoE weight loading
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/qwen2_moe.py
Labels: ready

#7422 [Misc] Update `awq` and `awq_marlin` to use `vLLMParameters`
  tests/weight_loading/models.txt
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/awq.py
  vllm/model_executor/layers/quantization/awq_marlin.py
Labels: ready

#7277 [Misc] `compressed-tensors` code reuse
  requirements-common.txt
  requirements-test.txt
  tests/quantization/test_compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a16_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#7457 [TPU] Support multi-host inference
  docs/source/getting_started/tpu-installation.rst
  vllm/distributed/device_communicators/tpu_communicator.py
Labels: tpu

#7396 [CI/Build]Reduce the time consumption for LoRA tests
  tests/lora/test_layer_variation.py
  tests/lora/test_punica_sizes.py
  tests/lora/test_punica_variation.py
Labels: ready

#7489 [misc][ci] fix cpu test with plugins
  .buildkite/run-cpu-test.sh
  .buildkite/test-pipeline.yaml
  tests/models/test_oot_registration.py
  tests/utils.py
Labels: ready

#7493 [Bugfix][Docs] Update list of mock imports
  .buildkite/test-pipeline.yaml
  docs/source/conf.py
Labels: ready

#2937 Fix empty output when temp is too low
  vllm/model_executor/layers/sampler.py
  vllm/sampling_params.py
Labels: ready

#7424 [Misc] Deprecation Warning when setting --engine-use-ray
  tests/async_engine/test_api_server.py
  tests/async_engine/test_async_llm_engine.py
  tests/async_engine/test_openapi_server_ray.py
  tests/spec_decode/e2e/conftest.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/envs.py
Labels: ready

#7452 [core] [3/N] multi-step args and sequence.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/sequence.py
Labels: ready

#7533 [TPU] Set per-rank XLA cache
  vllm/worker/tpu_worker.py
Labels: tpu

#7521 [Misc] Revert `compressed-tensors` code reuse
  requirements-common.txt
  requirements-test.txt
  tests/quantization/test_compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a16_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#7544 [Bugfix][TPU] Correct env variable for XLA cache path
  vllm/envs.py
Labels: tpu

#7175 [Bugfix] update neuron for version > 0.5.0
  vllm/engine/arg_utils.py
  vllm/executor/neuron_executor.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/neuron_worker.py
Labels: Inferentia/Trainium

#7182 [Misc] Update dockerfile for CPU to cover protobuf installation
  .buildkite/run-cpu-test.sh
  Dockerfile.cpu
  requirements-common.txt
Labels: x86 CPU

#7534 [Bugfix] Fix default weight loading for scalars
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#7566 [Bugfix][Harmless] Fix hardcoded float16 dtype for model_is_embedding
  vllm/entrypoints/openai/api_server.py
Labels: ready

#7343 [Misc] Add quantization config support for speculative model.
  tests/spec_decode/e2e/test_integration.py
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#7453 [Feature]: Add OpenAI server prompt_logprobs support #6508
  tests/entrypoints/openai/test_completion.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
Labels: ready

#5049 Chat method for offline llm
  .buildkite/test-pipeline.yaml
  examples/offline_inference_chat.py
  tests/entrypoints/llm/test_generate.py
  vllm/entrypoints/llm.py
Labels: ready

#7324 [Misc/Testing] Use `torch.testing.assert_close`
  tests/distributed/test_comm_ops.py
  tests/distributed/test_custom_all_reduce.py
  tests/kernels/quant_utils.py
  tests/kernels/test_activation.py
  tests/kernels/test_attention.py
  tests/kernels/test_blocksparse_attention.py
  tests/kernels/test_cache.py
  tests/kernels/test_cutlass.py
  tests/kernels/test_flash_attn.py
  tests/kernels/test_flashinfer.py
  tests/kernels/test_fp8_quant.py
  tests/kernels/test_int8_quant.py
  tests/kernels/test_layernorm.py
  tests/kernels/test_marlin_gemm.py
  tests/kernels/test_moe.py
  tests/kernels/test_pos_encoding.py
  tests/kernels/test_sampler.py
  tests/kernels/utils.py
  tests/lora/test_layers.py
  tests/lora/test_lora_manager.py
  tests/quantization/test_fp8.py
  tests/samplers/test_sampler.py
  tests/spec_decode/utils.py
  tests/test_logits_processor.py
  tests/worker/test_model_runner.py
Labels: ready

#7500 [CI] Fix crashes of performance benchmark
  .buildkite/nightly-benchmarks/run-benchmarks-suite.sh
  .buildkite/nightly-benchmarks/tests/descriptions.md
  .buildkite/nightly-benchmarks/tests/latency-tests.json
  .buildkite/nightly-benchmarks/tests/serving-tests.json
  .buildkite/nightly-benchmarks/tests/throughput-tests.json
Labels: perf-benchmarks, ready

#7513 [Bugfix][Hardware][AMD][Frontend] add quantization param to embedding checking method
  vllm/entrypoints/openai/api_server.py
Labels: rocm, ready

#7510 support tqdm in notebooks
  vllm/entrypoints/llm.py
Labels: ready

#7210 [Feature][Hardware][Amd] Add fp8 Linear Layer for Rocm
  csrc/quantization/fp8/common.cu
  tests/kernels/quant_utils.py
  tests/kernels/test_fp8_quant.py
  vllm/_custom_ops.py
  vllm/config.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#7415 [Kernel] W8A16 Int8 inside FusedMoE
  benchmarks/kernels/benchmark_moe.py
  tests/models/test_jamba.py
  tests/quantization/test_experts_int8.py
  vllm/config.py
  vllm/model_executor/layers/fused_moe/configs/E=8,N=14336,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=2048,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=3584,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=4096,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/configs/E=8,N=8192,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8.json
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/experts_int8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/models/jamba.py
Labels: ready

#7601 [Kernel] Add tuned triton configs for ExpertsInt8
  .gitignore
  vllm/model_executor/layers/fused_moe/configs/E=1,N=14336,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=14336,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=1792,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=1792,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=3072,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=3072,device_name=NVIDIA_H100_80GB_HBM3,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=3072,device_name=NVIDIA_H100_80GB_HBM3.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=3584,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=3584,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=7168,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=1,N=7168,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=14336,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=14336,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=1792,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=1792,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=3072,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=3072,device_name=NVIDIA_H100_80GB_HBM3,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=3584,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=3584,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=7168,device_name=NVIDIA_A100-SXM4-80GB,dtype=int8_w8a16.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=7168,device_name=NVIDIA_A100-SXM4-80GB.json
  vllm/model_executor/layers/fused_moe/configs/E=16,N=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=int8_w8a16.json
Labels: ready

#7571 [spec decode] [4/N] Move update_flash_attn_metadata to attn backend
  vllm/attention/backends/abstract.py
  vllm/attention/backends/flash_attn.py
  vllm/spec_decode/draft_model_runner.py
Labels: ready

#7440 [Core] Fix tracking of model forward time to the span traces in case of PP>1
  .buildkite/test-pipeline.yaml
  tests/tracing/test_tracing.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/worker/model_runner.py
Labels: ready

#7591 [Kernel] register punica functions as torch ops
  vllm/lora/ops/bgmv_expand.py
  vllm/lora/ops/bgmv_expand_slice.py
  vllm/lora/ops/bgmv_shrink.py
  vllm/lora/ops/sgmv_expand.py
  vllm/lora/ops/sgmv_expand_slice.py
  vllm/lora/ops/sgmv_shrink.py
Labels: ready

#7594 [Kernel][Misc] dynamo support for ScalarType
  csrc/core/scalar_type.hpp
  vllm/_core_ext.py
Labels: ready

#7596 [Kernel] fix types used in aqlm and ggml kernels to support dynamo
  csrc/ops.h
  csrc/quantization/aqlm/gemm_kernels.cu
  csrc/quantization/gguf/dequantize.cuh
  csrc/quantization/gguf/gguf_kernel.cu
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/aqlm.py
  vllm/model_executor/layers/quantization/gptq.py
Labels: ready

#7617 [Bugfix] Fix custom_ar support check
  vllm/distributed/device_communicators/custom_all_reduce.py
Labels: ready

#7610 .[Build/CI] Enabling passing AMD tests.
  .buildkite/test-pipeline.yaml
Labels: ready

#7618 [Bugfix] Clear engine reference in AsyncEngineRPCServer
  vllm/entrypoints/openai/rpc/server.py
Labels: ready

#7600 [aDAG] Unflake aDAG + PP tests
  .buildkite/test-pipeline.yaml
  tests/distributed/test_pipeline_parallel.py
  tests/utils.py
Labels: ready

#7612 [Bugfix] add >= 1.0 constraint for openai dependency
  requirements-common.txt
Labels: ready

#7621 [ci][test] fix engine/logger test
  tests/test_logger.py
Labels: ready

#7620 [core][misc] update libcudart finding
  vllm/distributed/device_communicators/cuda_wrapper.py
Labels: ready

#7626 [Misc]Fix BitAndBytes exception messages
  vllm/model_executor/model_loader/loader.py
Labels: ready

#7530 [VLM] Refactor `MultiModalConfig` initialization and profiling
  tests/entrypoints/openai/test_audio.py
  tests/multimodal/test_mapper.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/executor/cpu_executor.py
  vllm/executor/executor_base.py
  vllm/executor/gpu_executor.py
  vllm/executor/openvino_executor.py
  vllm/executor/ray_xpu_executor.py
  vllm/executor/tpu_executor.py
  vllm/executor/xpu_executor.py
  vllm/inputs/registry.py
  vllm/model_executor/model_loader/__init__.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/__init__.py
  vllm/multimodal/registry.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/target_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/embedding_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/tpu_model_runner.py
  vllm/worker/tpu_worker.py
  vllm/worker/utils.py
  vllm/worker/worker.py
  vllm/worker/xpu_model_runner.py
Labels: ready
