Repository vllm-project/vllm, pull requests merged in 2024-10, with the labels that each got.

#8795 [ci] Add CODEOWNERS for test directories
  .buildkite/test-pipeline.yaml
  .github/CODEOWNERS
Labels: ready

#8975 [CI][SpecDecode] Fix spec decode tests, use flash attention backend for spec decode CI tests.
  .buildkite/test-pipeline.yaml
  tests/spec_decode/test_multi_step_worker.py
Labels: ready

#8252 [Frontend][Core] Move guided decoding params into sampling params
  tests/entrypoints/llm/test_guided_generate.py
  tests/model_executor/conftest.py
  tests/model_executor/test_guided_processors.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/guided_fields.py
  vllm/model_executor/guided_decoding/lm_format_enforcer_decoding.py
  vllm/model_executor/guided_decoding/outlines_decoding.py
  vllm/sampling_params.py
Labels: ready

#8976 [CI/Build] Fix machete generated kernel files ordering
  csrc/quantization/machete/generate.py
Labels: ready

#8982 [torch.compile] fix tensor alias
  vllm/worker/embedding_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
Labels: ready

#8969 [Misc] add process_weights_after_loading for DummyLoader
  vllm/model_executor/model_loader/loader.py
Labels: ready

#8986 [Bugfix] Fix Fuyu tensor parallel inference
  tests/distributed/test_pipeline_parallel.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/persimmon.py
Labels: ready

#8991 [Bugfix] Fix Token IDs Reference for MiniCPM-V When Images are Provided With No Placeholders
  vllm/model_executor/models/minicpmv.py
Labels: ready

#8965 [Core] [Frontend] Priority scheduling for embeddings and in the OpenAI-API
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
Labels: ready

#8987 [Doc] Update list of supported models
  docs/source/models/supported_models.rst
  vllm/model_executor/models/__init__.py
Labels: ready

#8839 [Spec Decode] (1/2) Remove batch expansion
  .buildkite/test-pipeline.yaml
  tests/samplers/test_sampler.py
  tests/spec_decode/e2e/test_integration.py
  tests/spec_decode/e2e/test_medusa_correctness.py
  tests/spec_decode/e2e/test_mlp_correctness.py
  tests/spec_decode/e2e/test_ngram_correctness.py
  tests/spec_decode/test_multi_step_worker.py
  tests/spec_decode/test_scorer.py
  tests/spec_decode/test_spec_decode_worker.py
  tests/spec_decode/utils.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/engine/output_processor/interfaces.py
  vllm/engine/output_processor/multi_step.py
  vllm/model_executor/layers/sampler.py
  vllm/model_executor/sampling_metadata.py
  vllm/spec_decode/batch_expansion.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/interfaces.py
  vllm/spec_decode/mqa_scorer.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/worker/model_runner.py
Labels: ready

#8804 [Core] Combined support for multi-step scheduling, chunked prefill & prefix caching
  tests/multi_step/test_correctness_llm.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
Labels: ready

#8977 [Misc] Update Default Image Mapper Error Log
  vllm/multimodal/image.py
Labels: ready

#8645 [Core] CUDA Graphs for Multi-Step + Chunked-Prefill
  csrc/prepare_inputs/advance_step.cu
  vllm/attention/backends/flash_attn.py
  vllm/worker/model_runner.py
Labels: ready

#8192 [OpenVINO] Enable GPU support for OpenVINO vLLM backend
  docs/source/getting_started/openvino-installation.rst
  requirements-openvino.txt
  vllm/attention/backends/openvino.py
  vllm/envs.py
  vllm/executor/openvino_executor.py
  vllm/model_executor/model_loader/openvino.py
  vllm/worker/openvino_model_runner.py
  vllm/worker/openvino_worker.py
Labels: Intel GPU, ready

#8206 [Model] Adding Granite MoE.
  tests/models/decoder_only/language/test_granitemoe.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/granite.py
  vllm/model_executor/models/granitemoe.py
Labels: ready

#9025 [Doc] Update Granite model docs
  docs/source/models/supported_models.rst
Labels: ready

#9007 [Bugfix] example template should not add parallel_tool_prompt if tools is none
  examples/tool_chat_template_mistral_parallel.jinja
Labels: ready

#8971 [Misc] log when using default MoE config
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#9020 [BugFix] Enforce Mistral ToolCall id constraint when using the Mistral tool call parser
  tests/tool_use/test_parallel_tool_calls.py
  tests/tool_use/test_tool_calls.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: ready

#8678 [Core] Make BlockSpaceManagerV2 the default BlockManager to use.
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#8959 [Frontend] [Neuron] Parse literals out of override-neuron-config
  tests/engine/test_arg_utils.py
  vllm/engine/arg_utils.py
Labels: ready

#9054 Fix failing spec decode test
  tests/spec_decode/e2e/test_compatibility.py
Labels: ready

#9042 [Bugfix] Weight loading fix for OPT model
  vllm/model_executor/models/opt.py
Labels: ready

#8405 [Frontend][Feature] support tool calling for internlm/internlm2_5-7b-chat model
  docs/requirements-docs.txt
  docs/source/serving/openai_compatible_server.md
  examples/tool_chat_template_internlm2_tool.jinja
  tests/tool_use/utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/abstract_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/internlm2_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/llama_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: ready

#8845 [CI/Build] Per file CUDA Archs (improve wheel size and dev build times)
  CMakeLists.txt
  cmake/utils.cmake
  csrc/core/registration.h
  csrc/moe/marlin_moe_ops.cu
  csrc/moe/marlin_moe_ops.h
  csrc/moe/torch_bindings.cpp
  csrc/ops.h
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
  csrc/quantization/fp8/fp8_marlin.cu
  csrc/quantization/gptq_marlin/awq_marlin_repack.cu
  csrc/quantization/gptq_marlin/gptq_marlin.cu
  csrc/quantization/gptq_marlin/gptq_marlin_repack.cu
  csrc/quantization/machete/generate.py
  csrc/quantization/machete/machete_prepack_kernel.cuh
  csrc/quantization/machete/machete_prepack_launcher.cuh
  csrc/quantization/machete/machete_pytorch.cu
  csrc/quantization/marlin/dense/marlin_cuda_kernel.cu
  csrc/quantization/marlin/qqq/marlin_qqq_gemm_kernel.cu
  csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu
  csrc/torch_bindings.cpp
  tools/report_build_time_ninja.py
  vllm/_custom_ops.py
Labels: ready

#9047 [Misc] Enable multi-step output streaming by default
  vllm/engine/arg_utils.py
Labels: ready

#9064 [Misc] Move registry to its own file
  docs/source/models/adding_model.rst
  tests/models/test_registry.py
  vllm/lora/models.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/registry.py
  vllm/worker/model_runner.py
Labels: ready

#9071 [Bugfix] Reshape the dimensions of the input image embeddings in Qwen2VL
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#9062 [Bugfix] Flash attention arches not getting set properly
  CMakeLists.txt
Labels: ready

#9008 [Model] add a bunch of supported lora modules for mixtral
  tests/lora/conftest.py
  tests/lora/test_mixtral.py
  vllm/model_executor/models/mixtral.py
Labels: ready

#9039 [Hardware][PowerPC] Make oneDNN dependency optional for Power
  cmake/cpu_extension.cmake
Labels: ready

#8717 [Core][VLM] Test registration for OOT multimodal models
  docs/source/models/adding_model.rst
  find_cuda_init.py
  tests/conftest.py
  tests/entrypoints/openai/test_audio.py
  tests/entrypoints/openai/test_vision.py
  tests/models/test_oot_registration.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/__init__.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_opt.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/model_executor/models/registry.py
Labels: ready

#8999 Adds truncate_prompt_tokens param for embeddings creation
  tests/entrypoints/openai/test_embedding.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_embedding.py
Labels: ready

#7412 [CI] Update performance benchmark: upgrade trt-llm to r24.07, and add SGLang
  .buildkite/nightly-benchmarks/nightly-annotation.md
  .buildkite/nightly-benchmarks/nightly-descriptions.md
  .buildkite/nightly-benchmarks/nightly-pipeline.yaml
  .buildkite/nightly-benchmarks/run-nightly-suite.sh
  .buildkite/nightly-benchmarks/scripts/generate-nightly-markdown.py
  .buildkite/nightly-benchmarks/scripts/launch-server.sh
  .buildkite/nightly-benchmarks/scripts/launch-trt-server.sh
  .buildkite/nightly-benchmarks/scripts/nightly-annotate.sh
  .buildkite/nightly-benchmarks/scripts/plot-nightly-results.py
  .buildkite/nightly-benchmarks/scripts/run-lmdeploy-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-nightly-benchmarks.sh
  .buildkite/nightly-benchmarks/scripts/run-tgi-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-trt-nightly.sh
  .buildkite/nightly-benchmarks/scripts/run-vllm-nightly.sh
  .buildkite/nightly-benchmarks/scripts/summary-nightly-results.py
  .buildkite/nightly-benchmarks/tests/nightly-tests.json
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving.py
Labels: perf-benchmarks, nightly-benchmarks, ready

#9077 [Misc] Improved prefix cache example
  examples/offline_inference_with_prefix.py
Labels: ready

#9081 [Misc] Add random seed for prefix cache benchmark
  benchmarks/benchmark_prefix_caching.py
Labels: ready

#9085 [Misc] Fix CI lint
  benchmarks/benchmark_prefix_caching.py
Labels: ready

#9061 [torch.compile] improve allreduce registration
  vllm/distributed/device_communicators/custom_all_reduce.py
  vllm/distributed/parallel_state.py
Labels: ready

#9088 [Doc] Update README.md with Ray summit slides
  README.md
Labels: ready

#9084 [Bugfix] use blockmanagerv1 for encoder-decoder
  vllm/engine/arg_utils.py
Labels: ready

#8979 [Bugfix] Fixes for Phi3v and Ultravox Multimodal EmbeddingInputs Support
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/ultravox.py
Labels: ready

#9004 [Model] Support Gemma2 embedding model
  tests/conftest.py
  tests/models/embedding/language/test_embedding.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/gemma2_embedding.py
  vllm/model_executor/models/registry.py
Labels: ready

#9083 [Bugfix] Deprecate registration of custom configs to huggingface
  tests/models/decoder_only/vision_language/test_internvl.py
  tests/models/encoder_decoder/vision_language/test_mllama.py
  vllm/transformers_utils/config.py
Labels: ready

#8960 [Bugfix] Fix order of arguments matters in config.yaml
  docs/source/serving/openai_compatible_server.md
  tests/data/test_config.yaml
  tests/test_utils.py
  vllm/utils.py
Labels: ready

#9097 [core] use forward context for flash infer
  vllm/attention/backends/flashinfer.py
Labels: ready

#9101 [Bugfix] Fix try-catch conditions to import correct Flash Attention Backend in Draft Model
  vllm/spec_decode/draft_model_runner.py
Labels: ready

#9087 [Frontend] API support for beam search
  benchmarks/benchmark_throughput.py
  tests/conftest.py
  tests/entrypoints/openai/test_completion.py
  vllm/engine/async_llm_engine.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/logger.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/sampling_params.py
  vllm/utils.py
Labels: ready

#9104 [Misc] Remove user-facing error for removed VLM args
  docs/source/models/vlm.rst
  vllm/entrypoints/llm.py
Labels: ready

#9090 [Model] PP support for embedding models and update docs
  docs/source/models/supported_models.rst
  docs/source/models/vlm.rst
  tests/distributed/test_pipeline_parallel.py
  tests/utils.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/gemma2_embedding.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llama_embedding.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_rm.py
  vllm/model_executor/models/utils.py
  vllm/worker/embedding_model_runner.py
Labels: ready

#8709 [Bugfix] fix tool_parser error handling when serve a model not support it
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: ready

#9038 [Bugfix] Fix incorrect updates to num_computed_tokens in multi-step scheduling
  tests/core/test_num_computed_tokens_update.py
  tests/core/utils.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/engine/llm_engine.py
  vllm/engine/output_processor/interfaces.py
  vllm/engine/output_processor/multi_step.py
Labels: ready

#9044 [Bugfix][Hardware][CPU] Fix CPU model input for decode
  vllm/worker/cpu_model_runner.py
Labels: x86 CPU, ready

#9103 [BugFix][Core] Fix BlockManagerV2 when Encoder Input is None
  vllm/core/block/block_table.py
  vllm/core/block_manager_v2.py
  vllm/engine/arg_utils.py
Labels: ready

#9105 [core] remove beam search from the core
  benchmarks/backend_request_func.py
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_prioritization.py
  benchmarks/benchmark_serving.py
  benchmarks/benchmark_throughput.py
  examples/llm_engine_example.py
  examples/multilora_inference.py
  tests/basic_correctness/test_preemption.py
  tests/conftest.py
  tests/core/block/e2e/test_correctness.py
  tests/core/utils.py
  tests/samplers/test_beam_search.py
  tests/samplers/test_sampler.py
  vllm/core/scheduler.py
  vllm/engine/async_llm_engine.py
  vllm/engine/output_processor/single_step.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/envs.py
  vllm/model_executor/layers/sampler.py
  vllm/outputs.py
  vllm/sampling_params.py
  vllm/sequence.py
  vllm/utils.py
  vllm/worker/tpu_model_runner.py
Labels: ready

#9108 [Model] Explicit interface for vLLM models and support OOT embedding models
  tests/conftest.py
  tests/models/test_oot_registration.py
  tests/models/test_registry.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/__init__.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_gemma_embedding.py
  vllm/model_executor/models/__init__.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/interfaces_base.py
  vllm/model_executor/models/registry.py
  vllm/utils.py
Labels: ready

#9089 [Hardware][CPU] Cross-attention and Encoder-Decoder models support on CPU backend
  .buildkite/run-cpu-test.sh
  tests/models/encoder_decoder/language/test_bart.py
  vllm/attention/backends/torch_sdpa.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_worker.py
Labels: ready

#8859 [Core] Refactor GGUF parameters packing and forwarding
  tests/models/decoder_only/language/test_gguf.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/gguf.py
  vllm/model_executor/models/llama.py
Labels: ready

#9045 [Model] Support NVLM-D and fix QK Norm in InternViT
  docs/source/models/supported_models.rst
  examples/offline_inference_vision_language.py
  examples/offline_inference_vision_language_multi_image.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/models/intern_vit.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/nvlm_d.py
Labels: ready

#8451 [Doc]: Add deploying_with_k8s guide
  docs/source/index.rst
  docs/source/serving/deploying_with_k8s.rst
Labels: ready

#7876 [CI/Build] Add linting for github actions workflows
  .github/workflows/actionlint.yml
  .github/workflows/add_label_automerge.yml
  .github/workflows/clang-format.yml
  .github/workflows/matchers/actionlint.json
  .github/workflows/mypy.yaml
  .github/workflows/publish.yml
  .github/workflows/ruff.yml
  .github/workflows/yapf.yml
  .gitignore
  format.sh
  tools/actionlint.sh
Labels: ready

#9140 [misc] update utils to support comparing multiple settings
  tests/utils.py
Labels: ready

#9145 [Intel GPU] Fix xpu decode input
  vllm/worker/xpu_model_runner.py
Labels: ready

#9117 [Frontend] API support for beam search for MQLLMEngine
  tests/entrypoints/openai/test_completion.py
  vllm/beam_search.py
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/utils.py
Labels: ready

#9131 [Core][Frontend] Add Support for Inference Time mm_processor_kwargs
  examples/offline_inference_vision_language.py
  tests/multimodal/test_processor_kwargs.py
  tests/test_inputs.py
  tests/test_utils.py
  vllm/core/scheduler.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/llm.py
  vllm/inputs/data.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
  vllm/multimodal/audio.py
  vllm/multimodal/base.py
  vllm/multimodal/image.py
  vllm/multimodal/registry.py
  vllm/multimodal/video.py
  vllm/sequence.py
  vllm/utils.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/openvino_model_runner.py
Labels: ready

#9151 [Frontend] Add Early Validation For Chat Template / Tool Call Parser
  tests/entrypoints/openai/test_cli_args.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/scripts.py
Labels: ready

#8758 [CI/Build] Add examples folder into Docker image so that we can leverage the templates*.jinja when serving models
  Dockerfile
Labels: ready

#8537 [Bugfix] fix OpenAI API server startup with --disable-frontend-multiprocessing
  tests/entrypoints/openai/test_basic.py
  vllm/entrypoints/openai/api_server.py
Labels: ready

#9155 [Doc] Update vlm.rst to include an example on videos
  docs/source/models/vlm.rst
Labels: ready

#9132 [Doc] Improve contributing and installation documentation
  CONTRIBUTING.md
  SECURITY.md
  docs/source/getting_started/installation.rst
Labels: ready

#9086 [Bugfix] Try to handle older versions of pytorch
  tests/kernels/test_awq.py
  tests/kernels/test_awq_marlin.py
  vllm/_custom_ops.py
Labels: ready

#9162 mypy: check additional directories
  .github/workflows/mypy.yaml
  format.sh
  tools/mypy.sh
  vllm/usage/usage_lib.py
Labels: ready

#9161 Add `lm-eval` directly to requirements-test.txt
  .buildkite/lm-eval-harness/run-lm-eval-gsm-hf-baseline.sh
  .buildkite/lm-eval-harness/run-lm-eval-gsm-vllm-baseline.sh
  .buildkite/test-pipeline.yaml
  docs/source/quantization/fp8.rst
  requirements-test.txt
Labels: ready

#9148 support bitsandbytes quantization with more models
  tests/quantization/test_bitsandbytes.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/phi.py
Labels: ready

#9171 Add classifiers in setup.py
  setup.py
Labels: ready

#9173 Update link to KServe deployment guide
  docs/source/serving/deploying_with_kserve.rst
Labels: ready

#9167 [Misc] Improve validation errors around best_of and n
  vllm/sampling_params.py
Labels: ready

#9159 [Bugfix][Doc] Report neuron error in output
  setup.py
Labels: ready

#9174 [Model] Remap FP8 kv_scale in CommandR and DBRX
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/dbrx.py
Labels: ready

#9160 [Bugfix] Optimize composite weight loading and fix EAGLE weight loading
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_rm.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/utils.py
Labels: ready

#9165 [ci][test] use load dummy for testing
  .buildkite/test-pipeline.yaml
  tests/utils.py
  vllm/envs.py
Labels: ready

#9170 [Doc] Fix VLM prompt placeholder sample bug
  docs/source/models/vlm.rst
Labels: ready

#9188 [Bugfix] Access `get_vocab` instead of `vocab` in tool parsers
  vllm/entrypoints/openai/tool_parsers/abstract_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
Labels: ready

#1217 Add Dependabot configuration for GitHub Actions updates
  .github/dependabot.yml
Labels: ready

#7515 [Hardware][CPU] Support AWQ for CPU backend
  .buildkite/run-cpu-test.sh
  Dockerfile.cpu
  docs/source/quantization/supported_hardware.rst
  tests/quantization/test_ipex_quant.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/ipex_quant.py
  vllm/worker/cpu_worker.py
Labels: x86 CPU, ready

#9194 [CI/Build] mypy: check vllm/entrypoints
  tools/mypy.sh
  vllm/entrypoints/llm.py
Labels: ready

#9130 [CI/Build] Update Dockerfile install+deploy image to ubuntu 22.04
  Dockerfile
Labels: ready

#9201 [Core] Fix invalid args to _process_request
  vllm/engine/multiprocessing/client.py
Labels: ready

#9208 [misc] improve model support check in another process
  docs/requirements-docs.txt
  vllm/model_executor/models/registry.py
Labels: ready

#9213 [Bugfix] Fix Weight Loading Multiple GPU Test - Large Models
  tests/weight_loading/models-large.txt
  tests/weight_loading/models.txt
Labels: ready

#9212 [Bugfix] Machete garbage results for some models (large K dim)
  csrc/quantization/machete/machete_mainloop.cuh
  tests/kernels/test_machete_gemm.py
Labels: ready

#9149 [Core] Add an environment variable which needs to be set explicitly to allow BlockSpaceManagerV1
  .buildkite/test-pipeline.yaml
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_prefix_caching.py
  benchmarks/benchmark_throughput.py
  tests/basic_correctness/test_chunked_prefill.py
  tests/core/block/e2e/test_correctness.py
  tests/core/block/e2e/test_correctness_sliding_window.py
  tests/core/test_chunked_prefill_scheduler.py
  tests/core/test_scheduler.py
  tests/prefix_caching/test_prefix_caching.py
  tests/spec_decode/e2e/test_compatibility.py
  tests/utils.py
  vllm/config.py
  vllm/envs.py
Labels: ready

#9237 [Model] support input image embedding for minicpmv
  docs/source/models/supported_models.rst
  docs/source/models/vlm.rst
  vllm/model_executor/models/minicpmv.py
Labels: ready

#9121 [OpenVINO] Use torch 2.4.0 and newer optimim version
  requirements-openvino.txt
Labels: ready

#9218 [Bugfix] Fix Machete unittests failing with `NotImplementedError`
  csrc/quantization/machete/machete_pytorch.cu
Labels: ready

#9252 [CI/Build] Make the `Dockerfile.cpu` file's `PIP_EXTRA_INDEX_URL` Configurable as a Build Argument
  Dockerfile.cpu
Labels: ready

#9058 [torch.compile] integration with compilation control
  .buildkite/test-pipeline.yaml
  tests/compile/test_basic_correctness.py
  tests/compile/test_full_graph.py
  tests/compile/test_full_graph_multi_gpu.py
  tests/compile/test_full_graph_smoke.py
  tests/compile/utils.py
  tests/tpu/test_compilation.py
  tests/tpu/test_custom_dispatcher.py
  vllm/compilation/backends.py
  vllm/compilation/compile_context.py
  vllm/compilation/decorators.py
  vllm/compilation/levels.py
  vllm/compilation/wrapper.py
  vllm/envs.py
  vllm/model_executor/custom_op.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/platforms/tpu.py
  vllm/plugins/__init__.py
  vllm/sequence.py
  vllm/worker/model_runner.py
Labels: ready

#9258 [torch.compile] generic decorators
  vllm/compilation/decorators.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/llama.py
Labels: ready

#9257 [Doc][Neuron] add note to neuron documentation about resolving triton issue
  docs/source/getting_started/neuron-installation.rst
Labels: ready

#9235 [Misc] Fix sampling from sonnet for long context case
  benchmarks/benchmark_serving.py
Labels: ready

#9261 [misc] hide best_of from engine
  tests/entrypoints/openai/test_metrics.py
  tests/metrics/test_metrics.py
  tests/tracing/test_tracing.py
  vllm/core/scheduler.py
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
  vllm/engine/metrics_types.py
  vllm/engine/output_processor/single_step.py
  vllm/model_executor/layers/sampler.py
  vllm/outputs.py
  vllm/sampling_params.py
  vllm/sequence.py
  vllm/tracing.py
  vllm/worker/tpu_model_runner.py
Labels: ready

#9233 [Misc] Collect model support info in a single process per model
  docs/source/models/adding_model.rst
  vllm/engine/arg_utils.py
  vllm/engine/multiprocessing/engine.py
  vllm/model_executor/models/registry.py
Labels: ready

#9275 [Misc][LoRA] Support loading LoRA weights for target_modules in reg format
  tests/lora/conftest.py
  tests/lora/test_lora_checkpoints.py
  vllm/lora/models.py
  vllm/lora/utils.py
Labels: ready

#9277 [Bugfix] Fix priority in multiprocessing engine
  vllm/engine/multiprocessing/engine.py
Labels: ready

#9287 [Doc] Remove outdated comment to avoid misunderstanding
  vllm/core/block_manager_v2.py
Labels: ready

#8512 [Doc] Compatibility matrix for mutual exclusive features
  docs/source/index.rst
  docs/source/models/performance.rst
  docs/source/serving/compatibility_matrix.rst
  vllm/attention/backends/rocm_flash_attn.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/output_processor/multi_step.py
  vllm/executor/cpu_executor.py
  vllm/inputs/preprocess.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/utils.py
  vllm/worker/multi_step_model_runner.py
  vllm/worker/utils.py
Labels: ready

#9254 [Bugfix][CI/Build] Fix docker build where CUDA archs < 7.0 are being detected
  CMakeLists.txt
Labels: ready

#9202 [Bugfix] Sets `is_first_step_output` for TPUModelRunner
  vllm/worker/tpu_model_runner.py
Labels: tpu

#9295 [bugfix] fix f-string for error
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#9209 [BugFix] Fix tool call finish reason in streaming case
  vllm/entrypoints/openai/serving_chat.py
Labels: ready

#9298 [SpecDec] Remove Batch Expansion (2/3)
  tests/spec_decode/test_scorer.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/utils.py
  vllm/attention/backends/xformers.py
  vllm/spec_decode/mqa_scorer.py
  vllm/spec_decode/spec_decode_worker.py
Labels: ready

#9026 [Bugfix] Fix bug of xformer prefill for encoder-decoder
  vllm/attention/backends/xformers.py
Labels: ready

#9286 [Bugfix]Fix MiniCPM's LoRA bug
  vllm/lora/models.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/minicpm3.py
Labels: ready

#9317 [CI] Fix merge conflict
  vllm/attention/backends/placeholder_attn.py
Labels: ready

#9327 [Bugfix] Bandaid fix for speculative decoding tests
  vllm/worker/model_runner.py
Labels: ready

#9350 [TPU] Fix TPU SMEM OOM by Pallas paged attention kernel
  vllm/attention/backends/pallas.py
  vllm/worker/tpu_model_runner.py
Labels: tpu

#9296 [Frontend] merge beam search implementations
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
Labels: ready

#9095 [Model] Make llama3.2 support multiple and interleaved images
  examples/offline_inference_vision_language_multi_image.py
  tests/models/encoder_decoder/vision_language/test_mllama.py
  vllm/model_executor/models/mllama.py
Labels: ready

#9343 [Bugfix] Clean up some cruft in mamba.py
  docs/source/models/supported_models.rst
  vllm/model_executor/models/mamba.py
Labels: ready

#9345 [Frontend] Clarify model_type error messages
  vllm/entrypoints/chat_utils.py
Labels: ready

#9348 [Doc] Fix code formatting in spec_decode.rst
  docs/source/models/spec_decode.rst
Labels: ready

#9351 [Bugfix] Update InternVL input mapper to support image embeds
  vllm/model_executor/models/internvl.py
Labels: ready

#9357 [BugFix] Fix chat API continuous usage stats
  tests/entrypoints/openai/test_chat.py
  vllm/entrypoints/openai/serving_chat.py
Labels: ready

#9349 pass ignore_eos parameter to all benchmark_serving calls
  benchmarks/benchmark_serving.py
Labels: ready

#8909 [Misc] Directly use compressed-tensors for checkpoint definitions
  requirements-common.txt
  requirements-test.txt
  tests/quantization/test_compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a16_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#9034 [Bugfix] Fix vLLM UsageInfo and logprobs None AssertionError with empty token_ids
  tests/entrypoints/openai/test_chunked_prompt.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/sequence.py
Labels: ready

#9386 [Bugfix][CI/Build] Fix CUDA 11.8 Build
  CMakeLists.txt
Labels: ready

#9397 [Bugfix] Molmo text-only input bug fix
  vllm/model_executor/models/molmo.py
Labels: ready

#9250 [Misc] Standardize RoPE handling for Qwen2-VL
  benchmarks/kernels/benchmark_rope.py
  requirements-common.txt
  tests/kernels/test_pos_encoding.py
  tests/lora/test_layers.py
  tests/test_config.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/phi3_small.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/qwen2vl.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/model_runner.py
Labels: ready

#9406 [CI/Build] Test VLM embeddings
  .buildkite/test-pipeline.yaml
Labels: ready

#8688 [Core] Rename input data types
  docs/source/dev/input_processing/model_inputs_index.rst
  tests/models/decoder_only/vision_language/test_phi3v.py
  tests/models/decoder_only/vision_language/test_qwen.py
  tests/multimodal/test_processor_kwargs.py
  vllm/engine/llm_engine.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/inputs/parse.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
  vllm/model_executor/models/blip.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/ultravox.py
  vllm/sequence.py
Labels: ready

#9412 [Misc] Consolidate example usage of OpenAI client for multimodal models
  docs/source/models/vlm.rst
  examples/openai_api_client_for_multimodal.py
  examples/openai_audio_api_client.py
  examples/openai_vision_api_client.py
Labels: ready

#9410 [Model] Support SDPA attention for Molmo vision backbone
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/utils.py
Labels: ready

#9414 Support mistral interleaved attn
  vllm/config.py
Labels: ready

#9189 [Kernel][Model] Improve continuous batching for Jamba and Mamba
  csrc/mamba/causal_conv1d/causal_conv1d.cu
  csrc/mamba/causal_conv1d/causal_conv1d.h
  csrc/mamba/mamba_ssm/selective_scan.h
  csrc/mamba/mamba_ssm/selective_scan_fwd.cu
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/kernels/test_causal_conv1d.py
  tests/kernels/test_mamba_ssm.py
  tests/models/decoder_only/language/test_jamba.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/mamba/ops/causal_conv1d.py
  vllm/model_executor/layers/mamba/ops/mamba_ssm.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mamba.py
  vllm/model_executor/models/mamba_cache.py
Labels: ready

#9396 [Model][Bugfix] Add FATReLU activation and support for openbmb/MiniCPM-S-1B-sft
  docs/source/models/supported_models.rst
  vllm/model_executor/layers/activation.py
  vllm/model_executor/models/minicpm.py
Labels: ready

#9333 [Performance][Spec Decode] Optimize ngram lookup performance
  vllm/spec_decode/ngram_worker.py
Labels: ready

#9267 [CI/Build] mypy: Resolve some errors from checking vllm/engine
  tools/mypy.sh
  vllm/attention/layer.py
  vllm/compilation/backends.py
  vllm/compilation/decorators.py
  vllm/compilation/wrapper.py
  vllm/config.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/engine/metrics.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
  vllm/engine/output_processor/multi_step.py
  vllm/engine/output_processor/single_step.py
  vllm/engine/output_processor/stop_checker.py
  vllm/engine/output_processor/util.py
  vllm/inputs/parse.py
  vllm/model_executor/layers/sampler.py
  vllm/outputs.py
  vllm/sequence.py
Labels: ready

#9425 [Bugfix][Kernel] Prevent integer overflow in fp8 dynamic per-token quantize kernel
  csrc/quantization/fp8/common.cu
Labels: ready

#9391 [BugFix] [Kernel] Fix GPU SEGV occurring in int8 kernels
  csrc/quantization/compressed_tensors/int8_quant_kernels.cu
Labels: ready

#9442 Add notes on the use of Slack
  README.md
Labels: ready

#9395 [Kernel] Add Exllama as a backend for compressed-tensors
  vllm/envs.py
  vllm/model_executor/layers/quantization/kernels/MPLinearKernel.py
  vllm/model_executor/layers/quantization/kernels/__init__.py
  vllm/model_executor/layers/quantization/kernels/exllama.py
  vllm/model_executor/layers/quantization/kernels/machete.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/scalar_type.py
Labels: ready

#9461 [Misc] Print stack trace using `logger.exception`
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/internlm2_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/llama_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
  vllm/executor/multiproc_worker_utils.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/platforms/cuda.py
Labels: ready

#9446 [Bugfix] Allow prefill of assistant response when using `mistral_common`
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#9437 [TPU] Call torch._sync(param) during weight loading
  vllm/model_executor/utils.py
Labels: tpu

#8704 [Core] Deprecating block manager v1 and make block manager v2 default
  .buildkite/test-pipeline.yaml
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_prefix_caching.py
  benchmarks/benchmark_throughput.py
  benchmarks/overheads/benchmark_hashing.py
  docs/source/models/spec_decode.rst
  examples/offline_inference_mlpspeculator.py
  tests/basic_correctness/test_chunked_prefill.py
  tests/core/block/e2e/test_correctness.py
  tests/core/block/e2e/test_correctness_sliding_window.py
  tests/core/block/test_block_manager.py
  tests/core/test_block_manager.py
  tests/core/test_chunked_prefill_scheduler.py
  tests/core/test_num_computed_tokens_update.py
  tests/core/test_scheduler.py
  tests/metrics/test_metrics.py
  tests/multi_step/test_correctness_async_llm.py
  tests/multi_step/test_correctness_llm.py
  tests/prefix_caching/test_prefix_caching.py
  tests/spec_decode/e2e/test_compatibility.py
  tests/spec_decode/e2e/test_eagle_correctness.py
  tests/spec_decode/e2e/test_integration.py
  tests/spec_decode/e2e/test_integration_dist_tp2.py
  tests/spec_decode/e2e/test_integration_dist_tp4.py
  tests/spec_decode/e2e/test_logprobs.py
  tests/spec_decode/e2e/test_medusa_correctness.py
  tests/spec_decode/e2e/test_mlp_correctness.py
  tests/spec_decode/e2e/test_multistep_correctness.py
  tests/spec_decode/e2e/test_ngram_correctness.py
  tests/spec_decode/e2e/test_seed.py
  tests/utils.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/utils.py
  vllm/commit_id.py
  vllm/config.py
  vllm/core/block/utils.py
  vllm/core/block_manager.py
  vllm/core/block_manager_v1.py
  vllm/core/interfaces.py
  vllm/core/scheduler.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/envs.py
  vllm/worker/model_runner.py
Labels: ready

#9300 [torch.compile] Fine-grained CustomOp enabling mechanism
  tests/model_executor/test_enabled_custom_ops.py
  vllm/envs.py
  vllm/model_executor/custom_op.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/utils.py
Labels: ready

#9299 [Bugfix] Fix support for dimension like integers and ScalarType
  .buildkite/test-pipeline.yaml
  CMakeLists.txt
  csrc/core/scalar_type.hpp
  csrc/core/torch_bindings.cpp
  csrc/moe/marlin_moe_ops.cu
  csrc/moe/torch_bindings.cpp
  csrc/quantization/gptq_marlin/gptq_marlin.cu
  csrc/quantization/machete/machete_pytorch.cu
  csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu
  csrc/torch_bindings.cpp
  python_only_dev.py
  setup.py
  tests/compile/utils.py
  tests/kernels/test_machete_gemm.py
  tests/kernels/test_marlin_gemm.py
  tests/kernels/test_moe.py
  tests/test_scalartype.py
  tools/report_build_time_ninja.py
  vllm/_core_ext.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/scalar_type.py
Labels: ready

#9013 [Bugfix] Add random_seed to sample_hf_requests in benchmark_serving script
  benchmarks/benchmark_serving.py
Labels: ready

#9468 [Bugfix] Print warnings related to `mistral_common` tokenizer only once
  vllm/entrypoints/chat_utils.py
Labels: ready
