Repository vllm-project/vllm, pull requests merged in 2025-09, with the labels that each got.

#19737 v1: Support KV events from connectors
  examples/online_serving/kv_events_subscriber.py
  vllm/distributed/kv_events.py
  vllm/distributed/kv_transfer/kv_connector/v1/base.py
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/sched/scheduler.py
Labels: documentation, ready, v1

#24013 [Misc] Move fast prefill logic to separate method
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#23357 [CI/Build] Improve Tensor Schema tests speed by avoid engine core initialization
  .buildkite/test-pipeline.yaml
  tests/models/multimodal/processing/test_tensor_schema.py
  vllm/model_executor/models/granite_speech.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/ovis.py
  vllm/model_executor/models/ovis2_5.py
  vllm/model_executor/models/phi4mm.py
Labels: ready, ci/build, multi-modality, llama

#23677 [Misc] refactor code by import as for torch._inductor.config
  vllm/v1/worker/cpu_model_runner.py
Labels: ready, v1

#23471 Migrate Phi4 inputs to TensorSchema
  vllm/model_executor/models/phi4_multimodal.py
  vllm/model_executor/models/phi4mm.py
Labels: ready

#22769 [Bugfix] Add support for `<tool_call>` format in streaming mode for XLAM Tool Parser
  tests/tool_use/test_xlam_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/xlam_tool_parser.py
Labels: frontend, ready, tool-calling

#24014 [Misc] add hash_function doc string
  vllm/v1/core/kv_cache_utils.py
Labels: v1

#20904 [Frontend] Update the warning log when using VLLM_ALLOW_LONG_MAX_MODEL_LEN
  vllm/config/__init__.py
Labels: documentation, performance, ready, ci/build, qwen

#24026 [Doc]: fix typos in Python comments
  examples/offline_inference/multilora_inference.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/parallel_state.py
  vllm/entrypoints/openai/tool_parsers/pythonic_tool_parser.py
  vllm/model_executor/layers/fused_moe/moe_pallas.py
  vllm/model_executor/models/ovis.py
  vllm/model_executor/models/phi4mm_audio.py
  vllm/model_executor/models/phi4mm_utils.py
  vllm/third_party/pynvml.py
  vllm/transformers_utils/configs/nemotron.py
  vllm/transformers_utils/configs/nemotron_h.py
  vllm/transformers_utils/processors/ovis.py
  vllm/transformers_utils/processors/ovis2_5.py
  vllm/v1/spec_decode/ngram_proposer.py
Labels: documentation, frontend, tpu, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, llama

#24033 [Doc]: Fix CPU install docs: force torch-backend=cpu to avoid GPU torchvision errors
  docs/getting_started/installation/cpu/build.inc.md
Labels: documentation, ready

#23838 [Model]: support KeyeVL-1_5-8B
  docs/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  vllm/model_executor/layers/rotary_embedding/mrope.py
  vllm/model_executor/models/keye.py
  vllm/model_executor/models/keye_vl1_5.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, ready, multi-modality

#23802 Document multi-proc method selection for profiling
  docs/contributing/profiling.md
Labels: documentation

#24046 [docs][misc] IOProcessor plugins fixes
  docs/design/io_processor_plugins.md
  examples/online_serving/prithvi_geospatial_mae.py
  tests/plugins/prithvi_io_processor_plugin/prithvi_io_processor/prithvi_processor.py
  tests/plugins_tests/test_io_processor_plugins.py
  vllm/entrypoints/openai/protocol.py
  vllm/plugins/io_processors/interface.py
Labels: documentation, frontend, ready

#23817 [Model] Support DP for ViT on Kimi-VL-A3B-Thinking-2506
  docs/configuration/optimization.md
  tests/multimodal/test_utils.py
  vllm/model_executor/models/kimi_vl.py
  vllm/model_executor/models/moonvit.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/multimodal/utils.py
Labels: documentation, ready, multi-modality, qwen

#24042 [Doc]: fix typos in Python comments
  vllm/distributed/device_communicators/quick_all_reduce.py
  vllm/distributed/device_communicators/ray_communicator.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_responses.py
  vllm/executor/ray_utils.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/sampling_metadata.py
  vllm/scalar_type.py
  vllm/sequence.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/metrics/stats.py
Labels: new-model, frontend, ready, v1

#23506 [V1][Mamba1] - FP32 SSM Kernel Support
  csrc/mamba/mamba_ssm/selective_scan_fwd.cu
  tests/models/language/generation/test_hybrid.py
  vllm/model_executor/layers/mamba/mamba_utils.py
Labels: ready

#24028 [Bugfix] Fix the issue that Blip2ForConditionalGeneration' object has…
  vllm/model_executor/models/blip2.py
Labels: ready

#24051 Remove runtime checks based on pooling params
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#23148 [XPU][Feature] fp8 online quantization support for XPU
  vllm/_ipex_ops.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/ipex_quant.py
  vllm/platforms/xpu.py
Labels: ready

#24077 [Doc]: fix typos in Python comments
  tests/async_engine/test_api_server.py
  tests/core/block/e2e/test_correctness.py
  tests/engine/test_arg_utils.py
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  tests/lora/test_add_lora.py
  tests/lora/test_lora_allowed_token_ids.py
  tests/models/language/generation/test_common.py
  tests/models/language/generation/test_mistral.py
  tests/models/multimodal/generation/test_qwen2_vl.py
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/executor/test_executor.py
  tests/v1/spec_decode/test_eagle.py
  tests/v1/test_kv_sharing.py
  tests/v1/worker/test_gpu_model_runner.py
Labels: speculative-decoding, v1, multi-modality, qwen

#23104 correct LWS deployment yaml
  docs/deployment/frameworks/lws.md
  examples/online_serving/multi-node-serving.sh
Labels: documentation, ready

#24052 [Gemma3n] Fix audio batching
  examples/online_serving/openai_chat_completion_client_for_multimodal.py
  vllm/model_executor/models/gemma3n_mm.py
Labels: documentation, ready

#24031 [Model] Classification models support logit_bias / sigmoid_normalize
  vllm/config/__init__.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/jina_vl.py
Labels: ready

#24017 [docs] add SYS_NICE cap & `security-opt` for docker/k8s
  docs/getting_started/installation/cpu.md
  docs/getting_started/installation/cpu/arm.inc.md
  docs/getting_started/installation/cpu/s390x.inc.md
  docs/getting_started/installation/cpu/x86.inc.md
Labels: documentation, ready

#23945 [Bugfix] Fix transform_config parsing in Compressed Tensors
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
Labels: ready

#24100 Fix weights loading for Apertus
  vllm/model_executor/models/apertus.py
Labels: ready

#24121 [CI/Build] Disable SiluMul NVFP4 quant fusion tests
  .buildkite/test-pipeline.yaml
Labels: ci/build

#24081 [XPU] Fix the bug of LoRA logits on the XPU platform
  vllm/lora/layers.py
  vllm/lora/punica_wrapper/punica_xpu.py
  vllm/platforms/xpu.py
Labels: ready

#23656 [V1] Wrapper which plumbs request-level logits processors into vLLM batch-level logits processing
  examples/offline_inference/logits_processor/custom.py
  examples/offline_inference/logits_processor/custom_req.py
  examples/offline_inference/logits_processor/custom_req_init.py
  tests/v1/logits_processors/test_custom_offline.py
  tests/v1/logits_processors/utils.py
  vllm/v1/sample/logits_processor/__init__.py
Labels: documentation, ready, v1

#24071 fix some typos
  benchmarks/benchmark_block_pool.py
  benchmarks/benchmark_ngram_proposer.py
  csrc/quantization/cutlass_w4a8/w4a8_mm_entry.cu
  docs/configuration/optimization.md
  docs/design/io_processor_plugins.md
  examples/offline_inference/prithvi_geospatial_mae_io_processor.py
  examples/online_serving/prithvi_geospatial_mae.py
  tests/compile/piecewise/test_multiple_graphs.py
  tests/kernels/moe/test_mxfp4_moe.py
  tests/models/multimodal/processing/test_mllama4.py
  tests/quantization/test_modelopt.py
  tests/samplers/test_beam_search.py
  tests/v1/attention/test_chunked_local_attention.py
  tests/v1/kv_connector/unit/test_shared_storage_connector.py
  tests/v1/logits_processors/test_custom_offline.py
  vllm/benchmarks/serve.py
  vllm/config/compilation.py
  vllm/config/parallel.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/entrypoints/openai/serving_responses.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/quantization/compressed_tensors/transform/module.py
  vllm/model_executor/layers/quantization/mxfp4.py
  vllm/model_executor/models/gemma3n_mm.py
  vllm/model_executor/models/interns1.py
  vllm/third_party/pynvml.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/kv_connector_model_runner_mixin.py
Labels: documentation, performance, frontend, ready, v1, multi-modality, llama

#23660 [Compile] Fix Compile Warning for `w4a8_mm_entry.cu`
  csrc/quantization/cutlass_w4a8/w4a8_mm_entry.cu
Labels: ready

#24115 [Doc]: fix typos in Python comments
  .buildkite/nightly-benchmarks/scripts/compare-json-results.py
  benchmarks/benchmark_serving.py
  benchmarks/benchmark_serving_structured_output.py
  benchmarks/benchmark_throughput.py
  tools/profiler/visualize_layerwise_profile.py
  vllm/compilation/collective_fusion.py
  vllm/engine/multiprocessing/engine.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/model_executor/model_loader/default_loader.py
  vllm/v1/worker/xpu_worker.py
  vllm/worker/worker.py
Labels: performance, structured-output, ready, ci/build, v1

#24070 [Misc] Add check for dual_chunk_attention
  vllm/config/__init__.py
Labels: ready

#24141 [distributed][rl] remove nccl cumem env var override
  docs/usage/troubleshooting.md
  vllm/env_override.py
Labels: documentation, performance, ready, rl

#20189 [Nixl] Heterogeneous TP support FlashInfer
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
Labels: ready

#23907 [CI/Build] Serve images used by multimodal tests through local HTTP Server
  tests/conftest.py
  tests/entrypoints/llm/test_chat.py
  tests/entrypoints/openai/test_vision.py
  tests/entrypoints/openai/test_vision_embedding.py
  tests/models/multimodal/generation/test_pixtral.py
  tests/multimodal/test_utils.py
  tests/v1/entrypoints/openai/responses/test_image.py
  tests/v1/tpu/test_multimodal.py
  vllm/assets/image.py
Labels: tpu, ready, ci/build, v1, multi-modality

#24153 [Misc] Clean up deadcode for legacy processing pipeline
  tests/models/multimodal/processing/test_tensor_schema.py
  vllm/multimodal/utils.py
Labels: ready, multi-modality

#23931 Support add_generation_prompt in embeddings endpoint with chat request
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_embedding.py
Labels: frontend, ready

#23982 Fix MiniMax attention module prefix and remove useless code
  vllm/model_executor/layers/mamba/linear_attn.py
Labels: ready

#20388 FIX: Add libnuma-dev to Dockerfile for dev stage
  docker/Dockerfile
Labels: ready, ci/build

#23998 [V1] v1 engine + full CUDA graph support for PLaMo2
  docs/models/supported_models.md
  docs/usage/v1_guide.md
  tests/models/language/generation/test_hybrid.py
  tests/models/registry.py
  vllm/config/compilation.py
  vllm/model_executor/models/plamo2.py
Labels: documentation, performance, new-model, rocm, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, llama, qwen, deepseek, gpt-oss

#23289 [Attention] Blackwell FP8 MLA support with CUTLASS_MLA backend
  csrc/attention/mla/sm100_cutlass_mla_kernel.cu
  tests/kernels/test_cutlass_mla_decode.py
  vllm/platforms/cuda.py
  vllm/v1/attention/backends/mla/cutlass_mla.py
Labels: ready, v1, deepseek

#23887 [Feature][P/D]: Optimize NIXL Connector xfer Launch
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
Labels: ready

#23460 [Feature][gpt-oss] Add support for num_cached_tokens and num_reasoning_tokens tracking
  vllm/entrypoints/context.py
Labels: frontend, ready, gpt-oss

#24151 Remove deprecated `PyNcclConnector`
  benchmarks/disagg_benchmarks/disagg_overhead_benchmark.sh
  benchmarks/disagg_benchmarks/disagg_performance_benchmark.sh
  examples/offline_inference/disaggregated_prefill.py
  examples/online_serving/disaggregated_prefill.sh
  tests/kv_transfer/test_lookup_buffer.py
  tests/kv_transfer/test_send_recv.py
  vllm/config/__init__.py
Labels: documentation, performance, ready

#23927 [Feature][Responses API]Support MCP tools with streaming mode + background mode
  tests/entrypoints/openai/test_response_api_with_harmony.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/serving_responses.py
Labels: frontend, ready

#24146 [Kernel][Bugfix] Fix grouped topk cu
  csrc/moe/grouped_topk_kernels.cu
Labels: ready

#24010 [Refactor] Introduce basic Renderer for completion-style request
  tests/entrypoints/test_renderer.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_pooling.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/entrypoints/renderer.py
Labels: frontend, ready

#23503 Migrate ultravox inputs to TensorSchema
  vllm/model_executor/models/ultravox.py
Labels: ready

#23766 Improve flexibility of auto_tune.sh execution.
  benchmarks/auto_tune/README.md
  benchmarks/auto_tune/auto_tune.sh
Labels: performance, ready

#24234 [Doc] Update vLLM Singapore Meetup info
  README.md
  docs/community/meetups.md
Labels: documentation

#23725 [Misc] Removed force_fp8_e4m3fnuz from FP8LinearOp
  tests/compile/test_fusion.py
  tests/compile/test_silu_mul_quant_fusion.py
  tests/utils.py
  vllm/model_executor/layers/quantization/ptpc_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#24008 [Perf] Freeze core engine proc heap after init
  vllm/v1/engine/core.py
Labels: ready, v1

#24266 QWEN3 Coder Fused MoE kernels Optimization configs
  vllm/model_executor/layers/fused_moe/configs/E=160,N=640,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=160,N=640,device_name=NVIDIA_GB200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=160,N=640,device_name=NVIDIA_H100,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=20,N=2560,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=20,N=2560,device_name=NVIDIA_GB200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=20,N=2560,device_name=NVIDIA_H100,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=40,N=2560,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=40,N=2560,device_name=NVIDIA_GB200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=40,N=2560,device_name=NVIDIA_H100,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: performance, moe, ready, qwen

#23727 [Bugfix][Misc] Fix silu_and_mul_nvfp4_quant issue and extract common utils for nvfp4 kernel source files
  .buildkite/test-pipeline.yaml
  csrc/dispatch_utils.h
  csrc/ops.h
  csrc/quantization/fp4/activation_nvfp4_quant_fusion_kernels.cu
  csrc/quantization/fp4/nvfp4_blockwise_moe_kernel.cu
  csrc/quantization/fp4/nvfp4_experts_quant.cu
  csrc/quantization/fp4/nvfp4_quant_entry.cu
  csrc/quantization/fp4/nvfp4_quant_kernels.cu
  csrc/quantization/fp4/nvfp4_utils.cuh
  csrc/torch_bindings.cpp
  tests/kernels/quantization/test_silu_nvfp4_quant_fusion.py
Labels: ready, ci/build

#24236 [Frontend] Skip unnecessary detokenization when token_id is requested
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend, ready

#23709 Adding int4 and int8 models for CPU benchmarking
  .buildkite/nightly-benchmarks/tests/serving-tests-cpu-snc2.json
  .buildkite/nightly-benchmarks/tests/serving-tests-cpu-snc3.json
  docs/contributing/benchmarks.md
Labels: documentation, performance, ready, ci/build

#24326 [docs] add shenzhen meetup
  README.md
  docs/community/meetups.md
Labels: documentation

#24341 [Bugfix] Fix silu_mul+quant fusion test
  tests/compile/test_silu_mul_quant_fusion.py
Labels: ready

#24260 [CI] Add timeouts to tests
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build, force-merge

#23569 [Perf][V1] Fully overlap model execution
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/outputs.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: performance, ready, v1

#24346 Add @22quinn as code reviewer for RL related components
  .github/CODEOWNERS
Labels: ready, ci/build

#24294 [Doc]: fix typos in Python comments
  csrc/quantization/machete/generate.py
  docs/getting_started/installation/cpu.md
  tests/models/multimodal/generation/vlm_utils/core.py
  vllm/distributed/device_communicators/custom_all_reduce.py
  vllm/entrypoints/openai/tool_parsers/internlm2_tool_parser.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/engine/core.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, frontend, ready, v1, multi-modality, tool-calling

#24350 [KV Sharing] Raise error if using eagle with fast prefill
  vllm/config/__init__.py
  vllm/config/cache.py
Labels: ready

#23734 [Feature] Support Decode Context Parallel (DCP) for MLA
  .buildkite/test-pipeline.yaml
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/torch_bindings.cpp
  tests/distributed/test_context_parallel.py
  vllm/_custom_ops.py
  vllm/attention/ops/common.py
  vllm/attention/ops/flashmla.py
  vllm/config/parallel.py
  vllm/distributed/parallel_state.py
  vllm/engine/arg_utils.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/cutlass_mla.py
  vllm/v1/attention/backends/mla/flashattn_mla.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
  vllm/v1/attention/backends/mla/triton_mla.py
  vllm/v1/core/kv_cache_coordinator.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/single_type_kv_cache_manager.py
  vllm/v1/kv_cache_interface.py
  vllm/v1/worker/block_table.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
  vllm/worker/worker.py
Labels: rocm, ready, ci/build, v1

#24351 [Bugfix] Catch and log invalid token ids in detokenizer
  vllm/v1/engine/detokenizer.py
Labels: ready, v1

#24318 [New Model]: google/embeddinggemma-300m
  docs/models/supported_models.md
  tests/models/language/pooling/mteb_utils.py
  tests/models/language/pooling/test_st_projector.py
  tests/models/registry.py
  vllm/config/__init__.py
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/gemma3.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, ready

#24345 refactor: Turn GPUModelRunner.inputs_embeds to a CpuGpuBuffer
  vllm/v1/utils.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#24366 [CI] Disable flaky structured output test from CI
  tests/v1/entrypoints/llm/test_struct_output_generate.py
Labels: ready, v1

#24362 Add @benchislett to codeowner for spec decode and structured outputs
  .github/CODEOWNERS
Labels: ci/build

#24335 [Bugfix] Avoid uninitialized usage of azp_val when AZP is false.
  csrc/cpu/dnnl_kernels.cpp
Labels: ready

#24367 [Bugfix] Fix broken deepseek fp8 TP weights loading
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready, deepseek

#24371 [Bugfix] Fix test_mixtral_moe
  tests/kernels/moe/test_moe.py
Labels: ready, ci/build

#24324 [Fix] [gpt-oss] fix non-tool calling path for chat completion
  tests/entrypoints/openai/test_serving_chat.py
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend, ready, gpt-oss

#24370 [Bugfix] Fix unstable silu_mul+nvfp4 quant fusion test
  tests/compile/test_silu_mul_quant_fusion.py
  tests/kernels/quantization/nvfp4_utils.py
Labels: ready

#24265 break execute_model in gpu_model_runner into sub-functions for custom scopes
  vllm/envs.py
  vllm/v1/utils.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#24372 [attention][DCP] use AttentionImpl.need_to_return_lse_for_decode
  vllm/attention/backends/abstract.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#23475 Migrate Qwen2 inputs to TensorSchema
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
Labels: documentation, performance, new-model, rocm, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality, llama, qwen, deepseek

#24380 [CI][Fix] deterministic seed for flaky CI runs on structured outputs
  tests/v1/entrypoints/llm/test_struct_output_generate.py
Labels: ready, v1

#23908 [Benchmark] add benchmark for custom activation op
  benchmarks/kernels/benchmark_activation.py
Labels: performance, ready

#24378 [Misc] collect flashinfer version in collect_env.py
  vllm/collect_env.py
Labels: ready

#24391 [TPU] Remove TopKTopPSampler dependency for TPU sampler
  tests/v1/tpu/test_topk_topp_sampler.py
  vllm/v1/sample/ops/topk_topp_sampler.py
  vllm/v1/sample/tpu/sampler.py
Labels: tpu, ready, v1

#24397 Add @luccafong to codeowner for spec decode
  .github/CODEOWNERS
Labels: ready, ci/build

#24385 [Kernel] Support decode context parallelism on Blackwell with CUTLASS MLA
  csrc/attention/mla/sm100_cutlass_mla_kernel.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_cutlass_mla_decode.py
  vllm/_custom_ops.py
  vllm/v1/attention/backends/mla/cutlass_mla.py
Labels: ready, v1

#23830 [xpu] upgrade ipex/python3.12 for xpu
  docker/Dockerfile.xpu
  docs/getting_started/installation/gpu/xpu.inc.md
  requirements/xpu.txt
Labels: documentation, ready-for-merge, ready, ci/build

#22699 [P/D] Add a shutdown method to the Connector API
  vllm/distributed/kv_transfer/__init__.py
  vllm/distributed/kv_transfer/kv_connector/v1/base.py
  vllm/distributed/kv_transfer/kv_transfer_state.py
  vllm/executor/executor_base.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/worker/gpu_worker.py
  vllm/v1/worker/kv_connector_model_runner_mixin.py
  vllm/v1/worker/tpu_worker.py
  vllm/worker/worker_base.py
Labels: tpu, ready, v1

#24332 [Model] Remove unnecessary CUDA sync of GLM-4.1V image and video preprocess
  vllm/model_executor/models/glm4_1v.py
Labels: ready

#24334 [Model] Remove unnecessary CUDA sync of Qwen2VL image and video preprocess
  vllm/model_executor/models/qwen2_vl.py
Labels: ready, qwen

#24409 [gpt-oss][Responses API] Fix the function call id format
  vllm/entrypoints/harmony_utils.py
Labels: frontend, ready, gpt-oss

#24419 [Docs] Fix a tip indentation and typo
  docs/contributing/profiling.md
Labels: documentation

#24421 [Bugfix] Fix get_quant_config when using modelscope
  vllm/model_executor/model_loader/default_loader.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#23279 [Bugfix] Fix mamba2 prefill chunking
  tests/kernels/mamba/test_mamba_ssm_ssd.py
  vllm/model_executor/layers/mamba/ops/ssd_chunk_scan.py
  vllm/model_executor/layers/mamba/ops/ssd_combined.py
  vllm/model_executor/layers/mamba/ops/ssd_state_passing.py
  vllm/v1/attention/backends/mamba2_attn.py
Labels: ready, v1

#24337 [Misc] Terratorch related fixes
  examples/offline_inference/prithvi_geospatial_mae_io_processor.py
  examples/online_serving/prithvi_geospatial_mae.py
  requirements/test.in
  requirements/test.txt
  tests/entrypoints/openai/test_skip_tokenizer.py
  tests/models/registry.py
  tests/models/test_terratorch.py
  tests/plugins/prithvi_io_processor_plugin/prithvi_io_processor/__init__.py
  tests/plugins/prithvi_io_processor_plugin/prithvi_io_processor/prithvi_processor.py
  tests/plugins/prithvi_io_processor_plugin/setup.py
  tests/plugins_tests/test_io_processor_plugins.py
Labels: documentation, ready, ci/build

#23449 [Frontend] User-provided uuids for medias in chat. (RFC #22044)
  docs/features/multimodal_inputs.md
  tests/entrypoints/openai/test_vision.py
  tests/entrypoints/test_chat_utils.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/inputs/preprocess.py
  vllm/model_executor/models/terratorch.py
Labels: documentation, frontend, ready, v1, multi-modality

#24431 [Docs] Move feature compatibility tables to README
  docs/.nav.yml
  docs/features/README.md
Labels: documentation

#24102 [CI] Add nightly multiarch manifests to dockerhub
  .buildkite/release-pipeline.yaml
  .buildkite/scripts/cleanup-nightly-builds.sh
Labels: ready, ci/build

#24134 [Bugfix][Wide EP] Fix redundant work when using DeepEP, TP Attn, and EP MoE
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/models/deepseek_eagle.py
  vllm/model_executor/models/deepseek_mtp.py
  vllm/model_executor/models/deepseek_v2.py
Labels: speculative-decoding, ready, deepseek

#24329 [doc] update `vllm serve` cli args documentation
  vllm/entrypoints/openai/cli_args.py
Labels: frontend, ready

#23673 [Core] Use sha256 bytes instead of BlockHash to reduce GC overhead
  examples/online_serving/kv_events_subscriber.py
  tests/utils_/test_utils.py
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_single_type_kv_cache_manager.py
  tests/v1/core/utils.py
  tests/v1/engine/test_engine_args.py
  tests/v1/kv_connector/unit/utils.py
  vllm/config/cache.py
  vllm/distributed/kv_events.py
  vllm/engine/arg_utils.py
  vllm/envs.py
  vllm/utils/__init__.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_utils.py
Labels: documentation, performance, ready, v1

#24298 Add data_parallel_size to VllmConfig string representation
  vllm/config/__init__.py
Labels: ready

#24447 [Bugfix] Fix Apertus HF repo name
  docs/models/supported_models.md
  tests/models/language/generation/test_common.py
  tests/models/registry.py
Labels: documentation, ready, ci-failure

#24452 [Doc] mention fpdb for multiprocess breakpoints
  docs/usage/troubleshooting.md
Labels: documentation

#24443 [Performance][MM] Building the inverse permutation in O(n) time in Qwen2_5_VisionTransformer
  vllm/model_executor/models/qwen2_5_vl.py
Labels: ready, multi-modality, qwen

#23856 [gpt-oss] Validate gpt-oss python tool during initialization
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/tool.py
  vllm/entrypoints/tool_server.py
Labels: frontend, ready, gpt-oss

#24295 [RL] fast weight update with zmq + ipc handles
  examples/offline_inference/rlhf_colocate.py
  examples/offline_inference/rlhf_utils.py
Labels: documentation, ready, v1, rl

#23810 [Model] Systematic support for fp32 head, pooling models part
  tests/models/language/pooling/mteb_utils.py
  tests/models/language/pooling/test_bge_reranker_v2_gemma.py
  vllm/config/__init__.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/bert_with_rope.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/internlm2.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/jina_vl.py
  vllm/model_executor/models/modernbert.py
  vllm/model_executor/models/qwen2_rm.py
  vllm/model_executor/models/roberta.py
Labels: ready, qwen

#24128 [Core] Run garbage collector after CUDA graph capture to fix throughput regression
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#24279 [ROCm][CI/Build] Sync ROCm dockerfiles with the ROCm fork
  docker/Dockerfile.rocm
  docker/Dockerfile.rocm_base
Labels: rocm, ready, ci/build

#24501 [Bugfix] Fix hidden_size for multimodal classification model
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/utils.py
Labels: ready

#24368 [Misc] bump outlines_core to fix the version conflicts with outlines >= 1.2.0
  requirements/common.txt
Labels: ready, needs-rebase, ci/build

#24458 [TPU] Fix tpu structured decoding in mixed batches
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#23846 [Log] Use a relative path in debug-level logs to distinguish files with identical names
  vllm/logger.py
  vllm/logging_utils/formatter.py
Labels: ready

#24457 [Benchmark] Add option to skip oversampling in benchmark
  vllm/benchmarks/datasets.py
Labels: performance, ready

#24524 [Bugfix] Improve EPLB config validation error message
  vllm/config/parallel.py
Labels: ready

#24474 [Perf] Convert np array to torch tensor to index into block table for attn chunking
  vllm/v1/attention/backends/utils.py
Labels: ready, v1

#24546 Add @heheda12345 to CODEOWNERS of KVCacheManager related code
  .github/CODEOWNERS
Labels: ready, ci/build

#24129 [Hardware][Apple-CPU] Enable native bfloat16 on Apple Silicon (M2 and later)
  vllm/platforms/cpu.py
Labels: ready

#24540 [BugFix] Fix async core engine client finalizer
  vllm/v1/engine/core_client.py
Labels: bug, ready, v1

#24425 [P/D] MultiConnector supports shutdown
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
Labels: ready

#24392 [BugFix][Spec Decode] Fix out-of-range index triggered by eagle3; re-enable test for LlamaForCausalLMEagle3
  tests/models/registry.py
  tests/v1/e2e/test_spec_decode.py
  vllm/config/__init__.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llama_eagle3.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/configs/eagle.py
Labels: new-model, speculative-decoding, ready, v1, llama

#23845 [Bugfix] Update Run:AI Model Streamer Loading Integration
  setup.py
  tests/runai_model_streamer_test/test_runai_utils.py
  vllm/config/__init__.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/runai_streamer_loader.py
  vllm/transformers_utils/runai_utils.py
  vllm/transformers_utils/s3_utils.py
Labels: ready, ci/build

#24041 [Docs] Enable relative links in examples to function when rendered in the docs
  docs/mkdocs/hooks/generate_examples.py
Labels: documentation, ready

#24348 [Bugfix] Guard `_may_reorder_batch` for encoder-only models on CPU (#24319)
  tests/models/language/pooling/test_embedding.py
  vllm/config/__init__.py
  vllm/v1/worker/cpu_model_runner.py
Labels: ready, v1

#24543 Consolidate rendering parameters into RenderConfig dataclass
  tests/entrypoints/test_renderer.py
  vllm/entrypoints/openai/serving_classification.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_pooling.py
  vllm/entrypoints/openai/serving_tokenization.py
  vllm/entrypoints/renderer.py
Labels: frontend, ready

#23412 [ROCm][Bugfix] Fix Aiter RMSNorm
  tests/model_executor/test_enabled_custom_ops.py
  vllm/model_executor/layers/layernorm.py
  vllm/platforms/rocm.py
Labels: rocm, ready

#24537 [Docs] Document the extra memory footprint overhead when using EPLB
  docs/serving/expert_parallel_deployment.md
Labels: documentation

#23644 Support for NemotronH Nano VLM
  tests/models/registry.py
  vllm/config/__init__.py
  vllm/model_executor/models/nano_nemotron_vl.py
  vllm/model_executor/models/registry.py
Labels: new-model, ready

#23978 Feature/vit attention unification# 23880
  tests/kernels/attention/test_mha_attn.py
  vllm/attention/layer.py
  vllm/model_executor/models/idefics2_vision_model.py
  vllm/model_executor/models/intern_vit.py
  vllm/model_executor/models/interns1_vit.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/step3_vl.py
  vllm/model_executor/models/vision.py
  vllm/platforms/interface.py
Labels: performance, ready, llama

#24559 [BugFix][Multi Modal] Fix TensorSchema shape mismatch in Molmo
  vllm/model_executor/models/molmo.py
Labels: ready

#24418 [CI/Build] split true unit tests to Entrypoints Unit Tests
  .buildkite/test-pipeline.yaml
  tests/entrypoints/test_api_server_process_manager.py
Labels: ready, ci/build

#24189 [CI/Build] bump timm dependency
  docker/Dockerfile
Labels: ready, ci/build

#24178 [Bugfix] fix modelopt exclude_modules name mapping
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/models/nemotron_h.py
Labels: ready

#23619 [Bugfix] Fix DeepEP config for DP4TP4
  vllm/model_executor/layers/fused_moe/deepep_ht_prepare_finalize.py
Labels: ready

#23795 [CI] Fail subprocess tests with root-cause error
  requirements/test.in
  requirements/test.txt
  tests/async_engine/test_api_server.py
  tests/conftest.py
  tests/utils.py
  vllm/executor/ray_distributed_executor.py
Labels: ready, ci/build

#21088 [v1] Add Whisper model support (encoder-decoder)
  .buildkite/test-pipeline.yaml
  examples/offline_inference/encoder_decoder.py
  examples/offline_inference/encoder_decoder_multimodal.py
  tests/encoder_decoder/test_e2e_correctness.py
  tests/entrypoints/openai/test_encoder_decoder.py
  tests/models/language/generation/test_bart.py
  tests/models/multimodal/generation/test_whisper.py
  tests/models/multimodal/processing/test_tensor_schema.py
  tests/models/test_initialization.py
  tests/v1/test_oracle.py
  vllm/attention/layers/cross_attention.py
  vllm/config/__init__.py
  vllm/model_executor/models/voxtral.py
  vllm/model_executor/models/whisper.py
  vllm/transformers_utils/configs/mistral.py
  vllm/v1/attention/backends/cpu_attn.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/attention/backends/linear_attn.py
  vllm/v1/attention/backends/mamba_attn.py
  vllm/v1/attention/backends/rocm_aiter_fa.py
  vllm/v1/attention/backends/short_conv_attn.py
  vllm/v1/attention/backends/tree_attn.py
  vllm/v1/attention/backends/triton_attn.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/attention/backends/xformers.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/engine/processor.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/utils.py
Labels: documentation, speculative-decoding, ready, ci/build, v1, multi-modality

#19767 [torch.compile][ROCm][V1] Enable attention output FP8 fusion for V1 attention backends
  tests/compile/test_fusion_attn.py
  vllm/attention/ops/chunked_prefill_paged_decode.py
  vllm/attention/ops/prefix_prefill.py
  vllm/attention/ops/triton_unified_attention.py
  vllm/compilation/backends.py
  vllm/compilation/fusion_attn.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/v1/attention/backends/triton_attn.py
Labels: rocm, ready, torch.compile, v1

#24482 [gpt-oss] raise error for flashinfer backend without trtllm
  vllm/v1/attention/backends/flashinfer.py
Labels: ready, v1, gpt-oss

#23439 [Perf] Warmup FlashInfer attention during startup
  vllm/model_executor/warmup/kernel_warmup.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#24522 [Misc] Make timeout passable in init_distributed_environment
  vllm/distributed/parallel_state.py
Labels: ready

#23950 [Frontend][Multimodal] Allow skipping media data when UUIDs are provided.
  docs/features/multimodal_inputs.md
  examples/offline_inference/vision_language.py
  tests/entrypoints/openai/test_vision.py
  tests/entrypoints/test_chat_utils.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/multimodal/inputs.py
  vllm/multimodal/parse.py
  vllm/multimodal/processing.py
Labels: documentation, frontend, ready, multi-modality

#24534 [Model] Add Olmo3 model implementation
  docs/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/olmo2.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/olmo3.py
Labels: documentation, new-model, ready

#24762 [Bugfix] Fix GPUModelRunner has no attribute lora_manager
  vllm/v1/worker/lora_model_runner_mixin.py
Labels: ready, v1

#24789 [Chore] Remove unused batched RoPE op & kernel
  csrc/ops.h
  csrc/pos_encoding_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/core/test_pos_encoding.py
  tests/kernels/core/test_rotary_embedding.py
  vllm/_custom_ops.py
  vllm/_ipex_ops.py
  vllm/model_executor/layers/rotary_embedding/base.py
Labels: ready

#24750 [CI Failure] Fix test_flashinfer_cutlass_mxfp4_mxfp8_fused_moe
  csrc/attention/mla/sm100_cutlass_mla_kernel.cu
  tests/kernels/moe/test_mxfp4_moe.py
Labels: ready, ci-failure

#24765 [Misc] Correct an outdated comment.
  vllm/v1/engine/processor.py
Labels: v1

#24771 [CI][Spec Decode] Adjust threshold for flaky ngram spec decoding test again
  tests/v1/e2e/test_spec_decode.py
Labels: ready, v1

#24793 [Minor] Simplify duplicative device check for cuda
  vllm/platforms/cuda.py
Labels: ready

#24783 [Perf] Fix DeepGEMM Contiguous Layout Issue, 5.5% Throughput Improvement
  vllm/model_executor/layers/quantization/fp8.py
Labels: performance, ready, deepseek

#24819 [Benchmarks] Throw usage error when using dataset-name random and dataset-path together
  vllm/benchmarks/datasets.py
Labels: performance, ready

#24823 Force use C++17 globally to avoid compilation error
  CMakeLists.txt
  cmake/utils.cmake
Labels: ready, ci/build
