Repository vllm-project/vllm, pull requests merged in 2025-06, with the labels that each got.

#18909 [Bugfix] Fix EAGLE3 broken logits
  vllm/model_executor/models/llama_eagle3.py
Labels: ready

#18751 [Core] Rework dtype resolution
  tests/basic_correctness/test_basic_correctness.py
  tests/conftest.py
  tests/models/language/pooling/mteb_utils.py
  tests/models/language/pooling/test_classification.py
  tests/models/language/pooling/test_embedding.py
  tests/models/multimodal/generation/test_whisper.py
  tests/models/multimodal/processing/test_common.py
  tests/samplers/test_no_bad_words.py
  tests/test_utils.py
  vllm/config.py
  vllm/platforms/cpu.py
  vllm/transformers_utils/config.py
  vllm/utils.py
Labels: ready, multi-modality

#18987 [LoRA] Support dynamically initialize `packed_modules_mapping` for VLM with arbitrary components
  vllm/lora/models.py
  vllm/model_executor/model_loader/bitsandbytes_loader.py
  vllm/model_executor/models/intern_vit.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/utils.py
Labels: ready

#18968 Let max_num_batched_tokens use human_readable_int for large numbers
  vllm/engine/arg_utils.py
Labels: ready

#18991 [BugFix] fix data parallel construct ipv6 url addres
  vllm/distributed/parallel_state.py
Labels: ready

#18935 [Misc] reuse num_tokens_across_dp of get_dp_padding to avoid unnecessary dp all reduce in set_forward_context
  vllm/forward_context.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#18368 [Model] enable data parallel for Llama4 vision encoder
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/models/mllama4.py
  vllm/multimodal/utils.py
Labels: ready, multi-modality

#18403 [Frontend] enable custom logging for the uvicorn server (OpenAI API server)
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
Labels: frontend, ready

#18011 [Hardware][TPU] Initial support of model parallelism with single worker using SPMD
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
  examples/offline_inference/tpu.py
  tests/v1/tpu/test_spmd_model_weight_loading.py
  tests/v1/tpu/test_tpu_qkv_linear.py
  vllm/config.py
  vllm/distributed/tpu_distributed_utils.py
  vllm/envs.py
  vllm/model_executor/model_loader/tpu.py
  vllm/model_executor/utils.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/tpu_worker.py
Labels: documentation, tpu, ready, ci/build, v1

#19021 [Doc] Remove duplicate TOCs during MkDocs migration
  docs/cli/README.md
  docs/deployment/nginx.md
Labels: documentation, ready

#18929 Adding "LoRA Test %N" to AMD production tests
  .buildkite/scripts/hardware_ci/run-amd-test.sh
  .buildkite/test-pipeline.yaml
Labels: rocm, ci/build

#19046 [CPU][CI] Re-enable the CPU CI tests
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
  docker/Dockerfile.cpu
  vllm/distributed/parallel_state.py
Labels: ci/build

#18985 Add tarsier model support
  docs/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/tarsier.py
Labels: documentation, frontend, ready, multi-modality

#18999 [bugfix] small fix logic issue
  vllm/engine/arg_utils.py
Labels: documentation, ready

#18970 Reduce logs in CLI scripts and plugin loader
  vllm/benchmarks/datasets.py
  vllm/benchmarks/latency.py
  vllm/benchmarks/throughput.py
  vllm/compilation/backends.py
  vllm/plugins/__init__.py
Labels: ready

#19015 [v1][KVCacheManager] Rename BlockHashType to BlockHash
  docs/design/v1/prefix_caching.md
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_specialized_manager.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/single_type_kv_cache_manager.py
Labels: documentation, ready, v1

#19060 [Doc] Update V1 user guide for embedding and enc-dec models
  docs/usage/v1_guide.md
Labels: documentation, ready

#19088 [doc] clarify windows support
  docs/getting_started/installation/gpu.md
Labels: documentation

#19030 Fix underscores in dict keys passed via CLI
  tests/test_utils.py
  vllm/utils.py
Labels: ready

#19081 [Misc] Add missing `_Backend` enums
  vllm/platforms/interface.py
Labels: ready

#19093 Fix interaction between `Optional` and `Annotated` in CLI typing
  tests/engine/test_arg_utils.py
  vllm/engine/arg_utils.py
Labels: ready

#19031 [Bugfix] get_num_blocks_to_allocate with null_block
  tests/v1/core/test_specialized_manager.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/single_type_kv_cache_manager.py
Labels: ready, v1

#19075 [Bugfix]: Fix the incompatibility issue with tool_choice 'required' when Thinking is enabled
  tests/entrypoints/openai/test_completion_with_function_calling.py
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend, ready

#18411 [Bugfix][P/D] Fix Prefix Cache Bug
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
Labels: ready, v1

#19029 [Bugfix] Max concurrency estimation and check_enough_kv_cache_memory for models with sliding window layers
  tests/v1/core/test_kv_cache_utils.py
  vllm/v1/core/kv_cache_utils.py
Labels: ready, v1

#18925 feat: add data parallel rank to KVEventBatch
  .buildkite/test-pipeline.yaml
  tests/distributed/conftest.py
  tests/distributed/test_events.py
  tests/v1/engine/test_engine_core_client.py
  vllm/distributed/kv_events.py
  vllm/v1/core/sched/scheduler.py
Labels: documentation, ready, ci/build, v1

#18782 [Docs] Add developer doc about CI failures
  docs/contributing/ci-failures.md
Labels: documentation, ready

#18862 [Core] Cast multimodal input in hf processor
  vllm/inputs/registry.py
  vllm/multimodal/inputs.py
  vllm/spec_decode/draft_model_runner.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_pooling_model_runner.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/multi_step_neuron_model_runner.py
  vllm/worker/multi_step_neuronx_distributed_model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/pooling_model_runner.py
  vllm/worker/xpu_model_runner.py
Labels: tpu, speculative-decoding, ready, ci/build, v1, multi-modality

#18437 [KERNEL] Sampler. CUDA kernel for applying repetition penalty
  CMakeLists.txt
  csrc/ops.h
  csrc/sampler.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_apply_repetition_penalties.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/utils.py
Labels: ready, ci/build

#19115 [TPU] Skip hanging tests
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
  tests/v1/tpu/test_spmd_model_weight_loading.py
Labels: tpu, ready, ci/build, v1

#19113 Fix ValueError: Missing value for tag key(s): model_name,engine.
  tests/v1/metrics/test_ray_metrics.py
  vllm/v1/metrics/ray_wrappers.py
Labels: ready, v1

#19089 [Misc] Add packages for benchmark as extra dependency
  docs/cli/README.md
  setup.py
  vllm/benchmarks/datasets.py
Labels: documentation, frontend, ready, ci/build

#19092 Improve the output precision of embedding models
  tests/models/language/pooling/embed_utils.py
  tests/models/language/pooling/mteb_utils.py
  tests/models/language/pooling/test_gte.py
  tests/models/language/pooling/test_intfloat.py
  tests/models/language/pooling/test_jina.py
  tests/models/language/pooling/test_nomic.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/bert_with_rope.py
Labels: ready

#18678 [CI/Build][Bugfix] Ensure compatibility with transformers 4.52
  requirements/test.in
  requirements/test.txt
  tests/models/multimodal/generation/test_common.py
  tests/models/multimodal/generation/test_florence2.py
  tests/models/multimodal/generation/test_granite_speech.py
  tests/models/multimodal/generation/test_phi4mm.py
  tests/models/multimodal/generation/vlm_utils/model_utils.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  tests/models/test_initialization.py
  vllm/config.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/idefics3.py
Labels: ready, ci/build, multi-modality

#18874 Add DeepSeek-R1-0528 function call chat template
  docs/features/tool_calling.md
  examples/tool_chat_template_deepseekr1.jinja
Labels: documentation, ready, tool-calling

#18564 Sm100 blockwise fp8 swap ab
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm100_fp8.cu
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm100_fp8_dispatch.cuh
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
Labels: performance, ready

#19102 Allow AsyncLLMEngine.generate to target a specific DP rank
  examples/online_serving/multi_instance_data_parallel.py
  tests/tokenization/test_detokenize.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  tests/v1/engine/test_output_processor.py
  vllm/engine/async_llm_engine.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/processor.py
Labels: documentation, ready, v1

#18778 [Perf] Tunings for SM100 FP8 CUTLASS kernel
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_sm100_fp8_dispatch.cuh
Labels: performance, ready

#19108 [TPU] Update dynamo dump file name in compilation test
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
  tests/tpu/test_compilation.py
  tests/v1/tpu/worker/test_tpu_model_runner.py
Labels: tpu, ready, ci/build, v1

#19121 [Bugfix] fix v1 cpu worker fails on macOS
  vllm/engine/arg_utils.py
  vllm/platforms/cpu.py
Labels: bug, ready

#19111 [Kernel] Integrate batched/masked deepgemm kernel
  tests/kernels/moe/deepep_utils.py
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_triton_or_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/deepep_ll_prepare_finalize.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready

#18817 [Misc] refactor: simplify EngineCoreClient.make_async_mp_client in AsyncLLM
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core_client.py
Labels: ready, v1

#19167 [doc] small fix
  docs/models/extensions/tensorizer.md
Labels: documentation, ready

#18632 [Bugfix][Nixl] Fix full prefix cache hit bug
  tests/v1/kv_connector/unit/test_multi_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#19117 [Bugfix] Fix port handling in make_zmq_path
  vllm/utils.py
Labels: bug, ready, codex

#18770 [Torch Nightly]add missing dependency
  docker/Dockerfile.nightly_torch
  requirements/nightly_torch_test.txt
Labels: ready, ci/build

#19202 [Bugfix] properly catch PIL-related errors for vision models when incorrect data urls are provided
  tests/multimodal/test_utils.py
  vllm/multimodal/utils.py
Labels: ready, multi-modality

#19193 [mistral_common] Add v11 tokenizer
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: documentation, frontend, ready, v1, tool-calling

#19205 Add H20-3e fused MoE kernel tuning configs for DeepSeek-R1/V3
  vllm/model_executor/layers/fused_moe/configs/E=256,N=256,device_name=NVIDIA_H20-3e,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: performance, ready

#16226 [MISC][Bugfix] Use less CPU when message queue has been empty for some time
  tests/basic_correctness/test_basic_correctness.py
  vllm/distributed/device_communicators/shm_broadcast.py
  vllm/envs.py
Labels: ready, v1

#19090 [P/D][NixlConnector] Enable FlashInfer backend
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/platforms/interface.py
Labels: ready

#19217 [Quantization] Skip Fp4 Test for `compressed-tensors`
  tests/quantization/test_compressed_tensors.py
Labels: ready, ci/build

#19118 [V1] Use FlashInfer by default on Blackwell GPUs
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
Labels: performance, ready, v1

#18863 [Model] NemotronH support
  docs/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/nemotron_h.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/nemotron_h.py
Labels: documentation, ready

#19033 [Bugfix] Fix EAGLE vocab embedding construction for Llama 70B
  benchmarks/kernels/bench_fp8_gemm.py
  tests/v1/spec_decode/test_eagle.py
  vllm/model_executor/models/llama_eagle.py
  vllm/model_executor/models/llama_eagle3.py
  vllm/platforms/cuda.py
  vllm/utils.py
  vllm/v1/spec_decode/eagle.py
Labels: ready, v1

#17996 [v1] Hybrid Memory Allocator
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_scheduler.py
  tests/v1/core/test_specialized_manager.py
  tests/v1/e2e/test_correctness_sliding_window.py
  tests/v1/kv_connector/unit/test_nixl_connector.py
  tests/v1/kv_connector/unit/test_remote_decode_lifecycle.py
  tests/v1/kv_connector/unit/test_remote_prefill_lifecycle.py
  tests/v1/kv_connector/unit/utils.py
  tests/v1/worker/test_gpu_model_runner.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_coordinator.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/single_type_kv_cache_manager.py
  vllm/v1/kv_cache_interface.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: documentation, tpu, ready, v1

#19231 [TPU] update torch_xla pin
  requirements/tpu.txt
  tests/tpu/test_moe_pallas.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, ci/build, v1

#19247 [Chore] update CODEOWNERS
  .github/CODEOWNERS
Labels: ready, ci/build

#19182 [v1][P/D] Fix a edge case in kv cache schedule
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#19244 [TPU] fix kv cache dtype in model runner
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#19103 Unit Test for run_dp_sharded_vision_model
  tests/multimodal/test_utils.py
Labels: ready, multi-modality

#19291 [BugFix] Fix MultiConnector test after HMA changes
  tests/v1/kv_connector/unit/test_multi_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
  vllm/v1/core/kv_cache_manager.py
Labels: bug, ready, v1

#19225 [Bugfix][Core] Update cancellation logic in `generate()` to handle Generator exits
  tests/v1/engine/test_async_llm.py
  vllm/v1/engine/async_llm.py
Labels: ready, v1

#19163 [Misc][Tools][Benchmark] Fix and improve auto tune script
  benchmarks/auto_tune.sh
Labels: ready

#19296 [Build][ROCm] Update Dockerfile.rocm
  docker/Dockerfile.rocm
Labels: rocm, ready, ci/build

#19269 [Easy][Test] Simplify test_function_tool_use with multiple parametrizes
  tests/entrypoints/openai/test_completion_with_function_calling.py
Labels: ready

#18762 [Kernel] Integrate CUTLASS MoE kernel with PPLX
  CMakeLists.txt
  benchmarks/kernels/benchmark_grouped_gemm_cutlass.py
  csrc/ops.h
  csrc/quantization/cutlass_w8a8/moe/grouped_mm_c3x.cu
  csrc/quantization/cutlass_w8a8/moe/grouped_mm_c3x.cuh
  csrc/quantization/cutlass_w8a8/moe/moe_data.cu
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
  csrc/torch_bindings.cpp
  tests/kernels/moe/test_cutlass_moe.py
  tests/kernels/moe/test_pplx_cutlass_moe.py
  tests/kernels/moe/test_pplx_moe.py
  tests/kernels/quantization/test_cutlass_scaled_mm.py
  tests/pplx_utils.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_triton_or_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/modular_kernel.py
  vllm/model_executor/layers/fused_moe/pplx_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/triton_deep_gemm_moe.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready, ci/build

#19039 [TPU][Test] Add script to run benchmark on TPU for buildkite
  .buildkite/scripts/tpu/cleanup_docker.sh
  .buildkite/scripts/tpu/config_v6e_1.env
  .buildkite/scripts/tpu/docker_run_bm.sh
  .buildkite/scripts/tpu/run_bm.sh
Labels: tpu, ready, ci/build

#16078 Add FlexAttention to V1
  tests/kernels/test_flex_attention.py
  vllm/engine/arg_utils.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/v1/attention/backends/flex_attention.py
Labels: documentation, ready, ci/build, v1

#19309 [AMD] Update compatible packaging version
  docker/Dockerfile.rocm
  requirements/rocm.txt
Labels: rocm, ready, ci/build

#19283 [Bugfix]: Fix TypeError: 'float' object cannot be interpreted as an integer
  vllm/v1/utils.py
Labels: ready, v1

#19299 [Bugfix] Re-enable use_cudagraph in vLLM v1
  tests/compile/piecewise/test_simple.py
  tests/compile/piecewise/test_toy_llama.py
  tests/compile/test_config.py
  vllm/compilation/counter.py
  vllm/compilation/cuda_piecewise_backend.py
  vllm/config.py
Labels: ready

#19302 [Misc] Change tests/compile to use VLLM_V1 by default
  tests/compile/conftest.py
  tests/compile/piecewise/test_simple.py
Labels: ready

#19315 Add H20-3e fused MoE kernel tuning configs for Qwen3-235B-A22B
  vllm/model_executor/layers/fused_moe/configs/E=128,N=192,device_name=NVIDIA_H20-3e.json
  vllm/model_executor/layers/fused_moe/configs/E=128,N=384,device_name=NVIDIA_H20-3e.json
Labels: moe, ready, qwen

#19082 [Hardware][POWER] Add IBM POWER11 Support to CPU Extension Detection
  cmake/cpu_extension.cmake
Labels: ready, ci/build

#19242 [Multi Modal] Add an env var for message queue max chunk bytes
  vllm/envs.py
  vllm/v1/executor/multiproc_executor.py
Labels: ready, v1

#19201 [Bugfix] model_max_length should consider max_model_len in tokenizer_config
  vllm/config.py
  vllm/transformers_utils/config.py
Labels: frontend, ready

#19288 [Frontend] Remove unreachable code from llm.py
  vllm/entrypoints/llm.py
Labels: frontend, ready

#19343 [Misc] Cleanup compilation tests
  tests/compile/test_config.py
Labels: ready

#19333 [Doc] Fix description in the Automatic Prefix Caching design doc
  docs/design/v1/prefix_caching.md
Labels: documentation, ready

#19350 [CI/Build] Fix LoRA test
  tests/lora/conftest.py
  tests/lora/test_llama_tp.py
  tests/lora/test_lora_functions.py
  tests/lora/test_phi.py
  tests/lora/test_worker.py
Labels: ready

#19328 [Fix] Allow kernel compilation for CUDA capability 8.7
  CMakeLists.txt
Labels: documentation, ready, ci/build

#19358 [Docs] Fix a bullet list in usage/security.md
  docs/usage/security.md
Labels: documentation, ready

#19321 [full_graph] Fix query_start_loc padding
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#19319 [v1] Add fp32 support to v1 engine through flex attn
  tests/kernels/attention/test_attention_selector.py
  tests/v1/worker/test_gpu_model_runner.py
  vllm/engine/arg_utils.py
  vllm/platforms/cuda.py
Labels: ready, v1

#19348 [Bugfix][Core] Prevent token lengths exceeding `max_model_len` in V0
  tests/entrypoints/llm/test_generate.py
  vllm/engine/output_processor/stop_checker.py
Labels: ready

#19295 [Quantization] Bump compressed-tensors version
  requirements/common.txt
Labels: ready, ci/build

#19371 [TPU]Fix KV cache sharing tests
  tests/v1/tpu/worker/test_tpu_model_runner.py
Labels: tpu, ready, v1

#19312 [V1] Reuse V0's memory_profiling util for gpu worker memory profiling
  vllm/utils.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#19303 Use xla flag to improve the quantized model performance
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#19382 Fix docs/mkdocs/hooks/remove_announcement.py
  docs/mkdocs/hooks/remove_announcement.py
Labels: documentation

#19365 Add security warning to bug report template
  .github/ISSUE_TEMPLATE/400-bug-report.yml
Labels: ready, ci/build

#19404 Revert "[v1] Add fp32 support to v1 engine through flex attn"
  tests/kernels/attention/test_attention_selector.py
  tests/v1/worker/test_gpu_model_runner.py
  vllm/engine/arg_utils.py
  vllm/platforms/cuda.py
Labels: ready, v1

#19411 [BugFix][CPU] Fix CPU CI by ignore collecting test_pixtral
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
Labels: ready, ci/build

#19399 [Model] use AutoWeightsLoader for commandr
  vllm/model_executor/models/commandr.py
Labels: ready

#19401 Add H20-3e fused MoE kernel tuning configs for Qwen3-235B-A22B-FP8
  vllm/model_executor/layers/fused_moe/configs/E=128,N=384,device_name=NVIDIA_H20-3e,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=128,N=768,device_name=NVIDIA_H20-3e,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: ready

#19260 [New Model]: Support Qwen3 Embedding & Reranker
  docs/models/supported_models.md
  examples/offline_inference/qwen3_reranker.py
  tests/models/language/pooling/test_gte.py
  tests/models/language/pooling/test_qwen3_reranker.py
  tests/models/language/pooling/test_qwen3_reranker_seq_cls.py
  tests/models/registry.py
  vllm/model_executor/models/qwen3.py
  vllm/model_executor/models/registry.py
Labels: documentation, frontend, ready

#19394 [BugFix] Fix docker build cpu-dev image error
  docker/Dockerfile.cpu
Labels: ci/build

#19451 Fix test_max_model_len in tests/entrypoints/llm/test_generate.py
  tests/entrypoints/llm/test_generate.py
Labels: ready

#19454 [CI] Disable failing GGUF model test
  tests/models/quantization/test_gguf.py
Labels: ready

#19455 Add fused MOE config for Qwen3 30B A3B on B200
  vllm/model_executor/layers/fused_moe/configs/E=128,N=768,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: ready

#19442 Fix Typo in Documentation and Function Name
  tests/kernels/attention/test_encoder_decoder_attn.py
  tests/v1/sample/test_topk_topp_sampler.py
Labels: ready, v1

#19478 [Doc] Fix quantization link titles
  docs/features/quantization/README.md
  docs/features/quantization/quark.md
Labels: documentation

#19479 [Doc] Support "important" and "announcement" admonitions
  docs/contributing/README.md
  docs/contributing/model/multimodal.md
  docs/contributing/model/registration.md
  docs/contributing/model/tests.md
  docs/design/multiprocessing.md
  docs/features/multimodal_inputs.md
  docs/getting_started/quickstart.md
  docs/mkdocs/stylesheets/extra.css
  docs/models/generative_models.md
  docs/models/supported_models.md
  docs/serving/openai_compatible_server.md
  docs/usage/v1_guide.md
Labels: documentation, ready

#19475 Fix some typo
  vllm/model_executor/layers/rejection_sampler.py
Labels: ready

#19453 [Bugfix] Update the example code, make it work with the latest lmcache
  examples/others/lmcache/cpu_offload_lmcache.py
  examples/others/lmcache/kv_cache_sharing_lmcache_v1.py
Labels: documentation, ready

#17331 [AMD] [Quantization] Add override flag for attention dtype instead of using kv_cache_dtype trigger
  vllm/attention/backends/rocm_flash_attn.py
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: rocm, ready

#19514 [BugFix] Force registration of w8a8_block_fp8_matmul_deepgemm via lazy import
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
Labels: bug, ready

#19239 [Frontend] Improve error message in tool_choice validation
  vllm/entrypoints/openai/protocol.py
Labels: frontend, ready

#19522 [BugFix] Handle missing sep_token for Qwen3-Reranker in Score API
  vllm/entrypoints/openai/serving_score.py
Labels: frontend, ready

#19509 [AMD][Kernel][BugFix] fix test_rocm_compressed_tensors_w8a8 for rocm
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/compressed_tensors/triton_scaled_mm.py
Labels: bug, rocm, ready

#18018 [Security] Prevent new imports of (cloud)pickle
  .pre-commit-config.yaml
  tools/check_pickle_imports.py
Labels: ready, ci/build

#19492 [Bugfix][V1] Allow manual FlashAttention for Blackwell
  vllm/platforms/cuda.py
Labels: bug, ready, v1

#19523 [Doc] Add V1 column to supported models list
  docs/models/supported_models.md
  docs/usage/v1_guide.md
Labels: documentation, ready

#19233 [Perf] Vectorize static / dynamic INT8 quant kernels
  benchmarks/kernels/bench_int8_gemm.py
  csrc/quantization/compressed_tensors/int8_quant_kernels.cu
  csrc/quantization/vectorization_utils.cuh
  tests/kernels/quantization/test_int8_quant.py
Labels: performance, quantization, ready

#18196 [Doc] Unify structured outputs examples
  docs/features/reasoning_outputs.md
  docs/features/structured_outputs.md
  examples/online_serving/openai_chat_completion_structured_outputs.py
  examples/online_serving/openai_chat_completion_structured_outputs_structural_tag.py
  examples/online_serving/openai_chat_completion_structured_outputs_with_reasoning.py
  examples/online_serving/structured_outputs/README.md
  examples/online_serving/structured_outputs/pyproject.toml
  examples/online_serving/structured_outputs/structured_outputs.py
Labels: documentation, structured-output, ready

#19565 [V1] Resolve failed concurrent structred output requests
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#19378 Revert "[Build/CI] Add tracing deps to vllm container image (#15224)"
  .buildkite/test-pipeline.yaml
  requirements/common.txt
Labels: ready, ci/build

#19515 [BugFix] : Fix Batched DeepGemm Experts
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_triton_or_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/modular_kernel.py
  vllm/model_executor/layers/fused_moe/moe_align_block_size.py
  vllm/model_executor/layers/fused_moe/triton_deep_gemm_moe.py
Labels: ready

#19570 [Bugfix] Fix EAGLE vocab embedding for multimodal target model
  vllm/v1/spec_decode/eagle.py
Labels: ready, v1

#19582 [Doc] uses absolute links for structured outputs
  docs/features/structured_outputs.md
  examples/online_serving/structured_outputs/README.md
Labels: documentation, structured-output, misc, ready

#19586 [doc] fix incorrect link
  docs/design/multiprocessing.md
Labels: documentation, ready

#19539 [CPU] Refine default config for the CPU backend
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
  vllm/engine/arg_utils.py
  vllm/platforms/cpu.py
  vllm/v1/worker/cpu_model_runner.py
Labels: ready, ci/build, v1

#19533 [Fix] bump mistral common to support magistral
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
Labels: ready, ci/build

#19549 [Fix] The zip function in Python 3.9 does not have the strict argument
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#19064 [torch.compile] reorganize the cache directory to support compiling multiple models
  vllm/compilation/backends.py
  vllm/compilation/compiler_interface.py
  vllm/config.py
  vllm/model_executor/model_loader/utils.py
  vllm/v1/spec_decode/eagle.py
  vllm/v1/spec_decode/medusa.py
Labels: ready, v1

#19435 [BugFix] Honor `enable_caching` in connector-delayed kvcache load case
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/sched/scheduler.py
Labels: bug, ready, v1

#19592 [Model] Fix minimax model cache & lm_head precision
  vllm/model_executor/models/minimax_text_01.py
Labels: ready

#19573 [Refactor] Remove unused variables in `moe_permute_unpermute_kernel.inl`
  csrc/moe/permute_unpermute_kernels/moe_permute_unpermute_kernel.inl
Labels: ready

#18581 [CUDA] Enable full cudagraph for FlashMLA
  tests/compile/piecewise/test_full_cudagraph.py
  tests/compile/piecewise/test_simple.py
  tests/compile/piecewise/test_toy_llama.py
  tests/utils.py
  vllm/compilation/cuda_piecewise_backend.py
  vllm/entrypoints/llm.py
  vllm/forward_context.py
  vllm/v1/attention/backends/cpu_attn.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/spec_decode/eagle.py
  vllm/v1/worker/gpu_model_runner.py
Labels: rocm, structured-output, frontend, ready, v1, llama

#19377 [Doc] Add troubleshooting section to k8s deployment
  docs/deployment/k8s.md
Labels: documentation, ready

#19618 [torch.compile] Use custom ops when use_inductor=False
  vllm/config.py
Labels: ready

#19624 [BugFix] Fix DP Coordinator incorrect debug log message
  vllm/v1/engine/coordinator.py
Labels: bug, ready, v1

#18354 [V1][Metrics] Deprecate metrics with gpu_ prefix for non GPU specific metrics.
  vllm/v1/core/sched/scheduler.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
Labels: ready, v1

#19633 [Bugfix] Fix the speculative decoding test by setting the target dtype
  tests/spec_decode/e2e/test_multistep_correctness.py
Labels: speculative-decoding, ready

#19593 [Misc] Modularize CLI Argument Parsing in Benchmark Scripts
  benchmarks/benchmark_latency.py
  benchmarks/benchmark_long_document_qa_throughput.py
  benchmarks/benchmark_prefix_caching.py
  benchmarks/benchmark_prioritization.py
  benchmarks/benchmark_serving.py
  benchmarks/benchmark_serving_structured_output.py
  benchmarks/benchmark_throughput.py
Labels: structured-output, ready

#19316 [Bugfix] Fix auto dtype casting for BatchFeature
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/inputs/registry.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/utils.py
Labels: ready, v1

#19648 Only build CUTLASS MoE kernels on Hopper
  CMakeLists.txt
Labels: ready, ci/build

#19262 [Fix] Convert kv_transfer_config from dict to KVTransferConfig
  vllm/entrypoints/llm.py
Labels: frontend, ready

#19566 [Perf] Further tunings for SM100 FP8 CUTLASS kernel
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_sm100_fp8_dispatch.cuh
Labels: ready

#19339 [Kernel] Raise verbose error and consolidate `num_heads/num_kv_heads` divisibility check
  tests/kernels/attention/test_attention.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/dual_chunk_flash_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/attention/backends/pallas.py
  vllm/v1/attention/backends/triton_attn.py
Labels: rocm, tpu, ready, v1

#19627 [Benchmark] Refactor benchmark script for fp8 & int8
  benchmarks/kernels/bench_fp8_gemm.py
  benchmarks/kernels/bench_int8_gemm.py
Labels: ready

#19617 Enable prefix caching with full cuda graphs
  vllm/config.py
Labels: documentation, rocm, structured-output, frontend, speculative-decoding, ready, ci/build, v1, llama

#19589 [CI/Build] Fix torch nightly CI dependencies part 2
  requirements/nightly_torch_test.txt
Labels: ready, ci/build

#19609 [MISC] Remove unused variableds in C++
  csrc/attention/paged_attention_v1.cu
  csrc/attention/paged_attention_v2.cu
  csrc/prepare_inputs/advance_step.cu
  csrc/quantization/fp8/amd/quant_utils.cuh
  csrc/quantization/gptq/q_gemm.cu
  csrc/rocm/attention.cu
Labels: rocm, ready

#18957 [Bugfix][Core] Prefix caching causes incorrect outputs due to outdated ComputedBlocksTracker
  tests/core/test_scheduler.py
  vllm/core/block_manager.py
  vllm/core/scheduler.py
Labels: ready

#19564 [Misc][Frontend] passthrough `bad_words`
  vllm/entrypoints/openai/protocol.py
Labels: frontend, ready

#19620 [TPU] support attention head dim smaller than 128
  tests/v1/tpu/test_basic.py
  vllm/v1/attention/backends/pallas.py
Labels: tpu, ready, v1

#19672 [MISC] typo fix
  vllm/config.py
Labels: ready

#19344 [CI] Add mteb testing for rerank models
  requirements/test.in
  requirements/test.txt
  tests/conftest.py
  tests/entrypoints/openai/correctness/test_mteb_embed.py
  tests/entrypoints/openai/correctness/test_mteb_score.py
  tests/models/language/pooling/mteb_utils.py
  tests/models/language/pooling/test_baai.py
  tests/models/language/pooling/test_cross_encoder.py
  tests/models/language/pooling/test_jina.py
  tests/models/language/pooling/test_qwen3_reranker.py
  tests/models/language/pooling/test_qwen3_reranker_seq_cls.py
  tests/models/utils.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/bert_with_rope.py
Labels: ready, ci/build
