Repository vllm-project/vllm, pull requests merged in 2025-10, with the labels that each got.

#25982 [Model] MTP fallback to eager for DeepSeek v32
  tests/v1/spec_decode/test_eagle.py
  tests/v1/spec_decode/test_mtp.py
  vllm/config/speculative.py
  vllm/v1/attention/backends/mla/indexer.py
  vllm/v1/spec_decode/eagle.py
Labels: speculative-decoding, ready, v1, deepseek

#25843 Update launch_bounds_utils.h for correct compile on Multiple Cuda Arch - PTXAS out of range Warning
  csrc/launch_bounds_utils.h
Labels: bug, ready

#25709 [Log] Optimize Log for FP8MOE
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready

#25935 Fix INT8 quantization error on Blackwell GPUs (SM100+)
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_helper.hpp
  docs/features/quantization/int8.md
Labels: documentation, ready

#26000 [MM] Add text-only mode for Qwen3-VL
  vllm/model_executor/models/qwen3_vl.py
  vllm/model_executor/models/qwen3_vl_moe.py
Labels: ready, qwen

#25988 [BugFix] Fix default kv-cache-dtype default for DeepseekV3.2
  vllm/model_executor/models/config.py
Labels: deepseek

#25989 [Doc] updating torch.compile doc link
  docs/design/torch_compile.md
Labels: documentation, ready

#26003 [Misc] Factor out common `_apply_feature_select_strategy`
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/tarsier.py
  vllm/model_executor/models/vision.py
Labels: ready

#24673 [NVIDIA] Blackwell Family
  CMakeLists.txt
  cmake/utils.cmake
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm100_fp8_dispatch.cuh
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_sm100_fp8_dispatch.cuh
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
Labels: ready, ci/build

#25908 [ROCm][Build] Add support for AMD Ryzen AI MAX / AI 300 Series
  CMakeLists.txt
  csrc/rocm/attention.cu
  docker/Dockerfile.rocm_base
Labels: rocm, ready, ci/build

#25683 [Bug] Fix Negative Cuda Memory Usage
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#23014 Support RL online quantization with torchao
  tests/quantization/test_torchao.py
  vllm/model_executor/layers/quantization/torchao.py
  vllm/model_executor/model_loader/default_loader.py
  vllm/model_executor/model_loader/online_quantization.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: quantization, ready

#26029 [ROCm][Bugfix] Add missing parameter to ROCm backend
  vllm/v1/attention/backends/rocm_attn.py
Labels: rocm, ready, v1

#24909 Run:ai model streamer add GCS package support
  docs/models/extensions/runai_model_streamer.md
  requirements/nightly_torch_test.txt
  requirements/rocm.txt
  requirements/test.in
  requirements/test.txt
  tests/model_executor/model_loader/runai_model_streamer/test_runai_utils.py
Labels: documentation, rocm, ready, ci/build

#26065 Update base image to 22.04 (jammy)
  docker/Dockerfile
  docker/Dockerfile.nightly_torch
  docs/assets/contributing/dockerfile-stages-dependency.png
Labels: documentation, ready, ci/build

#26089 Change size of single CUDA graph for CI to 4
  tests/conftest.py
Labels: ready

#26073 [Model] Use `merge_by_field_config` for MM models (A-C)
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/cohere2_vision.py
Labels: ready

#26076 [Model] Use `merge_by_field_config` for MM models (D-F)
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/dots_ocr.py
  vllm/model_executor/models/ernie45_vl.py
  vllm/model_executor/models/fuyu.py
Labels: ready, deepseek

#25470 [Platform][CI] Added OOT platform interface e2e test that running on Ascend NPU
  .buildkite/scripts/hardware_ci/run-npu-test.sh
Labels: ready, ci/build

#24642 [Qwen][ROCm] Flash Attention Rotary Embeddings
  vllm/model_executor/layers/rotary_embedding/common.py
  vllm/model_executor/models/qwen2_vl.py
Labels: rocm, ready, qwen, module: rocm

#26040 [CI] Add Blackwell DeepSeek FP8 FlashInfer MoE tests
  tests/quantization/test_blackwell_moe.py
Labels: ready, ci/build, deepseek

#26063 [BugFix] Fix FI accuracy issue when used for MLA prefill
  vllm/v1/attention/backends/mla/common.py
Labels: bug, ready, v1

#25999 [Deepseek v3.2] Support indexer prefill chunking
  tests/v1/attention/test_sparse_mla_backends.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/v1/attention/backends/mla/indexer.py
Labels: ready, v1, deepseek

#25916 EAGLE 3: Fix preamble so that measured speedup over Eagle 1 becomes 32% instead of 5% on MTBench
  vllm/benchmarks/datasets.py
Labels: performance, ready

#25119 [Mamba][KVCacheManager] Simplify kv cache manage logic for mamba + MTP
  vllm/v1/core/single_type_kv_cache_manager.py
Labels: ready, v1

#26130 [Bugfix] Disable cascade attention with FlashInfer
  vllm/v1/attention/backends/flashinfer.py
Labels: ready, v1

#25893 [Attention] Move Backend enum into registry
  tests/compile/test_full_graph.py
  tests/compile/test_fusion_attn.py
  tests/kernels/attention/test_mha_attn.py
  tests/kernels/utils.py
  tests/v1/attention/test_attention_backends.py
  tests/v1/attention/test_mla_backends.py
  tests/v1/attention/utils.py
  tests/v1/spec_decode/test_eagle.py
  tests/v1/spec_decode/test_mtp.py
  tests/v1/spec_decode/test_tree_attention.py
  vllm/attention/backends/registry.py
  vllm/attention/layer.py
  vllm/attention/selector.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/envs.py
  vllm/model_executor/models/dots_ocr.py
  vllm/model_executor/models/ernie45_vl.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/keye.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/qwen3_vl.py
  vllm/model_executor/models/siglip2navit.py
  vllm/model_executor/models/vision.py
  vllm/platforms/__init__.py
  vllm/platforms/cpu.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
Labels: rocm, tpu, speculative-decoding, ready, v1, qwen, kv-connector

#26138 [CI/Build] Conditionally register cutlass_fp4_group_mm to fix building on Hopper
  csrc/quantization/fp4/nvfp4_blockwise_moe_kernel.cu
  csrc/torch_bindings.cpp
Labels: ready

#26144 [Bug]: Limit num_reqs in dummy_run when max_num_seqs is small
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#26104 [ROCm] [VL] [Bugfix] Fix vit flash attn dispatcher logic for ROCm
  vllm/attention/layer.py
  vllm/model_executor/models/dots_ocr.py
  vllm/model_executor/models/ernie45_vl.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/qwen3_vl.py
  vllm/model_executor/models/siglip2navit.py
  vllm/platforms/rocm.py
Labels: rocm, ready, qwen

#26117 [Model] Use `merge_by_field_config` for MM models (G)
  vllm/model_executor/models/gemma3_mm.py
  vllm/model_executor/models/gemma3n_mm.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/glm4v.py
  vllm/model_executor/models/granite_speech.py
Labels: ready

#22650 `FusedMoE` support for the Transformers backend
  docs/models/supported_models.md
  tests/models/registry.py
  tests/models/test_transformers.py
  tests/models/utils.py
  vllm/config/model.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/transformers.py
  vllm/model_executor/models/transformers_moe.py
  vllm/model_executor/models/transformers_pooling.py
Labels: documentation, new-model, ready

#26155 [CI] Fix distributed hybrid tests in CI
  tests/models/language/generation/test_hybrid.py
Labels: ready

#25388 [NIXL][Misc] Expose metrics from NIXL for logging to CLI
  requirements/kv_connectors.txt
  tests/v1/kv_connector/unit/test_nixl_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/v1/metrics/loggers.py
Labels: ready, ci/build, v1, kv-connector

#25631 [Multi Modal] Configurable MM Profiling
  docs/contributing/model/multimodal.md
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_mllama4.py
  tests/models/multimodal/processing/test_tensor_schema.py
  vllm/config/model.py
  vllm/config/multimodal.py
  vllm/engine/arg_utils.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/cohere2_vision.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/dots_ocr.py
  vllm/model_executor/models/ernie45_vl.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma3_mm.py
  vllm/model_executor/models/gemma3n_mm.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/glm4v.py
  vllm/model_executor/models/granite_speech.py
  vllm/model_executor/models/hyperclovax_vision.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/interns1.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/keye.py
  vllm/model_executor/models/kimi_vl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/midashenglm.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mistral3.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/nano_nemotron_vl.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/ovis.py
  vllm/model_executor/models/ovis2_5.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/phi4_multimodal.py
  vllm/model_executor/models/phi4mm.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/qwen3_vl.py
  vllm/model_executor/models/qwen_vl.py
  vllm/model_executor/models/rvl.py
  vllm/model_executor/models/skyworkr1v.py
  vllm/model_executor/models/step3_vl.py
  vllm/model_executor/models/terratorch.py
  vllm/model_executor/models/transformers.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/voxtral.py
  vllm/model_executor/models/whisper.py
  vllm/multimodal/profiling.py
  vllm/multimodal/registry.py
Labels: documentation, ready, multi-modality, llama, qwen, deepseek

#25668 [Doc] Fixed shape description for fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
Labels: ready

#24138 [Renderer] Move Processor out of AsyncLLM
  tests/entrypoints/openai/test_lora_resolvers.py
  tests/entrypoints/openai/test_serving_chat.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/v1/engine/async_llm.py
Labels: documentation, frontend, ready, v1

#24446 Re-enable prefill of max model length
  tests/v1/e2e/test_context_length.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#26165 [Renderer] Move Processor out of LLMEngine
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/inputs/parse.py
  vllm/v1/engine/llm_engine.py
Labels: frontend, ready, v1

#26174 Avoid division by zero in cache DS MLA kernel
  csrc/cache_kernels.cu
Labels: ready

#26148 Fix V1 engine serialization error with Ray distributed executor
  vllm/executor/ray_utils.py
Labels: ready

#25968 [Quantization/NVFP4] Speed up TRTLLM NVFP4 MOE weight loading and fix K/V scale loading for MLA Attn
  vllm/model_executor/layers/quantization/kv_cache.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#26183 [Perf] Remove hardcoded num_warps=1
  vllm/v1/sample/rejection_sampler.py
Labels: ready, v1

#26044 [Refactor] Optimize FP8 MOE Backend Choice and Log
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready

#25724 [responsesAPI] add better error messaging for long prompts
  tests/entrypoints/openai/test_serving_responses.py
  vllm/entrypoints/openai/serving_responses.py
Labels: frontend, ready, gpt-oss

#25974 [Misc] Add penalties sampling parameters to serve tool
  vllm/benchmarks/serve.py
Labels: performance, ready

#23953 [BugFix] Fix de-functionalization pass for rotary_embedding
  .buildkite/test-pipeline.yaml
  tests/compile/test_functionalization.py
  vllm/compilation/fix_functionalization.py
Labels: ready, ci/build

#26181 [CI] Fix Pre-commit Mypy Error
  vllm/transformers_utils/config.py
Labels: ready

#25488 [GPTOSS][DP/EP][Marlin] Enable GPTOSS DP/EP using Marlin kernels
  docs/design/moe_kernel_features.md
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/modular_kernel.py
  vllm/model_executor/layers/quantization/mxfp4.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
Labels: documentation, ready, gpt-oss

#26186 Fix issue of using only the part of video frame [Nemotron Nano]
  vllm/model_executor/models/nano_nemotron_vl.py
Labels: ready

#26134 [BugFix] Use async Mistral Tokenizer in Chat Completions
  tests/entrypoints/openai/test_serving_engine.py
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend, ready

#25769 Add batch invariant kernel override for FlashInfer backend [2/n]
  tests/v1/generation/test_batch_invariance.py
  vllm/model_executor/layers/batch_invariant.py
  vllm/v1/attention/backends/flashinfer.py
Labels: ready, v1

#25948 [cpu][perf] Accelerate unquantized-linear for AArch64 through oneDNN/ACL and weight prepack
  cmake/cpu_extension.cmake
  csrc/cpu/dnnl_helper.cpp
  csrc/cpu/dnnl_helper.h
  csrc/cpu/dnnl_kernels.cpp
  csrc/cpu/torch_bindings.cpp
  setup.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/utils.py
Labels: ready, ci/build

#25752 [V1] [Hybrid] Mamba2 Automatic Prefix Caching
  tests/models/language/generation/test_hybrid.py
  vllm/config/cache.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/layers/mamba/ops/causal_conv1d.py
  vllm/model_executor/layers/mamba/ops/mamba_ssm.py
  vllm/model_executor/layers/mamba/ops/ssd_combined.py
  vllm/model_executor/models/bamba.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/falcon_h1.py
  vllm/model_executor/models/granitemoehybrid.py
  vllm/model_executor/models/mamba2.py
  vllm/model_executor/models/nemotron_h.py
  vllm/model_executor/models/zamba2.py
  vllm/v1/attention/backends/mamba2_attn.py
  vllm/v1/core/single_type_kv_cache_manager.py
  vllm/v1/kv_cache_interface.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#26162 Support expert parallel in Transformers backend
  docs/models/supported_models.md
  vllm/model_executor/models/transformers_moe.py
Labels: documentation, ready

#26215 [Misc] Remove unused `executor.apply_model`
  vllm/executor/executor_base.py
Labels: ready

#26053 [CI Failure] fix_test_auto_prefix_cache_support
  tests/v1/core/test_scheduler.py
  vllm/config/vllm.py
Labels: ready, v1

#26220 Revert "Add batch invariant kernel override for FlashInfer backend [2/n]"
  tests/v1/generation/test_batch_invariance.py
  vllm/model_executor/layers/batch_invariant.py
  vllm/v1/attention/backends/flashinfer.py
Labels: ready, v1

#26054 Add Olmo 3 reasoning parser
  tests/reasoning/test_olmo3_reasoning_parser.py
  vllm/reasoning/__init__.py
  vllm/reasoning/olmo3_reasoning_parser.py
Labels: new-model, ready, tool-calling

#26168 [Core] Enable decode of context length equal to max model length
  tests/entrypoints/llm/test_generate.py
  tests/v1/e2e/test_context_length.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/sched/utils.py
Labels: ready, v1

#26219 Fix tensor device and dtype placement in Qwen2VL model
  vllm/model_executor/models/qwen2_vl.py
Labels: ready, qwen

#26227 [Frontend] Cache chat template kwargs resolution
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_pooling.py
  vllm/entrypoints/openai/serving_tokenization.py
Labels: frontend, ready

#26216 [Renderer] Clean up renderer code
  tests/entrypoints/openai/test_token_in_token_out.py
  tests/test_inputs.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/renderer.py
  vllm/inputs/parse.py
Labels: frontend, ready

#26232 [Easy] Add str repr for IterationStats
  tests/v1/metrics/test_stats.py
  vllm/v1/metrics/stats.py
Labels: ready, v1

#26238 [Bugfix] Allow `--skip-tokenizer-init` with `echo and return_token_ids`
  tests/entrypoints/openai/test_token_in_token_out.py
  vllm/entrypoints/openai/serving_completion.py
Labels: frontend, ready

#26112 [Perf][Easy] Early stop in request_block_hasher
  vllm/v1/core/kv_cache_utils.py
Labels: ready, v1

#26240 [Bugfix] Always apply MM processor even when no MM items are passed
  tests/conftest.py
  tests/test_inputs.py
  vllm/inputs/preprocess.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/multimodal/processing.py
Labels: ready, multi-modality, qwen

#25823 [Refactor][Kernel] support loading kernel from other place
  vllm/_custom_ops.py
  vllm/platforms/interface.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
Labels: tpu, ready

#26254 Fix per file ruff ignores related to typing
  pyproject.toml
  tests/compile/test_full_graph.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/plugins/prithvi_io_processor_plugin/prithvi_io_processor/prithvi_processor.py
  tests/v1/engine/test_llm_engine.py
  vllm/attention/backends/abstract.py
  vllm/attention/layer.py
  vllm/attention/layers/chunked_local_attention.py
  vllm/attention/ops/flashmla.py
  vllm/attention/ops/paged_attn.py
  vllm/engine/arg_utils.py
  vllm/engine/metrics.py
  vllm/engine/metrics_types.py
  vllm/entrypoints/harmony_utils.py
  vllm/executor/executor_base.py
  vllm/executor/msgspec_utils.py
  vllm/executor/ray_distributed_executor.py
  vllm/executor/ray_utils.py
  vllm/executor/uniproc_executor.py
  vllm/model_executor/layers/fused_moe/flashinfer_trtllm_moe.py
  vllm/multimodal/inputs.py
  vllm/plugins/io_processors/__init__.py
  vllm/utils/__init__.py
  vllm/utils/deep_gemm.py
  vllm/utils/flashinfer.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/core/sched/output.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/structured_output/__init__.py
  vllm/v1/structured_output/backend_guidance.py
  vllm/v1/structured_output/request.py
  vllm/v1/worker/worker_base.py
Labels: structured-output, frontend, ready, v1, multi-modality, gpt-oss

#26255 Update `ruff` pre-commit hooks version
  .buildkite/nightly-benchmarks/scripts/convert-results-json-to-markdown.py
  .pre-commit-config.yaml
Labels: performance, ci/build

#25998 [NVIDIA] flashinfer TRTLLM attention prefill token limit
  vllm/utils/flashinfer.py
Labels: ready

#26259 Fix per file ruff ignores related to simplification
  pyproject.toml
  tests/distributed/test_expert_placement.py
  tests/kernels/attention/test_cutlass_mla_decode.py
  tests/kernels/attention/test_flashmla.py
  tests/kernels/attention/test_lightning_attn.py
  tests/kernels/moe/test_pplx_moe.py
  tests/kernels/quantization/test_cutlass_scaled_mm.py
  tests/kernels/test_onednn.py
  tests/kernels/utils.py
  tests/multimodal/test_processing.py
  tools/profiler/print_layerwise_table.py
  vllm/_custom_ops.py
  vllm/attention/ops/triton_reshape_and_cache_flash.py
  vllm/distributed/parallel_state.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/executor/ray_distributed_executor.py
  vllm/model_executor/layers/batch_invariant.py
  vllm/model_executor/layers/fla/ops/chunk_o.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/modular_kernel.py
  vllm/model_executor/layers/fused_moe/rocm_aiter_fused_moe.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/lightning_attn.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
  vllm/model_executor/layers/quantization/quark/utils.py
  vllm/utils/__init__.py
  vllm/v1/sample/ops/bad_words.py
  vllm/v1/sample/rejection_sampler.py
  vllm/v1/worker/tpu_model_runner.py
Labels: rocm, frontend, tpu, ready, v1, multi-modality

#26052 [CI] Add Blackwell LM Eval Small Models test to nightly
  .buildkite/test-pipeline.yaml
  tests/evals/gsm8k/configs/models-blackwell.txt
Labels: ready, ci/build

#26177 [DOC] Update production-stack.md
  docs/deployment/integrations/production-stack.md
Labels: documentation, ready

#26252 [CI] Add comment about the single cudagraph capture size that is used
  tests/conftest.py
Labels: ready

#26222 [V1] [Hybrid] Some additional clean-up in Mamba2 prefix caching
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/layers/mamba/ops/causal_conv1d.py
  vllm/v1/attention/backends/mamba2_attn.py
  vllm/v1/core/single_type_kv_cache_manager.py
Labels: ready, v1

#26266 [Doc] Edited minor typo
  docs/design/plugin_system.md
Labels: documentation

#26270 [MISC] Add heheda12345 to CODEOWNERS of vllm/config/cache.py
  .github/CODEOWNERS
Labels: ci/build

#26274 [Misc] Clean up unnecessary E501 ignore
  vllm/benchmarks/datasets.py
  vllm/benchmarks/throughput.py
  vllm/compilation/inductor_pass.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/models/gemma3n_mm.py
  vllm/model_executor/models/registry.py
  vllm/v1/attention/backends/gdn_attn.py
Labels: performance, new-model, ready, v1

#26276 [Frontend] Consolidate tokenizer init code
  tests/test_inputs.py
  tests/v1/engine/test_processor_multi_modal_uuids.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/inputs/preprocess.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/processor.py
Labels: frontend, ready, v1

#26087 [Bugfix] Fix mrope in Transformers Backend
  tests/models/multimodal/generation/test_common.py
  vllm/model_executor/models/transformers.py
Labels: ready, multi-modality

#26281 Fix `DotsOCR` tensor type
  vllm/model_executor/models/dots_ocr.py
Labels: ready

#24463 [Attention] Remove unused reorder_batch method
  tests/v1/logits_processors/test_correctness.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/attention/backends/tree_attn.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/attention/backends/xformers.py
Labels: ready, v1

#25961 Support llama3 eagle3 head with llama4 verifier
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llama_eagle3.py
  vllm/model_executor/models/mllama4.py
  vllm/transformers_utils/configs/speculators/algos.py
  vllm/v1/worker/gpu_model_runner.py
Labels: speculative-decoding, ready, v1, llama

#26304 [Misc] auto_tune: kill specific vllm process
  benchmarks/auto_tune/auto_tune.sh
Labels: performance, ready

#26289 Add bias handling to CPUFusedMOE kernel
  tests/kernels/moe/test_moe.py
  vllm/model_executor/layers/fused_moe/cpu_fused_moe.py
Labels: ready

#26314 [Docs] Fix broken table in moe_kernel_features doc
  docs/design/moe_kernel_features.md
Labels: documentation, ready

#26209 [BugFix] Pad input buffers in _dummy_run
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#26313 [Perf] Add decode full-graph support to FlashInfer-MLA backend
  vllm/v1/attention/backends/mla/flashinfer_mla.py
Labels: ready, v1

#26024 [Docs][DBO] Add initial doc that describes the DBO implementation
  docs/design/dbo.md
Labels: documentation, ready

#25768 [Core] Simplify the Dp padding/should ubatch coordination logic
  tests/v1/attention/test_attention_splitting.py
  vllm/config/parallel.py
  vllm/engine/arg_utils.py
  vllm/envs.py
  vllm/forward_context.py
  vllm/v1/worker/dp_utils.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_ubatch_wrapper.py
  vllm/v1/worker/ubatch_splitting.py
  vllm/v1/worker/ubatch_utils.py
Labels: ready, v1

#26324 [BUG] Fix file parsing for load_format runai_streamer_sharded
  vllm/model_executor/model_loader/sharded_state_loader.py
Labels: ready

#26260 [Model] Define merge_by_field_config MM interface (R-T)
  vllm/model_executor/models/step3_vl.py
  vllm/model_executor/models/tarsier.py
  vllm/model_executor/models/terratorch.py
Labels: ready

#26265 [BugFix] Update KV block hash type from BlockHash to ExternalBlockHash in kv_events_subscriber - #26264
  examples/online_serving/kv_events_subscriber.py
Labels: documentation, ready

#25945 Add topk logits torch op for DS3.2.
  csrc/ops.h
  csrc/sampler.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_top_k_per_row.py
  vllm/model_executor/models/deepseek_v2.py
Labels: ready, deepseek

#24374 [Docs] add docs for cuda graph v1
  docs/assets/design/cuda_graphs/current_design.png
  docs/assets/design/cuda_graphs/executor_runtime.png
  docs/assets/design/cuda_graphs/previous_design.png
  docs/assets/design/cuda_graphs/wrapper_flow.png
  docs/design/cuda_graphs.md
  docs/design/torch_compile.md
Labels: documentation

#21166 [Feature][OCP MX] Support mxfp6 and mixed mxfp6-mxfp4
  docs/features/quantization/quark.md
  tests/kernels/moe/test_ocp_mx_moe.py
  tests/quantization/test_quark.py
  vllm/model_executor/layers/fused_moe/config.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/utils.py
  vllm/model_executor/layers/quantization/mxfp4.py
  vllm/model_executor/layers/quantization/quark/quark.py
  vllm/model_executor/layers/quantization/quark/quark_moe.py
  vllm/model_executor/layers/quantization/quark/schemes/__init__.py
  vllm/model_executor/layers/quantization/quark/schemes/quark_ocp_mx.py
  vllm/model_executor/layers/quantization/utils/mxfp4_utils.py
  vllm/model_executor/layers/quantization/utils/mxfp6_utils.py
  vllm/model_executor/layers/quantization/utils/mxfp8_utils.py
  vllm/model_executor/layers/quantization/utils/ocp_mx_utils.py
  vllm/scalar_type.py
  vllm/utils/flashinfer.py
Labels: documentation, performance, new-model, rocm, quantization, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, llama, qwen, deepseek, gpt-oss, kv-connector

#26342 [Misc] Move `LRUCache` into its own file
  tests/utils_/test_cache.py
  tests/utils_/test_utils.py
  vllm/lora/models.py
  vllm/multimodal/cache.py
  vllm/utils/__init__.py
  vllm/utils/cache.py
Labels: ready, multi-modality

#26341 [V0 Deprecation] Remove `VLLM_USE_V1` from tests
  .buildkite/test-pipeline.yaml
  tests/basic_correctness/test_basic_correctness.py
  tests/basic_correctness/test_cumem.py
  tests/compile/piecewise/test_full_cudagraph.py
  tests/compile/piecewise/test_simple.py
  tests/compile/test_async_tp.py
  tests/compile/test_config.py
  tests/compile/test_fusion_attn.py
  tests/config/test_mp_reducer.py
  tests/detokenizer/test_stop_strings.py
  tests/distributed/test_context_parallel.py
  tests/distributed/test_pipeline_parallel.py
  tests/distributed/test_sequence_parallel.py
  tests/entrypoints/llm/test_accuracy.py
  tests/entrypoints/openai/correctness/test_lmeval.py
  tests/entrypoints/openai/test_chat.py
  tests/entrypoints/openai/test_lora_adapters.py
  tests/entrypoints/openai/test_metrics.py
  tests/entrypoints/openai/test_prompt_validation.py
  tests/kernels/attention/test_attention_selector.py
  tests/kernels/test_flex_attention.py
  tests/models/multimodal/generation/test_maverick.py
  tests/plugins/vllm_add_dummy_platform/vllm_add_dummy_platform/dummy_platform.py
  tests/plugins_tests/test_scheduler_plugins.py
  tests/samplers/test_no_bad_words.py
  tests/tpu/lora/test_lora.py
  tests/v1/attention/utils.py
  tests/v1/core/test_kv_sharing.py
  tests/v1/core/test_scheduler_e2e.py
  tests/v1/cudagraph/test_cudagraph_mode.py
  tests/v1/e2e/test_cascade_attention.py
  tests/v1/e2e/test_correctness_sliding_window.py
  tests/v1/e2e/test_kv_sharing_fast_prefill.py
  tests/v1/e2e/test_min_tokens.py
  tests/v1/e2e/test_spec_decode.py
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_engine_args.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  tests/v1/engine/test_llm_engine.py
  tests/v1/entrypoints/llm/test_struct_output_generate.py
  tests/v1/kv_connector/nixl_integration/run_tpu_disagg_accuracy_test.sh
  tests/v1/kv_connector/nixl_integration/run_tpu_edge_case_test.sh
  tests/v1/metrics/test_ray_metrics.py
  tests/v1/sample/test_logprobs.py
  tests/v1/sample/test_sampling_params_e2e.py
  tests/v1/spec_decode/test_max_len.py
  tests/v1/tpu/test_basic.py
  tests/v1/tpu/test_perf.py
  tests/v1/tracing/test_tracing.py
  vllm/v1/worker/cpu_model_runner.py
Labels: structured-output, tpu, speculative-decoding, ready, ci/build, v1, multi-modality, kv-connector

#26316 [CI] Add Qwen3 MoE NVFP4 to Blackwell lm-eval
  .buildkite/test-pipeline.yaml
  tests/evals/gsm8k/configs/Qwen3-30B-A3B-NVFP4.yaml
  tests/evals/gsm8k/configs/models-blackwell.txt
Labels: ready, ci/build, qwen

#26113 [Frontend] CompilationConfig overhaul (#20283): deprecate use_inductor in favor of backend, simplify custom_ops
  tests/compile/piecewise/test_toy_llama.py
  tests/model_executor/test_enabled_custom_ops.py
  vllm/compilation/backends.py
  vllm/config/compilation.py
  vllm/config/vllm.py
  vllm/model_executor/custom_op.py
  vllm/platforms/cpu.py
Labels: ready, llama

#19482 [V1] Logit processors for rejection sampler
  tests/v1/logits_processors/test_custom_offline.py
  tests/v1/sample/test_rejection_sampler.py
  tests/v1/sample/test_sampler.py
  tests/v1/sample/utils.py
  tests/v1/worker/test_gpu_input_batch.py
  vllm/v1/sample/logits_processor/__init__.py
  vllm/v1/sample/metadata.py
  vllm/v1/sample/ops/bad_words.py
  vllm/v1/sample/rejection_sampler.py
  vllm/v1/sample/sampler.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, performance, new-model, rocm, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, llama, qwen, deepseek, gpt-oss, kv-connector

#25713 [TPU] update TPU benchmark threshold
  .buildkite/scripts/tpu/quantized_v6e_1.env
Labels: tpu, ready, ci/build

#26361 [Bugfix] Fix MTP+FlashInfer crash when trtllm kernels are available but disabled
  vllm/utils/flashinfer.py
Labels: bug, ready

#26332 Revert #24446 and #26168
  tests/entrypoints/llm/test_generate.py
  tests/v1/e2e/test_context_length.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/sched/utils.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#26347 Add SwigluOAI implementation for CPUFusedMOE
  vllm/model_executor/layers/fused_moe/cpu_fused_moe.py
Labels: ready, cpu

#26388 [Core] Simplify setting new_token_ids in CachedRequestData
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#23485 fix(v1/kv_cache): resolve async KV transfer bug in cascade attention
  vllm/v1/core/kv_cache_coordinator.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/single_type_kv_cache_manager.py
Labels: ready, v1

#25931 Add gather_indexer_k_quant_cache kernel
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/torch_bindings.cpp
  vllm/_custom_ops.py
Labels: ready

#26395 [Bugfix] Incorrect MM data format in `vllm bench throughput`
  vllm/benchmarks/throughput.py
Labels: performance, ready

#26218 fix[DP][v1]: Prevent hangs from mismatched worker configurations
  vllm/config/parallel.py
  vllm/v1/engine/core.py
  vllm/v1/engine/utils.py
Labels: ready, v1

#26279 [TPU] Rename tpu_commons to tpu_inference
  vllm/distributed/device_communicators/tpu_communicator.py
  vllm/model_executor/model_loader/default_loader.py
  vllm/platforms/__init__.py
  vllm/platforms/tpu.py
  vllm/v1/attention/backends/pallas.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#26197 [Feature] Enable E8M0 by Default on Hopper for DeepGEMM, 5% E2E throughput improvement
  vllm/envs.py
  vllm/transformers_utils/config.py
  vllm/utils/deep_gemm.py
Labels: ready

#26357 [Misc] add usedforsecurity=False in md5 hash call
  vllm/model_executor/models/registry.py
Labels: new-model, ready

#26403 [Model] Allow passing custom number of max tiles to Nano 2 VL
  vllm/model_executor/models/nano_nemotron_vl.py
Labels: ready

#26412 [Docs] Have mergify leave a comment with the docs preview link
  .github/mergify.yml
Labels: documentation, ready, ci/build

#26419 [Benchmarks] Add support for Qwen 3 VL MoE tuning
  benchmarks/kernels/benchmark_moe.py
Labels: performance, ready, qwen

#26424 [CI Failure] Fix pre-commit issue for install_nixl_from_source_ubuntu.py
  tools/install_nixl_from_source_ubuntu.py
Labels: kv-connector

#26423 [Bug] Fix DeepGEMM Attention Test
  pyproject.toml
  tests/kernels/attention/test_deepgemm_attention.py
Labels: ready
