Repository vllm-project/vllm, pull requests merged in 2025-08, with the labels that each got.

#21533 Add DeepGEMM to Dockerfile in vllm-base image
  docker/Dockerfile
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  tests/kernels/moe/test_deepgemm.py
  vllm/utils/deep_gemm.py
Labels: ready, ci/build, force-merge, deepseek

#21787 [Refactor] Remove Duplicate `per_block_cast_to_fp8`, Remove Dependencies of DeepGEMM
  benchmarks/kernels/deepgemm/benchmark_fp8_block_dense_gemm.py
  tests/kernels/moe/modular_kernel_tools/utils.py
  tests/kernels/moe/test_cutlass_grouped_gemm.py
  tests/kernels/moe/test_deepgemm.py
  tests/kernels/moe/utils.py
  tests/kernels/quant_utils.py
  tests/kernels/quantization/test_block_fp8.py
  vllm/utils/deep_gemm.py
Labels: performance, ready

#20873 [Bugfix] Fix: Fix multi loras with tp >=2 and LRU cache
  .buildkite/test-pipeline.yaml
  tests/lora/test_multi_loras_with_tp.py
  vllm/lora/layers.py
Labels: ready, ci/build

#22005 [Misc] Automatically resolve HF processor init kwargs
  examples/offline_inference/vision_language.py
  tests/lora/test_qwen2vl.py
  tests/models/multimodal/generation/test_common.py
  tests/models/multimodal/generation/vlm_utils/model_utils.py
  tests/models/multimodal/processing/test_transformers.py
  tests/models/registry.py
  tests/multimodal/test_processing.py
  vllm/config.py
  vllm/inputs/registry.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/florence2.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/hyperclovax_vision.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/keye.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/nemotron_vl.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/ovis.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/phi4_multimodal.py
  vllm/model_executor/models/phi4mm.py
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/skyworkr1v.py
  vllm/model_executor/models/smolvlm.py
  vllm/model_executor/models/tarsier.py
  vllm/model_executor/models/transformers.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/whisper.py
  vllm/transformers_utils/processor.py
  vllm/utils/__init__.py
Labels: documentation, ready, multi-modality, llama, qwen, deepseek

#22045 [Doc] Fix a syntax error of example code in structured_outputs.md
  docs/features/structured_outputs.md
Labels: documentation, structured-output

#21896 [Bugfix] Disable multi-modal preprocessor cache for DP
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/cli/serve.py
Labels: frontend, ready

#22055 Revert precompile wheel changes
  docker/Dockerfile
  requirements/test.txt
  setup.py
  vllm/envs.py
Labels: ready, ci/build

#22047 [Doc] Added warning of speculating with draft model
  docs/features/spec_decode.md
Labels: documentation, force-merge

#21953 [Quantization] Enable BNB support for InternS1
  vllm/model_executor/model_loader/bitsandbytes_loader.py
  vllm/model_executor/utils.py
Labels: ready

#21345 [Speculative Decoding] Add `speculators` config support
  tests/speculative_decoding/speculators/test_eagle3.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/models/llama_eagle3.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/speculators/__init__.py
  vllm/transformers_utils/configs/speculators/algos.py
  vllm/transformers_utils/configs/speculators/base.py
Labels: speculative-decoding, ready, v1, llama

#22083 [BUG] [ROCm] Fix import bug on ROCm
  vllm/compilation/pass_manager.py
Labels: rocm, ready

#22016 Fix `get_kwargs` for case where type hint is `list[Union[str, type]]`
  tests/engine/test_arg_utils.py
  vllm/engine/arg_utils.py
Labels: ready

#21841 [Bugfix][PD] set max_completion_tokens=1 if req has this value
  examples/online_serving/disaggregated_serving/disagg_proxy_demo.py
  examples/online_serving/disaggregated_serving_p2p_nccl_xpyd/disagg_proxy_p2p_nccl_xpyd.py
Labels: documentation, ready

#21462 [Refactor] Fix Compile Warning #1444-D
  csrc/moe/topk_softmax_kernels.cu
Labels: bug, ready

#22032 [BugFix] Don't change title of top-level process
  vllm/entrypoints/cli/serve.py
  vllm/entrypoints/openai/api_server.py
Labels: bug, frontend, ready

#22089 [Docs] use `uv` in CPU installation docs
  docs/getting_started/installation/cpu/apple.inc.md
  docs/getting_started/installation/cpu/build.inc.md
  docs/getting_started/installation/cpu/s390x.inc.md
Labels: documentation, force-merge

#21739 Deprecate `--disable-log-requests` and replace with `--enable-log-requests`
  .buildkite/nightly-benchmarks/README.md
  .buildkite/nightly-benchmarks/tests/genai-perf-tests.json
  .buildkite/nightly-benchmarks/tests/nightly-tests.json
  .buildkite/nightly-benchmarks/tests/serving-tests-cpu-snc2.json
  .buildkite/nightly-benchmarks/tests/serving-tests-cpu-snc3.json
  .buildkite/nightly-benchmarks/tests/serving-tests-cpu.json
  .buildkite/nightly-benchmarks/tests/serving-tests.json
  tests/config/test_mp_reducer.py
  tests/mq_llm_engine/test_load.py
  tests/v1/engine/test_async_llm.py
  tests/v1/test_async_llm_dp.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/engine.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/run_batch.py
  vllm/utils/__init__.py
  vllm/v1/engine/async_llm.py
Labels: performance, frontend, ready, ci/build, v1

#21922 [Bugfix] fix when skip tokenizer init
  tests/v1/engine/test_llm_engine.py
  vllm/v1/engine/processor.py
Labels: bug, ready, v1

#21119 security policy: take 1
  SECURITY.md
Labels: documentation

#21837 [Bugfix] [Performance] DeepEPHighThroughput + DeepSeek : Quant before Dispatch
  vllm/model_executor/layers/fused_moe/deepep_ht_prepare_finalize.py
Labels: ready, deepseek

#20836 [compile][startup] Disable C++ compilation of symbolic shapes
  vllm/compilation/decorators.py
Labels: ready

#21970 Add lora test for tp>1 case for TPU.
  tests/tpu/lora/test_lora.py
Labels: tpu, ready

#21538 [BugFix] Harden distributed DP startup
  vllm/utils/__init__.py
  vllm/v1/engine/coordinator.py
  vllm/v1/engine/core.py
Labels: ready, v1

#21877 [CI] Initial tests for SM100 Blackwell runner
  .buildkite/test-pipeline.yaml
  tests/compile/test_fusion_all_reduce.py
  tests/kernels/quantization/test_cutlass_scaled_mm.py
Labels: ready, ci/build

#22036 [Perf] Optimize `reshape_and_cache_flash` CUDA Kernel
  benchmarks/kernels/benchmark_reshape_and_cache_flash.py
  csrc/cache_kernels.cu
Labels: performance, ready

#21733 feat: Add Support GPTQ Quantization MOE on ROCM vllm serve
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/gptq.py
Labels: rocm, ready

#21367 [V1][CUDA] Full cudagraph support for FlashInfer
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
  vllm/v1/attention/backends/triton_attn.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: rocm, ready, v1

#22066 [Model] Qwen2.5 VL SiLU-and-Mul
  vllm/model_executor/models/qwen2_5_vl.py
Labels: ready, qwen

#22101 [Misc] `VLLM_TARGET_DEVICE.lower()`
  vllm/envs.py
Labels: ready

#21617 [BugFix] Improve internal DP load balancing
  vllm/entrypoints/openai/api_server.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/coordinator.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/metrics/stats.py
  vllm/v1/utils.py
Labels: frontend, ready, v1

#21559 [Test] Add Unit Test for Batched DeepGEMM
  tests/kernels/moe/test_batched_deepgemm.py
  tests/kernels/moe/test_deepgemm.py
  vllm/utils/deep_gemm.py
Labels: ready, ci/build

#22069 [FEAT][ROCm] Enable running Flash Attention as ViT attn backend for Qwen-VL models on ROCm platform.
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/vision.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
Labels: rocm, ready, qwen

#22040 [Misc] Getting and passing ray runtime_env to workers
  tests/config/test_config_generation.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/executor/ray_utils.py
  vllm/ray/lazy_utils.py
  vllm/utils/__init__.py
Labels: ready

#22038 Fix test_kv_sharing_fast_prefill flakiness
  tests/v1/e2e/test_kv_sharing_fast_prefill.py
Labels: ready, v1

#22034 [Bugfix] Mamba2 remove bugged initial state condition in chunk scan
  vllm/model_executor/layers/mamba/ops/ssd_chunk_scan.py
Labels: ready

#20000 [PERF] Use faster way of decode in tokenizer: avoid useless list-to-list conversion
  vllm/transformers_utils/tokenizer.py
Labels: performance

#22000 for glm-4.1V update
  docs/models/supported_models.md
  tests/models/registry.py
  tests/tool_use/test_glm4_moe_tool_parser.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, ready, tool-calling

#21643 [xpu]support moe models on XPU platform
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#22123 [Misc] Bump ray to 2.48.0
  requirements/cuda.txt
  requirements/nightly_torch_test.txt
  requirements/test.in
  requirements/test.txt
Labels: ready, ci/build

#21754 [Misc] Add tensor schema test coverage for multimodal models
  .buildkite/test-pipeline.yaml
  tests/conftest.py
  tests/models/multimodal/test_tensor_schema.py
  tests/models/registry.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/keye.py
  vllm/transformers_utils/processors/deepseek_vl2.py
Labels: ready, ci/build, multi-modality, deepseek

#21309 Support CUTLASS NVFP4 (w4a4) for Blackwell Geforce GPUs (SM120)
  CMakeLists.txt
  csrc/quantization/fp4/nvfp4_blockwise_moe_kernel.cu
  csrc/quantization/fp4/nvfp4_quant_entry.cu
  csrc/quantization/fp4/nvfp4_quant_kernels.cu
  csrc/quantization/fp4/nvfp4_scaled_mm_entry.cu
  csrc/quantization/fp4/nvfp4_scaled_mm_sm120_kernels.cu
Labels: ready, ci/build

#21786 [executor] feat: add supports_pp attr to executors
  vllm/engine/arg_utils.py
  vllm/executor/executor_base.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/executor/ray_distributed_executor.py
Labels: ready, v1

#21980 [V1] [P/D] Refactor KV Connector Path
  tests/v1/kv_connector/unit/test_output_aggreagator.py
  tests/v1/kv_connector/unit/test_remote_decode_lifecycle.py
  tests/v1/kv_connector/unit/test_remote_prefill_lifecycle.py
  tests/v1/kv_connector/unit/utils.py
  vllm/distributed/kv_transfer/kv_connector/utils.py
  vllm/sequence.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/outputs.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
  vllm/v1/worker/kv_connector_model_runner_mixin.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#22145 [CI/Build][Bugfix] Fix Qwen2.5 tests in CPU CI via fallback silu_and_mul to torch native implementation
  vllm/model_executor/layers/activation.py
Labels: qwen

#21213 Add chat doc in quick start
  docs/getting_started/quickstart.md
Labels: documentation

#22143 fuse fp32 for GLM-4.5 e_score_correction_bias
  vllm/model_executor/models/glm4_moe.py
Labels: ready

#22153 [Bugfix] Fix failing multimodal standard test
  tests/models/multimodal/test_tensor_schema.py
  tests/models/registry.py
Labels: ready, multi-modality

#21981 Use `aiohttp` connection pool for benchmarking
  vllm/benchmarks/lib/endpoint_request_func.py
  vllm/benchmarks/lib/ready_checker.py
  vllm/benchmarks/serve.py
Labels: performance, ready

#22154 [fix] fix correct assertion syntax error in attention utils.
  vllm/v1/attention/backends/utils.py
Labels: v1

#22158 [RLHF] Fix torch.dtype not serializable in example
  examples/offline_inference/rlhf.py
  examples/offline_inference/rlhf_utils.py
Labels: documentation, ready

#21925 [PD] add test for chat completions endpoint
  tests/v1/kv_connector/nixl_integration/test_disagg_accuracy.py
  tests/v1/kv_connector/nixl_integration/toy_proxy_server.py
Labels: ready, v1

#22147 remove duplicate code within cleanup_dist_env_and_memory
  vllm/distributed/parallel_state.py
Labels: ready

#20401 Add tree attention backend for v1 (part 1)
  tests/v1/attention/test_attention_backends.py
  tests/v1/attention/utils.py
  tests/v1/spec_decode/test_eagle.py
  tests/v1/spec_decode/test_tree_attention.py
  vllm/attention/ops/triton_unified_attention.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/v1/attention/backends/tree_attn.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/spec_decode/eagle.py
Labels: speculative-decoding, ready, v1, llama

#22156 [refactor] improve ConstantList exception specificity
  vllm/v1/utils.py
Labels: ready, v1

#22105 Remove index_put from MM embeddings merging
  vllm/model_executor/models/utils.py
Labels: ready, v1

#22163 [CI Bugfix] Fix wNa16 kernel not found for test_shared_storage_connector_hashes
  tests/v1/kv_connector/unit/test_shared_storage_connector.py
Labels: ready, v1

#22174 [Bugfix] Fix failing GGUF models test
  vllm/transformers_utils/config.py
Labels: ready

#21792 [Sampler] Support returning all logprobs or logits
  tests/v1/sample/test_logprobs.py
  vllm/config.py
  vllm/sampling_params.py
  vllm/v1/engine/logprobs.py
  vllm/v1/engine/processor.py
  vllm/v1/worker/gpu_input_batch.py
Labels: ready, v1

#21725 Fix Arcee model weight loading: Add custom load_weights
  tests/models/registry.py
  vllm/model_executor/models/arcee.py
Labels: ready

#22185 [Responses API] Ignore `store=True` and process the request by default
  vllm/entrypoints/openai/serving_responses.py
  vllm/envs.py
Labels: frontend, ready

#21629 [Bug] Update auto_tune.sh to separate benchmarking and profiling.
  benchmarks/auto_tune/auto_tune.sh
Labels: performance, ready

#21819 [Bugfix][V1][P/D]Fix the uneven polling issue in the toy proxy for P2pNcclConnector
  examples/online_serving/disaggregated_serving_p2p_nccl_xpyd/disagg_proxy_p2p_nccl_xpyd.py
Labels: documentation, ready

#21173 [Bugfix] V1 Fix the cursor leakage issue during request scheduling.
  tests/v1/core/test_scheduler.py
  vllm/v1/core/sched/scheduler.py
Labels: bug, ready, v1

#21785 [V0 deprecation][P/D] Deprecate v0 `KVConnectorBase` code (1/2)
  .buildkite/test-pipeline.yaml
  tests/kv_transfer/test_disagg.py
  vllm/distributed/kv_transfer/kv_connector/base.py
  vllm/distributed/kv_transfer/kv_connector/factory.py
  vllm/distributed/kv_transfer/kv_connector/lmcache_connector.py
  vllm/distributed/kv_transfer/kv_connector/mooncake_store_connector.py
  vllm/distributed/kv_transfer/kv_connector/simple_connector.py
  vllm/distributed/kv_transfer/kv_connector/utils.py
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
  vllm/distributed/kv_transfer/kv_connector_agent.py
  vllm/distributed/kv_transfer/kv_transfer_state.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/worker/kv_connector_model_runner_mixin.py
Labels: ready, ci/build, v1

#22202 [ROCm][Bugfix] Compilation passes fix
  vllm/compilation/pass_manager.py
Labels: rocm, ready

#22149 fix: kimi_k2 return empty tool call list
  vllm/entrypoints/openai/tool_parsers/kimi_k2_tool_parser.py
Labels: frontend, ready, tool-calling

#22204 Optimize configuration access with LRU cache in custom ops
  vllm/config.py
  vllm/model_executor/custom_op.py
Labels: ready

#22226 [Bugfix] Misaligned params in TreeAttentionImpl
  vllm/v1/attention/backends/tree_attn.py
Labels: ready, v1

#22217 [UX] Fail if an invalid attention backend is specified
  tests/kernels/attention/test_attention_selector.py
  vllm/attention/selector.py
Labels: ready

#22228 [Core] Factor out common logic for MM budget calculation
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/utils.py
Labels: tpu, ready, v1

#20538 [Model] Pooling model activation supports per request control by PoolingParams
  tests/entrypoints/llm/test_classify.py
  tests/entrypoints/llm/test_embedding.py
  tests/entrypoints/llm/test_reward.py
  tests/entrypoints/llm/test_score.py
  tests/entrypoints/openai/test_classification.py
  tests/entrypoints/openai/test_embedding.py
  tests/entrypoints/openai/test_rerank.py
  tests/entrypoints/openai/test_score.py
  tests/models/language/pooling/test_override_pooler_config.py
  tests/models/language/pooling/test_reward.py
  tests/models/utils.py
  tests/test_pooling_params.py
  vllm/config.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/jina_vl.py
  vllm/model_executor/models/qwen2_rm.py
  vllm/pooling_params.py
Labels: frontend, ready, qwen

#22242 [Docs][TPU] Highlight TPU Software version selection
  docs/getting_started/installation/google_tpu.md
Labels: documentation, tpu

#22095 [NVIDIA] Support Flashinfer TRT-LLM Prefill Attention Kernel
  .buildkite/test-pipeline.yaml
  benchmarks/kernels/benchmark_trtllm_decode_attention.py
  benchmarks/kernels/benchmark_trtllm_prefill_attention.py
  tests/kernels/attention/test_flashinfer_trtllm_attention.py
  tests/kernels/attention/test_flashinfer_trtllm_decode_attention.py
  vllm/attention/backends/flashinfer.py
  vllm/envs.py
  vllm/utils/flashinfer.py
  vllm/v1/attention/backends/flashinfer.py
Labels: performance, ready, ci/build, v1

#21946 [Misc] correct static type check for GroupCoordinator
  vllm/distributed/device_communicators/ray_communicator.py
  vllm/distributed/eplb/eplb_state.py
  vllm/distributed/parallel_state.py
Labels: ready

#22271 [CI][TPU] Fix docker clean up
  .buildkite/scripts/hardware_ci/run-tpu-v1-test-part2.sh
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
  .buildkite/scripts/tpu/config_v6e_1.env
  .buildkite/scripts/tpu/docker_run_bm.sh
  .buildkite/scripts/tpu/quantized_v6e_1.env
Labels: tpu, ready, ci/build

#22286 [Bugfix] Remove faulty test for oot attention backend
  tests/plugins_tests/test_platform_plugins.py
Labels: ready

#22278 [Bugfix] Fix 3D input passed into cutlass_scaled_mm
  vllm/_custom_ops.py
Labels: bug, ready, ci-failure

#22264 [Bugfix][CI/Build][ROCm] Make sure to use the headers from the build folder on ROCm
  cmake/utils.cmake
Labels: rocm, ready, ci/build

#22313 Upgrade FA3 for attention sink
  cmake/external_projects/vllm_flash_attn.cmake
Labels: ci/build

#22316 Increase openai-python version
  requirements/common.txt
Labels: ci/build

#21931 Update transformers to `v4.55`
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
  tests/models/multimodal/generation/test_common.py
  tests/models/registry.py
  tests/quantization/test_experts_int8.py
  vllm/model_executor/models/interfaces_base.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/transformers.py
  vllm/model_executor/models/utils.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/ovis.py
Labels: ready, ci/build, multi-modality, qwen

#22327 Add GPT-OSS model code and config [1/N]
  tests/models/registry.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/gpt_oss.py
  vllm/model_executor/models/registry.py
Labels: new-model

#22332 [gpt-oss] Add openai-harmony as default dependency
  requirements/common.txt
Labels: ci/build

#22340 [gpt-oss] Add Tool/ConversationContext classes and harmony_utils
  vllm/entrypoints/context.py
  vllm/entrypoints/harmony_utils.py
  vllm/entrypoints/tool.py
Labels: frontend

#22342 [gpt-oss] Support chat completion api
  vllm/entrypoints/harmony_utils.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend

#22374 [gpt-oss] Add loop for built-in tool call
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_responses.py
Labels: frontend

#22335 [gpt-oss] attention sink init fix gemini
  vllm/v1/attention/backends/flashinfer.py
Labels: v1

#22378 Fix trtllm-gen attention env and add attention sink
  vllm/envs.py
  vllm/model_executor/models/gpt_oss.py
  vllm/utils/flashinfer.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/utils.py
Labels: v1

#22166 [model] Support MiniCPM-V 4.0
  docs/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/minicpmv.py
Labels: documentation, ready, ci/build, force-merge

#22273 Support encoder_only attention for FlexAttention
  tests/kernels/test_flex_attention.py
  vllm/v1/attention/backends/flex_attention.py
Labels: ready, v1

#22350 [XPU]Fix `flash_attn_varlen_func` interface on xpu
  vllm/_ipex_ops.py
Labels: ready

#21924 [Qwen3] Enable dual-chunk-attention support for Qwen3 models.
  vllm/model_executor/models/qwen3.py
  vllm/model_executor/models/qwen3_moe.py
Labels: ready-for-merge, ready, qwen

#22417 [Bugfix] Fix wrong method name in Intern-S1 image processor
  vllm/model_executor/models/interns1.py
Labels: ready

#22385 Use float32 for test_completion.py
  tests/v1/entrypoints/openai/test_completion.py
Labels: ready, v1

#22015 [Bugfix]: Fix the streaming output for function calls in the minimax
  tests/tool_use/test_minimax_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/minimax_tool_parser.py
Labels: frontend, ready, tool-calling

#22314 [Bugfix] Add proper comparison for package versions
  benchmarks/kernels/benchmark_bitblas.py
  docs/design/arch_overview.md
  vllm/attention/ops/triton_decode_attention.py
  vllm/model_executor/layers/quantization/bitblas.py
  vllm/model_executor/layers/quantization/bitsandbytes.py
  vllm/model_executor/layers/quantization/deepspeedfp.py
  vllm/model_executor/layers/quantization/gptq_bitblas.py
  vllm/model_executor/layers/quantization/ipex_quant.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/bitblas.py
  vllm/model_executor/layers/quantization/utils/bitblas_utils.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/model_executor/model_loader/bitsandbytes_loader.py
  vllm/v1/sample/ops/topk_topp_sampler.py
Labels: documentation, performance, ready, v1

#22356 Update `hf_xet` pin to resolve hangs
  requirements/common.txt
  requirements/nightly_torch_test.txt
  requirements/test.in
  requirements/test.txt
Labels: ready, ci/build

#22373 Optimize logger init performance by using module-level constants
  vllm/logger.py
Labels: ready

#22214 preload heavy modules when mp method is forkserver
  vllm/benchmarks/latency.py
  vllm/entrypoints/openai/api_server.py
Labels: performance, frontend, ready

#22167 [Bugfix] EPLB load statistics problem
  vllm/distributed/eplb/eplb_state.py
  vllm/model_executor/layers/fused_moe/layer.py
Labels: documentation, performance, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, qwen

#22099 [Frontend] Update OpenAI error response to upstream format
  tests/entrypoints/openai/test_classification.py
  tests/entrypoints/openai/test_lora_resolvers.py
  tests/entrypoints/openai/test_serving_models.py
  tests/entrypoints/openai/test_transcription_validation.py
  tests/entrypoints/openai/test_translation_validation.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_models.py
Labels: frontend, ready

#21990 [Misc] Support routing logic simulation
  tests/test_routing_simulator.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/routing_simulator.py
Labels: ready

#21578 [Docs] Factor out troubleshooting to its own guide; add section for Ray Observability
  docs/serving/distributed_serving.md
  docs/serving/distributed_troubleshooting.md
Labels: documentation, force-merge

#12022 [Doc] update docs for nightly benchmarks
  .buildkite/nightly-benchmarks/README.md
Labels: performance, ci/build, unstale, force-merge

#22165 [Docs] Update features/disagg_prefill, add v1 examples and development
  docs/assets/features/disagg_prefill/high_level_design.png
  docs/assets/features/disagg_prefill/workflow.png
  docs/features/disagg_prefill.md
Labels: documentation

#22198 [Core] Store only the keys for multi-modal data in P0
  docs/configuration/conserving_memory.md
  docs/configuration/optimization.md
  examples/offline_inference/mistral-small.py
  examples/offline_inference/vision_language.py
  tests/models/utils.py
  tests/multimodal/test_cache.py
  tests/multimodal/test_processing.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/cli/serve.py
  vllm/envs.py
  vllm/multimodal/cache.py
  vllm/multimodal/processing.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/engine/core.py
  vllm/v1/engine/mm_input_cache.py
  vllm/v1/engine/processor.py
Labels: documentation, frontend, ready, v1, multi-modality

#22352 [Bugfix] Add missing `packed_modules_mapping` to `DeepseekV2ForCausalLM`
  vllm/model_executor/models/deepseek_v2.py
Labels: ready, deepseek

#22457 [Core] Simplify mm processing cache
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/transformers.py
  vllm/multimodal/processing.py
  vllm/v1/serial_utils.py
Labels: ready, v1, multi-modality, qwen

#22451 Remove `from_dict` from `SpeculativeConfig`
  tests/v1/spec_decode/test_ngram.py
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: speculative-decoding, ready, v1

#21496 [ROCm] [V1] [SpecDec] Enable Speculative Decoding on ROCm V1 Engine
  tests/utils.py
  tests/v1/attention/utils.py
  tests/v1/e2e/test_spec_decode.py
  tests/v1/spec_decode/test_eagle.py
  tests/v1/spec_decode/test_max_len.py
  vllm/v1/spec_decode/eagle.py
Labels: rocm, speculative-decoding, ready, v1

#22469 [PERF] Use pybase64 to more quickly decode prompt embeddings
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend

#20101 Add ModelOpt Qwen3 nvfp4 support
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen3_moe.py
Labels: ready, qwen

#21963 Fix Flashinfer CUTLASS MOE Allgather
  vllm/distributed/device_communicators/cuda_communicator.py
  vllm/forward_context.py
  vllm/model_executor/layers/fused_moe/flashinfer_cutlass_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/layer.py
Labels: bug, ready, deepseek

#22131 [Kernel] Add support for block FP8 on SM120 (NVIDIA 5090 and RTX PRO 6000)
  CMakeLists.txt
  csrc/cutlass_extensions/common.hpp
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm120_fp8.cu
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm120_fp8_dispatch.cuh
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_kernels.hpp
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x_sm120.cu
Labels: ready, ci/build

#22065 [Bugfix] Fix RuntimeError: Index put requires the source and destination dtypes match
  tests/v1/entrypoints/openai/test_completion_with_image_embeds.py
  vllm/model_executor/models/utils.py
Labels: ready, v1

#22382 [bench] Fix benchmark/serve.py to ignore unavailable results
  vllm/benchmarks/serve.py
Labels: performance

#22491 [CI/Build] Fix multimodal tests
  vllm/engine/llm_engine.py
  vllm/multimodal/registry.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/llm_engine.py
Labels: ready, v1, multi-modality

#22485 [Misc] fix openai version
  requirements/common.txt
Labels: ready, ci/build

#22459 [Docs] Improve API docs (+small tweaks)
  docs/.nav.yml
  docs/api/summary.md
  docs/features/quantization/inc.md
  docs/mkdocs/hooks/generate_examples.py
  mkdocs.yaml
Labels: documentation

#22506 Remove exception for Python 3.8 typing from linter
  pyproject.toml
  vllm/utils/__init__.py
Labels: ready

#20267 [Benchmark] Add benchmark tool for multi turn conversations
  benchmarks/multi_turn/README.md
  benchmarks/multi_turn/bench_dataset.py
  benchmarks/multi_turn/bench_utils.py
  benchmarks/multi_turn/benchmark_serving_multi_turn.py
  benchmarks/multi_turn/convert_sharegpt_to_openai.py
  benchmarks/multi_turn/generate_multi_turn.json
  benchmarks/multi_turn/requirements.txt
Labels: performance, ready

#22466 [Docs] Rename “Distributed inference and serving” to “Parallelism & Scaling”
  docs/models/supported_models.md
  docs/serving/parallelism_scaling.md
  docs/usage/troubleshooting.md
Labels: documentation, ready

#22427 [gpt-oss] Support tool call and implement MCP tool server
  vllm/entrypoints/harmony_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/serving_responses.py
  vllm/entrypoints/tool_server.py
Labels: frontend, v1

#22215 [Misc] DeepGEMM : Avoid JIT generation in the hot-path
  vllm/model_executor/layers/fused_moe/deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/warmup/deep_gemm_warmup.py
  vllm/model_executor/warmup/kernel_warmup.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#18097 [Frontend] Add unix domain socket support
  docs/cli/README.md
  tests/entrypoints/openai/test_uds.py
  tests/utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
Labels: documentation, frontend, ready

#22524 Extract `CompilationConfig` from `config.py`
  tests/engine/test_arg_utils.py
  vllm/config/__init__.py
  vllm/config/compilation.py
  vllm/config/utils.py
  vllm/engine/arg_utils.py
Labels: ready

#22300 [XPU] upgrade torch 2.8 on for XPU
  docker/Dockerfile.xpu
  requirements/xpu.txt
  vllm/plugins/__init__.py
  vllm/v1/worker/xpu_worker.py
Labels: ready, ci/build, v1

#21901 [Bugfix] Fix ModernBert cuda graph capturing in v1
  tests/models/language/pooling/mteb_utils.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/bert_with_rope.py
  vllm/model_executor/models/modernbert.py
  vllm/model_executor/models/roberta.py
Labels: ready

#22299 Implicit language-model-only mode via limit-mm-per-prompt
  tests/multimodal/test_registry.py
  vllm/config/__init__.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/mistral3.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/step3_vl.py
  vllm/multimodal/registry.py
  vllm/v1/core/encoder_cache_manager.py
  vllm/v1/engine/core.py
  vllm/v1/engine/mm_input_cache.py
  vllm/v1/engine/processor.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, ci/build, v1, multi-modality, llama, qwen

#22194 [Log] Add Warning for Deprecation of DeepGEMM old version
  vllm/utils/deep_gemm.py
Labels: ready

#22151 [V1] [Hybrid] Support Minimax-Text-01 in V1
  vllm/model_executor/layers/lightning_attn.py
  vllm/model_executor/layers/mamba/mamba_utils.py
  vllm/model_executor/models/minimax_text_01.py
  vllm/v1/attention/backends/linear_attn.py
  vllm/v1/attention/backends/mamba_selectors.py
Labels: ready, v1

#21913 [Misc] Use config definitions from Transformers library
  vllm/model_executor/models/aimv2.py
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/dbrx.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/dots1.py
  vllm/model_executor/models/exaone4.py
  vllm/model_executor/models/glm4_moe.py
  vllm/model_executor/models/minimax_text_01.py
  vllm/model_executor/models/olmoe.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/qwen3_moe.py
Labels: ready, qwen, deepseek

#22463 Fix loading of quantized BigCode models
  vllm/model_executor/models/gpt_bigcode.py
Labels: ready

#22097 [ROCm][Misc] Rename the context_len to seq_len in ROCm custom paged attention kernel
  csrc/rocm/attention.cu
  csrc/rocm/ops.h
  csrc/rocm/torch_bindings.cpp
Labels: rocm, ready

#22557 [Bugfix] Fix failing GPT-OSS initialization test
  tests/models/registry.py
  tests/models/test_initialization.py
Labels: ready

#22562 Update docs for Minimax-Text support
  docs/models/supported_models.md
  docs/usage/v1_guide.md
Labels: documentation, rocm

#22520 GLM-4.5V with new class name at transformers
  docs/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/glm4_moe.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/config.py
Labels: documentation, new-model, ready

#22563 [CI] [Hybrid] Speed up hybrid models test by removing large models
  tests/models/language/generation/test_hybrid.py
Labels: ready

#22567 [Docs] Reduce noise in docs and `--help` from the JSON tip
  docs/cli/README.md
  docs/configuration/engine_args.md
  vllm/engine/arg_utils.py
  vllm/utils/__init__.py
Labels: documentation, frontend

#22565 Move `ParallelConfig` from `config/__init__.py` to `config/parallel.py`
  .github/CODEOWNERS
  vllm/config/__init__.py
  vllm/config/compilation.py
  vllm/config/parallel.py
Labels: ready, ci/build

#20495 [Model] Gemma3n MM
  docs/models/supported_models.md
  examples/offline_inference/audio_language.py
  examples/offline_inference/vision_language.py
  requirements/test.in
  requirements/test.txt
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  tests/test_test.py
  vllm/model_executor/models/gemma3n.py
  vllm/model_executor/models/gemma3n_mm.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, frontend, ready, ci/build, multi-modality, qwen

#21401 [V1] [Hybrid] Enable Full CUDA Graph (decode-only) for Mamba layers
  tests/models/language/generation/test_hybrid.py
  vllm/v1/attention/backends/mamba_attn.py
Labels: rocm, ready, v1

#22508 [oss] Init gpt-oss bf16 support
  vllm/model_executor/layers/fused_moe/config.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/models/gpt_oss.py
Labels: performance, ready, deepseek

#22394 [TPU] kv cache update kernel doesn't need to be padded slices to multiple of num_slices_per_block
  tests/v1/tpu/test_kv_cache_update_kernel.py
  vllm/attention/ops/pallas_kv_cache_update.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#22579 [Minor] Fix pre-commit error on main
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#22566 [Misc] code clean duplicate set_current_vllm_config in _set_vllm_config
  tests/kernels/moe/modular_kernel_tools/parallel_utils.py
Labels: ready

#22585 [Doc] Fix API doc link in side navigation
  docs/.nav.yml
Labels: documentation

#22499 [Misc] Further refine type annotations in parallel state
  vllm/distributed/eplb/eplb_state.py
  vllm/distributed/parallel_state.py
Labels: ready

#22588 [Docs] Fix warnings in docs build
  docs/api/summary.md
  docs/configuration/tpu.md
  docs/contributing/model/multimodal.md
  docs/models/generative_models.md
  docs/models/pooling_models.md
  docs/models/supported_models.md
  vllm/attention/layers/__init__.py
  vllm/inputs/__init__.py
  vllm/model_executor/warmup/__init__.py
  vllm/sampling_params.py
Labels: documentation

#22574 [Misc] Replace flaky image urls in pixtral test
  tests/models/multimodal/generation/test_pixtral.py
  tests/models/utils.py
Labels: ready, multi-modality
