Repository vllm-project/vllm, pull requests merged in 2025-07, with the labels that each got.

#15897 [Doc] add config and troubleshooting guide for NCCL & GPUDirect RDMA
  docs/serving/distributed_serving.md
  docs/usage/troubleshooting.md
Labels: documentation

#19516 [V1] Only print cudagraph tqdm on rank 0 with `is_global_first_rank`
  vllm/distributed/parallel_state.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#20268 Enable ZP Support for Machete
  benchmarks/kernels/benchmark_machete.py
  tests/kernels/quantization/test_machete_mm.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/machete.py
Labels: performance, ready

#20255 [CPU] Update custom ops for the CPU backend
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
  cmake/cpu_extension.cmake
  csrc/cpu/sgl-kernels/common.h
  csrc/cpu/sgl-kernels/gemm.cpp
  csrc/cpu/sgl-kernels/gemm.h
  csrc/cpu/sgl-kernels/gemm_fp8.cpp
  csrc/cpu/sgl-kernels/gemm_int8.cpp
  csrc/cpu/sgl-kernels/moe.cpp
  csrc/cpu/sgl-kernels/moe_fp8.cpp
  csrc/cpu/sgl-kernels/moe_int8.cpp
  csrc/cpu/sgl-kernels/vec.h
  csrc/cpu/shm.cpp
  csrc/cpu/torch_bindings.cpp
  docs/getting_started/installation/cpu.md
  tests/models/language/generation/test_common.py
  vllm/_custom_ops.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/cpu_fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/utils.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
  vllm/platforms/cpu.py
Labels: documentation, ready, ci/build

#20288 [Bugfix] Fix deepep tests
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  tests/kernels/moe/test_deepep_moe.py
Labels: ready

#20289 [doc] fix the incorrect logo in dark mode
  docs/README.md
  docs/mkdocs/stylesheets/extra.css
Labels: documentation, ready

#20200 [Perf] Validate @config in pre-commit instead of dynamically
  .pre-commit-config.yaml
  tests/test_config.py
  tests/tools/__init__.py
  tests/tools/test_config_validator.py
  tools/validate_config.py
  vllm/config.py
Labels: ready

#20068 [Misc] Minor refactor of NIXL background handshake
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
Labels: ready

#20114 [Model]Add Tencent HunYuanMoEV1 Model Support
  docs/models/supported_models.md
  tests/models/registry.py
  tests/models/test_initialization.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/hunyuan_v1_moe.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready, ci/build

#20301 [CUDA graphs] Enable full cuda graphs with FA3 AoT scheduling
  cmake/external_projects/vllm_flash_attn.cmake
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, ci/build, v1

#20291 [Optimization] Cache sampled token ids in model runner
  tests/v1/worker/test_gpu_model_runner.py
  vllm/distributed/kv_transfer/kv_connector/v1/shared_storage_connector.py
  vllm/v1/core/sched/output.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#20236 remove unused variables in marlin_template.h
  csrc/moe/marlin_moe_wna16/marlin_template.h
  csrc/quantization/gptq_marlin/marlin_template.h
Labels: ready

#20269 [Refactor] Refactor import utils
  pyproject.toml
  tests/build_cython.py
  tools/check_pickle_imports.py
  vllm/utils/__init__.py
Labels: ready

#20290 Enable group size 64 for Machete
  tests/kernels/quantization/test_machete_mm.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/machete.py
  vllm/model_executor/layers/quantization/utils/machete_utils.py
Labels: ready

#20333 [Refactor] Remove duplicate `find_free_port`
  tests/kernels/moe/utils.py
  vllm/model_executor/layers/fused_moe/utils.py
Labels: ready

#20285 [Misc][Doc] Add missing comment for LLM
  vllm/entrypoints/llm.py
Labels: frontend

#20230 [Doc][TPU] Add models and features supporting matrix.
  docs/.nav.yml
  docs/features/compatibility_matrix.md
  docs/models/hardware_supported_models/tpu.md
Labels: documentation, ready

#20105 [Frontend] Support configurable mm placeholder strings & flexible video sampling policies via CLI flags.
  tests/async_engine/test_async_llm_engine.py
  tests/engine/test_arg_utils.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/multimodal/test_utils.py
  tests/multimodal/test_video.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/chat_utils.py
  vllm/multimodal/audio.py
  vllm/multimodal/image.py
  vllm/multimodal/utils.py
  vllm/multimodal/video.py
Labels: frontend, ready, multi-modality

#20126 [Model][VLM] Support Keye-VL-8B-Preview
  docs/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/registry.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/keye.py
  vllm/model_executor/models/registry.py
Labels: documentation, frontend, ready

#20352 [Docs] Fix indentations for 2-level items in deprecation_policy.md
  docs/contributing/deprecation_policy.md
Labels: documentation

#20220 [Model] Add Ernie4.5 and Ernie4.5MoE Model Support
  docs/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/ernie45.py
  vllm/model_executor/models/ernie45_moe.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, ready

#20382 [Minor] Clean up incorrect comment in test
  tests/engine/test_options.py
Labels: ready

#20369 [Misc] add handler HF_TOKEN is emptry string
  vllm/transformers_utils/config.py
Labels: ready

#20254 [ROCm][FEAT] Enable Full Graph Mode in AITER MLA V1 Attn Backend (Decode Phase only)
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
Labels: rocm, ready, v1

#20375 [Docs] Update EAGLE example
  docs/features/spec_decode.md
Labels: documentation, ready

#20136 [Bugfix] Fixes for FlashInfer's TORCH_CUDA_ARCH_LIST
  docker/Dockerfile
Labels: ready, ci/build

#20381 [Bugfix] Fix import of CutlassExpertsFp8 in compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready

#20389 [Misc] Small: Fix video loader return type annotations.
  tests/multimodal/test_utils.py
  vllm/multimodal/utils.py
  vllm/multimodal/video.py
Labels: ready, multi-modality

#20385 [TPU] Add a case to cover RedHatAI/Meta-Llama-3.1-8B-Instruct-quantized.w8a8
  .buildkite/scripts/tpu/quantized_v6e_1.env
Labels: tpu, ready, ci/build, llama

#20297 [Feature] Support MiniMax-M1 function calls features
  docs/features/tool_calling.md
  examples/tool_chat_template_minimax_m1.jinja
  tests/tool_use/test_minimax_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/minimax_tool_parser.py
Labels: documentation, frontend, ready, tool-calling

#20406 [Misc] Add rules to label Speculative Decoding Related PRs
  .github/mergify.yml
Labels: ci/build

#20417 [doc] fix link
  examples/offline_inference/profiling_tpu/README.md
Labels: documentation, tpu

#20363 [Bugfix] Fix flaky `test_streaming_response` test
  requirements/common.txt
Labels: ready, ci/build

#20390 [CI] Trimming some failing test groups from AMDPRODUCTION.
  .buildkite/test-pipeline.yaml
Labels: rocm, ci/build

#20107 [Misc] adjust for ipv6 for mookcacke url parse
  tests/test_utils.py
  vllm/distributed/kv_transfer/kv_pipe/mooncake_pipe.py
  vllm/utils/__init__.py
Labels: ready

#20432 [Misc] Remove _maybe_ignore_quant_config from GLM4.1v
  vllm/model_executor/models/glm4_1v.py
Labels: ready

#18864 [Kernel] Enable fp8 support for pplx and BatchedTritonExperts.
  tests/kernels/moe/parallel_utils.py
  tests/kernels/moe/test_batched_moe.py
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  tests/kernels/moe/test_deepep_moe.py
  tests/kernels/moe/test_pplx_cutlass_moe.py
  tests/kernels/moe/test_pplx_moe.py
  tests/kernels/moe/utils.py
  tests/kernels/quant_utils.py
  tests/kernels/utils.py
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_triton_or_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/config.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/deepep_ht_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/deepep_ll_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/fused_batched_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/modular_kernel.py
  vllm/model_executor/layers/fused_moe/pplx_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/prepare_finalize.py
  vllm/model_executor/layers/fused_moe/utils.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/models/qwen3_moe.py
Labels: performance, ready, v1, qwen

#20400 [Misc] Fix `Unable to detect current VLLM config. Defaulting to NHD kv cache layout` warning
  vllm/distributed/kv_transfer/kv_connector/utils.py
  vllm/v1/attention/backends/utils.py
Labels: ready, v1

#20455 Change warn_for_unimplemented_methods to debug
  vllm/utils/__init__.py
Labels: ready

#20420 Add ignore consolidated file in mistral example code
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
Labels: documentation, ready

#20365 [Structured Outputs][V1] Skipping with models doesn't contain tokenizers
  tests/v1/core/test_scheduler.py
  tests/v1/engine/test_llm_engine.py
  vllm/v1/engine/processor.py
  vllm/v1/structured_output/__init__.py
Labels: structured-output, ready, v1

#20331 [Perf] Optimize Vectorization Utils for Int 8 Quantization Kernels
  csrc/quantization/compressed_tensors/int8_quant_kernels.cu
  csrc/quantization/vectorization_utils.cuh
Labels: performance, ready

#20428 [Misc] Add SPDX-FileCopyrightText
  benchmarks/kernels/bench_fp8_gemm.py
  examples/offline_inference/spec_decode.py
  examples/online_serving/disaggregated_serving_p2p_nccl_xpyd/disagg_proxy_p2p_nccl_xpyd.py
  examples/online_serving/multi_instance_data_parallel.py
  examples/online_serving/openai_chat_completion_client_with_tools_xlam.py
  examples/online_serving/openai_chat_completion_client_with_tools_xlam_streaming.py
  tests/compile/test_fusion_attn.py
  tests/kernels/moe/parallel_utils.py
  tests/kernels/moe/test_deepep_deepgemm_moe.py
  tests/kernels/moe/test_deepep_moe.py
  tests/kernels/moe/test_deepgemm.py
  tests/kernels/test_apply_repetition_penalties.py
  tests/kernels/test_flex_attention.py
  tests/models/language/pooling/test_intfloat.py
  tests/quantization/test_rtn.py
  tests/tool_use/test_minimax_tool_parser.py
  tests/tool_use/test_xlam_tool_parser.py
  tests/v1/sample/test_logits_processors.py
  tests/v1/test_request.py
  tests/v1/tpu/test_spmd_model_weight_loading.py
  tests/v1/tpu/test_tpu_qkv_linear.py
  tools/check_pickle_imports.py
  tools/check_spdx_header.py
  vllm/compilation/fusion_attn.py
  vllm/distributed/eplb/__init__.py
  vllm/distributed/eplb/eplb_state.py
  vllm/distributed/eplb/rebalance_algo.py
  vllm/distributed/eplb/rebalance_execute.py
  vllm/distributed/kv_transfer/kv_connector/v1/p2p/p2p_nccl_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/p2p/p2p_nccl_engine.py
  vllm/distributed/kv_transfer/kv_connector/v1/p2p/tensor_memory_pool.py
  vllm/distributed/tpu_distributed_utils.py
  vllm/entrypoints/openai/tool_parsers/xlam_tool_parser.py
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/batched_triton_or_deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/cpu_fused_moe.py
  vllm/model_executor/layers/fused_moe/deepep_ht_prepare_finalize.py
  vllm/model_executor/layers/fused_moe/deepep_ll_prepare_finalize.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w4a4_nvfp4.py
  vllm/model_executor/layers/quantization/deepgemm.py
  vllm/model_executor/layers/quantization/rtn.py
  vllm/model_executor/model_loader/tpu.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/dots1.py
  vllm/model_executor/models/glm4_1v.py
  vllm/model_executor/models/tarsier.py
  vllm/transformers_utils/configs/nemotron_h.py
  vllm/v1/attention/backends/cpu_attn.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/attention/backends/mla/cutlass_mla.py
  vllm/v1/attention/backends/rocm_aiter_fa.py
  vllm/v1/core/kv_cache_coordinator.py
  vllm/v1/pool/metadata.py
  vllm/v1/sample/logits_processor.py
  vllm/v1/worker/cpu_model_runner.py
  vllm/v1/worker/cpu_worker.py
  vllm/v1/worker/xpu_model_runner.py
  vllm/v1/worker/xpu_worker.py
Labels: documentation, performance, frontend, tpu, speculative-decoding, ready, v1, tool-calling

#20168 [Model][3/N] Automatic conversion of CrossEncoding model
  docs/models/supported_models.md
  tests/models/language/pooling/test_embedding.py
  tests/models/language/pooling/test_gte.py
  tests/models/language/pooling/test_mxbai_rerank.py
  vllm/config.py
  vllm/model_executor/models/adapters.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/qwen3.py
Labels: documentation, qwen

#19757 [feat]: CUTLASS block scaled group gemm for SM100
  CMakeLists.txt
  csrc/cutlass_extensions/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp
  csrc/ops.h
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm.cuh
  csrc/quantization/cutlass_w8a8/moe/blockwise_scaled_group_mm_sm100.cu
  csrc/quantization/machete/machete_mainloop.cuh
  csrc/sparse/cutlass/sparse_scaled_mm_c3x.cuh
  csrc/torch_bindings.cpp
  tests/kernels/moe/test_cutlass_grouped_gemm.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready, ci/build

#20502 [CI Bugfix] Fix pre-commit failures on main
  tests/kernels/moe/test_cutlass_grouped_gemm.py
  vllm/multimodal/utils.py
Labels: ready, multi-modality, ci-failure

#20497 [Doc] fix mutltimodal_inputs.md gh examples link
  docs/features/multimodal_inputs.md
Labels: documentation

#20508 [Misc] Add security warning for development mode endpoints
  vllm/entrypoints/openai/api_server.py
Labels: frontend

#20494 [Misc] Remove the unused LoRA test code
  tests/lora/conftest.py
  vllm/multimodal/utils.py
Labels: ready, multi-modality

#20507 Fix unknown attribute of topk_indices_dtype in CompressedTensorsW8A8Fp8MoECutlassMethod
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
Labels: ready

#19754 [v1] Re-add fp32 support to v1 engine through FlexAttention
  .github/workflows/lint-and-deploy.yaml
  tests/kernels/attention/test_attention_selector.py
  tests/v1/worker/test_gpu_model_runner.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/tensorizer_loader.py
  vllm/platforms/cuda.py
  vllm/v1/attention/backends/flex_attention.py
  vllm/v1/sample/ops/topk_topp_sampler.py
Labels: ready, ci/build, v1

#20487 test_attention compat with coming xformers change
  tests/kernels/attention/test_attention.py
Labels: ready

#20491 [BUG] Fix #20484. Support empty sequence in cuda penalty kernel
  csrc/sampler.cu
  tests/kernels/test_apply_repetition_penalties.py
Labels: ready

#20509 [Bugfix] Fix missing per_act_token parameter in compressed_tensors_moe
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
Labels: ready

#20513 [BugFix] Fix: ImportError when building on hopper systems
  .github/CODEOWNERS
  csrc/ops.h
  csrc/quantization/cutlass_w8a8/moe/blockwise_scaled_group_mm_sm100.cu
  csrc/torch_bindings.cpp
Labels: ready, ci/build

#20339 [TPU][Bugfix] fix the MoE OOM issue
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#20518 [Misc] call the pre-defined func
  vllm/entrypoints/openai/tool_parsers/deepseekv3_tool_parser.py
  vllm/entrypoints/openai/tool_parsers/xlam_tool_parser.py
Labels: frontend, ready, tool-calling, deepseek

#20412 [V0 deprecation] Remove V0 CPU/XPU/TPU backends
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
  .buildkite/scripts/hardware_ci/run-xpu-test.sh
  examples/online_serving/chart-helm/values.yaml
  tests/kernels/attention/test_attention_selector.py
  vllm/attention/backends/cpu_mla.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/torch_sdpa.py
  vllm/platforms/cpu.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_pooling_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/multi_step_tpu_worker.py
  vllm/worker/tpu_model_runner.py
  vllm/worker/tpu_worker.py
  vllm/worker/xpu_model_runner.py
  vllm/worker/xpu_worker.py
Labels: documentation, performance, structured-output, frontend, tpu, speculative-decoding, ready, ci/build, v1, multi-modality, tool-calling, qwen

#20530 [BugFix][Spec Decode] Fix spec token ids in model runner
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#20527 [Bugfix] Add `use_cross_encoder` flag to use correct activation in `ClassifierPooler`
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_score.py
  vllm/model_executor/layers/pooler.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/roberta.py
  vllm/pooling_params.py
  vllm/transformers_utils/config.py
Labels: frontend, ready

#20504 Implement OpenAI Responses API [1/N]
  tests/entrypoints/openai/test_openai_schema.py
  tests/v1/entrypoints/openai/responses/__init__.py
  tests/v1/entrypoints/openai/responses/conftest.py
  tests/v1/entrypoints/openai/responses/test_basic.py
  tests/v1/entrypoints/openai/responses/test_stateful.py
  tests/v1/entrypoints/openai/responses/test_structured_output.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_responses.py
  vllm/reasoning/abs_reasoning_parsers.py
Labels: frontend, ready, v1

#19410 [Refactor]Abstract Platform Interface for Distributed Backend and Add xccl Support for Intel XPU
  docs/getting_started/installation/gpu/xpu.inc.md
  vllm/platforms/__init__.py
  vllm/platforms/cpu.py
  vllm/platforms/cuda.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
  vllm/utils/__init__.py
  vllm/v1/worker/cpu_worker.py
  vllm/v1/worker/gpu_worker.py
  vllm/v1/worker/tpu_worker.py
  vllm/worker/hpu_worker.py
  vllm/worker/neuron_worker.py
  vllm/worker/worker.py
Labels: documentation, rocm, tpu, ready, v1

#20537 [XPU][CI] add v1/core test in xpu hardware ci
  .buildkite/scripts/hardware_ci/run-xpu-test.sh
  docker/Dockerfile.xpu
  vllm/platforms/xpu.py
Labels: ready, ci/build

#20545 Add docstrings to url_schemes.py to improve readability
  docs/mkdocs/hooks/url_schemes.py
Labels: documentation, ready

#20552 [Docs] Clean up tables in supported_models.md
  docs/models/supported_models.md
Labels: documentation

#18878 [Misc] remove unused jinaai_serving_reranking
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready

#20539 [Misc] Set the minimum openai version
  requirements/common.txt
Labels: ready, ci/build

#20565 [Doc] Remove extra whitespace from CI failures doc
  docs/contributing/ci-failures.md
Labels: documentation

#20563 [Doc] Fix internal links so they don't always point to latest
  docs/features/structured_outputs.md
Labels: documentation, structured-output

#20571 [Doc] Add outline for content tabs
  docs/mkdocs/stylesheets/extra.css
Labels: documentation

#20572 [Doc] Fix some MkDocs snippets used in the installation docs
  docs/getting_started/installation/cpu/apple.inc.md
  docs/getting_started/installation/cpu/arm.inc.md
  docs/getting_started/installation/cpu/s390x.inc.md
  docs/getting_started/installation/cpu/x86.inc.md
  docs/getting_started/installation/gpu.md
  docs/getting_started/installation/gpu/cuda.inc.md
  docs/getting_started/installation/gpu/rocm.inc.md
  docs/getting_started/installation/gpu/xpu.inc.md
Labels: documentation

#20486 [Bugfix] Prevent IndexError for cached requests when pipeline parallelism is disabled
  vllm/v1/core/sched/scheduler.py
Labels: v1

#19334 [Feature] microbatch tokenization
  tests/entrypoints/openai/test_serving_chat.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/utils/__init__.py
Labels: frontend, ready, qwen

#20308 [Kernel] Optimize Prefill Attention in Unified Triton Attention Kernel
  vllm/attention/ops/triton_unified_attention.py
Labels: ready

#19608 [Misc] feat output content in stream response
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready, qwen

#18615 Fix links in multi-modal model contributing page
  docs/contributing/model/multimodal.md
  vllm/model_executor/models/interfaces.py
Labels: documentation, ready

#20570 [Config] Refactor mistral configs
  vllm/model_executor/models/llama.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/mistral.py
Labels: ready, llama

#20573 [Misc] Improve logging for dynamic shape cache compilation
  vllm/compilation/backends.py
Labels: ready

#20167 [Bugfix] Fix Maverick correctness by filling zero to cache space in cutlass_moe
  tests/kernels/moe/test_cutlass_moe.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
Labels: ready

#19209 [Bugfix]: Fix messy code when using logprobs
  tests/test_utils.py
  tests/v1/engine/test_output_processor.py
  vllm/transformers_utils/detokenizer_utils.py
Labels: frontend, ready, v1

#20582 [Doc] Syntax highlight request responses as JSON instead of bash
  docs/serving/openai_compatible_server.md
Labels: documentation

#20594 [Docs] Rewrite offline inference guide
  docs/serving/offline_inference.md
Labels: documentation

#20597 [Docs] Improve docstring for ray data llm example
  examples/offline_inference/batch_llm_inference.py
Labels: documentation

#20595 [Docs] Add Ray Serve LLM section to openai compatible server guide
  docs/serving/openai_compatible_server.md
Labels: documentation

#20604 [Misc] improve error msg
  vllm/entrypoints/cli/serve.py
Labels: frontend, ready

#20560 [CI/Build][CPU] Fix CPU CI and remove all CPU V0 files
  .buildkite/scripts/hardware_ci/run-cpu-test.sh
  tests/basic_correctness/test_chunked_prefill.py
  tests/models/language/generation/test_common.py
  tests/models/language/pooling/test_embedding.py
  tests/models/language/pooling/test_reward.py
  tests/quantization/test_compressed_tensors.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/ops/ipex_attn.py
  vllm/v1/attention/backends/cpu_attn.py
Labels: ci/build, v1

#20278 [TPU] Temporary fix vmem oom for long model len by reducing page size
  vllm/v1/attention/backends/pallas.py
Labels: tpu, ready, v1

#19619 [Frontend] [Core] Integrate Tensorizer in to S3 loading machinery, allow passing arbitrary arguments during save/load
  examples/others/tensorize_vllm_model.py
  requirements/nightly_torch_test.txt
  requirements/rocm.txt
  requirements/test.in
  requirements/test.txt
  setup.py
  tests/entrypoints/openai/test_tensorizer_entrypoint.py
  tests/lora/test_llama_tp.py
  tests/tensorizer_loader/conftest.py
  tests/tensorizer_loader/test_tensorizer.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/lora/models.py
  vllm/lora/peft_helper.py
  vllm/model_executor/model_loader/tensorizer.py
  vllm/model_executor/model_loader/tensorizer_loader.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/model_runner.py
Labels: documentation, rocm, ready, dependencies, ci/build, v1, llama

#20139 [PD][Nixl] Remote consumer READ timeout for clearing request blocks
  tests/v1/kv_connector/unit/test_nixl_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/envs.py
Labels: ready, v1

#20589 Update torch/xla pin to 20250703
  requirements/tpu.txt
Labels: ready, ci/build

#20631 [Model] Implement missing `get_language_model` for Keye-VL
  vllm/model_executor/models/keye.py
Labels: ready

#20618 Revert invalid spellchecker fix on deepseek_vl2
  vllm/model_executor/models/deepseek_vl2.py
Labels: ready, deepseek

#20166 [Bugfix] Fix topk_ids indices_type for CUTLASS w8a8 FP8 MoE
  csrc/quantization/cutlass_w8a8/moe/moe_data.cu
  vllm/model_executor/layers/fused_moe/pplx_prepare_finalize.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
Labels: ready

#20635 [Bugfix] Fix GLM-4.1-V video prompt update
  vllm/model_executor/models/glm4_1v.py
Labels: ready

#20632 [TPU][Bugfix] disable phi-3 test
  tests/v1/tpu/test_basic.py
Labels: tpu, ready, v1

#20636 [tech debt] Revisit lora request model checker
  tests/entrypoints/openai/test_serving_models.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_models.py
Labels: frontend, ready

#20554 [Hardware][PPC64LE] Enable V1 for ppc64le and ARM
  vllm/engine/arg_utils.py
  vllm/platforms/cpu.py
  vllm/v1/attention/backends/cpu_attn.py
  vllm/v1/worker/cpu_worker.py
Labels: v1

#20628 [Bugfix] set default set cuda_graph_sizes to min(self.max_num_seqs * 2, 512)
  vllm/config.py
Labels: ready

#20640 [feat] enable SM100 CUTLASS block scaled group gemm for smaller batch sizes
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: performance, ready

#20642 Fix bullets in incremental_build.md
  docs/contributing/incremental_build.md
Labels: documentation, ready

#20649 [XPU] Use spawn with XPU multiprocessing
  tests/utils.py
  tests/v1/e2e/test_cascade_attention.py
  vllm/utils/__init__.py
Labels: ready, v1

#20659 [Intel GPU] support ray as distributed executor backend for XPU.
  .buildkite/scripts/hardware_ci/run-xpu-test.sh
  vllm/executor/ray_distributed_executor.py
Labels: ready, ci/build

#20667 [Docs] fix minimax tool_calling docs error
  docs/features/tool_calling.md
Labels: documentation, ready, tool-calling

#20499 [V1] [Doc] Update V1 docs for Mamba models
  docs/models/supported_models.md
  docs/usage/v1_guide.md
Labels: documentation, v1

#20673 [doc] update doc format
  docs/contributing/ci/update_pytorch_version.md
Labels: documentation

#20643 [Bugfix] Fix handling of Tensorizer arguments for LoadConfig
  tests/tensorizer_loader/test_tensorizer.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/tensorizer.py
  vllm/model_executor/model_loader/tensorizer_loader.py
Labels: bug, usage, ready

#20652 [XPU][CI] enhance xpu test support
  tests/conftest.py
  vllm/distributed/device_communicators/xpu_communicator.py
  vllm/distributed/parallel_state.py
  vllm/platforms/xpu.py
  vllm/v1/worker/xpu_model_runner.py
Labels: ready, v1

#18218 [Kernel] Triton implementation of causal-conv1d for Mamba-based models
  CMakeLists.txt
  csrc/mamba/causal_conv1d/causal_conv1d.cu
  csrc/mamba/causal_conv1d/causal_conv1d.h
  csrc/mamba/causal_conv1d/static_switch.h
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/kernels/mamba/test_causal_conv1d.py
  tests/kernels/mamba/test_mamba_ssm_ssd.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/mamba/mamba2_metadata.py
  vllm/model_executor/layers/mamba/mamba_mixer.py
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/layers/mamba/ops/causal_conv1d.py
  vllm/model_executor/models/mamba_cache.py
  vllm/v1/attention/backends/mamba_attn.py
Labels: ready, ci/build, v1

#19818 [Kernel] Add Conch backend for mixed-precision linear layer
  requirements/rocm.txt
  vllm/model_executor/layers/quantization/kernels/mixed_precision/__init__.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/conch.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/machete.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/marlin.py
Labels: rocm, ready, ci/build, force-merge

#19487 [BugFix]: Properly set engine_id when using multi connector
  tests/v1/kv_connector/unit/test_multi_connector.py
  tests/v1/kv_connector/unit/test_nixl_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/multi_connector.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
Labels: bug, ready, v1

#20701 [Misc] Simplify the prefix caching logic on draft tokens
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#20651 [CI/Build] Fix FlashInfer double build in Dockerfile
  docker/Dockerfile
Labels: ready, ci/build

#20665 Correct PPMissingLayer handling in Deepseek-V2-Lite PP deployment
  vllm/model_executor/models/deepseek_v2.py
Labels: ready, deepseek

#20696 [BugFix][CPU] Fix CPU worker dependency on cumem_allocator
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#19555 [KVConnector] Aggregate finished requests on the scheduler
  vllm/distributed/kv_transfer/kv_connector/v1/base.py
  vllm/distributed/kv_transfer/kv_connector/v1/nixl_connector.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#20747 [Misc] loose new-model tagger conditions
  .github/mergify.yml
Labels: ci/build

#20728 [CI/Build] Fix Basic Models Test
  tests/models/test_initialization.py
Labels: ready

#20738 [Bugfix][Build][Non-CUDA] Only referencing CMAKE_CUDA_COMPILER_VERSION on CUDA where it is defined
  CMakeLists.txt
Labels: ready, ci/build

#20724 [CI Bugfix] Skip failing Tensorizer+LoRA test
  tests/lora/test_llama_tp.py
Labels: ready, llama

#20692 [Misc] Clean up mark to fork process in BNB tests
  tests/models/quantization/test_bitsandbytes.py
Labels: ready

#20741 [ROCm][Regression] Remove tensor creation that harms performance on ROCm
  vllm/platforms/rocm.py
Labels: rocm, ready

#20260 [Model][VLM] Support JinaVL Reranker
  .buildkite/test-pipeline.yaml
  docs/models/supported_models.md
  docs/serving/openai_compatible_server.md
  examples/offline_inference/vision_language_pooling.py
  examples/online_serving/openai_cross_encoder_score_for_multimodal.py
  tests/models/multimodal/pooling/test_jinavl_reranker.py
  tests/models/registry.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_score.py
  vllm/entrypoints/score_utils.py
  vllm/model_executor/models/config.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/jina_vl.py
  vllm/model_executor/models/registry.py
Labels: documentation, new-model, frontend, ready, ci/build, multi-modality

#20717 Fix DeepSeek-R1-0528 chat template
  examples/tool_chat_template_deepseekr1.jinja
Labels: documentation, ready, tool-calling, deepseek

#20760 [Bugfix] [CI] Fix Tensorizer LoRA test
  tests/lora/test_llama_tp.py
  vllm/lora/peft_helper.py
  vllm/model_executor/model_loader/tensorizer.py
Labels: ready, llama

#15975 [V0][V1][Core] Add outlines integration for V1, and update V0 integration.
  requirements/common.txt
  tests/entrypoints/llm/test_guided_generate.py
  tests/model_executor/test_guided_processors.py
  tests/tool_use/test_tool_choice_required.py
  tests/v1/entrypoints/llm/test_struct_output_generate.py
  vllm/config.py
  vllm/envs.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/outlines_decoding.py
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
  vllm/v1/engine/processor.py
  vllm/v1/structured_output/__init__.py
  vllm/v1/structured_output/backend_outlines.py
Labels: structured-output, ready, ci/build, v1, tool-calling

#20714 [Bugfix] Remove assertion of expert_map being None
  vllm/model_executor/layers/fused_moe/pplx_prepare_finalize.py
Labels: ready

#20785 [Docs] Lazy import gguf
  vllm/entrypoints/score_utils.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: frontend, ready

#20789 Add kimi-k2 tool parser
  tests/tool_use/test_kimi_k2_tool_parser.py
  vllm/config.py
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/kimi_k2_tool_parser.py
Labels: frontend, ready, tool-calling

#20211 [Model] Support HF format of minimax
  tests/models/registry.py
  vllm/model_executor/models/minimax_text_01.py
  vllm/model_executor/models/registry.py
Labels: new-model, ready

#20034 [Attention] MLA - Flashinfer Ragged Prefill
  tests/v1/kv_connector/__init__.py
  tests/v1/kv_connector/unit/test_multi_connector.py
  tests/v1/kv_connector/unit/utils.py
  vllm/attention/layer.py
  vllm/attention/utils/kv_sharing_utils.py
  vllm/logger.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/cutlass_mla.py
  vllm/v1/attention/backends/utils.py
Labels: documentation, performance, frontend, ready, v1, deepseek

#20660 [V1] Enable Mamba2 layers other than MambaMixer2 in the v1 engine
  vllm/config.py
  vllm/model_executor/layers/mamba/abstract.py
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/models/bamba.py
  vllm/model_executor/models/falcon_h1.py
  vllm/model_executor/models/granitemoehybrid.py
  vllm/model_executor/models/mamba2.py
  vllm/model_executor/models/nemotron_h.py
  vllm/model_executor/models/zamba2.py
  vllm/v1/attention/backends/mamba_attn.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#19825 [Core] Add Flashinfer TRTLLM Backend for Flashinfer decode path (SM100).
  benchmarks/kernels/benchmark_trtllm_attention.py
  tests/kernels/attention/test_flashinfer_trtllm_decode_attention.py
  vllm/attention/backends/flashinfer.py
  vllm/engine/arg_utils.py
  vllm/envs.py
  vllm/platforms/cuda.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/utils.py
Labels: performance, ready, v1

#20764 [Bugfix] Refactor `/invocations` to be task-agnostic
  tests/entrypoints/openai/test_chat.py
  tests/entrypoints/openai/test_classification.py
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_embedding.py
  tests/entrypoints/openai/test_pooling.py
  tests/entrypoints/openai/test_rerank.py
  tests/entrypoints/openai/test_score.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/protocol.py
Labels: frontend, ready

#20819 [doc] fix ordered list issue
  docs/features/spec_decode.md
Labels: documentation

#20814 [Bugfix] Fix OOM in language generation test
  tests/models/language/generation/test_common.py
Labels: ready

#20821 Update kimi-k2 tool calling docs, enable unit tests
  docs/features/tool_calling.md
  tests/tool_use/test_kimi_k2_tool_parser.py
Labels: documentation, ready, tool-calling

#20845 [CI Bug] Fix Async Engine, Inputs, Utils, Worker Test: 'State' object has no attribute 'enable_server_load_tracking'
  vllm/entrypoints/utils.py
Labels: bug, frontend, ready

#20154 Add pynccl all-gatherv and reducescatterv
  tests/distributed/test_pynccl.py
  vllm/distributed/device_communicators/base_device_communicator.py
  vllm/distributed/device_communicators/cuda_communicator.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/device_communicators/pynccl_wrapper.py
  vllm/distributed/parallel_state.py
Labels: ready

#20541 [CI/Build] Ensure compatability with Transformers v4.53
  requirements/test.in
  requirements/test.txt
  tests/models/multimodal/generation/test_common.py
  tests/models/multimodal/processing/test_common.py
  tests/models/test_initialization.py
  vllm/inputs/registry.py
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma3.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/whisper.py
Labels: ready, ci/build, multi-modality, qwen

#20637 [Frontend] Abstract prompt and SpeechToTextConfig for transcriptions models
  vllm/config.py
  vllm/entrypoints/openai/speech_to_text.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/whisper.py
Labels: frontend, ready

#20854 [Bugfix] Replace unavailable video url in multimodal test
  tests/multimodal/test_utils.py
Labels: ready, multi-modality

#20834 [Misc] Respect `no_use_tqdm_on_load` flag while capturing CUDA graph
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/model_runner.py
Labels: ready, v1

#20833 [Bug] Fix DeepGemm for EP low latency case
  vllm/model_executor/layers/fused_moe/batched_deep_gemm_moe.py
Labels: bug, ready, deepseek

#20846 [Docs] Update basic.md
  docs/contributing/model/basic.md
Labels: documentation, ready

#20823 [Bugfix] Fix torch.compile x LoRA for PyTorch 2.8
  vllm/lora/layers.py
Labels: ready

#20790 [cold start time] add envs.VLLM_COMPILE_DEPYF to guard decompile
  vllm/compilation/wrapper.py
  vllm/envs.py
Labels: ready, torch.compile

#20693 Remove extra tensor on CPU
  vllm/v1/sample/logits_processor.py
Labels: ready, v1

#20419 Enable ModelOpt Llama4 fp8 checkpoint deployment
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/llama4.py
  vllm/model_executor/models/mllama4.py
Labels: quantization, ready, llama

#20853 Revert "Use NVCC --compress-mode to reduce binary size by 30% #20694"
  CMakeLists.txt
Labels: ready, ci/build

#20843 [Bugfix] Fix Tensor Parallelism Padding Consistency in Granite Models
  vllm/model_executor/models/granite.py
Labels: ready
