Repository vllm-project/vllm, pull requests merged in 2025-02, with the labels that each got.

#12600 [V1] Bugfix: Validate Model Input Length
  vllm/v1/engine/processor.py
Labels: ready

#11161 [BugFix] fix wrong output when using lora and num_scheduler_steps=8
  vllm/worker/model_runner.py
  vllm/worker/worker.py
Labels: ready

#12617 Fix target matching for fused layers with compressed-tensors
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: quantization, ready

#12599 [ci] Upgrade transformers to 4.48.2 in CI dependencies
  requirements-common.txt
  requirements-test.in
  requirements-test.txt
Labels: ready, ci/build

#12562 [Bugfix/CI] Fixup benchmark_moe.py
  benchmarks/kernels/benchmark_moe.py
Labels: moe, ready

#12517 Fix: Respect `sparsity_config.ignore` in Cutlass Integration
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#12601 [Attention] Deepseek v3 MLA support with FP8 compute
  vllm/attention/backends/mla/utils.py
  vllm/attention/backends/triton_mla.py
  vllm/attention/layer.py
  vllm/config.py
  vllm/envs.py
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/deepseek_v3.py
  vllm/worker/cache_engine.py
Labels: ready

#12280 [CI/Build] Add label automation for structured-output, speculative-decoding, v1
  .github/mergify.yml
Labels: ready, ci/build

#12642 Disable chunked prefill and/or prefix caching when MLA is enabled
  vllm/config.py
Labels: ready

#12637 Apply torch.compile to fused_moe/grouped_topk
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/models/deepseek_v3.py
Labels: ready

#12643 doc: fixing minor typo in readme.md
  README.md
Labels: documentation, ready

#12648 [Bugfix] fix moe_wna16 get_quant_method
  vllm/model_executor/layers/quantization/moe_wna16.py
Labels: ready

#12620 [Core] Silence unnecessary deprecation warnings
  vllm/lora/request.py
Labels: ready

#12653 [V1][Minor] Avoid frequently creating ConstantList
  vllm/v1/request.py
Labels: ready, v1

#12608 [Core][v1] Unify allocating slots in prefill and decode in KV cache manager
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/scheduler.py
Labels: ready, v1

#12392 [Hardware][Intel GPU] add XPU bf16 support
  docs/source/getting_started/installation/gpu/xpu.inc.md
  vllm/platforms/xpu.py
Labels: documentation, ready

#12667 [doc][misc] clarify VLLM_HOST_IP for multi-node inference
  docs/source/serving/distributed_serving.md
  vllm/executor/ray_utils.py
Labels: documentation

#12668 [Doc] Deprecate Discord
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, ready

#12574 [Kernel] port sgl moe_align_block_size kernels
  csrc/moe/moe_align_sum_kernels.cu
  csrc/moe/moe_ops.h
  csrc/moe/torch_bindings.cpp
  vllm/_custom_ops.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#12669 make sure mistral_common not imported for non-mistral models
  .buildkite/test-pipeline.yaml
  tests/standalone_tests/lazy_imports.py
  vllm/multimodal/video.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ci/build

#12666 Properly check if all fused layers are in the list of targets
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
Labels: ready

#12570 Fix for attention layers to remain unquantized during moe_wn16 quant
  vllm/model_executor/layers/quantization/moe_wna16.py
Labels: documentation, quantization, structured-output, frontend, speculative-decoding, ready, ci/build, v1

#12681 [ci/build] fix gh200 test
  .buildkite/check-wheel-size.py
  .buildkite/run-gh200-test.sh
  Dockerfile
Labels: ci/build

#11330 [Model]: Add `transformers` backend support
  .buildkite/test-pipeline.yaml
  docs/source/models/supported_models.md
  requirements-common.txt
  tests/models/registry.py
  tests/models/test_oot_registration.py
  tests/models/test_transformers.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/transformers.py
Labels: documentation, ready, ci/build

#12694 [Misc] Fix improper placement of SPDX header in scripts
  cmake/hipify.py
  tests/models/test_transformers.py
  tools/check_spdx_header.py
  tools/report_build_time_ninja.py
  vllm/attention/ops/triton_flash_attention.py
  vllm/model_executor/models/transformers.py
Labels: ready, ci/build

#12696 [Bugfix][Kernel] Fix per-token/per-channel quantization for Hopper scaled mm
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x.cu
Labels: ready

#12704 Squelch MLA warning for Compressed-Tensors Models
  vllm/config.py
Labels: ready

#12707 [Model] Add Deepseek V3 fp8_w8a8 configs for B200
  vllm/model_executor/layers/quantization/utils/configs/N=24576,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=1536,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=32768,K=512,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4096,K=512,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4608,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=512,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=576,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=16384,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=18432,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2048,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2304,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=256,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128, 128].json
Labels: ready

#12582 [MISC] Remove model input dumping when exception
  .github/ISSUE_TEMPLATE/400-bug-report.yml
  tests/basic_correctness/test_basic_correctness.py
  vllm/worker/model_runner.py
  vllm/worker/model_runner_base.py
Labels: ready, ci/build

#12415 [V1] Revert `uncache_blocks` and support recaching full blocks
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
Labels: ready, v1

#12621 [Core] Improve hash collision avoidance in prefix caching
  tests/core/block/test_prefix_caching_block.py
  vllm/core/block/prefix_caching_block.py
  vllm/v1/core/kv_cache_utils.py
Labels: ready, v1

#12710 Support Pixtral-Large HF by using llava multimodal_projector_bias config
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
Labels: ready

#12709 [Doc] Replace ibm-fms with ibm-ai-platform
  docs/source/features/spec_decode.md
  examples/offline_inference/mlpspeculator.py
  tests/models/registry.py
  tests/spec_decode/e2e/test_mlp_correctness.py
  vllm/model_executor/models/mlp_speculator.py
Labels: documentation, speculative-decoding, ready

#12711 [Quant] Fix use_mla TypeError and support loading pure-sparsity Compressed Tensors configs
  vllm/config.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
Labels: ready

#12381 [Misc] Add BNB quantization for Whisper
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/whisper.py
Labels: ready

#12553 [VLM] Merged multi-modal processor for InternVL-based models
  docs/source/contributing/model/multimodal.md
  docs/source/models/supported_models.md
  tests/models/decoder_only/vision_language/test_h2ovl.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_h2ovl.py
  tests/models/multimodal/processing/test_internvl.py
  tests/models/multimodal/processing/test_llava_next.py
  tests/models/multimodal/processing/test_llava_onevision.py
  tests/models/multimodal/processing/test_phi3v.py
  tests/models/multimodal/processing/test_qwen2_vl.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/inputs.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/registry.py
Labels: documentation, ready

#12674 [V1] Remove constraints on partial requests
  tests/v1/core/test_scheduler.py
  vllm/v1/core/scheduler.py
  vllm/v1/worker/block_table.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#12660 [VLM] Implement merged multimodal processor and V1 support for idefics3
  docs/source/models/supported_models.md
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_idefics3.py
  vllm/inputs/registry.py
  vllm/model_executor/models/idefics3.py
Labels: documentation, ready

#12689 [Model] [Bugfix] Fix loading of fine-tuned models based on Phi-3-Small
  vllm/model_executor/models/phi3_small.py
Labels: ready

#12722 Avoid unnecessary multi-modal input data copy when len(batch) == 1
  vllm/multimodal/inputs.py
Labels: ready

#12630 [Build] update requirements of no-device for plugin usage
  setup.py
Labels: ci/build

#12728 [Bugfix] Fix CI failures for InternVL and Mantis models
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/registry.py
  tests/multimodal/test_processing.py
  tests/multimodal/test_processor_kwargs.py
Labels: ready

#12579 [V1][Metrics] Add request_success_total counter, labelled with finish reason
  tests/entrypoints/openai/test_metrics.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/engine/output_processor.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
  vllm/v1/request.py
Labels: ready, v1

#12676 [Perf] Mem align KV caches for CUDA devices (MLA perf improvement)
  csrc/cache.h
  csrc/cache_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_cache.py
  vllm/_custom_ops.py
  vllm/attention/backends/triton_mla.py
  vllm/attention/ops/triton_decode_attention.py
  vllm/envs.py
  vllm/utils.py
  vllm/worker/cache_engine.py
Labels: ready

#12368 [Core] add and implement `VLLM_LOGITS_PROCESSOR_THREADS`
  vllm/envs.py
  vllm/model_executor/layers/logits_processor.py
Labels: ready

#12713 [ROCM][AMD][TRITON] Halving warps number for fw_prefill to reduce spilling
  vllm/attention/ops/prefix_prefill.py
Labels: rocm, ready

#12727 Refactor `Linear` handling in `TransformersModel`
  vllm/model_executor/layers/linear.py
  vllm/model_executor/models/transformers.py
Labels: ready

#12729 [VLM] Add MLA with pure RoPE support for deepseek-vl2 models
  vllm/attention/backends/mla/utils.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/deepseek_v3.py
Labels: ready

#12736 [Misc] Bump the compressed-tensors version
  requirements-common.txt
Labels: ready, ci/build

#12634 [Model][Quant] Fix GLM, Fix fused module mappings for quantization
  vllm/model_executor/layers/quantization/base_config.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py
  vllm/model_executor/layers/quantization/compressed_tensors/utils.py
  vllm/model_executor/layers/quantization/quark/quark.py
  vllm/model_executor/layers/quantization/quark/utils.py
  vllm/model_executor/layers/quantization/utils/quant_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/glm4_vision_encoder.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/qwen.py
Labels: ready

#12748 [Doc] Update PR Reminder with link to Developer Slack
  .github/workflows/reminder_comment.yml
Labels: ready, ci/build

#12750 [Bugfix] Fix OpenVINO model runner
  vllm/attention/backends/openvino.py
  vllm/model_executor/model_loader/openvino.py
  vllm/worker/openvino_model_runner.py
Labels: ready

#12760 [V1][Misc] Shorten `FinishReason` enum and use constant strings
  vllm/v1/engine/__init__.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
  vllm/v1/request.py
Labels: ready, v1

#12546 [Bugfix] Fix 'ModuleNotFoundError: No module named 'intel_extension_for_pytorch'' for --tensor-parallel-size more than 1
  vllm/distributed/parallel_state.py
Labels: ready

#12732 [core][distributed] exact ray placement control
  .buildkite/test-pipeline.yaml
  examples/offline_inference/ray_placement.py
  vllm/envs.py
  vllm/executor/ray_distributed_executor.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
Labels: ci/build

#12536 [Kernel] Use self.kv_cache and forward_context.attn_metadata in Attention.forward
  vllm/attention/layer.py
Labels: ready

#12767 [VLM] Use shared field to pass token ids to model
  vllm/model_executor/models/internvl.py
  vllm/multimodal/inputs.py
Labels: ready

#12780 [Docs] Drop duplicate [source] links
  docs/source/conf.py
Labels: documentation, ready

#12781 [VLM] Update compatibility with transformers 4.49
  docs/source/models/supported_models.md
  examples/template_pixtral_hf.jinja
  tests/entrypoints/test_chat_utils.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/embedding/vision_language/test_llava_next.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/minicpmv.py
  vllm/multimodal/inputs.py
Labels: documentation, ready

#12789 [ROCm][Kernel] Using the correct warp_size value
  csrc/moe/moe_align_sum_kernels.cu
Labels: ready

#12796 [Bugfix] Better FP8 supported defaults
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
Labels: ready

#12799 [Misc][Easy] Remove the space from the file name
  vllm/model_executor/layers/fused_moe/configs/E=256,N=128,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/configs/E=256,N=256,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/utils/configs/N=1536,K=1536,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=1536,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=1536,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=2048,K=512,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=2048,K=512,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=2304,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=2304,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=24576,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=24576,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=256,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=1536,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=32768,K=512,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=32768,K=512,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=36864,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=36864,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4096,K=512,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4096,K=512,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4608,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4608,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=512,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=576,K=7168,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=576,K=7168,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=1024,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=1024,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=1152,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=1152,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=128,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=16384,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=16384,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=18432,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=18432,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2048,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2048,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2304,device_name=NVIDIA_H100_80GB_HBM3,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2304,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=256,device_name=NVIDIA_H200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
Labels: ready

#11253 [Model] LoRA Support for Ultravox model
  docs/source/models/supported_models.md
  tests/conftest.py
  tests/lora/test_ultravox.py
  vllm/model_executor/models/ultravox.py
Labels: documentation, ready

#12793 [Misc] Remove duplicated DeepSeek V2/V3 model definition
  vllm/config.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/deepseek_v3.py
  vllm/model_executor/models/registry.py
Labels: ready

#12757 [Misc] Update w2 scale loading for GPTQMarlinMoE
  tests/weight_loading/models-large.txt
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
Labels: ready

#12814 [Docs] Add Google Cloud Slides
  README.md
Labels: documentation, ready

#12807 [Attention] Use FA3 for MLA on Hopper
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/mla/utils.py
  vllm/attention/backends/utils.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, v1

#12797 [misc] Reduce number of config file requests to HuggingFace
  vllm/transformers_utils/config.py
Labels: ready

#12833 [Misc] Remove unnecessary decode call
  vllm/inputs/preprocess.py
Labels: ready

#12777 [Kernel] Make rotary_embedding ops more flexible with input shape
  csrc/pos_encoding_kernels.cu
  tests/kernels/test_pos_encoding.py
  vllm/attention/backends/mla/utils.py
  vllm/model_executor/models/deepseek_v2.py
Labels: ready

#12828 [Bugfix] Fix unsupported FA version check for Turing GPU
  vllm/attention/backends/utils.py
Labels: ready

#10957 [V1] LoRA Support
  tests/lora/conftest.py
  tests/lora/test_baichuan.py
  tests/lora/test_chatglm3_tp.py
  tests/lora/test_gemma.py
  tests/lora/test_llama_tp.py
  tests/lora/test_lora_bias_e2e.py
  tests/lora/test_phi.py
  tests/lora/test_quant_model.py
  tests/v1/core/test_kv_cache_utils.py
  vllm/lora/layers.py
  vllm/model_executor/layers/logits_processor.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/lora_model_runner_mixin.py
Labels: ready, v1

#12804 [MISC] Check space in the file names in the pre commit checks
  .pre-commit-config.yaml
  vllm/model_executor/layers/quantization/utils/configs/N=24576,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=1536,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=3072,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=32768,K=512,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4096,K=512,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=4608,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=512,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=576,K=7168,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=16384,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=18432,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2048,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=2304,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
  vllm/model_executor/layers/quantization/utils/configs/N=7168,K=256,device_name=NVIDIA_B200,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: ready

#12848 [Bugfix] FA2 illegal memory access
  CMakeLists.txt
Labels: ready, ci/build

#12836 [Bugfix] Missing quant_config in deepseek embedding layer
  vllm/model_executor/models/deepseek_v2.py
Labels: ready

#12837 Prevent unecessary requests to huggingface hub
  tests/entrypoints/offline_mode/test_offline_mode.py
  vllm/transformers_utils/config.py
Labels: ready

#12880 [MISC][EASY] Break check file names into entry and args in the pre-commit hooks
  .pre-commit-config.yaml
Labels: ready

#12868 [Misc] Remove unnecessary detokenization in multimodal processing
  tests/entrypoints/openai/test_audio.py
  tests/entrypoints/openai/test_vision.py
  tests/entrypoints/openai/test_vision_embedding.py
  vllm/inputs/preprocess.py
Labels: ready

#12718 [Model] Add support for partial rotary embeddings in Phi3 model
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/llama.py
Labels: ready

#9880 [V1] Logprobs and prompt logprobs support
  tests/v1/core/test_scheduler.py
  tests/v1/engine/conftest.py
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_llm_engine.py
  tests/v1/engine/test_output_processor.py
  tests/v1/engine/utils.py
  tests/v1/entrypoints/__init__.py
  tests/v1/entrypoints/conftest.py
  tests/v1/entrypoints/openai/test_completion.py
  tests/v1/sample/test_logprobs.py
  tests/v1/sample/test_logprobs_e2e.py
  tests/v1/sample/utils.py
  vllm/outputs.py
  vllm/transformers_utils/detokenizer_utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/logprobs.py
  vllm/v1/engine/output_processor.py
  vllm/v1/engine/processor.py
  vllm/v1/metrics/stats.py
  vllm/v1/outputs.py
  vllm/v1/sample/metadata.py
  vllm/v1/sample/sampler.py
  vllm/v1/serial_utils.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: frontend, ready, ci/build, v1

#12501 [ROCm] [Feature] [Doc] [Dockerfile] [BugFix] Support Per-Token-Activation Per-Channel-Weight FP8 Quantization Inferencing
  Dockerfile.rocm_base
  docs/source/getting_started/installation/gpu/rocm.inc.md
  tests/quantization/test_fp8.py
  tests/quantization/test_ptpc_fp8.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/ptpc_fp8.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/platforms/rocm.py
Labels: documentation, rocm, ready, ci/build

#11590 [V1] LM Eval With Streaming Integration Tests
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build

#12723 [Bugfix] Fix disagg hang caused by the prefill and decode communication issues
  vllm/distributed/kv_transfer/kv_lookup_buffer/simple_buffer.py
Labels: ready, v1

#12928 [V1][Minor] Remove outdated comment
  vllm/v1/core/kv_cache_manager.py
Labels: v1

#12922 [V1] Move KV block hashes from Request to KVCacheManager
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/scheduler.py
  vllm/v1/request.py
Labels: ready, v1

#12905 [Bugfix] Fix Qwen2_5_VLForConditionalGeneration packed_modules_mapping
  vllm/model_executor/models/qwen2_5_vl.py
Labels: ready

#12896 [Misc] Fix typo in the example file
  examples/online_serving/openai_chat_embedding_client_for_multimodal.py
Labels: ready

#12859 [Bugfix] Fix multi-round chat error when mistral tokenizer is used
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#12934 [bugfix] respect distributed_executor_backend in world_size=1
  tests/engine/test_executor.py
  vllm/config.py
  vllm/engine/llm_engine.py
  vllm/v1/executor/abstract.py
Labels: v1

#12418 [Misc] Add offline test for disaggregated prefill
  examples/offline_inference/disaggregated_prefill.py
Labels: ready

#12943 [V1][Minor] Move cascade attn logic outside _prepare_inputs
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#12874 [Build] Make pypi install work on CPU platform
  setup.py
Labels: ready, ci/build

#12812 [Hardware][Intel-Gaudi] Enable long-contexts + LoRA support for Intel Gaudi
  vllm/lora/punica_wrapper/punica_hpu.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/worker/hpu_model_runner.py
Labels: ready

#12898 [misc] Add LoRA to benchmark_serving
  benchmarks/benchmark_serving.py
Labels: ready

#12926 [Misc] Log time consumption on weight downloading
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#12925 [CI] Resolve transformers-neuronx version conflict
  .buildkite/run-neuron-test.sh
  Dockerfile.neuron
  requirements-neuron.txt
  setup.py
Labels: ready, ci/build

#12949 [Doc] Correct HF repository for TeleChat2 models
  docs/source/models/supported_models.md
Labels: documentation, ready

#12944 [Misc] Add qwen2.5-vl BNB support
  vllm/model_executor/models/qwen2_5_vl.py
Labels: ready

#12941 [CI/Build] Auto-fix Markdown files
  .buildkite/nightly-benchmarks/README.md
  .buildkite/nightly-benchmarks/nightly-annotation.md
  .buildkite/nightly-benchmarks/nightly-descriptions.md
  .buildkite/nightly-benchmarks/performance-benchmarks-descriptions.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  README.md
  benchmarks/README.md
  csrc/quantization/cutlass_w8a8/Epilogues.md
  csrc/quantization/machete/Readme.md
  docs/source/getting_started/installation/gpu/rocm.inc.md
  docs/source/serving/engine_args.md
  examples/offline_inference/openai/openai_batch.md
  examples/offline_inference/profiling_tpu/README.md
  examples/online_serving/chart-helm/README.md
  examples/online_serving/opentelemetry/Otel.md
  examples/online_serving/prometheus_grafana/README.md
  examples/other/logging_configuration.md
  vllm/distributed/kv_transfer/README.md
Labels: documentation, ready, ci/build

#12935 [Bugfix] Remove unused seq_group_metadata_list from ModelInputForGPU
  vllm/worker/model_runner.py
Labels: ready

#12959 [bugfix] fix early import of flash attention
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/mla/utils.py
  vllm/attention/backends/utils.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, v1

#12449 [VLM] Merged multi-modal processor for GLM4V
  docs/source/models/supported_models.md
  examples/offline_inference/vision_language.py
  tests/models/multimodal/processing/test_common.py
  vllm/model_executor/models/chatglm.py
Labels: documentation, ready

#12968 [V1][Minor] Remove outdated comment
  vllm/v1/core/kv_cache_manager.py
Labels: ready, v1

#10130 [RFC] [Mistral] FP8 format
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/pixtral.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: quantization, ready

#12969 [V1] Cache `uses_mrope` in GPUModelRunner
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#12963 [core] port pynvml into vllm codebase
  .pre-commit-config.yaml
  requirements-cuda.txt
  tests/utils.py
  vllm/third_party/__init__.py
  vllm/third_party/pynvml.py
  vllm/utils.py
Labels: ci/build

#12979 [MISC] Always import version library first in the vllm package
  vllm/__init__.py
Labels: ready

#12981 [core] improve error handling when wake up from sleep mode
  csrc/cumem_allocator.cpp
  tests/basic_correctness/test_cumem.py
Labels: ready

#12984 [core][rlhf] add colocate example for RLHF
  .buildkite/test-pipeline.yaml
  examples/offline_inference/rlhf_colocate.py
Labels: ready, ci/build

#12918 [V1] Use msgpack for core request serialization
  vllm/v1/engine/__init__.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/serial_utils.py
Labels: ready, v1

#13003 [Doc] Add link to tool_choice tracking issue in tool_calling.md
  docs/source/features/tool_calling.md
Labels: documentation, ready

#13008 [misc] Add retries with exponential backoff for HF file existence check
  vllm/transformers_utils/config.py
Labels: ready

#13012 [Bugfix] Clean up and fix multi-modal processors
  docs/source/features/compatibility_matrix.md
  tests/models/decoder_only/language/test_models.py
  tests/models/multimodal/processing/test_common.py
  tests/multimodal/utils.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2_vl.py
Labels: documentation, ready

#13007 Fix seed parameter behavior in vLLM
  docs/seed_parameter_behavior.md
  tests/test_seed_behavior.py
  vllm/platforms/interface.py
Labels: documentation, ready

#12912 [Model] Ultravox Model: Support v0.5 Release
  docs/source/models/supported_models.md
  docs/source/serving/multimodal_inputs.md
  examples/offline_inference/audio_language.py
  examples/online_serving/openai_chat_completion_client_for_multimodal.py
  tests/distributed/test_pipeline_parallel.py
  tests/entrypoints/openai/test_audio.py
  tests/entrypoints/test_chat_utils.py
  tests/models/decoder_only/audio_language/test_ultravox.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  vllm/model_executor/models/ultravox.py
  vllm/transformers_utils/configs/ultravox.py
Labels: documentation, ready

#13022 [misc] Fix setup.py condition to avoid AMD from being mistaken with CPU
  setup.py
Labels: ready, ci/build

#13062 [V1][Minor] Move scheduler outputs to a separate file
  vllm/v1/core/scheduler.py
  vllm/v1/core/scheduler_output.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#13065 [Docs] Annouce Meta Meetup
  README.md
Labels: documentation, ready

#12884 [Bugfix] Support missing tool parameters in mistral tokenizer
  tests/tokenization/test_mistral_tokenizer.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: ready

#12933 [Core] Don't do platform detection at import time
  vllm/executor/executor_base.py
  vllm/executor/ray_utils.py
  vllm/platforms/cuda.py
Labels: ready

#12970 [Misc] LoRA - Refactor Punica ops tests
  tests/lora/test_punica_ops.py
  tests/lora/test_punica_ops_sizes.py
  tests/lora/test_punica_ops_variation.py
  tests/lora/utils.py
Labels: ready

#13025 [Bugfix]: Reasoning output bug according to the chat template change
  examples/online_serving/openai_chat_completion_with_reasoning.py
  tests/entrypoints/openai/reasoning_parsers/test_deepseekr1_reasoning_parser.py
  vllm/entrypoints/openai/reasoning_parsers/deepseek_r1_reasoning_parser.py
Labels: frontend, ready

#12592 [V1][Metrics] Add GPU prefix cache hit rate % gauge
  tests/entrypoints/openai/test_metrics.py
  tests/v1/core/test_kv_cache_utils.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/scheduler.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
Labels: ready, v1

#13027 [executor] init `local_rank` as device index
  vllm/executor/uniproc_executor.py
Labels: ready

#12863 [Build] Fix cuda link target of cumem_allocator in CPU env
  CMakeLists.txt
Labels: ready, ci/build

#13089 [Bugfix] fix flaky test
  tests/test_seed_behavior.py
Labels: ready

#12644 [V1][Metrics] Add several request timing histograms
  tests/entrypoints/openai/test_metrics.py
  tests/v1/core/test_scheduler.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  tests/v1/engine/test_output_processor.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/output_processor.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
  vllm/v1/request.py
Labels: ready, v1

#13088 Set `torch_dtype` in `TransformersModel`
  vllm/model_executor/models/transformers.py
Labels: ready

#13024 [Misc] Fix typo at comments at metrics.py
  vllm/engine/metrics.py
Labels: ready

#13023 Fix initializing GGUF weights for ColumnParallelLinear when using tensor parallel > 1
  vllm/model_executor/layers/linear.py
Labels: ready

#13077 [CI/Build][Bugfix] Fix CPU backend default threads num
  vllm/platforms/cpu.py
Labels: ready

#12976 [Bugfix] Guided decoding falls back to outlines when fails to import xgrammar
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
Labels: structured-output, ready

#13114 [Misc] Move pre-commit suggestion back to the end
  .pre-commit-config.yaml
Labels: ready

#12518 [RFC][vllm-API] Support tokenizer registry for customized tokenizer in vLLM
  benchmarks/benchmark_serving.py
  tests/tokenization/test_tokenizer_registry.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_score.py
  vllm/logits_process.py
  vllm/transformers_utils/tokenizer.py
  vllm/transformers_utils/tokenizer_base.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: documentation, structured-output, frontend, speculative-decoding, ready, ci/build, v1

#12830 [Model] IBM/NASA Prithvi Geospatial model
  examples/offline_inference/prithvi_geospatial_mae.py
  tests/models/registry.py
  vllm/attention/backends/placeholder_attn.py
  vllm/inputs/preprocess.py
  vllm/model_executor/models/prithvi_geospatial_mae.py
  vllm/model_executor/models/registry.py
  vllm/worker/pooling_model_runner.py
Labels: ready

#13123 [ci] Add more source file dependencies for some tests
  .buildkite/test-pipeline.yaml
Labels: ci/build

#12923 [Misc] AMD Build Improvements
  csrc/moe/moe_align_sum_kernels.cu
  csrc/rocm/attention.cu
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/configs/__init__.py
Labels: ready, AMD GPU

#13148 [Bugfix] Fix num video tokens calculation for Qwen2-VL
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#12332 [Frontend] Generate valid tool call IDs when using `tokenizer-mode=mistral`
  tests/mistral_tool_use/__init__.py
  tests/mistral_tool_use/conftest.py
  tests/mistral_tool_use/test_mistral_tool_calls.py
  tests/mistral_tool_use/utils.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/tool_parsers/mistral_tool_parser.py
  vllm/transformers_utils/tokenizers/__init__.py
  vllm/transformers_utils/tokenizers/mistral.py
Labels: frontend, ready

#13151 [Misc] Delete unused LoRA modules
  tests/lora/test_lora_manager.py
  vllm/lora/models.py
  vllm/lora/punica_wrapper/punica_base.py
Labels: ready

#12998 Introduce VLLM_CUDART_SO_PATH to allow users specify the .so path
  vllm/distributed/device_communicators/cuda_wrapper.py
  vllm/envs.py
Labels: ready

#13162 [CI/Build] Use mypy matcher for pre-commit CI job
  .github/workflows/pre-commit.yml
Labels: ready, ci/build

#7086 [CORE] [QUANT] Support for GPTQModel's `dynamic` quantization per module override/control
  tests/quantization/test_gptq_dynamic.py
  tests/quantization/test_lm_head.py
  vllm/lora/layers.py
  vllm/model_executor/layers/logits_processor.py
  vllm/model_executor/layers/quantization/gptq.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/utils/gptq_utils.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
Labels: quantization, ready, force-merge

#13119 [Bugfix] Allow fallback to AWQ from AWQMarlin at per-layer granularity
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/moe_wna16.py
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
Labels: quantization, ready, force-merge

#13170 [CI] Fix failing FP8 cpu offload test
  tests/quantization/test_cpu_offload.py
Labels: ready

#13173 [V1][Bugfix] Copy encoder input ids to fix set iteration issue during VLM abort
  vllm/v1/core/encoder_cache_manager.py
Labels: ready, v1

#13182 [CI/Build] Ignore ruff warning up007
  pyproject.toml
Labels: ready, force-merge

#12706 [perf-benchmark] cleanup unused Docker images and volumes in H100 benchmark instance
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
Labels: perf-benchmarks, ci/build, force-merge

#12784 [NVIDIA] Support nvfp4 quantization
  CMakeLists.txt
  cmake/utils.cmake
  csrc/cuda_utils.h
  csrc/cuda_utils_kernels.cu
  csrc/ops.h
  csrc/quantization/fp4/nvfp4_quant_entry.cu
  csrc/quantization/fp4/nvfp4_quant_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_nvfp4_quant.py
  tests/test_scalartype.py
  vllm/_custom_ops.py
  vllm/scalar_type.py
Labels: ready, ci/build, force-merge

#12792 [Bugfix][Example] Fix GCed profiling server for TPU
  examples/offline_inference/profiling_tpu/profiling.py
Labels: ready, force-merge
