Repository vllm-project/vllm, pull requests merged in 2025-03, with the labels that each got.

#14059 [Docs] Add `pipeline_parallel_size` to optimization docs
  docs/source/performance/optimization.md
Labels: documentation, ready

#14060 [Bugfix] Add file lock for ModelScope download
  benchmarks/backend_request_func.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/transformers_utils/tokenizer.py
Labels: ready

#12931 [Misc][Kernel]: Add GPTQAllSpark Quantization
  CMakeLists.txt
  benchmarks/kernels/benchmark_marlin.py
  csrc/quantization/gptq_allspark/allspark_qgemm_w8a16.cu
  csrc/quantization/gptq_allspark/allspark_repack.cu
  csrc/quantization/gptq_allspark/allspark_utils.cuh
  csrc/torch_bindings.cpp
  tests/kernels/test_allspark_gemm.py
  tests/quantization/test_compressed_tensors.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/__init__.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/allspark.py
  vllm/model_executor/layers/quantization/utils/allspark_utils.py
Labels: quantization, ready, ci/build

#14053 [Bugfix][V1][Minor] Fix shutting_down flag checking in V1 MultiprocExecutor
  vllm/v1/executor/multiproc_executor.py
Labels: ready, v1

#13841 [Documentation] Add more deployment guide for Kubernetes deployment
  docs/source/deployment/integrations/index.md
  docs/source/deployment/integrations/production-stack.md
  docs/source/deployment/k8s.md
Labels: documentation, ready

#14050 [Doc] Consolidate `whisper` and `florence2` examples
  examples/offline_inference/audio_language.py
  examples/offline_inference/encoder_decoder_multimodal.py
  examples/offline_inference/florence2_inference.py
  examples/offline_inference/whisper.py
  vllm/model_executor/models/whisper.py
Labels: documentation, ready

#13985 [V1][Minor] Do not print attn backend twice
  vllm/platforms/cuda.py
Labels: ready

#14065 [ROCm][V1][Bugfix] Add get_builder_cls method to the ROCmAttentionBackend class
  vllm/v1/attention/backends/rocm_attn.py
Labels: ready, v1

#14073 [v1][Bugfix] Only cache blocks that are not in the prefix cache
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_manager.py
Labels: ready, v1

#14081 [v1] Add `__repr__` to KVCacheBlock to avoid recursive print
  vllm/v1/core/kv_cache_utils.py
Labels: ready, v1

#13770 [Model] Add LoRA support for TransformersModel
  .buildkite/test-pipeline.yaml
  docs/source/models/supported_models.md
  tests/lora/conftest.py
  tests/lora/test_transfomers_model.py
  vllm/lora/layers.py
  vllm/lora/utils.py
  vllm/model_executor/models/transformers.py
Labels: documentation, ready, ci/build

#14063 [Misc] Accurately capture the time of loading weights
  vllm/model_executor/model_loader/loader.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/model_runner.py
Labels: ready, v1

#14086 [Doc] Source building add clone step
  docs/source/getting_started/installation/cpu/build.inc.md
Labels: documentation, ready

#12955 [v0][structured output] Support reasoning output
  docs/source/features/reasoning_outputs.md
  examples/online_serving/openai_chat_completion_structured_outputs_with_reasoning.py
  tests/model_executor/test_guided_processors.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/client.py
  vllm/entrypoints/openai/cli_args.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/outlines_decoding.py
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
  vllm/model_executor/guided_decoding/reasoner/__init__.py
  vllm/model_executor/guided_decoding/reasoner/deepseek_reasoner.py
  vllm/model_executor/guided_decoding/reasoner/reasoner.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
Labels: documentation, structured-output, frontend, ready

#14051 [Bugfix] Explicitly include "omp.h" for MacOS to avoid installation failure
  csrc/cpu/cpu_types_arm.hpp
Labels: ready

#14106 [Misc] typo find in deepseek_v2
  vllm/model_executor/models/deepseek_v2.py
Labels: ready

#14010 [Misc][Platform] Move use allgather to platform
  vllm/model_executor/layers/logits_processor.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/tpu.py
Labels: ready

#13921 [Build] Make sure local main branch is synced when VLLM_USE_PRECOMPILED=1
  setup.py
  tests/standalone_tests/python_only_compile.sh
  vllm/envs.py
Labels: ci/build

#14147 Improve the docs for `TransformersModel`
  docs/source/models/supported_models.md
Labels: documentation, ready

#14141 Fix `head_dim` not existing in all model configs (Transformers backend)
  vllm/model_executor/models/transformers.py
Labels: ready

#14134 [V0][Metrics] Remove unimplemented `vllm:tokens_total`
  vllm/engine/metrics.py
Labels: ready

#14136 [V0][Metrics] Deprecate some KV/prefix cache metrics
  vllm/engine/metrics.py
Labels: ready

#14082 [V1] Simplify stats logging
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/metrics/loggers.py
Labels: ready, v1

#14055 [WIP][[V1][Metrics] Implement max_num_generation_tokens, request_params_n, and request_params_max_tokens metrics
  tests/entrypoints/openai/test_metrics.py
  vllm/v1/engine/output_processor.py
  vllm/v1/engine/parallel_sampling.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
Labels: ready, v1

#14100 [Bugfix] Allow shared_experts skip quantization for DeepSeekV2/V3
  vllm/model_executor/models/deepseek_v2.py
Labels: bug, ready

#13625 [Kernel] Optimize moe intermediate_cache usage
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#14056 [Docs] Add GPTQModel
  docs/source/features/quantization/auto_awq.md
  docs/source/features/quantization/gptqmodel.md
  docs/source/features/quantization/index.md
Labels: documentation, ready

#14155 [v1] Add comments to the new ragged paged attention Pallas kernel
  vllm/v1/attention/backends/pallas.py
Labels: ready, v1

#13313 [Model] Add support for GraniteMoeShared models
  docs/source/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/granitemoeshared.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready

#14068 [core] moe fp8 block quant tuning support
  benchmarks/kernels/benchmark_moe.py
  vllm/model_executor/layers/fused_moe/configs/E=256,N=256,device_name=AMD_Instinct_MI300X,dtype=fp8_w8a8,block_shape=[128,128].json
Labels: performance, ready

#14099 [core] Pass all driver env vars to ray workers unless excluded
  vllm/executor/ray_distributed_executor.py
Labels: ready

#14164 Fix benchmark_moe.py tuning for CUDA devices
  benchmarks/kernels/benchmark_moe.py
Labels: bug, ready

#14189 [sleep mode] error out with expandable_segments
  vllm/device_allocator/cumem.py
Labels: ready

#14200 [doc] add "Failed to infer device type" to faq
  docs/source/getting_started/troubleshooting.md
Labels: documentation

#13869 [V1][BugFix] Fix remaining sync engine client shutdown errors/hangs
  tests/v1/engine/test_llm_engine.py
  vllm/utils.py
  vllm/v1/engine/core_client.py
Labels: ready, v1

#14135 [V0][Metrics] Deprecate some questionable request time metrics
  vllm/engine/metrics.py
Labels: ready

#14161 [V1][Molmo] Fix get_multimodal_embeddings() in molmo.py
  examples/offline_inference/vision_language.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/florence2.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/glm4v.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/whisper.py
Labels: documentation, ready

#13988 [TPU][Profiler] Support start_profile/stop_profile in TPU worker
  requirements-tpu.txt
  vllm/v1/worker/tpu_worker.py
  vllm/worker/tpu_worker.py
Labels: documentation, ready, ci/build, v1

#14225 [Frontend] Do `prompt_logprobs` clamping for chat as well as completions
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend, ready

#14215 [Docs] Update Dockerfile dependency image
  docs/source/assets/contributing/dockerfile-stages-dependency.png
Labels: documentation, ready

#12745 [v1][Metrics] Add design doc
  docs/source/assets/design/v1/metrics/intervals-1.png
  docs/source/assets/design/v1/metrics/intervals-2.png
  docs/source/assets/design/v1/metrics/intervals-3.png
  docs/source/design/v1/metrics.md
  docs/source/index.md
Labels: documentation, ready, v1

#14228 Serialize using safetensors for KV caches
  vllm/distributed/kv_transfer/kv_pipe/mooncake_pipe.py
Labels: ready

#13240 Clean up unused padding_idx variables across many model definitions
  vllm/model_executor/models/arctic.py
  vllm/model_executor/models/baichuan.py
  vllm/model_executor/models/bart.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/deepseek.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/exaone.py
  vllm/model_executor/models/florence2.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/granite.py
  vllm/model_executor/models/granitemoe.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/internlm2.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/mamba.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/mixtral_quant.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/nemotron.py
  vllm/model_executor/models/olmoe.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/orion.py
  vllm/model_executor/models/phimoe.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/solar.py
  vllm/model_executor/models/starcoder2.py
  vllm/model_executor/models/whisper.py
Labels: ready

#14145 [ROCm] Disable a few more kernel tests that are broken on ROCm
  .buildkite/run-amd-test.sh
Labels: ready, ci/build

#14158 [V1][TPU] TPU multimodal model support for ragged attention
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#14248 [misc] announce china meetup
  README.md
Labels: documentation

#14199 Moved numba from common requirements to cuda/rocm specific requirements
  requirements-common.txt
  requirements-cuda.txt
  requirements-rocm.txt
Labels: ready, ci/build, force-merge

#14157 Disable GPTQ AllSpark kernels for CUDA Compiler < 12.0
  CMakeLists.txt
Labels: ready, ci/build, force-merge

#13750 [Bugfix] Fix gptq_marlin for deepseek-v3
  vllm/model_executor/layers/quantization/gptq_marlin.py
Labels: bug, ready, force-merge

#14235 [V1][Bugfix] Do not reset prefix caching metrics
  vllm/v1/metrics/loggers.py
Labels: ready, v1

#14119 [Model] New model support for Phi-4-multimodal-instruct
  docs/source/models/supported_models.md
  requirements-common.txt
  tests/models/registry.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/phi4mm.py
  vllm/model_executor/models/phi4mm_audio.py
  vllm/model_executor/models/phi4mm_utils.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/vision_siglip_navit.py
Labels: documentation, frontend, ready, ci/build

#13931 [V1] EP/TP MoE + DP Attention
  examples/offline_inference/data_parallel.py
  tests/kernels/test_moe.py
  vllm/attention/layer.py
  vllm/compilation/backends.py
  vllm/forward_context.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/dbrx.py
  vllm/model_executor/models/jamba.py
  vllm/model_executor/models/mixtral.py
  vllm/model_executor/models/olmoe.py
  vllm/model_executor/models/phimoe.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/platforms/cuda.py
  vllm/utils.py
  vllm/v1/engine/core.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, ready, v1

#14251 Temporarily disable test_awq_gemm_opcheck
  tests/kernels/test_awq.py
Labels: ready

#14066 [Frontend] Allow return_tokens_as_token_ids to be passed as a request param
  tests/entrypoints/openai/test_return_tokens_as_ids.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
Labels: frontend, ready

#14256 [Misc][V1] Avoid using `envs.VLLM_USE_V1` in mm processing
  vllm/inputs/preprocess.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/prithvi_geospatial_mae.py
  vllm/multimodal/processing.py
  vllm/v1/engine/processor.py
Labels: ready, v1

#14169 [Bugfix][V1] Fix allowed_token_ids for v1 Sampler
  vllm/v1/engine/processor.py
  vllm/v1/worker/gpu_input_batch.py
Labels: ready, v1

#14217 [Doc] Update nginx guide: remove privileged from vllm container run and add target GPU ID
  docs/source/deployment/nginx.md
Labels: documentation, ready

#14278 [Doc] [3/N] Refer code examples for common cases in dev multimodal processor
  docs/source/contributing/model/multimodal.md
Labels: documentation, ready

#14159 [V1][Frontend] Add Testing For V1 Runtime Parameters
  tests/v1/sample/test_sampling_params_e2e.py
  vllm/v1/engine/processor.py
  vllm/v1/worker/gpu_input_batch.py
Labels: ready, v1

#14177 [LoRA] Remove linear hack outside transformers backend
  vllm/lora/layers.py
  vllm/lora/utils.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/models/transformers.py
Labels: ready

#14276 [Misc] Add Qwen2MoeForCausalLM moe tuning support
  benchmarks/kernels/benchmark_moe.py
Labels: ready, ci/build

#14293 [Doc] Fixed typo in prefix_caching.md
  docs/source/design/v1/prefix_caching.md
Labels: documentation, ready

#14292 [Bugfix] Fix broken vision language example
  examples/offline_inference/vision_language.py
Labels: documentation, ready

#14297 [Docs] Add Meta Slides
  README.md
  docs/source/community/meetups.md
Labels: documentation

#14304 [V1][Minor] Remove obsolete FIXME comment
  vllm/v1/worker/gpu_input_batch.py
Labels: v1

#13997 Deprecate `best_of` Sampling Parameter in anticipation for vLLM V1
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving.py
  examples/offline_inference/llm_engine_example.py
  examples/online_serving/opentelemetry/dummy_client.py
  tests/core/test_scheduler.py
  tests/core/utils.py
  tests/v1/sample/test_sampling_params_e2e.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/sampling_params.py
  vllm/v1/engine/processor.py
Labels: documentation, frontend, ready, v1

#14267 [misc] Add FlashMLA as a new option of VLLM_ATTENTION_BACKEND env
  vllm/envs.py
Labels: documentation, ready

#14308 [V1][Easy] Add empty allowed_token_ids in the v1 sampler test
  tests/v1/sample/test_sampling_params_e2e.py
Labels: ready, v1

#14237 [Bugfix] Fix DeepSeek MTP crash when using TP1ModelRunner with CUDA graph due to shape mismatch
  vllm/spec_decode/draft_model_runner.py
Labels: bug, speculative-decoding, ready

#14302 [Bugfix] Remove num_tokens_across_dp
  vllm/forward_context.py
Labels: ready

#14255 [BugFix] Fix prefix caching V0 MLA
  vllm/attention/backends/mla/common.py
Labels: ready

#14243 [CI/Build] Use spawn multiprocessing mode for V1 test pipeline
  .buildkite/test-pipeline.yaml
Labels: ci/build

#13917 Add benchmark for DeepGEMM and vLLM Block FP8 Dense GEMM
  benchmarks/kernels/deepgemm/README.md
  benchmarks/kernels/deepgemm/benchmark_fp8_block_dense_gemm.py
Labels: performance

#13850 [Build] Add UV_HTTP_TIMEOUT to avoid timeout during installation
  Dockerfile
Labels: ci/build

#14253 [BugFix] MLA + V1, illegal memory access and accuracy issues
  tests/v1/worker/test_gpu_input_batch.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/triton_mla.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#14318 [misc] Mention `ray list nodes` command to troubleshoot ray issues
  docs/source/serving/distributed_serving.md
  vllm/executor/ray_utils.py
Labels: documentation, ready

#14315 [V1] LoRA - Enable more V1 tests
  tests/lora/test_chatglm3_tp.py
  tests/lora/test_mixtral.py
  tests/lora/test_qwen2vl.py
  tests/lora/test_ultravox.py
  tests/lora/test_worker.py
Labels: ready

#11301 [Bugfix][CI] ALiBi test case in xformers multi_query_kv_attention
  tests/kernels/test_attention.py
  tests/kernels/test_prefix_prefill.py
  vllm/attention/backends/xformers.py
Labels: ready

#14244 [Hardware] Update the flash attn tag to support Blackwell
  cmake/external_projects/vllm_flash_attn.cmake
  vllm/attention/backends/utils.py
Labels: ready, ci/build

#14015 [Model] Update Paligemma multimodal processing with PromptUpdate
  docs/source/models/supported_models.md
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/multimodal/processing/test_common.py
  vllm/model_executor/models/paligemma.py
Labels: documentation, ready

#14275 [VLM] Support Pixtral-HF on V1
  docs/source/models/supported_models.md
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/pixtral.py
Labels: documentation, ready, v1

#13301 [Frontend][Docs] Transcription API streaming
  docs/source/serving/openai_compatible_server.md
  examples/online_serving/openai_transcription_client.py
  tests/entrypoints/openai/test_transcription_validation.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_transcription.py
Labels: documentation, frontend, ready

#14077 [Doc] Update reasoning with stream example to use OpenAI library
  docs/source/features/reasoning_outputs.md
  examples/online_serving/openai_chat_completion_with_reasoning_streaming.py
Labels: documentation, ready

#14363 [Doc] Correct beam_search using in generative_models.md
  docs/source/models/generative_models.md
Labels: documentation, ready

#14152 [Kernel] [V1] Improved performance for V1 Triton (ROCm) backend
  tests/kernels/test_prefix_prefill.py
  vllm/attention/ops/chunked_prefill_paged_decode.py
  vllm/attention/ops/prefix_prefill.py
  vllm/v1/attention/backends/rocm_attn.py
Labels: rocm, ready, v1

#14326 [Bugfix][Core] fix abort_seq_group and memory leak when n>1
  vllm/core/scheduler.py
  vllm/engine/llm_engine.py
Labels: ready

#14366 [Doc] Fix date typo in README.md
  README.md
Labels: documentation

#14356 Reinstate `best_of` for V0
  tests/v1/sample/test_sampling_params_e2e.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/sampling_params.py
  vllm/v1/engine/processor.py
Labels: frontend, ready, v1

#12613 Adding cpu inference with VXE ISA for s390x architecture
  Dockerfile.s390x
  cmake/cpu_extension.cmake
  csrc/cpu/attention.cpp
  csrc/cpu/cpu_types.hpp
  csrc/cpu/cpu_types_vxe.hpp
  csrc/cpu/quant.cpp
  requirements-cpu.txt
Labels: ready, ci/build

#14371 Add authors to license header.
  vllm/attention/ops/chunked_prefill_paged_decode.py
Labels: ready

#13897 Fix mla prefill context performance
  vllm/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/common.py
Labels: ready, v1

#14305 [Distributed] Add enable_expert_parallel arg
  examples/offline_inference/data_parallel.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/layer.py
Labels: documentation, ready

#13569 [CI/Build] Use uv python for docker rather than ppa:deadsnakes/ppa
  Dockerfile
Labels: ready, ci/build

#14345 [CI] Disable spawn when running V1 Test
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build

#14306 [Kernel] Add needs_fixed_stride_order tag to most GEMMs
  csrc/torch_bindings.cpp
Labels: ready

#14382 [Bugfix] Fix use_direct_call condition in FusedMoE layer for
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#14313 [Bug] Fix Attention when ignored in by quant_method
  vllm/attention/layer.py
Labels: bug, quantization

#14221 [V1][Bugfix] Standardize quantized kv cache rejection for attention backends
  vllm/attention/backends/abstract.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashmla.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/triton_mla.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/triton_mla.py
Labels: bug, ready, v1

#14298 [Docs] Add nsight guide to profiling docs
  docs/source/contributing/profiling/profiling_index.md
Labels: documentation

#14310 [Hardware][TPU]Enable ragged paged attention kernel and resolve recompilation issue
  requirements-tpu.txt
  vllm/v1/attention/backends/pallas.py
  vllm/v1/worker/tpu_model_runner.py
Labels: ready, ci/build, v1

#14385 [Doc] Fix a typo
  benchmarks/benchmark_serving.py
Labels: ready

#14183 [Bugfix] Correctly call `cudaProfilerStop` in benchmarks script
  benchmarks/kernels/benchmark_layernorm.py
  benchmarks/kernels/benchmark_lora.py
  benchmarks/kernels/benchmark_machete.py
  benchmarks/kernels/benchmark_moe.py
  benchmarks/kernels/benchmark_paged_attention.py
  benchmarks/kernels/benchmark_quant.py
Labels: ready

#14384 [Perf] Reduce MLA CPU overheads in V1
  vllm/model_executor/layers/rotary_embedding.py
  vllm/v1/attention/backends/mla/common.py
Labels: performance, ready, v1

#14390 [FP8] Refactor apply_fp8_linear and apply_fp8_linear_generic into an object
  tests/compile/test_fusion.py
  vllm/attention/backends/mla/common.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_fp8.py
  vllm/model_executor/layers/quantization/fbgemm_fp8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/modelopt.py
  vllm/model_executor/layers/quantization/ptpc_fp8.py
  vllm/model_executor/layers/quantization/quark/schemes/quark_w8a8_fp8.py
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/v1/attention/backends/mla/common.py
Labels: ready, v1

#14396 [BugFix] Illegal Memory Access in the blockwise cutlass fp8 GEMMs
  csrc/cutlass_extensions/gemm/collective/sm90_mma_tma_gmma_ss_warpspecialized_fp8_blockwise_scaling.hpp
Labels: bug, ready

#14370 [Bugfix] Fix JambaForCausalLM LoRA
  tests/lora/conftest.py
  tests/lora/test_jamba.py
  tests/lora/test_layers.py
  vllm/lora/layers.py
Labels: ready, force-merge

#14358 [Build] Add nightly wheel fallback when latest commit wheel unavailable
  setup.py
Labels: ready, ci/build

#14402 [GH] Auto-apply multi-modality label to relevant PRs
  .github/mergify.yml
Labels: ready, ci/build

#14414 correct wrong markdown syntax
  docs/source/design/huggingface_integration.md
Labels: documentation, ready

#14422 [Bugfix] Further clean up LoRA test
  tests/lora/conftest.py
  tests/lora/test_mixtral.py
  tests/lora/test_quant_model.py
Labels: ready

#14417 [Bugfix] Clean up multi-modal processors
  vllm/config.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/registry.py
Labels: ready, multi-modality

#14274 [Misc] Set default value of seed to None
  tests/distributed/test_torchrun_example.py
  tests/entrypoints/llm/test_encode.py
  tests/entrypoints/llm/test_guided_generate.py
  tests/entrypoints/openai/test_chat_echo.py
  tests/entrypoints/openai/test_metrics.py
  tests/entrypoints/openai/test_root_path.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/llm.py
  vllm/utils.py
Labels: structured-output, frontend, ready

#12712 [BUGFIX] Skip tokenization support for throughput benchmark
  benchmarks/benchmark_throughput.py
  vllm/engine/arg_utils.py
Labels: ready, force-merge

#14329 Use the optimized block sizes after tuning the kernel.
  vllm/v1/attention/backends/pallas.py
Labels: ready, v1

#14420 [Doc] Update prefix_caching.md to match the example image
  docs/source/design/v1/prefix_caching.md
Labels: documentation, ready

#14343 [Misc] Add Phi4-MM example
  examples/offline_inference/audio_language.py
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  vllm/model_executor/models/phi4mm.py
Labels: documentation, ready

#14437 [v1] torch.compile integration explanation
  docs/source/design/v1/torch_compile.md
  docs/source/index.md
  vllm/compilation/compiler_interface.py
Labels: documentation

#14388 [V1] Eagerly remove finished requests from the batch
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/metrics/loggers.py
  vllm/v1/outputs.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: ready, v1

#14220 [V1][Metrics] Fix traceback with preemptions+LoRA
  vllm/v1/metrics/stats.py
Labels: ready, v1

#14459 [Bugfix] Fix torch_xla which can't handle None seed introduced in #14274
  vllm/v1/worker/tpu_worker.py
Labels: ready, v1

#13949 [V1] Prompt logprobs + APC compatibility; prompt logprobs reqs cannot fill APC
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_scheduler.py
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_llm_engine.py
  tests/v1/engine/utils.py
  tests/v1/sample/test_logprobs.py
  tests/v1/sample/utils.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/engine/processor.py
Labels: documentation, structured-output, frontend, speculative-decoding, ready, ci/build, v1

#14462 [Bugfix][V1] Handle MLA in kv_cache_interface
  vllm/v1/kv_cache_interface.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: ready, v1

#14471 Revert "[Perf] Reduce MLA CPU overheads in V1 (#14384)"
  vllm/model_executor/layers/rotary_embedding.py
  vllm/v1/attention/backends/mla/common.py
Labels: v1

#14369 [Bugfix][Disaggregated] Add a check in send_kv_caches_and_hidden_states and fix the reshape of the KVCache
  vllm/distributed/kv_transfer/kv_connector/simple_connector.py
Labels: ready

#14380 [MISC][V1] Register process killing handler only in the main thread
  vllm/v1/engine/core_client.py
Labels: ready, v1

#13300 [core] add `extra_args` to `SamplingParams`
  vllm/sampling_params.py
Labels: ready

#12888 [CI/Build] refactor: set timezone of container to UTC
  Dockerfile
Labels: ready, ci/build

#14478 [Doc]add doc for Qwen models tool calling
  docs/source/features/tool_calling.md
Labels: documentation, ready

#14479 [Doc] Added QwQ-32B to the supported models list in the reasoning out…
  docs/source/features/reasoning_outputs.md
Labels: documentation, ready

#14469 [Bugfix] Make the deviceprofiler include LoRA memory.
  vllm/worker/model_runner.py
Labels: ready

#14439 Add training doc signposting to TRL
  docs/source/index.md
  docs/source/training/trl.md
Labels: documentation, ready

#14482 Add RLHF document
  docs/source/generate_examples.py
  docs/source/index.md
  docs/source/training/rlhf.md
Labels: documentation, ready

#14480 [CI/Build] Use a fixed seed to avoid flaky tests
  tests/entrypoints/openai/test_chat_echo.py
  tests/entrypoints/openai/test_metrics.py
  tests/entrypoints/openai/test_root_path.py
  tests/utils.py
Labels: ready

#13618 [V1] TPU - Add tensor parallel support via Ray
  tests/entrypoints/llm/test_accuracy.py
  tests/v1/tpu/__init__.py
  tests/v1/tpu/test_basic.py
  vllm/executor/ray_distributed_executor.py
  vllm/executor/ray_utils.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, ci/build, v1

#14453 [VLM] Add TP support for Phi-4-MM
  examples/offline_inference/audio_language.py
  vllm/model_executor/models/phi4mm.py
  vllm/model_executor/models/phi4mm_audio.py
  vllm/model_executor/models/phi4mm_utils.py
Labels: documentation, ready

#14407 [Misc] add `use_tqdm_on_load` to reduce logs
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#13776 [V1][Core] Fix memory issue with logits & sampling
  tests/basic_correctness/test_cumem.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#12547 Move requirements into their own directory
  .buildkite/nightly-benchmarks/scripts/run-nightly-benchmarks.sh
  .buildkite/run-cpu-test.sh
  .buildkite/test-pipeline.yaml
  .github/workflows/publish.yml
  .github/workflows/scripts/build.sh
  .pre-commit-config.yaml
  .readthedocs.yaml
  Dockerfile
  Dockerfile.arm
  Dockerfile.cpu
  Dockerfile.hpu
  Dockerfile.neuron
  Dockerfile.openvino
  Dockerfile.ppc64le
  Dockerfile.rocm
  Dockerfile.s390x
  Dockerfile.tpu
  Dockerfile.xpu
  MANIFEST.in
  docs/README.md
  docs/source/contributing/overview.md
  docs/source/getting_started/installation/ai_accelerator/hpu-gaudi.inc.md
  docs/source/getting_started/installation/ai_accelerator/neuron.inc.md
  docs/source/getting_started/installation/ai_accelerator/openvino.inc.md
  docs/source/getting_started/installation/ai_accelerator/tpu.inc.md
  docs/source/getting_started/installation/cpu/apple.inc.md
  docs/source/getting_started/installation/cpu/build.inc.md
  docs/source/getting_started/installation/gpu/cuda.inc.md
  docs/source/getting_started/installation/gpu/rocm.inc.md
  docs/source/getting_started/installation/gpu/xpu.inc.md
  format.sh
  pyproject.toml
  requirements/build.txt
  requirements/common.txt
  requirements/cpu.txt
  requirements/cuda.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/hpu.txt
  requirements/lint.txt
  requirements/neuron.txt
  requirements/openvino.txt
  requirements/rocm-build.txt
  requirements/rocm.txt
  requirements/test.in
  requirements/test.txt
  requirements/tpu.txt
  requirements/xpu.txt
  setup.py
  use_existing_torch.py
Labels: documentation, ready, ci/build

#14476 [Bugfix] DeepSeek Accuracy
  vllm/v1/attention/backends/mla/common.py
Labels: ready, v1

#14361 [Bugfix] Fix profiling OOM and decouple encoder multimodal profiling
  tests/multimodal/test_processing.py
  vllm/inputs/registry.py
  vllm/multimodal/profiling.py
Labels: ready, multi-modality

#14496 Update CODEOWNERS for structured output
  .github/CODEOWNERS
Labels: ready, ci/build

#14492 [Misc] Upgrade to Python 3.9 typing for additional directories
  pyproject.toml
  vllm/assets/video.py
  vllm/inputs/data.py
  vllm/inputs/parse.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
  vllm/multimodal/base.py
  vllm/multimodal/hasher.py
  vllm/multimodal/image.py
  vllm/multimodal/registry.py
  vllm/multimodal/video.py
  vllm/usage/usage_lib.py
Labels: ready, multi-modality

#13376 [V1] Support bad_words in sampler
  tests/test_utils.py
  tests/v1/sample/test_rejection_sampler.py
  tests/v1/sample/test_sampler.py
  tests/v1/sample/test_sampling_params_e2e.py
  tests/v1/worker/test_gpu_input_batch.py
  vllm/sampling_params.py
  vllm/utils.py
  vllm/v1/engine/processor.py
  vllm/v1/sample/metadata.py
  vllm/v1/sample/ops/bad_words.py
  vllm/v1/sample/sampler.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#14504 Revert "[V1][Core] Fix memory issue with logits & sampling"
  tests/basic_correctness/test_cumem.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#14451 [Attention] Default to FlashMLA backend for MLA
  vllm/platforms/cuda.py
Labels: ready, force-merge

#14467 [V1][TPU] Remove unnecessary padding for running on TPU.
  vllm/v1/attention/backends/pallas.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#14505 [Feat] Support chunked prefill for LMCache connector
  vllm/distributed/kv_transfer/kv_connector/lmcache_connector.py
Labels: ready

#12428 [Bugfix] Fix tqdm progress bar when SamplingParams.n > 1
  vllm/entrypoints/llm.py
Labels: frontend, ready

#14498 [Bugfix] Revert QKVCrossParallelLinear usage in Mllama to keep BNB quantization work
  vllm/model_executor/models/mllama.py
Labels: ready

#14510 [Hardware][TPU] Fix the recompiling issue in logits processor after warmup
  examples/offline_inference/tpu.py
  vllm/v1/worker/tpu_model_runner.py
Labels: documentation, ready, v1
