Repository vllm-project/vllm, pull requests merged in 2025-04, with the labels that each got.

#14125 [Distributed] Add custom allreduce support for ROCM
  CMakeLists.txt
  csrc/custom_all_reduce.cu
  csrc/custom_all_reduce.cuh
  csrc/custom_all_reduce_test.cu
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/distributed/test_custom_all_reduce.py
  tests/utils.py
  vllm/_custom_ops.py
  vllm/config.py
  vllm/distributed/device_communicators/custom_all_reduce.py
  vllm/platforms/cuda.py
  vllm/platforms/rocm.py
Labels: rocm, ready, ci/build

#15829 Rename fallback model and refactor supported models section
  docs/source/index.md
  docs/source/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/transformers.py
Labels: documentation, ready

#14886 [Frontend] Add Phi-4-mini function calling support
  examples/tool_chat_template_phi4_mini.jinja
  vllm/entrypoints/openai/tool_parsers/__init__.py
  vllm/entrypoints/openai/tool_parsers/phi4mini_tool_parser.py
Labels: documentation, frontend, ready

#15824 [Bugfix]: Fix is_embedding_layer condition in VocabParallelEmbedding
  vllm/model_executor/layers/vocab_parallel_embedding.py
Labels: ready, force-merge

#15834 [V1] TPU - Fix fused MOE
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#14097 [V1] Implement sliding window attention in kv_cache_manager
  tests/core/block/e2e/test_correctness_sliding_window.py
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_scheduler.py
  tests/v1/core/test_specialized_manager.py
  tests/v1/e2e/test_correctness_sliding_window.py
  vllm/config.py
  vllm/v1/core/block_pool.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/core/specialized_manager.py
  vllm/v1/engine/core.py
  vllm/v1/kv_cache_interface.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#15792 fix: can not use uv run collect_env close #13888
  collect_env.py
Labels: ready

#15798 [Feature] specify model in config.yaml
  docs/source/serving/openai_compatible_server.md
  tests/config/test_config.yaml
  tests/config/test_config_with_model.yaml
  tests/conftest.py
  tests/test_utils.py
  vllm/entrypoints/cli/serve.py
  vllm/utils.py
Labels: documentation, frontend, ready

#15868 [Docs] Fix small error in link text
  docs/source/models/supported_models.md
Labels: documentation, ready

#15828 [Bugfix] Fix no video/image profiling edge case for `MultiModalDataParser`
  vllm/multimodal/parse.py
Labels: ready, multi-modality

#15831 [Misc] Use envs.VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE
  vllm/envs.py
  vllm/executor/ray_distributed_executor.py
Labels: ready

#15725 setup correct nvcc version with CUDA_HOME
  setup.py
Labels: ready, ci/build

#15505 [Model] Support Mistral3 in the HF Transformers format
  docs/source/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/registry.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/mistral3.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/vision.py
Labels: documentation, new model, frontend, ready, ci/build

#15746 [Misc] remove unused script
  python_only_dev.py
Labels: ready

#15884 Remove `format.sh` as it's been unsupported >70 days
  format.sh
Labels: ready

#15876 [New Model]: jinaai/jina-reranker-v2-base-multilingual
  docs/source/models/supported_models.md
  tests/models/embedding/language/test_jina_reranker_v2.py
  vllm/model_executor/models/roberta.py
Labels: documentation, ready

#15861 [Doc] Quark quantization documentation
  docs/source/features/quantization/index.md
  docs/source/features/quantization/quark.md
Labels: documentation

#15890 Reinstate `format.sh` and make `pre-commit` installation simpler
  .pre-commit-config.yaml
  format.sh
Labels: ready

#15055 [Misc] Allow using OpenCV as video IO fallback
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
  setup.py
  vllm/assets/video.py
  vllm/multimodal/video.py
Labels: ready, ci/build, multi-modality

#15820 [ROCm][Build][Bugfix] Bring the base dockerfile in sync with the ROCm fork
  docker/Dockerfile.rocm_base
  requirements/rocm-build.txt
Labels: ci/build

#13932 Add option to use DeepGemm contiguous grouped gemm kernel for fused MoE operations.
  benchmarks/kernels/benchmark_moe.py
  tests/kernels/test_block_fp8.py
  vllm/_custom_ops.py
  vllm/envs.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/quantization/fp8.py
Labels: ready, ci/build

#15867 [CI/Build] Clean up LoRA tests
  tests/lora/test_baichuan.py
  tests/lora/test_gemma.py
  tests/lora/test_layers.py
  tests/lora/test_minicpmv_tp.py
  tests/lora/test_transfomers_model.py
Labels: ready

#15441 [Model] Aya Vision
  docs/source/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/registry.py
Labels: documentation, frontend, ready, multi-modality

#15889 [Model] Add module name prefixes to gemma3
  vllm/model_executor/models/gemma3.py
Labels: ready

#15729 [V1][Spec Decode] Implement Eagle Proposer [1/N]
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/v1/spec_decode/eagle.py
  vllm/v1/spec_decode/ngram_proposer.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#15898 [Docs] update usage stats language
  docs/source/serving/usage_stats.md
Labels: documentation

#15875 [BugFix] make sure socket close
  vllm/entrypoints/openai/api_server.py
Labels: bug, frontend, ready

#13454 [Model][MiniMaxText01] Support MiniMaxText01 model inference
  docs/source/models/supported_models.md
  tests/kernels/test_lightning_attn.py
  tests/models/registry.py
  vllm/config.py
  vllm/engine/async_llm_engine.py
  vllm/model_executor/layers/lightning_attn.py
  vllm/model_executor/models/constant_size_cache.py
  vllm/model_executor/models/mamba_cache.py
  vllm/model_executor/models/minimax_cache.py
  vllm/model_executor/models/minimax_text_01.py
  vllm/model_executor/models/registry.py
Labels: documentation, structured-output, frontend, speculative-decoding, ready, ci/build, v1, multi-modality

#15905 [Docs] Add Ollama meetup slides
  README.md
  docs/source/community/meetups.md
Labels: documentation

#15909 Fix input triton kernel for eagle
  vllm/v1/spec_decode/eagle.py
Labels: v1

#15907 [V1] Fix: make sure `k_index` is int64 for `apply_top_k_only`
  vllm/v1/sample/ops/topk_topp_sampler.py
Labels: v1

#15841 [Bugfix] Fix imports for MoE on CPU
  vllm/model_executor/layers/fused_moe/rocm_aiter_fused_moe.py
Labels: ready

#15902 [V1][Minor] Enhance SpecDecoding Metrics Log in V1
  vllm/v1/spec_decode/metrics.py
Labels: ready, v1

#15917 [Doc] Update rocm.inc.md
  docs/source/getting_started/installation/gpu/rocm.inc.md
Labels: documentation

#15927 [V1][Bugfix] Fix typo in MoE TPU checking
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#15866 [Benchmark]Fix error message
  benchmarks/benchmark_dataset.py
  benchmarks/benchmark_serving.py
Labels: ready

#15923 [Misc] Replace print with logger
  vllm/entrypoints/openai/tool_parsers/phi4mini_tool_parser.py
Labels: frontend

#15920 [CI/Build] Further clean up LoRA tests
  .buildkite/test-pipeline.yaml
  tests/lora/conftest.py
  tests/lora/test_layers.py
  tests/lora/test_llama_tp.py
  tests/lora/test_minicpmv_tp.py
  tests/lora/test_transfomers_model.py
Labels: ready, ci/build

#15848 [Bugfix] Fix cache block size calculation for CPU MLA
  vllm/worker/cpu_worker.py
Labels: ready

#15879 [Kernel] Add more dtype support for GGUF dequantization
  csrc/ops.h
  csrc/quantization/gguf/dequantize.cuh
  csrc/quantization/gguf/ggml-common.h
  csrc/quantization/gguf/gguf_kernel.cu
  csrc/torch_bindings.cpp
  tests/kernels/test_ggml.py
  tests/kernels/test_gguf.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/gguf.py
Labels: ready

#15500 [core] Add tags parameter to wake_up()
  tests/basic_correctness/test_cumem.py
  tests/entrypoints/openai/test_sleep.py
  vllm/device_allocator/cumem.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/api_server.py
  vllm/executor/executor_base.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/worker/gpu_worker.py
  vllm/worker/worker.py
Labels: frontend, ready, v1

#15488 [V1] Fix json_object support with xgrammar
  requirements/common.txt
  tests/v1/entrypoints/llm/test_struct_output_generate.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
  vllm/v1/structured_output/backend_xgrammar.py
Labels: structured-output, ready, ci/build, v1

#15873 Add minimum version for `huggingface_hub` to enable Xet downloads
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
Labels: ci/build

#15940 [CI] Remove duplicate entrypoints-test
  .buildkite/test-pipeline.yaml
Labels: ci/build

#15938 [Bugfix] Fix the issue where the model name is empty string, causing no response with the model name.
  tests/entrypoints/openai/test_chat.py
  vllm/entrypoints/openai/serving_engine.py
Labels: frontend

#15458 [Metrics] Hide deprecated metrics
  tests/entrypoints/openai/test_metrics.py
  tests/utils.py
  vllm/engine/metrics.py
  vllm/version.py
Labels: ready

#15934 [CPU][Bugfix] Using custom allreduce for CPU backend
  cmake/cpu_extension.cmake
  csrc/cpu/cpu_types_x86.hpp
  csrc/cpu/shm.cpp
  csrc/cpu/torch_bindings.cpp
  csrc/cpu/utils.cpp
  docs/source/getting_started/installation/cpu.md
  vllm/distributed/device_communicators/cpu_communicator.py
  vllm/worker/cpu_worker.py
Labels: documentation, ready, ci/build

#15770 [Model] use AutoWeightsLoader in model load_weights
  docs/source/models/supported_models.md
  vllm/model_executor/models/bamba.py
  vllm/model_executor/models/exaone.py
  vllm/model_executor/models/falcon.py
Labels: documentation, ready

#15859 Restricted cmake to be less than version 4 as 4.x breaks the build of…
  docker/Dockerfile.ppc64le
Labels: ready, ci/build

#15950 [V1] Support Mistral3 in V1
  docs/source/models/supported_models.md
  vllm/model_executor/models/mistral3.py
Labels: documentation

#15969 Fix `huggingface-cli[hf-xet]` -> `huggingface-cli[hf_xet]`
  requirements/common.txt
  requirements/test.in
Labels: ready, ci/build

#15736 [V1][TPU] TPU-optimized top-p implementation (avoids scattering).
  .buildkite/run-tpu-v1-test.sh
  tests/v1/tpu/test_topk_topp_sampler.py
  vllm/v1/sample/ops/topk_topp_sampler.py
Labels: tpu, ready, ci/build, v1

#15903 [TPU] optimize the all-reduce performance
  vllm/distributed/device_communicators/tpu_communicator.py
  vllm/distributed/parallel_state.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#15883 [V1][TPU] Do not compile sampling more than needed
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#15943 fix: better error message for get_config close #13889
  vllm/transformers_utils/config.py
Labels: ready

#15980 [bugfix] add seed in torchrun_example.py
  examples/offline_inference/torchrun_example.py
  vllm/config.py
Labels: documentation

#15982 [ROCM][V0] PA kennel selection when no sliding window provided
  vllm/platforms/rocm.py
Labels: ready

#15955 [Benchmark] Add AIMO Dataset to Benchmark
  benchmarks/benchmark_dataset.py
  benchmarks/benchmark_serving.py
Labels: ready

#15994 [misc] improve error message for "Failed to infer device type"
  vllm/config.py
Labels: ready

#15367 [Bugfix][V1] Fix bug from putting llm_engine.model_executor in a background process
  examples/offline_inference/load_sharded_state.py
  examples/offline_inference/save_sharded_state.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/worker/gpu_worker.py
Labels: documentation, ready, v1

#15922 [doc] update contribution link
  README.md
Labels: documentation, ready

#15573 [SupportsQuant] Bert, Blip, Blip2, Bloom
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/blip.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/bloom.py
Labels: documentation, structured-output, frontend, speculative-decoding, ci/build, v1, multi-modality

#15952 [SupportsQuant] Chameleon, Chatglm, Commandr
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/chatglm.py
  vllm/model_executor/models/commandr.py
Labels: documentation, structured-output, frontend, ci/build, v1

#15914 [Minor] Fused experts refactor
  tests/kernels/test_block_fp8.py
  tests/kernels/test_cutlass_moe.py
  vllm/model_executor/layers/fused_moe/__init__.py
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/deep_gemm_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/moe_align_block_size.py
  vllm/model_executor/layers/fused_moe/utils.py
Labels: ready

#16024 [Misc][Performance] Advance tpu.txt to the most recent nightly torch …
  requirements/tpu.txt
Labels: ready, ci/build

#15586 Re-enable the AMD Testing for the passing tests.
  .buildkite/run-amd-test.sh
  .buildkite/test-pipeline.yaml
Labels: ci/build

#15981 [TPU] Switch Test to Non-Sliding Window
  tests/tpu/test_compilation.py
Labels: tpu, ready

#16033 [Bugfix] Fix function names in test_block_fp8.py
  tests/kernels/test_block_fp8.py
Labels: bug, ready

#14252 [ROCm] Tweak the benchmark script to run on ROCm
  .buildkite/nightly-benchmarks/scripts/run-performance-benchmarks.sh
Labels: rocm, ci/build

#15974 [Misc] improve gguf check
  vllm/transformers_utils/utils.py
Labels: ready

#16041 [TPU][V1] Remove ragged attention kernel parameter hard coding
  vllm/v1/attention/backends/pallas.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#16023 [V1][Spec Decode] Avoid logging useless nan metrics
  tests/v1/core/test_scheduler.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#15945 [Hardware][Gaudi][BugFix] fix arguments of hpu fused moe
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#15995 [Bugfix][kernels] Fix half2float conversion in gguf kernels
  csrc/quantization/gguf/ggml-common.h
Labels: ready

#15998 [Benchmark][Doc] Update throughput benchmark and README
  benchmarks/README.md
  benchmarks/benchmark_throughput.py
Labels: ready

#16002 [CPU] Change default block_size for CPU backend
  vllm/platforms/cpu.py
Labels: ready

#16010 [Distributed] [ROCM] Fix custom allreduce enable checks
  vllm/config.py
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
Labels: ready

#15717 [ROCm][Bugfix] Use platform specific FP8 dtype
  vllm/attention/ops/prefix_prefill.py
Labels: ready

#15413 [ROCm][Bugfix] Bring back fallback to eager mode removed in #14917, but for ROCm only
  vllm/config.py
Labels: ready

#16057 [Bugfix] Fix default behavior/fallback for pp in v1
  vllm/engine/arg_utils.py
Labels: bug, ready, v1

#15906 [V1] DP scale-out (1/N): Use zmq ROUTER/DEALER sockets for input queue
  vllm/utils.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/utils.py
Labels: ready, v1

#16075 Revert "[V1] Scatter and gather placeholders in the model runner"
  docs/source/contributing/model/multimodal.md
  docs/source/models/supported_models.md
  examples/offline_inference/audio_language.py
  tests/models/decoder_only/audio_language/test_ultravox.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_pixtral.py
  tests/models/multimodal/processing/test_llava_next.py
  tests/models/multimodal/processing/test_llava_onevision.py
  tests/models/registry.py
  tests/multimodal/test_processing.py
  tests/v1/core/test_kv_cache_utils.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma3_mm.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mistral3.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen_vl.py
  vllm/model_executor/models/skyworkr1v.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/base.py
  vllm/multimodal/inputs.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/utils.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/request.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/utils.py
Labels: documentation, tpu, v1, multi-modality

#16071 [Kernel][Bugfix] Re-fuse triton moe weight application
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: bug, moe, ready

#16059 [Bugfix][TPU] Fix V1 TPU worker for sliding window
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#15750 [V1][Spec Decode] Update N-gram Proposer Interface
  vllm/v1/spec_decode/ngram_proposer.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, v1

#16027 [Misc] Auto detect bitsandbytes pre-quantized models
  docs/source/features/quantization/bnb.md
  tests/quantization/test_bitsandbytes.py
  vllm/engine/arg_utils.py
Labels: documentation, quantization, ready

#16089 [CI] Fix benchmark script level
  .buildkite/scripts/run-benchmarks.sh
Labels: ready, ci/build

#16086 fix: support clang17 for macos and fix the real libomp
  cmake/cpu_extension.cmake
Labels: ready, ci/build

#16082 [doc] fix 404
  docs/source/models/supported_models.md
Labels: documentation, ready

#16091 Revert "doc: add info for macos clang errors (#16049)"
  docs/source/getting_started/installation/cpu/apple.inc.md
Labels: documentation, ready

#16094 Fix some capitalisations in generated examples doc titles
  docs/source/generate_examples.py
Labels: documentation, ready

#16095 [Misc] format output for encoder_decoder.py
  examples/offline_inference/encoder_decoder.py
Labels: documentation

#16098 [Misc] Remove redundant code
  vllm/entrypoints/chat_utils.py
Labels: frontend, ready

#15946 [Bugfix] fix use_atomic_add support of marlin kernel when using v1 engine
  csrc/quantization/gptq_marlin/gptq_marlin.cu
  vllm/model_executor/layers/quantization/utils/marlin_utils.py
Labels: ready

#16104 [Model] Support Llama4 in vLLM
  benchmarks/kernels/benchmark_moe.py
  docs/source/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_llama4.py
  tests/models/registry.py
  tests/models/test_registry.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/layers/fused_moe/configs/E=16,N=1024,device_name=AMD_Instinct_MI300X.json
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/experts_int8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/gguf.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/moe_wna16.py
  vllm/model_executor/layers/quantization/quark/quark_moe.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llama4.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/registry.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/triton_attn.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, frontend, ready, ci/build, v1, multi-modality

#16022 [Benchmark] Add sampling parameters to benchmark_serving.
  benchmarks/README.md
  benchmarks/backend_request_func.py
  benchmarks/benchmark_serving.py
Labels: ready

#14501 [Frontend] Fix typo in tool chat templates for llama3.2 and toolace
  examples/tool_chat_template_llama3.2_pythonic.jinja
  examples/tool_chat_template_toolace.jinja
Labels: documentation, ready

#16100 [Misc] refactor example eagle
  examples/offline_inference/eagle.py
Labels: documentation, ready

#16025 [Doc][Bugfix] Add missing EOF in k8s deploy doc
  docs/source/deployment/k8s.md
Labels: documentation, ready

#16119 [Misc] Improve model redirect to accept json dictionary
  vllm/envs.py
  vllm/transformers_utils/utils.py
Labels: ready

#16103 [Model] use AutoWeightsLoader for stablelm,starcoder2,zamba2
  vllm/model_executor/models/stablelm.py
  vllm/model_executor/models/starcoder2.py
  vllm/model_executor/models/zamba2.py
Labels: ready

#16040 [Bugfix] LoRA : Fix the order in which the kernels process LoRAs
  vllm/lora/ops/triton_ops/lora_kernel_metadata.py
Labels: ready

#16093 [Bugfix] add hf_token to EngineArgs
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/entrypoints/llm.py
  vllm/transformers_utils/config.py
Labels: frontend, ready

#16116 [Misc] update requires-python in pyproject.toml
  pyproject.toml
Labels: ready

#16135 [V1][Minor] Optimize get_cached_block
  vllm/v1/core/block_pool.py
Labels: ready, v1

#15202 [Metrics] Add bucket for `request_latency`, `time_to_first_token` and `time_per_output_token`
  vllm/engine/metrics.py
  vllm/v1/metrics/loggers.py
Labels: ready, v1

#16139 [V1][Minor] Minor simplification for get_computed_blocks
  vllm/v1/core/kv_cache_manager.py
Labels: ready, v1

#16147 [Misc] Update Mistral-3.1 example
  examples/offline_inference/mistral-small.py
Labels: documentation, ready

#16129 [Bugfix] Make dummy encoder prompt padding alternative and add missing warnings
  tests/models/multimodal/processing/test_mllama.py
  tests/models/utils.py
  vllm/model_executor/models/whisper.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
Labels: ready, multi-modality

#16149 [CI] Set max transformers version for Ultravox model test
  tests/models/registry.py
Labels: ready

#16154 doc: fix some typos in doc
  docs/source/design/mm_processing.md
  docs/source/design/v1/torch_compile.md
  docs/source/features/quantization/gguf.md
Labels: documentation, ready

#16148 [V1][Structured Output] Add `supports_structured_output()` method to Platform
  vllm/platforms/cpu.py
  vllm/platforms/cuda.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
  vllm/v1/engine/processor.py
Labels: tpu, ready, v1

#16175 [Misc] improve example mlpspeculator and llm_engine_example
  examples/offline_inference/llm_engine_example.py
  examples/offline_inference/mlpspeculator.py
Labels: documentation, ready

#16186 [Doc]Update image to latest version
  docs/source/deployment/docker.md
Labels: documentation, ready

#16113 Upstream Llama4 Support to Main
  .buildkite/test-pipeline.yaml
  benchmarks/kernels/benchmark_moe.py
  docs/source/models/supported_models.md
  examples/offline_inference/audio_language.py
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
  tests/models/decoder_only/audio_language/test_ultravox.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_phi3v.py
  tests/models/decoder_only/vision_language/test_pixtral.py
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_llama4.py
  tests/models/registry.py
  tests/models/test_initialization.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/layers/fused_moe/configs/E=16,N=1024,device_name=AMD_Instinct_MI300X.json
  vllm/model_executor/layers/fused_moe/cutlass_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/layernorm.py
  vllm/model_executor/layers/quantization/awq_marlin.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/experts_int8.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/gguf.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/moe_wna16.py
  vllm/model_executor/layers/quantization/quark/quark_moe.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llama4.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/telechat2.py
  vllm/model_executor/models/teleflm.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/triton_attn.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, frontend, ready, ci/build, v1, multi-modality

#16187 [Bugfix] Re-enable support for `ChatGLMForConditionalGeneration`
  docs/source/models/supported_models.md
  tests/models/registry.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready

#16158 [V1] Revert the default `max_num_seqs` to V0 values for most hardware
  docs/source/getting_started/v1_user_guide.md
  tests/v1/engine/test_engine_args.py
  vllm/engine/arg_utils.py
Labels: documentation, ready, v1

#16181 [Misc] Human-readable `max-model-len` cli arg
  tests/engine/test_arg_utils.py
  vllm/engine/arg_utils.py
Labels: ready

#16201 [Misc] Move Llama 4 projector call into encoder execution
  vllm/model_executor/models/mllama4.py
Labels: ready

#16210 [Bugfix] Fix guidance backend for Qwen models
  vllm/v1/structured_output/backend_guidance.py
Labels: ready, v1

#16137 [V1][BugFix] Exit properly if engine core fails during startup
  requirements/test.in
  requirements/test.txt
  tests/v1/engine/test_engine_core_client.py
  vllm/v1/engine/core_client.py
  vllm/v1/utils.py
Labels: bug, ready, ci/build, v1

#15921 [Misc] add description attribute in CLI
  vllm/entrypoints/cli/benchmark/base.py
  vllm/entrypoints/cli/benchmark/main.py
  vllm/entrypoints/cli/openai.py
  vllm/entrypoints/cli/serve.py
Labels: frontend, ready

#15878 [Bugfix][V0] XGrammar structured output supports Enum
  tests/entrypoints/llm/test_guided_generate.py
  vllm/model_executor/guided_decoding/utils.py
Labels: structured-output, ready, v0

#14231 Torchao
  docs/source/features/quantization/index.md
  docs/source/features/quantization/torchao.md
  tests/quantization/test_torchao.py
  vllm/model_executor/layers/quantization/__init__.py
  vllm/model_executor/layers/quantization/torchao.py
Labels: documentation, quantization, ready

#16031 [ROCm][Bugfix][FP8] Make fp8 quant respect fused modules mapping
  vllm/model_executor/layers/quantization/fp8.py
Labels: bug, rocm, ready

#16174 [core] do not send error across process
  vllm/v1/executor/multiproc_executor.py
Labels: ready, v1

#16196 [Misc] Update compressed-tensors to version 0.9.3
  requirements/common.txt
Labels: ready, ci/build

#16218 Update BASE_IMAGE to 2.22 release of Neuron
  docker/Dockerfile.neuron
Labels: ci/build

#16076 [V1] Scatter and gather placeholders in the model runner
  docs/source/contributing/model/multimodal.md
  docs/source/models/supported_models.md
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_pixtral.py
  tests/models/multimodal/processing/test_llama4.py
  tests/models/multimodal/processing/test_llava_next.py
  tests/models/multimodal/processing/test_llava_onevision.py
  tests/multimodal/test_processing.py
  tests/v1/core/test_kv_cache_utils.py
  vllm/model_executor/models/aya_vision.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/gemma3_mm.py
  vllm/model_executor/models/h2ovl.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/internvl.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/minicpmo.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mistral3.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/nvlm_d.py
  vllm/model_executor/models/paligemma.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen_vl.py
  vllm/model_executor/models/skyworkr1v.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/base.py
  vllm/multimodal/inputs.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/utils.py
  vllm/v1/core/kv_cache_utils.py
  vllm/v1/core/sched/scheduler.py
  vllm/v1/request.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/utils.py
Labels: documentation, tpu, ready, v1, multi-modality

#16161 [Bugfix] fix use-ep bug to enable ep by dp/tp size > 1
  vllm/model_executor/layers/fused_moe/layer.py
Labels: ready

#16212 Add warning for Attention backends that do not support irope yet
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/v1/attention/backends/pallas.py
Labels: tpu, ready, v1

#16194 [Bugfix] Fix and reorganize broken GGUF tests and bump gguf version
  requirements/common.txt
  tests/models/decoder_only/language/test_gguf.py
Labels: ready, ci/build

#15782 [torch.compile][TPU] Make @support_torch_compile work for XLA backend
  vllm/v1/worker/tpu_model_runner.py
  vllm/v1/worker/tpu_worker.py
Labels: tpu, ready, v1

#15837 [V1] Add `disable_chunked_mm_input` arg to disable partial mm input prefill
  tests/v1/core/test_scheduler.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#16225 [Misc] Merge the logs of pp layers partitions
  vllm/distributed/utils.py
Labels: ready

#16213 [Docs] Add Slides from Singapore Meetup
  README.md
  docs/source/community/meetups.md
Labels: documentation, ready

#16252 [Misc] format and refactor some examples
  examples/offline_inference/mistral-small.py
  examples/offline_inference/multilora_inference.py
  examples/offline_inference/neuron.py
  examples/offline_inference/neuron_int8_quantization.py
  examples/offline_inference/prefix_caching.py
  examples/offline_inference/reproduciblity.py
  examples/offline_inference/rlhf.py
  examples/offline_inference/simple_profiling.py
  examples/offline_inference/torchrun_example.py
  examples/offline_inference/tpu.py
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_embedding.py
  examples/offline_inference/vision_language_multi_image.py
Labels: documentation, tpu, ready

#16241 [Misc] Add warning for multimodal data in LLM.beam_search
  vllm/entrypoints/llm.py
Labels: frontend, ready

#16203 [Model] use AutoWeightsLoader for phimoe,qwen2_moe,qwen3_moe
  vllm/model_executor/models/phimoe.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/qwen3_moe.py
Labels: ready

#16247 [BugFix][ROCm] Fix GGUF MoE Dispatch Block_Dim for ROCm
  csrc/quantization/gguf/moe.cuh
Labels: ready

#16256 [Bugfix] Remove triton do_bench fast_flush arg
  tests/kernels/test_flashmla.py
Labels: ready

#16257 Update to transformers==4.51.1
  requirements/common.txt
  requirements/test.in
  requirements/test.txt
Labels: ready, ci/build

#16272 [Misc] Avoid stripping meaningful whitespace from `nvidia-smi topo -m` output in collect_env.py
  collect_env.py
Labels: ready

#16156 [Bugfix] Proper input validation for multi-modal encoder-decoder models
  examples/offline_inference/encoder_decoder_multimodal.py
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/engine/test_short_mm_context.py
  tests/entrypoints/llm/test_prompt_validation.py
  tests/entrypoints/openai/test_prompt_validation.py
  tests/models/encoder_decoder/vision_language/test_mllama.py
  vllm/engine/llm_engine.py
  vllm/multimodal/profiling.py
  vllm/v1/engine/processor.py
Labels: documentation, ready, v1, multi-modality

#15328 [Bugfix] Handle `process_weights_after_loading` for `QKVCrossParallelLinear`
  vllm/model_executor/layers/linear.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/model_loader/loader.py
Labels: bug, ready, force-merge

#16276 Add warning that content below line in template will be removed
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready, ci/build

#16209 [BugFix] Fix Llama4 - Index Error When Single Request Near Max Context
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, v1

#14809 [Bugfix] fix deepseek fp16 scale bug
  vllm/model_executor/models/deepseek_v2.py
Labels: bug, ready

#16270 [CI/Build] Fix CI LoRA failure
  tests/lora/conftest.py
  tests/lora/test_baichuan.py
  tests/lora/test_chatglm3_tp.py
  tests/lora/test_layers.py
  tests/lora/test_llama_tp.py
  tests/lora/test_punica_ops.py
  tests/lora/test_quant_model.py
  tests/lora/test_transfomers_model.py
Labels: ready

#15961 Add support to modelopt quantization of Mixtral model
  vllm/model_executor/models/mixtral_quant.py
Labels: ready
