Repository vllm-project/vllm, pull requests merged in 2025-01, with the labels that each got.

#11533 [Benchmark] Add benchmark script for CPU offloading
  benchmarks/benchmark_long_document_qa_throughput.py
Labels: ready

#11660 [Bugfix][Refactor] Unify model management in frontend
  tests/entrypoints/openai/test_cli_args.py
  tests/entrypoints/openai/test_lora_lineage.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/entrypoints/openai/test_serving_models.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/entrypoints/openai/serving_models.py
  vllm/entrypoints/openai/serving_pooling.py
  vllm/entrypoints/openai/serving_score.py
  vllm/entrypoints/openai/serving_tokenization.py
Labels: frontend, ready

#11661 [VLM] Add max-count checking in data parser for single image models
  docs/source/models/supported_models.md
  tests/multimodal/test_processing.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/multimodal/parse.py
Labels: documentation, ready

#11663 [Misc] Optimize Qwen2-VL LoRA test
  tests/lora/test_qwen2vl.py
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#11667 [Misc] Replace space with - in the file names
  .github/ISSUE_TEMPLATE/400-bug-report.yml
  .github/ISSUE_TEMPLATE/500-feature-request.yml
  .github/ISSUE_TEMPLATE/600-new-model.yml
  .github/ISSUE_TEMPLATE/700-performance-discussion.yml
  .github/ISSUE_TEMPLATE/800-misc-discussion.yml
Labels: ready, ci/build

#11666 [Doc] Fix typo
  vllm/model_executor/layers/rejection_sampler.py
  vllm/v1/sample/ops/topk_topp_sampler.py
Labels: ready

#11635 [V1] Implement Cascade Attention
  CMakeLists.txt
  tests/conftest.py
  tests/kernels/test_cascade_flash_attn.py
  tests/system_messages/sonnet3.5_nov2024.txt
  tests/v1/e2e/__init__.py
  tests/v1/e2e/test_cascade_attention.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/scheduler.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready, ci/build

#11669 [VLM] Move supported limits and max tokens to merged multi-modal processor
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_phi3v.py
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_qwen2_vl.py
  tests/multimodal/test_processing.py
  vllm/inputs/registry.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/parse.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
Labels: ready

#11674 [VLM][Bugfix] Multi-modal processor compatible with V1 multi-input
  vllm/multimodal/inputs.py
  vllm/multimodal/processing.py
  vllm/v1/engine/processor.py
Labels: ready

#11680 [mypy] Pass type checking in vllm/inputs
  tools/mypy.sh
  vllm/inputs/data.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
Labels: ready

#11682 [VLM] Merged multi-modal processor for LLaVA-NeXT
  tests/models/decoder_only/vision_language/mm_processor_kwargs/test_llava_next.py
  tests/multimodal/test_mapper.py
  tests/multimodal/test_processing.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/utils.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/parse.py
Labels: ready

#11689 According to vllm.EngineArgs, the name should be distributed_executor_backend
  docs/source/serving/distributed_serving.md
Labels: documentation, ready

#10013 [Bugfix] Free cross attention block table for preempted-for-recompute sequence group.
  vllm/core/scheduler.py
Labels: ready

#11692 [V1][Minor] Optimize token_ids_cpu copy
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#11493 Resolve race conditions in Marlin kernel
  csrc/quantization/gptq_marlin/gptq_marlin.cu
Labels: ready

#11576 [Misc] Minimum requirements for SageMaker compatibility
  Dockerfile
  examples/sagemaker-entrypoint.sh
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready, ci/build

#11694 Update default max_num_batch_tokens for chunked prefill
  docs/source/usage/performance.md
Labels: documentation, ready

#11710 [perf-benchmark] Fix dependency for steps in benchmark pipeline
  .buildkite/nightly-benchmarks/benchmark-pipeline.yaml
Labels: ci/build

#11280 [Model] Whisper model implementation
  .buildkite/test-pipeline.yaml
  examples/offline_inference_whisper.py
  tests/models/encoder_decoder/audio_language/__init__.py
  tests/models/encoder_decoder/audio_language/test_whisper.py
  tests/models/registry.py
  vllm/config.py
  vllm/inputs/preprocess.py
  vllm/model_executor/models/registry.py
  vllm/model_executor/models/whisper.py
  vllm/multimodal/processing.py
  vllm/sequence.py
  vllm/transformers_utils/tokenizer.py
  vllm/transformers_utils/tokenizer_group/base_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/ray_tokenizer_group.py
  vllm/transformers_utils/tokenizer_group/tokenizer_group.py
  vllm/worker/enc_dec_model_runner.py
Labels: ready, ci/build

#11659 [V1] Simplify Shutdown
  tests/v1/engine/test_engine_core_client.py
  vllm/entrypoints/llm.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/utils.py
Labels: frontend, ready

#11708 [Bugfix] Fix ColumnParallelLinearWithLoRA slice
  vllm/lora/layers.py
Labels: ready, ci/build

#11721 [V1] Improve TP>1 Error Handling + Stack Trace
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/executor/multiproc_executor.py
Labels: ready

#11719 [Misc]Add BNB quantization for Qwen2VL
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#11695 Update requirements-tpu.txt to support python 3.9 and 3.11
  requirements-tpu.txt
  vllm/worker/tpu_model_runner.py
Labels: tpu, ready, ci/build

#11724 [V1] Chore: cruft removal
  vllm/entrypoints/llm.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/processor.py
Labels: frontend, ready

#11656 log GPU blocks num for MultiprocExecutor
  vllm/v1/executor/multiproc_executor.py
Labels: ready

#11701 Update tool_calling.md
  docs/source/usage/tool_calling.md
Labels: documentation, ready

#11718 Update bnb.md with example for OpenAI
  docs/source/quantization/bnb.md
Labels: documentation, ready

#11712 [V1] Add `RayExecutor` support for `AsyncLLM` (api server)
  vllm/v1/engine/async_llm.py
Labels: ready

#11513 [V1] Add kv cache utils tests.
  tests/v1/core/test_kv_cache_utils.py
Labels: ready

#11233 [Core][Bugfix] Use correct device to initialize GPU data during CUDA-graph-capture
  tests/distributed/test_custom_all_reduce.py
  tests/distributed/test_pynccl.py
  vllm/distributed/parallel_state.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/model_runner.py
Labels: ready

#11717 [VLM] Merged multi-modal processors for LLaVA-NeXT-Video and LLaVA-OneVision
  tests/models/decoder_only/vision_language/processing/__init__.py
  tests/models/decoder_only/vision_language/processing/test_idefics3.py
  tests/models/decoder_only/vision_language/processing/test_internvl.py
  tests/models/decoder_only/vision_language/processing/test_llava_next.py
  tests/models/decoder_only/vision_language/processing/test_llava_onevision.py
  tests/models/decoder_only/vision_language/processing/test_phi3v.py
  tests/models/decoder_only/vision_language/processing/test_qwen.py
  tests/models/decoder_only/vision_language/processing/test_qwen2_vl.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/test_qwen2_vl.py
  tests/multimodal/test_processing.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/parse.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
  vllm/transformers_utils/tokenizer.py
Labels: ready, ci/build

#11735 [Bugfix] Fix precision error in LLaVA-NeXT feature size calculation
  tests/models/decoder_only/vision_language/processing/test_llava_next.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_onevision.py
Labels: ready

#11736 [Model] Remove unnecessary weight initialization logic
  vllm/model_executor/layers/resampler.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/minicpmv.py
Labels: ready

#11738 [Bugfix][V1] Fix test_kv_cache_utils.py
  tests/v1/core/test_kv_cache_utils.py
Labels: ready

#11744 [distributed] remove pynccl's redundant stream
  tests/distributed/test_pynccl.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/parallel_state.py
Labels: ready

#11752 [Frontend] Improve `StreamingResponse` Exception Handling
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
Labels: frontend, ready

#11749 [distributed] remove pynccl's redundant change_state
  tests/distributed/test_pynccl.py
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/parallel_state.py
Labels: ready

#11645 [Doc] [1/N] Reorganize Getting Started section
  docs/source/design/arch_overview.md
  docs/source/design/multiprocessing.md
  docs/source/getting_started/faq.md
  docs/source/getting_started/installation/cpu-arm.md
  docs/source/getting_started/installation/cpu-x86.md
  docs/source/getting_started/installation/gpu-cuda.md
  docs/source/getting_started/installation/gpu-rocm.md
  docs/source/getting_started/installation/hpu-gaudi.md
  docs/source/getting_started/installation/index.md
  docs/source/getting_started/installation/neuron.md
  docs/source/getting_started/installation/openvino.md
  docs/source/getting_started/installation/tpu.md
  docs/source/getting_started/installation/xpu.md
  docs/source/getting_started/quickstart.md
  docs/source/getting_started/troubleshooting.md
  docs/source/index.md
  docs/source/models/generative_models.md
  docs/source/models/pooling_models.md
  docs/source/serving/distributed_serving.md
  docs/source/usage/spec_decode.md
  docs/source/usage/structured_outputs.md
  vllm/utils.py
Labels: documentation, ready

#11723 [Bugfix] Remove block size constraint
  vllm/config.py
Labels: ready

#11693 [V1] Add BlockTable class
  vllm/v1/worker/block_table.py
  vllm/v1/worker/gpu_input_batch.py
  vllm/v1/worker/gpu_model_runner.py
Labels: ready

#11753 [Misc] Fix typo for valid_tool_parses
  vllm/entrypoints/openai/api_server.py
Labels: frontend, ready

#11754 [V1] Refactor get_executor_cls
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/executor/abstract.py
Labels: ready

#11740 [mypy] Forward pass function type hints in lora
  vllm/lora/layers.py
  vllm/lora/models.py
  vllm/model_executor/layers/linear.py
Labels: ready

#11679 k8s-config: Update the secret to use stringData
  docs/source/serving/deploying_with_k8s.md
Labels: documentation, ready

#11746 [VLM] Separate out profiling-related logic
  tests/multimodal/test_processing.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/registry.py
Labels: ready

#11755 [Doc][2/N] Reorganize Models and Usage sections
  .github/ISSUE_TEMPLATE/600-new-model.yml
  docs/source/assets/features/disagg_prefill/abstraction.jpg
  docs/source/assets/features/disagg_prefill/overview.jpg
  docs/source/contributing/model/basic.md
  docs/source/contributing/model/index.md
  docs/source/contributing/model/multimodal.md
  docs/source/contributing/model/registration.md
  docs/source/design/automatic_prefix_caching.md
  docs/source/design/kernel/paged_attention.md
  docs/source/dev/offline_inference/offline_index.md
  docs/source/features/automatic_prefix_caching.md
  docs/source/features/compatibility_matrix.md
  docs/source/features/disagg_prefill.md
  docs/source/features/lora.md
  docs/source/features/multimodal_inputs.md
  docs/source/features/quantization/auto_awq.md
  docs/source/features/quantization/bnb.md
  docs/source/features/quantization/fp8.md
  docs/source/features/quantization/fp8_e4m3_kvcache.md
  docs/source/features/quantization/fp8_e5m2_kvcache.md
  docs/source/features/quantization/gguf.md
  docs/source/features/quantization/index.md
  docs/source/features/quantization/int8.md
  docs/source/features/quantization/supported_hardware.md
  docs/source/features/spec_decode.md
  docs/source/features/structured_outputs.md
  docs/source/features/tool_calling.md
  docs/source/index.md
  docs/source/models/adding_model.md
  docs/source/models/supported_models.md
  docs/source/performance/optimization.md
  docs/source/serving/engine_args.md
  docs/source/serving/env_vars.md
  docs/source/serving/openai_compatible_server.md
  docs/source/serving/usage_stats.md
  vllm/attention/backends/rocm_flash_attn.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/output_processor/multi_step.py
  vllm/executor/cpu_executor.py
  vllm/platforms/cpu.py
  vllm/spec_decode/spec_decode_worker.py
  vllm/utils.py
  vllm/worker/multi_step_model_runner.py
  vllm/worker/utils.py
Labels: documentation, ready, ci/build

#11771 [doc] explain how to add interleaving sliding window support
  docs/source/contributing/model/basic.md
Labels: documentation

#11676 [Bugfix][V1] Fix molmo text-only inputs
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  vllm/model_executor/models/molmo.py
Labels: ready

#11690 [Kernel] Move attn_type to Attention.__init__()
  tests/kernels/test_encoder_decoder_attn.py
  tests/kernels/utils.py
  vllm/attention/backends/abstract.py
  vllm/attention/backends/blocksparse_attn.py
  vllm/attention/backends/flash_attn.py
  vllm/attention/backends/flashinfer.py
  vllm/attention/backends/hpu_attn.py
  vllm/attention/backends/ipex_attn.py
  vllm/attention/backends/pallas.py
  vllm/attention/backends/rocm_flash_attn.py
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/attention/layer.py
  vllm/model_executor/models/bart.py
  vllm/model_executor/models/bert.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/qwen2.py
  vllm/v1/attention/backends/flash_attn.py
Labels: ready

#11685 [V1] Extend beyond image modality and support mixed-modality inference with Llava-OneVision
  docs/source/models/supported_models.md
  tests/multimodal/test_utils.py
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/molmo.py
  vllm/multimodal/__init__.py
  vllm/multimodal/hasher.py
  vllm/multimodal/inputs.py
  vllm/multimodal/processing.py
  vllm/multimodal/utils.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/mm_input_mapper.py
  vllm/v1/engine/processor.py
  vllm/v1/request.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, ready

#11772 [Bugfix] Fix LLaVA-NeXT feature size precision error (for real)
  tests/models/decoder_only/vision_language/processing/test_llava_next.py
  tests/models/decoder_only/vision_language/processing/test_llava_onevision.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_onevision.py
Labels: documentation, ready

#11776 [Model] Future-proof Qwen2-Audio multi-modal processor
  vllm/model_executor/models/qwen2_audio.py
Labels: ready

#11766 [Doc][3/N] Reorganize Serving section
  README.md
  docs/source/assets/deployment/architecture_helm_deployment.png
  docs/source/contributing/dockerfile/dockerfile.md
  docs/source/contributing/model/registration.md
  docs/source/deployment/docker.md
  docs/source/deployment/frameworks/bentoml.md
  docs/source/deployment/frameworks/cerebrium.md
  docs/source/deployment/frameworks/dstack.md
  docs/source/deployment/frameworks/helm.md
  docs/source/deployment/frameworks/index.md
  docs/source/deployment/frameworks/lws.md
  docs/source/deployment/frameworks/skypilot.md
  docs/source/deployment/frameworks/triton.md
  docs/source/deployment/integrations/index.md
  docs/source/deployment/integrations/kserve.md
  docs/source/deployment/integrations/kubeai.md
  docs/source/deployment/integrations/llamastack.md
  docs/source/deployment/k8s.md
  docs/source/deployment/nginx.md
  docs/source/design/arch_overview.md
  docs/source/features/disagg_prefill.md
  docs/source/features/spec_decode.md
  docs/source/getting_started/installation/gpu-rocm.md
  docs/source/getting_started/installation/hpu-gaudi.md
  docs/source/getting_started/quickstart.md
  docs/source/index.md
  docs/source/models/extensions/index.md
  docs/source/models/extensions/runai_model_streamer.md
  docs/source/models/extensions/tensorizer.md
  docs/source/models/supported_models.md
  docs/source/serving/distributed_serving.md
  docs/source/serving/integrations.md
  docs/source/serving/integrations/index.md
  docs/source/serving/integrations/langchain.md
  docs/source/serving/integrations/llamaindex.md
  docs/source/serving/metrics.md
  docs/source/serving/multimodal_inputs.md
  docs/source/serving/offline_inference.md
  docs/source/serving/openai_compatible_server.md
  docs/source/serving/usage_stats.md
Labels: documentation

#11234 [Kernel][LoRA]Punica prefill kernels fusion
  .buildkite/test-pipeline.yaml
  tests/lora/test_minicpmv.py
  tests/lora/test_minicpmv_tp.py
  tests/lora/test_punica_sizes.py
  tests/lora/test_punica_variation.py
  tests/lora/utils.py
  vllm/lora/ops/sgmv_expand.py
  vllm/lora/ops/sgmv_expand_slice.py
  vllm/lora/ops/sgmv_shrink.py
  vllm/lora/ops/utils.py
  vllm/lora/punica_wrapper/punica_gpu.py
Labels: ready, ci/build

#11784 [Bugfix] Update attention interface in `Whisper`
  vllm/model_executor/models/whisper.py
Labels: ready

#11779 [CI] Fix neuron CI and run offline tests
  .buildkite/run-neuron-test.sh
  Dockerfile.neuron
  examples/offline_inference_neuron.py
Labels: ci/build

#11768 fix init error for MessageQueue when n_local_reader is zero
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#9925 [Doc] Create a vulnerability management team
  SECURITY.md
  docs/source/contributing/vulnerability_management.md
  docs/source/index.md
Labels: documentation

#11788 [CI][CPU] adding build number to docker image name
  .buildkite/run-cpu-test.sh
Labels: ready, ci/build

#11798 [V1][Doc] Update V1 support for `LLaVa-NeXT-Video`
  docs/source/models/supported_models.md
Labels: documentation, ready

#11733 [V1] Support audio language models on V1
  docs/source/models/supported_models.md
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/ultravox.py
Labels: documentation, ready

#11806 [doc] update how pip can install nightly wheels
  docs/source/getting_started/installation/gpu-cuda.md
Labels: documentation

#11808 [Doc] Add note to `gte-Qwen2` models
  docs/source/models/supported_models.md
Labels: documentation

#11750 [optimization] remove python function call for custom op
  vllm/_custom_ops.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#11795 [Bugfix] update the prefix for qwen2
  vllm/model_executor/models/qwen2.py
Labels: ready

#11417 [Doc]Add documentation for using EAGLE in vLLM
  docs/source/features/spec_decode.md
Labels: documentation, ready

#11794 [Bugfix] Significant performance drop on CPUs with --num-scheduler-steps > 1
  vllm/engine/arg_utils.py
Labels: ready

#11741 [Bugfix] Fix image input for Pixtral-HF
  examples/offline_inference_vision_language_multi_image.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/utils.py
Labels: ready

#11813 [Misc] sort torch profiler table by kernel timing
  benchmarks/benchmark_latency.py
Labels: ready

#11824 Remove the duplicate imports of MultiModalKwargs and PlaceholderRange…
  vllm/v1/core/scheduler.py
Labels: ready

#11518 Fixed docker build for ppc64le
  Dockerfile.ppc64le
Labels: ready, ci/build

#11732 [OpenVINO] Fixed Docker.openvino build
  Dockerfile.openvino
Labels: ready, ci/build

#11810 [Bugfix] Add checks for LoRA and CPU offload
  vllm/config.py
Labels: ready

#11639 [Docs] reorganize sponsorship page
  README.md
  docs/source/community/sponsors.md
Labels: documentation

#11825 [Bug] Fix pickling of `ModelConfig` when RunAI Model Streamer is used
  vllm/config.py
Labels: ready

#11809 [misc] improve memory profiling
  tests/test_utils.py
  tests/vllm_test_utils/vllm_test_utils/__init__.py
  tests/vllm_test_utils/vllm_test_utils/monitor.py
  vllm/utils.py
Labels: ready

#11830 [doc] update wheels url
  docs/source/getting_started/installation/gpu-cuda.md
  python_only_dev.py
  setup.py
Labels: documentation, ready, ci/build

#11696 [Hardware][Apple] Native support for macOS Apple Silicon
  cmake/cpu_extension.cmake
  csrc/cpu/cpu_types_arm.hpp
  csrc/cpu/utils.cpp
  docs/source/getting_started/installation/cpu-apple.md
  docs/source/getting_started/installation/cpu-arm.md
  docs/source/getting_started/installation/index.md
  requirements-cpu.txt
  setup.py
  vllm/config.py
  vllm/entrypoints/openai/api_server.py
  vllm/utils.py
Labels: documentation, frontend, ready, ci/build

#11614 [torch.compile] consider relevant code in compilation cache
  vllm/compilation/backends.py
  vllm/compilation/decorators.py
  vllm/config.py
  vllm/sequence.py
Labels: ready

#11812 [VLM] Reorganize profiling/processing-related code
  tests/models/decoder_only/vision_language/processing/test_llava_next.py
  tests/models/decoder_only/vision_language/processing/test_llava_onevision.py
  tests/models/decoder_only/vision_language/processing/test_phi3v.py
  tests/models/decoder_only/vision_language/processing/test_qwen2_vl.py
  tests/multimodal/test_processing.py
  tests/plugins/vllm_add_dummy_model/vllm_add_dummy_model/my_llava.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
  vllm/model_executor/models/aria.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/llava_next.py
  vllm/model_executor/models/llava_next_video.py
  vllm/model_executor/models/llava_onevision.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/qwen2_audio.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
  vllm/multimodal/registry.py
Labels: ready

#11843 [Doc][4/N] Reorganize API Reference
  .buildkite/test-pipeline.yaml
  Dockerfile
  docs/source/api/engine/async_llm_engine.md
  docs/source/api/engine/index.md
  docs/source/api/engine/llm_engine.md
  docs/source/api/multimodal/index.md
  docs/source/api/offline_inference/index.md
  docs/source/api/offline_inference/llm.md
  docs/source/api/offline_inference/llm_inputs.md
  docs/source/api/params.md
  docs/source/assets/contributing/dockerfile-stages-dependency.png
  docs/source/contributing/dockerfile/dockerfile.md
  docs/source/design/arch_overview.md
  docs/source/design/multimodal/adding_multimodal_plugin.md
  docs/source/dev/pooling_params.md
  docs/source/dev/sampling_params.md
  docs/source/getting_started/quickstart.md
  docs/source/index.md
  docs/source/serving/offline_inference.md
  docs/source/serving/openai_compatible_server.md
  vllm/multimodal/base.py
  vllm/multimodal/inputs.py
  vllm/multimodal/registry.py
  vllm/pooling_params.py
Labels: documentation, ready, ci/build

#11823 [Bugfix][XPU] fix silu_and_mul
  vllm/model_executor/layers/activation.py
  vllm/plugins/__init__.py
Labels: ready

#11848 [Misc] Move some model utils into vision file
  vllm/model_executor/models/clip.py
  vllm/model_executor/models/pixtral.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/siglip.py
  vllm/model_executor/models/utils.py
  vllm/model_executor/models/vision.py
  vllm/multimodal/inputs.py
  vllm/multimodal/utils.py
Labels: ready

#11852 [Doc] Expand Multimodal API Reference
  docs/source/api/multimodal/index.md
  docs/source/api/multimodal/inputs.md
  docs/source/api/multimodal/parse.md
  docs/source/api/multimodal/processing.md
  docs/source/api/multimodal/profiling.md
  docs/source/api/multimodal/registry.md
  vllm/multimodal/parse.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
Labels: documentation, ready

#11847 [Misc]add some explanations for BlockHashType
  vllm/v1/core/kv_cache_utils.py
Labels: ready

#11785 [TPU][Quantization] TPU `W8A8`
  .buildkite/run-tpu-test.sh
  tests/tpu/test_quantization_accuracy.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_w8a8_int8.py
  vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_wNa16.py
  vllm/model_executor/layers/quantization/gptq_marlin.py
  vllm/model_executor/layers/quantization/kernels/__init__.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/MPLinearKernel.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/__init__.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/exllama.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/machete.py
  vllm/model_executor/layers/quantization/kernels/mixed_precision/marlin.py
  vllm/model_executor/layers/quantization/kernels/scaled_mm/ScaledMMLinearKernel.py
  vllm/model_executor/layers/quantization/kernels/scaled_mm/__init__.py
  vllm/model_executor/layers/quantization/kernels/scaled_mm/cutlass.py
  vllm/model_executor/layers/quantization/kernels/scaled_mm/xla.py
  vllm/model_executor/layers/quantization/utils/w8a8_utils.py
  vllm/model_executor/parameter.py
  vllm/platforms/tpu.py
Labels: documentation, tpu, ready, ci/build

#11698 [Kernel][Triton][AMD] Use block size heuristic for avg 2.8x speedup for int8 models
  vllm/model_executor/layers/quantization/compressed_tensors/triton_scaled_mm.py
Labels: ready

#10864 [CI] Turn on basic correctness tests for V1
  tests/basic_correctness/test_basic_correctness.py
Labels: ready

#11815 treat do_lower_case in the same way as the sentence-transformers library
  tests/entrypoints/openai/test_serving_chat.py
  tests/models/embedding/language/test_embedding.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/inputs/preprocess.py
  vllm/transformers_utils/tokenizer_group/__init__.py
Labels: frontend, ready

#11849 [Doc] Recommend uv and python 3.12 for quickstart guide
  docs/source/getting_started/quickstart.md
Labels: documentation

#11298 [Misc] Move `print_*_once` from utils to logger
  .github/workflows/lint-and-deploy.yaml
  vllm/attention/backends/torch_sdpa.py
  vllm/attention/backends/xformers.py
  vllm/config.py
  vllm/entrypoints/chat_utils.py
  vllm/inputs/preprocess.py
  vllm/inputs/registry.py
  vllm/logger.py
  vllm/lora/peft_helper.py
  vllm/lora/punica_wrapper/punica_selector.py
  vllm/model_executor/custom_op.py
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/fp8.py
  vllm/model_executor/layers/quantization/kv_cache.py
  vllm/model_executor/layers/quantization/utils/marlin_utils_fp8.py
  vllm/model_executor/model_loader/weight_utils.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/olmoe.py
  vllm/model_executor/models/qwen2_moe.py
  vllm/model_executor/models/vision.py
  vllm/utils.py
Labels: frontend, ready, ci/build

#11878 [Doc] Intended links Python multiprocessing library
  docs/source/design/multiprocessing.md
Labels: documentation, ready

#11870 [perf]fix current stream
  vllm/distributed/device_communicators/pynccl.py
  vllm/distributed/parallel_state.py
  vllm/utils.py
  vllm/worker/multi_step_model_runner.py
Labels: ready

#11882 [Bugfix] Override dunder methods of placeholder modules
  tests/test_utils.py
  vllm/utils.py
Labels: ready

#11875 [Bugfix] fix beam search input errors and latency benchmark script
  benchmarks/benchmark_latency.py
  vllm/entrypoints/llm.py
Labels: frontend, ready

#11884 [Doc] Add model development API Reference
  .buildkite/test-pipeline.yaml
  docs/source/api/inference_params.md
  docs/source/api/model/adapters.md
  docs/source/api/model/index.md
  docs/source/api/model/interfaces.md
  docs/source/api/model/interfaces_base.md
  docs/source/index.md
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/interfaces_base.py
Labels: documentation, ready, ci/build

#11894 [ci]try to fix flaky multi-step tests
  tests/multi_step/test_correctness_async_llm.py
  tests/utils.py
Labels: ready

#11891 [Misc] Provide correct Pixtral-HF chat template
  docs/source/models/supported_models.md
  examples/template_pixtral_hf.jinja
  tests/entrypoints/test_chat_utils.py
Labels: documentation, ready

#11907 [Docs] Add Modal to deployment frameworks
  docs/source/deployment/frameworks/bentoml.md
  docs/source/deployment/frameworks/index.md
  docs/source/deployment/frameworks/modal.md
Labels: documentation, ready

#11896 [Doc][5/N] Move Community and API Reference to the bottom
  README.md
  docs/source/design/automatic_prefix_caching.md
  docs/source/index.md
Labels: documentation, ready

#11900 [VLM] Enable tokenized inputs for merged multi-modal processor
  tests/multimodal/test_processing.py
  vllm/inputs/data.py
  vllm/inputs/preprocess.py
  vllm/model_executor/models/blip2.py
  vllm/model_executor/models/chameleon.py
  vllm/model_executor/models/fuyu.py
  vllm/model_executor/models/interfaces.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/phi3v.py
  vllm/model_executor/models/ultravox.py
  vllm/multimodal/processing.py
  vllm/multimodal/profiling.py
Labels: ready

#11904 [Doc] Show default pooling method in a table
  docs/source/models/generative_models.md
  docs/source/models/pooling_models.md
Labels: documentation

#11677 [torch.compile] Hide KV cache behind torch.compile boundary
  tests/kernels/test_encoder_decoder_attn.py
  tests/test_utils.py
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/attention/layer.py
  vllm/config.py
  vllm/forward_context.py
  vllm/utils.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/worker/cpu_enc_dec_model_runner.py
  vllm/worker/cpu_model_runner.py
  vllm/worker/cpu_pooling_model_runner.py
  vllm/worker/cpu_worker.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/pooling_model_runner.py
  vllm/worker/worker.py
  vllm/worker/worker_base.py
Labels: ready

#11727 [Bugfix] Validate lora adapters to avoid crashing server
  tests/entrypoints/openai/test_lora_adapters.py
  tests/entrypoints/openai/test_lora_lineage.py
  tests/entrypoints/openai/test_serving_chat.py
  tests/entrypoints/openai/test_serving_models.py
  tests/entrypoints/openai/test_shutdown.py
  vllm/engine/async_llm_engine.py
  vllm/engine/multiprocessing/__init__.py
  vllm/engine/multiprocessing/client.py
  vllm/engine/multiprocessing/engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/run_batch.py
  vllm/entrypoints/openai/serving_models.py
  vllm/lora/worker_manager.py
  vllm/v1/engine/async_llm.py
Labels: frontend, ready

#11885 [optimization] remove python function call for custom activation op
  vllm/_custom_ops.py
  vllm/model_executor/layers/activation.py
Labels: ready

#11328 [platform] support pytorch custom op pluggable
  vllm/model_executor/custom_op.py
  vllm/platforms/interface.py
Labels: ready

#11923 Replace "online inference" with "online serving"
  .buildkite/run-cpu-test.sh
  docs/source/features/structured_outputs.md
  docs/source/getting_started/installation/hpu-gaudi.md
  docs/source/getting_started/quickstart.md
  docs/source/models/generative_models.md
  docs/source/models/pooling_models.md
  docs/source/models/supported_models.md
  docs/source/serving/multimodal_inputs.md
  examples/online_serving/openai_chat_completion_client_for_multimodal.py
  tests/models/decoder_only/audio_language/test_ultravox.py
  vllm/model_executor/models/molmo.py
Labels: documentation, ready, ci/build

#11925 [Doc] [1/N] Initial guide for merged multi-modal processor
  docs/requirements-docs.txt
  docs/source/api/multimodal/index.md
  docs/source/api/multimodal/inputs.md
  docs/source/conf.py
  docs/source/contributing/model/index.md
  docs/source/contributing/model/multimodal.md
  docs/source/contributing/model/registration.md
  docs/source/design/input_processing/input_processing_pipeline.md
  docs/source/design/input_processing/model_inputs_index.md
  docs/source/design/mm_processing.md
  docs/source/index.md
  docs/source/serving/multimodal_inputs.md
  vllm/config.py
  vllm/inputs/__init__.py
  vllm/inputs/registry.py
  vllm/multimodal/__init__.py
  vllm/multimodal/base.py
  vllm/multimodal/inputs.py
  vllm/multimodal/registry.py
Labels: documentation, ready

#11318 [platform] support custom torch.compile backend key
  vllm/model_executor/layers/rejection_sampler.py
  vllm/model_executor/layers/vocab_parallel_embedding.py
  vllm/model_executor/models/commandr.py
  vllm/model_executor/models/phi3_small.py
  vllm/platforms/interface.py
Labels: ready

#11930 [Misc] Clean up debug code in Deepseek-V3
  vllm/model_executor/models/deepseek_v3.py
Labels: ready

#11920 [Misc] Update benchmark_prefix_caching.py fixed example usage
  benchmarks/benchmark_prefix_caching.py
Labels: ready

#11939 [Bugfix] Check that number of images matches number of <|image|> tokens with mllama
  vllm/model_executor/models/mllama.py
Labels: ready

#11941 [mypy] Fix mypy warnings in api_server.py
  vllm/entrypoints/openai/api_server.py
Labels: documentation, frontend, ready, ci/build

#11672 [Bugfix][SpecDecode] Adjust Eagle model architecture to align with intended design
  vllm/model_executor/models/eagle.py
Labels: ready

#11921 [Bugfix] fused_experts_impl wrong compute type for float32
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#11934 [CI/Build] Move model-specific multi-modal processing tests
  .buildkite/test-pipeline.yaml
  tests/models/multimodal/__init__.py
  tests/models/multimodal/processing/__init__.py
  tests/models/multimodal/processing/test_common.py
  tests/models/multimodal/processing/test_idefics3.py
  tests/models/multimodal/processing/test_internvl.py
  tests/models/multimodal/processing/test_llava_next.py
  tests/models/multimodal/processing/test_llava_onevision.py
  tests/models/multimodal/processing/test_phi3v.py
  tests/models/multimodal/processing/test_qwen.py
  tests/models/multimodal/processing/test_qwen2_vl.py
  tests/multimodal/test_processing.py
  tests/multimodal/utils.py
Labels: ready, ci/build

#11951 [Doc] Basic guide for writing unit tests for new models
  docs/source/contributing/model/basic.md
  docs/source/contributing/model/index.md
  docs/source/contributing/model/registration.md
  docs/source/contributing/model/tests.md
  tests/models/registry.py
  tests/models/test_initialization.py
Labels: documentation, ready

#11940 [Bugfix] Fix RobertaModel loading
  tests/model_executor/test_model_load_with_params.py
  tests/models/embedding/language/test_embedding.py
  vllm/model_executor/models/roberta.py
Labels: ready

#11742 [Model] Add cogagent model support vLLM
  vllm/model_executor/models/chatglm.py
Labels: ready

#11963 [V1] Avoid sending text prompt to core engine
  vllm/v1/engine/__init__.py
  vllm/v1/engine/core_client.py
Labels: ready

#11857 [CI/Build] Add markdown linter
  .github/workflows/doc-lint.yml
  docs/README.md
  docs/source/api/model/index.md
  docs/source/community/sponsors.md
  docs/source/contributing/model/multimodal.md
  docs/source/contributing/overview.md
  docs/source/deployment/docker.md
  docs/source/deployment/frameworks/cerebrium.md
  docs/source/deployment/frameworks/dstack.md
  docs/source/deployment/frameworks/skypilot.md
  docs/source/deployment/integrations/llamastack.md
  docs/source/deployment/k8s.md
  docs/source/design/automatic_prefix_caching.md
  docs/source/features/quantization/auto_awq.md
  docs/source/features/quantization/bnb.md
  docs/source/features/quantization/fp8.md
  docs/source/features/quantization/fp8_e4m3_kvcache.md
  docs/source/features/quantization/gguf.md
  docs/source/features/quantization/int8.md
  docs/source/features/spec_decode.md
  docs/source/features/tool_calling.md
  docs/source/getting_started/faq.md
  docs/source/getting_started/installation/cpu-apple.md
  docs/source/getting_started/installation/cpu-x86.md
  docs/source/getting_started/installation/gpu-cuda.md
  docs/source/getting_started/installation/gpu-rocm.md
  docs/source/getting_started/installation/hpu-gaudi.md
  docs/source/getting_started/installation/neuron.md
  docs/source/getting_started/installation/openvino.md
  docs/source/getting_started/installation/tpu.md
  docs/source/getting_started/installation/xpu.md
  docs/source/getting_started/quickstart.md
  docs/source/getting_started/troubleshooting.md
  docs/source/index.md
  docs/source/models/extensions/runai_model_streamer.md
  docs/source/models/supported_models.md
  docs/source/performance/optimization.md
  docs/source/serving/distributed_serving.md
  docs/source/serving/integrations/langchain.md
  docs/source/serving/integrations/llamaindex.md
  docs/source/serving/metrics.md
  docs/source/serving/multimodal_inputs.md
  docs/source/serving/offline_inference.md
  docs/source/serving/openai_compatible_server.md
  format.sh
  pyproject.toml
  requirements-lint.txt
  tools/doc-lint.sh
  tools/sphinx-lint.sh
Labels: documentation, ready, ci/build

#11578 [Model] Initialize support for Deepseek-VL2 models
  .buildkite/test-pipeline.yaml
  docs/source/models/supported_models.md
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/decoder_only/vision_language/test_models.py
  tests/models/decoder_only/vision_language/vlm_utils/model_utils.py
  tests/models/registry.py
  tests/models/test_initialization.py
  vllm/entrypoints/chat_utils.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/model_executor/models/deepseek_v3.py
  vllm/model_executor/models/deepseek_vl2.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/registry.py
  vllm/transformers_utils/config.py
  vllm/transformers_utils/configs/__init__.py
  vllm/transformers_utils/configs/deepseek_vl2.py
Labels: documentation, frontend, ready, ci/build

#11764 [Hardware][TPU] workaround fix for MoE on TPU
  tests/kernels/test_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/moe_torch_iterative.py
Labels: ready

#11962 [V1][Core][1/n] Logging and Metrics
  tests/v1/engine/test_engine_core.py
  tests/v1/engine/test_engine_core_client.py
  vllm/v1/core/scheduler.py
  vllm/v1/engine/__init__.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/metrics/__init__.py
  vllm/v1/metrics/loggers.py
  vllm/v1/metrics/stats.py
Labels: ready

#9685 [Model] Support GGUF models newly added in `transformers` 4.46.0
  examples/offline_inference/gguf_inference.py
  tests/models/decoder_only/language/test_gguf.py
  vllm/model_executor/layers/linear.py
  vllm/model_executor/models/gpt2.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/stablelm.py
  vllm/model_executor/models/starcoder2.py
Labels: quantization, ready

#11973 [V1] [2/n] Logging and Metrics - `OutputProcessor` Abstraction
  tests/v1/engine/test_async_llm.py
  tests/v1/engine/test_output_processor.py
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core_client.py
  vllm/v1/engine/detokenizer.py
  vllm/v1/engine/llm_engine.py
  vllm/v1/engine/output_processor.py
  vllm/v1/metrics/stats.py
Labels: ready

#11983 [MISC] fix typo in kv transfer send recv test
  tests/kv_transfer/test_send_recv.py
Labels: ready

#11979 [Bug] Fix usage of `.transpose()` and `.view()` consecutively.
  vllm/attention/layer.py
  vllm/model_executor/models/intern_vit.py
Labels: ready

#11947 [Misc] Fix Deepseek V2 fp8 kv-scale remapping
  vllm/model_executor/models/deepseek_v2.py
Labels: ready

#11555 [Misc]Minor Changes about Worker
  vllm/v1/worker/gpu_worker.py
  vllm/worker/worker.py
Labels: ready

#11948 [platform] add ray_device_key
  vllm/executor/ray_utils.py
  vllm/platforms/cuda.py
  vllm/platforms/hpu.py
  vllm/platforms/interface.py
  vllm/platforms/neuron.py
  vllm/platforms/rocm.py
  vllm/platforms/tpu.py
  vllm/platforms/xpu.py
  vllm/v1/executor/ray_utils.py
Labels: ready

#11980 Fix Max Token ID for Qwen-VL-Chat
  vllm/transformers_utils/tokenizer.py
Labels: ready

#11967 [Kernel] Attention.forward with unified_attention when use_direct_call=True
  vllm/attention/layer.py
  vllm/utils.py
  vllm/worker/hpu_model_runner.py
  vllm/worker/hpu_worker.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/openvino_model_runner.py
  vllm/worker/openvino_worker.py
  vllm/worker/tpu_model_runner.py
  vllm/worker/tpu_worker.py
  vllm/worker/xpu_model_runner.py
Labels: ready

#11998 [Doc][V1] Update model implementation guide for V1 support
  docs/source/contributing/model/basic.md
  docs/source/contributing/model/multimodal.md
Labels: documentation, ready

#11982 bugfix: Fix signature mismatch in benchmark's `get_tokenizer` function
  benchmarks/backend_request_func.py
Labels: ready

#12013 [Doc] Fix build from source and installation link in README.md
  README.md
Labels: documentation, ready

#12002 [Bugfix] Fix deepseekv3 gate bias error
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: ready

#12019 [Docs] Add Sky Computing Lab to project intro
  README.md
  docs/source/index.md
Labels: documentation

#12014 [Hardware][Gaudi][Bugfix] Fix set_forward_context arguments and CI test execution
  .buildkite/run-hpu-test.sh
  Dockerfile.hpu
  vllm/worker/hpu_model_runner.py
Labels: ready, ci/build

#12025 [Doc] Update Quantization Hardware Support Documentation
  docs/source/features/quantization/supported_hardware.md
Labels: documentation, ready

#12031 [Bugfix] Fix various bugs in multi-modal processor
  tests/multimodal/test_processing.py
  vllm/multimodal/processing.py
  vllm/multimodal/registry.py
Labels: ready

#12040 [Bugfix][Kernel] Give unique name to BlockSparseFlashAttention
  vllm/attention/backends/blocksparse_attn.py
  vllm/platforms/interface.py
Labels: ready

#12041 Explain where the engine args go when using Docker
  docs/source/deployment/docker.md
Labels: documentation, ready

#12045 [Doc]: Update the Json Example of the `Engine Arguments` document
  vllm/engine/arg_utils.py
Labels: ready

#11924 [Misc] Merge bitsandbytes_stacked_params_mapping and packed_modules_mapping
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/baichuan.py
  vllm/model_executor/models/exaone.py
  vllm/model_executor/models/falcon.py
  vllm/model_executor/models/gemma.py
  vllm/model_executor/models/gemma2.py
  vllm/model_executor/models/granite.py
  vllm/model_executor/models/idefics3.py
  vllm/model_executor/models/llama.py
  vllm/model_executor/models/llava.py
  vllm/model_executor/models/minicpm.py
  vllm/model_executor/models/minicpm3.py
  vllm/model_executor/models/minicpmv.py
  vllm/model_executor/models/mllama.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/nemotron.py
  vllm/model_executor/models/opt.py
  vllm/model_executor/models/phi.py
  vllm/model_executor/models/phi3.py
  vllm/model_executor/models/qwen.py
  vllm/model_executor/models/qwen2.py
  vllm/model_executor/models/qwen2_vl.py
  vllm/model_executor/models/solar.py
Labels: ready

#11624 [Kernel] Support MulAndSilu
  csrc/activation_kernels.cu
  csrc/ops.h
  csrc/torch_bindings.cpp
  tests/kernels/test_activation.py
  vllm/model_executor/layers/activation.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/ultravox.py
Labels: ready

#12046 [HPU][Bugfix] Don't use /dev/accel/accel0 for HPU autodetection in setup.py
  setup.py
Labels: ready, ci/build

#11369 [Platform] Refactor current_memory_usage() function in DeviceMemoryProfiler to Platform
  vllm/platforms/cuda.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
  vllm/platforms/xpu.py
  vllm/utils.py
Labels: ready

#10467 [Misc] Add multipstep chunked-prefill support for FlashInfer
  csrc/prepare_inputs/advance_step.cu
  tests/multi_step/test_correctness_llm.py
  vllm/attention/backends/flashinfer.py
  vllm/worker/model_runner.py
  vllm/worker/multi_step_model_runner.py
Labels: ready
