Repository vllm-project/vllm, pull requests merged in 2025-05, with the labels that each got.

#17488 [CI][TPU] Skip Multimodal test
  tests/v1/tpu/test_multimodal.py
Labels: tpu, ready, v1, force-merge

#17495 [Bugfix][ROCm] Fix import error on ROCm
  vllm/model_executor/layers/rotary_embedding.py
Labels: ready, force-merge

#17411 [Bugfix] Temporarily disable gptq_bitblas on ROCm
  docs/source/features/quantization/supported_hardware.md
  vllm/model_executor/layers/quantization/gptq_bitblas.py
Labels: documentation

#17510 [CI][TPU] Skip structured outputs+spec decode tests on TPU
  tests/v1/entrypoints/llm/test_struct_output_generate.py
Labels: ready, v1

#17500 [CI][Bugfix] Fix failing V1 Test due to missing 'cache_salt' arg
  tests/v1/engine/test_engine_core_client.py
Labels: ready, v1

#17511 FIxing the AMD test failures caused by PR#16457
  docker/Dockerfile.rocm
  vllm/model_executor/layers/rotary_embedding.py
Labels: rocm, ci/build

#17389 [Build] Require setuptools >= 77.0.3 for PEP 639
  pyproject.toml
  requirements/build.txt
  requirements/common.txt
  requirements/hpu.txt
  requirements/rocm-build.txt
  requirements/test.txt
  requirements/tpu.txt
  requirements/xpu.txt
Labels: ready, ci/build

#17229 [ROCm] Effort to reduce the number of environment variables in command line
  docker/Dockerfile.rocm
Labels: rocm, ready, ci/build

#15506 [BugFix] fix speculative decoding memory leak when speculation is disabled
  tests/spec_decode/test_memory_usage.py
  vllm/spec_decode/spec_decode_worker.py
Labels: bug, speculative-decoding, ready, v0

#17494 [BugFix] Fix mla cpu - missing 3 required positional arguments
  vllm/_ipex_ops.py
  vllm/attention/backends/cpu_mla.py
Labels: bug, ready

#17418 Avoid overwriting vllm_compile_cache.py
  vllm/compilation/backends.py
Labels: ready

#16506 [Core] Enable IPv6 with vllm.utils.make_zmq_socket()
  tests/test_utils.py
  vllm/utils.py
Labels: ready

#17453 Improve configs - `ObservabilityConfig`
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#17285 [Bugfix][Benchmarks] Allow benchmark of deepspeed-mii backend to select a model
  benchmarks/backend_request_func.py
Labels: ready

#17525 [Frontend] Show progress bar for adding requests
  vllm/entrypoints/llm.py
Labels: frontend, ready

#17521 [Misc] Clean up test docstrings and names
  .buildkite/test-pipeline.yaml
  tests/models/language/generation/test_common.py
  tests/models/language/generation/test_granite.py
  tests/models/language/generation/test_mistral.py
  tests/models/language/generation/test_phimoe.py
  tests/models/language/pooling/test_classification.py
  tests/models/language/pooling/test_embedding.py
  tests/models/language/pooling/test_jina.py
  tests/models/language/pooling/test_scoring.py
  tests/models/language/pooling/test_snowflake_arctic_embed.py
  tests/models/language/pooling/test_truncation_control.py
  tests/models/multimodal/generation/test_pixtral.py
  tests/models/multimodal/generation/test_whisper.py
  tests/models/quantization/test_aqlm.py
  tests/models/quantization/test_bitblas.py
  tests/models/quantization/test_gptq_bitblas.py
  tests/models/quantization/test_gptq_marlin.py
  tests/models/quantization/test_gptq_marlin_24.py
  tests/models/test_transformers.py
Labels: ready, ci/build, multi-modality

#17450 Fix more broken speculative decode tests
  tests/spec_decode/e2e/test_medusa_correctness.py
  tests/spec_decode/e2e/test_mlp_correctness.py
  tests/spec_decode/e2e/test_ngram_correctness.py
  vllm/spec_decode/multi_step_worker.py
Labels: speculative-decoding, ready

#17522 [doc] add streamlit integration
  docs/source/assets/deployment/streamlit-chat.png
  docs/source/deployment/frameworks/index.md
  docs/source/deployment/frameworks/streamlit.md
  examples/online_serving/streamlit_openai_chatbot_webserver.py
Labels: documentation, ready

#17452 [Feature][Frontend]: Deprecate --enable-reasoning
  docs/source/features/reasoning_outputs.md
  examples/online_serving/openai_chat_completion_structured_outputs_with_reasoning.py
  examples/online_serving/openai_chat_completion_tool_calls_with_reasoning.py
  examples/online_serving/openai_chat_completion_with_reasoning.py
  examples/online_serving/openai_chat_completion_with_reasoning_streaming.py
  tests/entrypoints/openai/test_chat_with_tool_reasoning.py
  tests/entrypoints/openai/test_cli_args.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/engine/llm_engine.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/cli_args.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/model_executor/guided_decoding/__init__.py
  vllm/model_executor/guided_decoding/outlines_logits_processors.py
  vllm/model_executor/guided_decoding/xgrammar_decoding.py
Labels: documentation, structured-output, frontend, ready, tool-calling

#17536 [ROCm] remove unsupported archs from rocm triton flash-attention supported list
  vllm/attention/ops/triton_flash_attention.py
Labels: rocm, ready

#10867 [torch.compile] Add torch inductor pass for fusing silu_and_mul with subsequent scaled_fp8_quant operations
  CMakeLists.txt
  csrc/core/math.hpp
  csrc/ops.h
  csrc/quantization/activation_kernels.cu
  csrc/torch_bindings.cpp
  tests/compile/test_functionalization.py
  tests/compile/test_silu_mul_quant_fusion.py
  tests/kernels/test_fused_quant_activation.py
  vllm/compilation/activation_quant_fusion.py
  vllm/compilation/fix_functionalization.py
  vllm/compilation/pass_manager.py
Labels: frontend, ready, ci/build

#17460 [Misc] refactor example - cpu_offload_lmcache
  examples/lmcache/README.md
  examples/lmcache/cpu_offload_lmcache.py
  examples/lmcache/cpu_offload_lmcache_v1.py
Labels: documentation, ready

#17532 [CI/Build] Remove `awscli` dependency
  requirements/nightly_torch_test.txt
  requirements/rocm.txt
  requirements/test.in
  requirements/test.txt
Labels: ready, ci/build

#17531 Move the last arguments in `arg_utils.py` to be in their final groups
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#17537 [Model] Refactor Ovis2 to support original tokenizer
  examples/offline_inference/vision_language.py
  examples/offline_inference/vision_language_multi_image.py
  tests/models/registry.py
  vllm/model_executor/models/ovis2.py
  vllm/transformers_utils/processors/ovis2.py
Labels: documentation, ready

#17542 [ROCm] update installation guide to include build aiter from source instructions
  docs/source/getting_started/installation/gpu/rocm.inc.md
Labels: documentation, rocm, ready

#17201 [Misc]add configurable cuda graph size
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#16034 [ROCM] Add gfx950 to the custom attention archs
  csrc/rocm/attention.cu
  vllm/platforms/rocm.py
Labels: ready

#17207 [Misc][Tools][Benchmark] Publish script to auto tune server parameters
  benchmarks/auto_tune.sh
Labels: ready

#17504 [V1][Spec Decode] Apply torch.compile & cudagraph to EAGLE3
  vllm/model_executor/models/llama_eagle3.py
  vllm/v1/spec_decode/eagle.py
Labels: ready, v1

#17541 [Bugfix] Disable gptq_bitblas for <SM80 to fix GPTQ on V100/T4
  vllm/model_executor/layers/quantization/gptq_bitblas.py
Labels: bug, ready

#17554 [Doc] note that not all unit tests pass on CPU platforms
  docs/source/contributing/overview.md
Labels: documentation, ready

#17484 [Attention] MLA move o_proj q_proj into cuda-graph region
  vllm/attention/backends/cpu_mla.py
  vllm/attention/backends/flashmla.py
  vllm/attention/backends/mla/common.py
  vllm/attention/backends/rocm_aiter_mla.py
  vllm/attention/backends/triton_mla.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/flashmla.py
  vllm/v1/attention/backends/mla/triton_mla.py
Labels: ready, v1

#17555 [CI] Actually run tests/kv_transfer/test_disagg.py in CI
  tests/kv_transfer/test_disagg.py
Labels: ready

#17572 Check if bitblas is installed during support check
  vllm/model_executor/layers/quantization/utils/bitblas_utils.py
Labels: ready

#17573 [Misc] Continue refactoring model tests
  examples/offline_inference/qwen2_5_omni/only_thinker.py
  examples/offline_inference/vision_language.py
  tests/conftest.py
  tests/models/multimodal/generation/test_interleaved.py
  tests/models/multimodal/pooling/test_intern_vit.py
  vllm/assets/video.py
Labels: documentation, ready, multi-modality

#16869 Add `pt_load_map_location` to allow loading to cuda
  tests/quantization/test_torchao.py
  tests/test_config.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: ready

#17317 [Bugifx] Remove TritonPlaceholder from sys.modules
  vllm/triton_utils/importing.py
Labels: ready

#15428 [Core] [Bugfix] Add Input Embeddings
  tests/conftest.py
  tests/core/test_scheduler.py
  tests/core/utils.py
  tests/models/language/generation/test_common.py
  tests/worker/test_model_runner.py
  vllm/attention/backends/flashinfer.py
  vllm/core/scheduler.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/output_processor/multi_step.py
  vllm/engine/output_processor/single_step.py
  vllm/inputs/__init__.py
  vllm/inputs/data.py
  vllm/inputs/parse.py
  vllm/inputs/preprocess.py
  vllm/model_executor/layers/sampler.py
  vllm/sequence.py
  vllm/spec_decode/draft_model_runner.py
  vllm/spec_decode/multi_step_worker.py
  vllm/worker/enc_dec_model_runner.py
  vllm/worker/model_runner.py
  vllm/worker/pooling_model_runner.py
Labels: frontend, speculative-decoding, ready

#17567 [BugFix] Fix Memory Leak
  tests/v1/core/test_scheduler.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#17575 [Misc] Rename assets for testing
  examples/offline_inference/qwen2_5_omni/only_thinker.py
  examples/offline_inference/vision_language.py
  tests/conftest.py
  tests/models/multimodal/generation/test_common.py
  tests/models/multimodal/generation/test_florence2.py
  tests/models/multimodal/generation/test_granite_speech.py
  tests/models/multimodal/generation/test_interleaved.py
  tests/models/multimodal/generation/test_mllama.py
  tests/models/multimodal/generation/test_qwen2_vl.py
  tests/models/multimodal/generation/test_ultravox.py
  tests/models/multimodal/generation/vlm_utils/builders.py
  tests/models/multimodal/generation/vlm_utils/model_utils.py
  tests/models/multimodal/generation/vlm_utils/runners.py
  tests/models/multimodal/generation/vlm_utils/types.py
  tests/models/multimodal/pooling/test_intern_vit.py
  tests/models/multimodal/processing/test_h2ovl.py
  tests/models/multimodal/processing/test_idefics3.py
  tests/models/multimodal/processing/test_internvl.py
  tests/models/multimodal/processing/test_llama4.py
  tests/models/multimodal/processing/test_minimax_vl_01.py
  tests/models/multimodal/processing/test_phi3v.py
  tests/models/multimodal/processing/test_phi4mm.py
  tests/models/multimodal/processing/test_qwen2_vl.py
  tests/models/multimodal/processing/test_smolvlm.py
  tests/models/quantization/test_awq.py
  vllm/assets/audio.py
  vllm/assets/image.py
  vllm/assets/video.py
Labels: documentation, ready, multi-modality

#17422 add more pytorch related tests for torch nightly
  .buildkite/test-pipeline.yaml
  requirements/nightly_torch_test.txt
  vllm/sampling_params.py
Labels: ready, ci/build

#17584 [doc] add the print result
  docs/source/features/quantization/fp8.md
Labels: documentation

#17577 Automatically tell users that dict args must be valid JSON in CLI
  tests/engine/test_arg_utils.py
  vllm/config.py
  vllm/engine/arg_utils.py
Labels: ready

#17378 [Security] Fix image hash collision
  tests/multimodal/assets/image1.png
  tests/multimodal/assets/image2.png
  tests/multimodal/test_hasher.py
  vllm/multimodal/hasher.py
Labels: ready, multi-modality, security

#16745 Support W8A8 INT8 MoE for compressed-tensors
  vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py
  vllm/model_executor/layers/quantization/kernels/scaled_mm/cutlass.py
Labels: quantization, moe, ready

#17589 [doc] miss result
  docs/source/features/quantization/fp8.md
Labels: documentation

#17582 [Misc] Clean up input processing
  tests/models/multimodal/pooling/test_intern_vit.py
  vllm/engine/async_llm_engine.py
  vllm/engine/llm_engine.py
  vllm/engine/protocol.py
  vllm/entrypoints/llm.py
  vllm/inputs/data.py
  vllm/inputs/parse.py
  vllm/inputs/preprocess.py
  vllm/multimodal/processing.py
Labels: frontend, ready, v1, multi-modality

#17574 [BugFix][Attention] Fix sliding window attention in V1 giving incorrect results
  vllm/v1/attention/backends/flash_attn.py
Labels: ready, v1

#14568 permute/unpermute kernel for moe optimization
  CMakeLists.txt
  benchmarks/kernels/benchmark_grouped_gemm_cutlass.py
  benchmarks/kernels/benchmark_moe.py
  benchmarks/kernels/benchmark_moe_permute_unpermute.py
  csrc/moe/moe_permute_unpermute_op.cu
  csrc/moe/permute_unpermute_kernels/dispatch.h
  csrc/moe/permute_unpermute_kernels/moe_permute_unpermute_kernel.cu
  csrc/moe/permute_unpermute_kernels/moe_permute_unpermute_kernel.h
  csrc/moe/permute_unpermute_kernels/moe_permute_unpermute_kernel.inl
  csrc/moe/torch_bindings.cpp
  tests/kernels/moe/test_moe.py
  tests/kernels/moe/test_moe_permute_unpermute.py
  tests/kernels/quantization/test_awq_marlin.py
  tests/kernels/quantization/test_block_fp8.py
  vllm/model_executor/layers/fused_moe/fused_marlin_moe.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/layer.py
  vllm/model_executor/layers/fused_moe/moe_permute_unpermute.py
  vllm/model_executor/models/arctic.py
Labels: ready, ci/build

#17561 Add NVIDIA TensorRT Model Optimizer in vLLM documentation
  docs/source/features/quantization/index.md
  docs/source/features/quantization/modelopt.md
  docs/source/features/quantization/supported_hardware.md
Labels: documentation

#16263 [Hardware][AMD] Improve OAM device ID + llama4 Maverick MOE tuning
  benchmarks/kernels/benchmark_moe.py
  vllm/model_executor/layers/fused_moe/configs/E=128,N=1024,device_name=AMD_Instinct_MI300X.json
  vllm/platforms/rocm.py
Labels: rocm, ready

#17594 [easy] Print number of needed GPUs in skip message
  tests/compile/test_basic_correctness.py
Labels: ready

#17606 [release] Add command to clean up Docker containers/images in TPU release machine
  .buildkite/release-pipeline.yaml
Labels: ci/build

#17576 Update test requirements to CUDA 12.8
  .pre-commit-config.yaml
  requirements/test.txt
Labels: ready, ci/build

#17508 [Frontend][TPU] Add TPU default max-num-batched-tokens based on device name
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/platforms/tpu.py
Labels: tpu, ready

#17602 [Build/CI] Upgrade CUTLASS to 3.9.1
  CMakeLists.txt
Labels: ready, ci/build

#17601 [Bugfix][ROCm] Using device_type because on ROCm the API is still torch.cuda
  vllm/platforms/interface.py
Labels: bug, rocm, ready

#17607 [Core] Gate `prompt_embeds` behind a feature flag
  tests/engine/test_options.py
  tests/engine/test_skip_tokenizer_init.py
  tests/models/language/generation/test_common.py
  tests/worker/test_model_runner.py
  vllm/config.py
  vllm/engine/arg_utils.py
  vllm/inputs/preprocess.py
  vllm/worker/model_runner.py
Labels: ready

#17613 [Bugfix] Fix broken Qwen2.5-omni tests
  tests/models/multimodal/generation/test_common.py
  tests/models/multimodal/generation/vlm_utils/model_utils.py
  tests/models/multimodal/processing/test_common.py
  tests/models/registry.py
Labels: ready, multi-modality

#17615 [Misc] V0 fallback for `--enable-prompt-embeds`
  vllm/engine/arg_utils.py
  vllm/inputs/preprocess.py
Labels: ready

#17629 [Bugfix] Prioritize dtype in root config before checking text config
  vllm/config.py
Labels: ready

#17635 [Bugfix][Easy] Fix whitespace in shm_broadcast.py logging
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: ready

#17637 [Bugfix] fix KeyError on top logprobs are special tokens
  vllm/entrypoints/openai/serving_chat.py
Labels: frontend

#17641 [Build/CI] Upgrade CUTLASS to 3.9.2
  CMakeLists.txt
Labels: ready, ci/build

#17654 [Doc] Fix broken cuda installation doc rendering
  requirements/docs.txt
Labels: documentation, ready, ci/build

#17616 Use git-path commit in hook
  .pre-commit-config.yaml
Labels: ready

#17651 [Benchmarks] Remove invalid option under V1 engine
  benchmarks/benchmark_serving_structured_output.py
  benchmarks/run_structured_output_benchmark.sh
Labels: structured-output, ready

#17642 [BugFix] Increase timeout for startup failure test
  tests/v1/engine/test_engine_core_client.py
Labels: bug, ready, v1

#17335 [TPU] Enable gemma3-27b with TP>1 on multi-chips.
  tests/v1/tpu/test_basic.py
  vllm/platforms/tpu.py
Labels: tpu, ready, v1

#17072 [TPU][V1] Add support for top-logprobs
  tests/v1/tpu/test_sampler.py
  vllm/v1/sample/tpu/metadata.py
  vllm/v1/sample/tpu/sampler.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#17497 [Model] Add GraniteMoeHybrid 4.0 model
  docs/source/models/supported_models.md
  tests/models/language/generation/test_granitemoehybrid.py
  tests/models/language/generation/test_hybrid.py
  tests/models/registry.py
  vllm/model_executor/models/granitemoehybrid.py
  vllm/model_executor/models/registry.py
Labels: documentation, ready

#17138 [easy] Fix logspam on PiecewiseBackend errors
  vllm/compilation/backends.py
Labels: ready

#17219 [Doc] Update notes for H2O-VL and Gemma3
  docs/source/models/supported_models.md
Labels: documentation, ready

#17690 [Misc] Fix ScalarType float4 naming
  tests/kernels/quantization/test_nvfp4_quant.py
  tests/test_scalartype.py
  vllm/scalar_type.py
Labels: ready

#17446 [Bugfix] Fix triton import with local TritonPlaceholder
  benchmarks/kernels/benchmark_moe.py
  benchmarks/kernels/benchmark_rmsnorm.py
  benchmarks/kernels/deepgemm/benchmark_fp8_block_dense_gemm.py
  tests/kernels/attention/test_flashmla.py
  tests/test_triton_utils.py
  vllm/attention/ops/blocksparse_attention/blocksparse_attention_kernel.py
  vllm/attention/ops/blocksparse_attention/utils.py
  vllm/attention/ops/chunked_prefill_paged_decode.py
  vllm/attention/ops/prefix_prefill.py
  vllm/attention/ops/triton_decode_attention.py
  vllm/attention/ops/triton_flash_attention.py
  vllm/attention/ops/triton_merge_attn_states.py
  vllm/lora/ops/triton_ops/kernel_utils.py
  vllm/model_executor/layers/fused_moe/fused_moe.py
  vllm/model_executor/layers/fused_moe/moe_align_block_size.py
  vllm/model_executor/layers/lightning_attn.py
  vllm/model_executor/layers/mamba/ops/mamba_ssm.py
  vllm/model_executor/layers/mamba/ops/ssd_bmm.py
  vllm/model_executor/layers/mamba/ops/ssd_chunk_scan.py
  vllm/model_executor/layers/mamba/ops/ssd_chunk_state.py
  vllm/model_executor/layers/mamba/ops/ssd_combined.py
  vllm/model_executor/layers/mamba/ops/ssd_state_passing.py
  vllm/model_executor/layers/quantization/awq_triton.py
  vllm/model_executor/layers/quantization/compressed_tensors/triton_scaled_mm.py
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
  vllm/model_executor/layers/quantization/utils/int8_utils.py
  vllm/triton_utils/__init__.py
  vllm/triton_utils/importing.py
  vllm/v1/sample/rejection_sampler.py
  vllm/v1/spec_decode/eagle.py
Labels: ready, v1

#17673 [V1] Enable TPU V1 backend by default
  vllm/engine/arg_utils.py
Labels: ready

#14219 [V1][PP] Support PP for MultiprocExecutor
  tests/distributed/test_pipeline_parallel.py
  vllm/engine/arg_utils.py
  vllm/v1/executor/multiproc_executor.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/gpu_worker.py
Labels: ready, v1

#17394 [v1] AttentionMetadata for each layer
  vllm/attention/layer.py
  vllm/forward_context.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/attention/backends/flashinfer.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/utils.py
  vllm/v1/spec_decode/eagle.py
  vllm/v1/worker/gpu_model_runner.py
  vllm/v1/worker/tpu_model_runner.py
Labels: tpu, ready, v1

#17426 [Feat] Add deprecated=True to CLI args
  vllm/engine/arg_utils.py
  vllm/utils.py
Labels: ready

#17709 [Docs] Use gh-file to add links to tool_calling.md
  docs/source/features/tool_calling.md
Labels: documentation, ready, tool-calling

#17479 [v1] Introduce KVCacheBlocks as interface between Scheduler and KVCacheManager
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/sched/scheduler.py
Labels: ready, v1

#17692 [doc] Add RAG Integration example
  docs/source/deployment/frameworks/index.md
  docs/source/deployment/frameworks/retrieval_augmented_generation.md
  examples/online_serving/retrieval_augmented_generation_with_langchain.py
  examples/online_serving/retrieval_augmented_generation_with_llamaindex.py
Labels: documentation, ready

#17723 Make right sidebar more readable in "Supported Models"
  docs/source/models/supported_models.md
Labels: documentation, ready

#17732 [Bugfix] Fix for the condition to accept empty encoder inputs for mllama
  vllm/engine/llm_engine.py
Labels: ready

#16828 [Kernel] Unified Triton kernel that doesn't distinguish between prefill + decode
  tests/kernels/test_triton_unified_attention.py
  vllm/attention/ops/triton_unified_attention.py
  vllm/v1/attention/backends/triton_attn.py
Labels: ready, v1

#17748 Fix doc build performance
  docs/source/conf.py
  requirements/docs.txt
Labels: documentation, ready, ci/build

#17744 [ROCm] fix num_stages for default moe config to avoid triton OutOfResource error
  vllm/model_executor/layers/fused_moe/fused_moe.py
Labels: rocm, ready

#17669 Add logging for torch nightly version
  docker/Dockerfile.nightly_torch
  requirements/nightly_torch_test.txt
Labels: ready, ci/build

#17146 [Model] Mamba2 causal conv1d Refactor to Split Prefill and Decode Requests for Corresponding Kernels
  tests/kernels/mamba/test_mamba_ssm_ssd.py
  vllm/model_executor/layers/mamba/mamba2_metadata.py
  vllm/model_executor/layers/mamba/mamba_mixer2.py
  vllm/model_executor/layers/mamba/ops/ssd_combined.py
  vllm/model_executor/models/bamba.py
  vllm/model_executor/models/granitemoehybrid.py
  vllm/model_executor/models/mamba2.py
  vllm/model_executor/models/zamba2.py
Labels: ready

#17684 Removed unused marlin cuda code
  csrc/moe/marlin_kernels/marlin_moe_kernel.h
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku4.cu
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku4.h
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku4b8.cu
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku4b8.h
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku8b128.cu
  csrc/moe/marlin_kernels/marlin_moe_kernel_ku8b128.h
  csrc/moe/marlin_moe_ops.cu
  csrc/quantization/fp8/fp8_marlin.cu
Labels: ready

#17496 [TPU] Add kernel test for moe_pallas
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
  tests/tpu/test_moe_pallas.py
  vllm/attention/backends/pallas.py
  vllm/model_executor/layers/fused_moe/moe_pallas.py
Labels: tpu, ready, ci/build

#17717 Replace lm-eval bash script with pytest and use enforce_eager for faster CI
  .buildkite/lm-eval-harness/conftest.py
  .buildkite/lm-eval-harness/run-tests.sh
  .buildkite/lm-eval-harness/test_lm_eval_correctness.py
  .buildkite/test-pipeline.yaml
Labels: ready, ci/build

#17740 [BugFix][Spec Decode] Fix hidden size mismatch between target and eagle head
  vllm/v1/spec_decode/eagle.py
Labels: speculative-decoding, ready, v1

#17712 [Misc] Split model loader
  tests/runai_model_streamer_test/test_runai_model_streamer_loader.py
  tests/test_sharded_state_loader.py
  tests/utils.py
  vllm/config.py
  vllm/model_executor/model_loader/__init__.py
  vllm/model_executor/model_loader/base_loader.py
  vllm/model_executor/model_loader/bitsandbytes_loader.py
  vllm/model_executor/model_loader/default_loader.py
  vllm/model_executor/model_loader/dummy_loader.py
  vllm/model_executor/model_loader/gguf_loader.py
  vllm/model_executor/model_loader/loader.py
  vllm/model_executor/model_loader/runai_streamer_loader.py
  vllm/model_executor/model_loader/sharded_state_loader.py
  vllm/model_executor/model_loader/tensorizer_loader.py
  vllm/model_executor/model_loader/utils.py
  vllm/model_executor/models/mllama4.py
  vllm/model_executor/models/ultravox.py
  vllm/model_executor/models/utils.py
  vllm/v1/spec_decode/eagle.py
  vllm/v1/worker/gpu_worker.py
  vllm/worker/model_runner.py
Labels: ready, v1

#17726 [Misc] Use `apply_rotary_emb` from vllm_flash_attn for Qwen2-VL vision RoPE
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#16780 [Kernel] GGUF MoeVec kernel
  csrc/ops.h
  csrc/quantization/gguf/gguf_kernel.cu
  csrc/quantization/gguf/moe_vec.cuh
  csrc/torch_bindings.cpp
  tests/kernels/quantization/test_ggml.py
  tests/kernels/quantization/test_gguf.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/quantization/gguf.py
Labels: ready

#17735 [Kernel] Use fused rmsnorm for some models like qwen3 series
  csrc/layernorm_kernels.cu
  vllm/_custom_ops.py
  vllm/model_executor/models/intern_vit.py
  vllm/model_executor/models/molmo.py
  vllm/model_executor/models/olmo2.py
  vllm/model_executor/models/qwen3.py
  vllm/model_executor/models/qwen3_moe.py
Labels: ready

#17699 [Misc] Remove qlora_adapter_name_or_path
  examples/offline_inference/lora_with_quantization_inference.py
  vllm/engine/arg_utils.py
  vllm/model_executor/model_loader/weight_utils.py
Labels: documentation, ready, ci/build

#16357 Add NeuronxDistributedInference support, Speculative Decoding, Dynamic on-device sampling
  examples/offline_inference/neuron_eagle.py
  examples/offline_inference/neuron_speculation.py
  requirements/neuron.txt
  tests/neuron/1_core/test_neuron_model_runner.py
  vllm/config.py
  vllm/engine/llm_engine.py
  vllm/model_executor/model_loader/neuron.py
  vllm/model_executor/model_loader/neuronx_distributed.py
  vllm/platforms/__init__.py
  vllm/platforms/neuron.py
  vllm/worker/multi_step_neuron_model_runner.py
  vllm/worker/multi_step_neuronx_distributed_model_runner.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/neuron_worker.py
  vllm/worker/neuronx_distributed_model_runner.py
Labels: documentation, ci/build

#17754 Fix test_memory_usage_no_spec
  tests/spec_decode/test_memory_usage.py
Labels: speculative-decoding, ready

#17566 Make key optional for rotary embedding
  csrc/cpu/pos_encoding.cpp
  csrc/cpu/torch_bindings.cpp
  csrc/ops.h
  csrc/pos_encoding_kernels.cu
  csrc/torch_bindings.cpp
  tests/kernels/core/test_pos_encoding.py
  tests/kernels/core/test_rotary_embedding.py
  tests/neuron/1_core/test_rotary_embedding.py
  vllm/_custom_ops.py
  vllm/model_executor/layers/rotary_embedding.py
Labels: ready

#17782 [doc] update the issue link
  docs/source/features/quantization/fp8.md
  docs/source/features/quantization/int4.md
  docs/source/features/quantization/int8.md
Labels: documentation, ready

#17139 [ROCm][FP8][Kernel] FP8 quantization fused into Custom Paged Attention
  csrc/rocm/attention.cu
  csrc/rocm/ops.h
  csrc/rocm/torch_bindings.cpp
  vllm/_custom_ops.py
Labels: rocm, ready

#17776 Only depend on importlib-metadata for Python < 3.10
  requirements/common.txt
Labels: ready, ci/build

#17791 [Bugfix] Fix Video IO error for short video
  tests/multimodal/test_utils.py
  vllm/multimodal/video.py
Labels: ready, multi-modality

#17781 Fix and simplify `deprecated=True` CLI `kwarg`
  examples/offline_inference/basic/chat.py
  examples/offline_inference/basic/generate.py
  vllm/engine/arg_utils.py
  vllm/utils.py
Labels: documentation, ready

#17793 [Bugfix] Fix missing lora name mapping for lora without prefix
  tests/lora/test_utils.py
  vllm/lora/utils.py
Labels: ready

#16943 [Quantization] Quark MXFP4 format loading
  tests/models/quantization/test_mxfp4.py
  vllm/envs.py
  vllm/model_executor/layers/quantization/quark/quark.py
  vllm/model_executor/layers/quantization/quark/schemes/__init__.py
  vllm/model_executor/layers/quantization/quark/schemes/quark_w4a4_mxfp4.py
  vllm/model_executor/layers/quantization/utils/mxfp4_utils.py
  vllm/model_executor/model_loader/utils.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
Labels: ready

#17811 [BugFix] Avoid secondary missing `MultiprocExecutor.workers` error
  vllm/v1/executor/multiproc_executor.py
Labels: bug, ready, v1

#13407 [Core][Feature] Input metadata dump on crash
  .github/ISSUE_TEMPLATE/400-bug-report.yml
  tests/basic_correctness/test_basic_correctness.py
  vllm/logging_utils/dump_input.py
  vllm/v1/core/sched/output.py
  vllm/v1/engine/core.py
Labels: ready, ci/build, v1

#17810 Don't call the venv `vllm`
  docs/source/getting_started/installation/python_env_setup.inc.md
Labels: documentation, ready

#17600 [BugFix] Fix `--disable-log-stats` in V1 server mode
  vllm/v1/engine/async_llm.py
  vllm/v1/engine/core_client.py
Labels: bug, ready, v1

#16072 [Core] Support full cuda graph in v1
  docs/source/design/v1/torch_compile.md
  tests/compile/piecewise/test_full_cudagraph.py
  vllm/config.py
  vllm/v1/attention/backends/flash_attn.py
  vllm/v1/worker/gpu_model_runner.py
Labels: documentation, ready, ci/build, v1

#17800 Improve exception reporting in MP engine
  vllm/engine/multiprocessing/engine.py
Labels: ready, v0

#17771 [Installation] OpenTelemetry version update
  requirements/common.txt
Labels: ready, ci/build

#17071 [Kernel][Hardware][AMD] Bf16 mfma opt for ROCm skinny GEMMs
  csrc/rocm/skinny_gemms.cu
  tests/kernels/quantization/test_rocm_skinny_gemms.py
  vllm/model_executor/layers/utils.py
  vllm/platforms/rocm.py
Labels: ready

#17153 [Hardware][Power] Enable compressed tensor W8A8 INT8 quantization for POWER
  cmake/cpu_extension.cmake
  csrc/cpu/cpu_types_vsx.hpp
  csrc/cpu/quant.cpp
  csrc/cpu/torch_bindings.cpp
Labels: quantization, ready, ci/build

#17648 [Hardware][Intel-Gaudi] Support Automatic Prefix Caching on HPU
  vllm/attention/backends/hpu_attn.py
  vllm/attention/ops/hpu_paged_attn.py
  vllm/worker/hpu_model_runner.py
Labels: ready

#17805 [Frontend] Chat template fallbacks for multimodal models
  docs/source/serving/multimodal_inputs.md
  examples/template_florence2.jinja
  examples/template_paligemma.jinja
  examples/template_qwen_vl.jinja
  tests/entrypoints/openai/test_chat_template.py
  tests/entrypoints/test_chat_utils.py
  tests/models/registry.py
  vllm/entrypoints/chat_utils.py
  vllm/entrypoints/llm.py
  vllm/entrypoints/openai/api_server.py
  vllm/entrypoints/openai/serving_engine.py
  vllm/transformers_utils/chat_templates/__init__.py
  vllm/transformers_utils/chat_templates/registry.py
  vllm/transformers_utils/chat_templates/template_basic.jinja
  vllm/transformers_utils/chat_templates/template_blip2.jinja
  vllm/transformers_utils/chat_templates/template_chatml.jinja
  vllm/transformers_utils/chat_templates/template_deepseek_vl2.jinja
  vllm/transformers_utils/chat_templates/template_fuyu.jinja
Labels: documentation, frontend, ready

#17753 [Bugfix] Fix bad words for Mistral models
  vllm/logits_process.py
  vllm/sampling_params.py
Labels: ready

#17763 [Misc] support model prefix & add deepseek vl2 tiny fused moe config
  benchmarks/kernels/benchmark_moe.py
  vllm/model_executor/layers/fused_moe/configs/E=64,N=896,device_name=NVIDIA_H20.json
Labels: ready

#17644 [Bugfix] Fix tool call template validation for Mistral models
  examples/tool_chat_template_mistral3.jinja
Labels: documentation, ready, tool-calling

#17820 [TPU] Fix the test_sampler
  tests/v1/tpu/test_sampler.py
  vllm/v1/attention/backends/pallas.py
Labels: tpu, ready, ci/build, v1

#12612 [Bugfix] Fix quark fp8 format loading on AMD GPUs
  tests/quantization/test_quark.py
  vllm/model_executor/layers/quantization/quark/schemes/quark_w8a8_fp8.py
Labels: documentation, frontend, speculative-decoding, ready, ci/build, v1

#17836 [Doc] Fix a typo in the file name
  examples/offline_inference/reproducibility.py
Labels: documentation, ready

#17819 [Easy] Eliminate c10::optional usage in vllm/csrc
  csrc/quantization/gptq_allspark/allspark_qgemm_w8a16.cu
  csrc/quantization/gptq_allspark/allspark_repack.cu
  csrc/rocm/attention.cu
  csrc/rocm/ops.h
Labels: ready

#17828 [Misc] add chatbox integration
  docs/source/assets/deployment/chatbox-chat.png
  docs/source/assets/deployment/chatbox-settings.png
  docs/source/deployment/frameworks/chatbox.md
  docs/source/deployment/frameworks/index.md
Labels: documentation, ready

#17848 Fix transient dependency error in docs build
  requirements/docs.txt
Labels: ready, ci/build

#17838 [Bugfix] `use_fast` failing to be propagated to Qwen2-VL image processor
  vllm/model_executor/models/qwen2_5_omni_thinker.py
  vllm/model_executor/models/qwen2_5_vl.py
  vllm/model_executor/models/qwen2_vl.py
Labels: ready

#17841 [Misc] Delete LoRA-related redundancy code
  vllm/lora/models.py
  vllm/model_executor/models/grok1.py
  vllm/model_executor/models/nemotron_nas.py
  vllm/model_executor/models/phi4mm.py
Labels: ready

#17858 [CI] Fix test_collective_rpc
  tests/entrypoints/llm/test_collective_rpc.py
Labels: ready

#17334 [Test] Attempt all TPU V1 tests, even if some of them fail.
  .buildkite/scripts/hardware_ci/run-tpu-v1-test.sh
Labels: ready, ci/build

#17012 [CI] Prune down lm-eval small tests
  .buildkite/lm-eval-harness/configs/Meta-Llama-3.2-1B-Instruct-FP8-compressed-tensors.yaml
  .buildkite/lm-eval-harness/configs/Qwen2.5-1.5B-Instruct.yaml
  .buildkite/lm-eval-harness/configs/Qwen2.5-VL-3B-Instruct-FP8-dynamic.yaml
  .buildkite/lm-eval-harness/configs/models-large.txt
  .buildkite/lm-eval-harness/configs/models-small.txt
Labels: ready, ci/build

#17414 Fix noisy warning for uncalibrated q_scale/p_scale
  vllm/model_executor/layers/quantization/kv_cache.py
Labels: ready

#14383 Add cutlass support for blackwell fp8 blockwise gemm
  CMakeLists.txt
  csrc/cutlass_extensions/common.hpp
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm100_fp8.cu
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_blockwise_sm100_fp8_dispatch.cuh
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_helper.hpp
  csrc/quantization/cutlass_w8a8/c3x/scaled_mm_kernels.hpp
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x_sm100.cu
  csrc/quantization/cutlass_w8a8/scaled_mm_c3x_sm90.cu
  csrc/quantization/cutlass_w8a8/scaled_mm_entry.cu
  tests/kernels/quantization/test_cutlass_scaled_mm.py
  vllm/model_executor/layers/quantization/utils/fp8_utils.py
Labels: ready, ci/build

#17523 [FEAT][ROCm]: Support AITER MLA on V1 Engine
  docker/Dockerfile.rocm_base
  tests/kernels/attention/test_attention_selector.py
  tests/kernels/attention/test_rocm_attention_selector.py
  vllm/attention/ops/rocm_aiter_mla.py
  vllm/engine/arg_utils.py
  vllm/model_executor/layers/fused_moe/rocm_aiter_fused_moe.py
  vllm/platforms/interface.py
  vllm/platforms/rocm.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
Labels: rocm, ready, ci/build, v1

#17839 [V1][Structured Output] Update llguidance (`>= 0.7.11`) to avoid AttributeError (no `StructTag`)
  requirements/common.txt
Labels: ready, ci/build

#17668 [Attention] MLA move rotary embedding to cuda-graph region
  vllm/attention/backends/mla/common.py
  vllm/attention/backends/rocm_aiter_mla.py
  vllm/model_executor/layers/rotary_embedding.py
  vllm/model_executor/models/deepseek_v2.py
  vllm/v1/attention/backends/mla/common.py
  vllm/v1/attention/backends/mla/flashmla.py
Labels: ready, v1

#17251 [BUGFIX]: return fast when request requires prompt logprobs
  tests/v1/core/test_prefix_caching.py
  vllm/v1/core/kv_cache_manager.py
Labels: ready, v1

#17846 [Doc] Update several links in reasoning_outputs.md
  docs/source/features/reasoning_outputs.md
Labels: documentation, ready

#17884 [Doc] remove visible token in doc
  docs/source/design/v1/prefix_caching.md
Labels: documentation, ready

#17880 [Bugfix][ROCm] Fix AITER MLA V1
  vllm/v1/attention/backends/mla/rocm_aiter_mla.py
Labels: ready, v1

#17252 [Bugfix][CPU] Fix broken AVX2 CPU TP support
  vllm/distributed/device_communicators/cpu_communicator.py
Labels: ready

#17853 Fix Whisper crash caused by invalid``` max_num_batched_tokens``` config
  vllm/config.py
Labels: ready

#17773 Change `top_k` to be disabled with `0` (still accept `-1` for now)
  tests/samplers/test_sampler.py
  vllm/entrypoints/openai/protocol.py
  vllm/model_executor/sampling_metadata.py
  vllm/sampling_params.py
  vllm/worker/neuron_model_runner.py
  vllm/worker/tpu_model_runner.py
Labels: frontend, tpu, ready

#17864 [BugFix][AMD] Compatible patch for latest AITER(05/07/2025)
  vllm/attention/backends/mla/common.py
  vllm/attention/backends/rocm_aiter_mla.py
  vllm/attention/ops/rocm_aiter_mla.py
  vllm/model_executor/layers/fused_moe/rocm_aiter_fused_moe.py
Labels: rocm, ready

#17474 [v1] Move block management logic from KVCacheManager to SpecializedManager
  tests/v1/core/test_kv_cache_utils.py
  tests/v1/core/test_prefix_caching.py
  tests/v1/core/test_scheduler.py
  tests/v1/core/test_specialized_manager.py
  vllm/v1/core/kv_cache_manager.py
  vllm/v1/core/specialized_manager.py
Labels: ready, v1

#17856 [CI/Build] Automatically retry flaky tests
  tests/kernels/moe/test_moe.py
  tests/tensorizer_loader/conftest.py
  tests/tensorizer_loader/test_tensorizer.py
Labels: ready, v1

#17907 [Misc] Add references in ray_serve_deepseek example
  examples/online_serving/ray_serve_deepseek.py
Labels: documentation, ready
